// Auxiliar Administrativo del Estado: Defensor del Pueblo (tema 3, LO 3/1981,
// BOE-A-1981-10325) y Administración General del Estado (tema 8, Ley 40/2015,
// BOE-A-2015-10566).
import type { Destino, PreguntaOficial } from "./tipos";

const T3: Destino[] = [["auxiliar-administrativo", 3]];
const T8: Destino[] = [["auxiliar-administrativo", 8]];
const dp = (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma: "LODP", destinos: T3, ...x });
const age = (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma: "LRJSP", destinos: T8, ...x });

export const DEFENSOR: PreguntaOficial[] = [
  dp({ id: "of-dp-01", art: "Artículo segundo",
    cita: "El Defensor del Pueblo será elegido por las Cortes Generales para un periodo de cinco años",
    clave: "cinco años",
    e: "Según el artículo 2.1 de la Ley Orgánica 3/1981, el Defensor del Pueblo es elegido por las Cortes Generales para un periodo de:",
    ok: "Cinco años.", mal: ["Cuatro años.", "Seis años.", "Nueve años."], d: 1 }),
  dp({ id: "of-dp-02", art: "Artículo segundo",
    cita: "Se designará en las Cortes Generales una Comisión Mixta Congreso-Senado encargada de relacionarse con el Defensor del Pueblo",
    clave: "Comisión Mixta Congreso-Senado",
    e: "Conforme al artículo 2.2 de la Ley Orgánica 3/1981, el órgano de las Cortes encargado de relacionarse con el Defensor del Pueblo es:",
    ok: "Una Comisión Mixta Congreso-Senado.", mal: ["La Diputación Permanente del Congreso.", "La Comisión Constitucional del Senado.", "La Mesa del Congreso de los Diputados."], d: 2 }),
  dp({ id: "of-dp-03", art: "Artículo tercero",
    cita: "Podrá ser elegido Defensor del Pueblo cualquier español mayor de edad que se encuentre en el pleno disfrute de sus derechos civiles y políticos.",
    clave: "cualquier español mayor de edad",
    e: "Según el artículo 3 de la Ley Orgánica 3/1981, puede ser elegido Defensor del Pueblo:",
    ok: "Cualquier español mayor de edad en el pleno disfrute de sus derechos civiles y políticos.",
    mal: ["Solo un jurista con más de quince años de ejercicio profesional.", "Solo un funcionario de carrera del Subgrupo A1.", "Solo un miembro de las Cortes Generales."], d: 1 }),
  dp({ id: "of-dp-04", art: "Artículo cuarto",
    cita: "El Defensor del Pueblo tomará posesión de su cargo ante las Mesas de ambas Cámaras reunidas conjuntamente",
    clave: "Mesas de ambas Cámaras",
    e: "Conforme al artículo 4.2 de la Ley Orgánica 3/1981, el Defensor del Pueblo toma posesión de su cargo ante:",
    ok: "Las Mesas de ambas Cámaras reunidas conjuntamente.", mal: ["El Rey, en el Palacio Real.", "El Pleno del Tribunal Constitucional.", "El Presidente del Gobierno."], d: 2 }),
  dp({ id: "of-dp-05", art: "Artículo quinto",
    cita: "Por actuar con notoria negligencia en el cumplimiento de las obligaciones y deberes del cargo.",
    clave: "notoria negligencia",
    e: "¿Cuál de las siguientes es una causa de cese del Defensor del Pueblo según el artículo 5.1 de la Ley Orgánica 3/1981?",
    ok: "Actuar con notoria negligencia en el cumplimiento de las obligaciones y deberes del cargo.",
    mal: ["La disolución de las Cortes Generales.", "El cambio de Gobierno.", "La presentación de una moción de censura."], d: 2 }),
  dp({ id: "of-dp-06", art: "Artículo sexto",
    cita: "El Defensor del Pueblo no estará sujeto a mandato imperativo alguno. No recibirá instrucciones de ninguna Autoridad.",
    clave: "No recibirá instrucciones de ninguna Autoridad",
    e: "Según el artículo 6.1 de la Ley Orgánica 3/1981, el Defensor del Pueblo:",
    ok: "No está sujeto a mandato imperativo alguno y no recibirá instrucciones de ninguna Autoridad.",
    mal: ["Recibe instrucciones de la Comisión Mixta Congreso-Senado.", "Actúa siguiendo las directrices del Ministerio de Justicia.", "Está sujeto al mandato de los grupos que lo propusieron."], d: 1 }),
  dp({ id: "of-dp-07", art: "Artículo octavo",
    cita: "El Defensor del Pueblo estará auxiliado por un Adjunto Primero y un Adjunto Segundo",
    clave: "un Adjunto Primero y un Adjunto Segundo",
    e: "Conforme al artículo 8.1 de la Ley Orgánica 3/1981, el Defensor del Pueblo está auxiliado por:",
    ok: "Un Adjunto Primero y un Adjunto Segundo.", mal: ["Tres Adjuntos de igual rango.", "Un Secretario General nombrado por el Gobierno.", "Un Adjunto por cada Comunidad Autónoma."], d: 1 }),
  dp({ id: "of-dp-08", art: "Artículo diez",
    cita: "Podrá dirigirse al Defensor del Pueblo toda persona natural o jurídica que invoque un interés legítimo, sin restricción alguna.",
    clave: "sin restricción alguna",
    e: "Según el artículo 10.1 de la Ley Orgánica 3/1981, puede dirigirse al Defensor del Pueblo toda persona natural o jurídica que invoque un interés legítimo:",
    ok: "Sin restricción alguna, ni por nacionalidad, residencia, sexo o minoría de edad.",
    mal: ["Siempre que sea de nacionalidad española.", "Siempre que sea mayor de edad.", "Siempre que haya agotado la vía judicial."], d: 2 }),
  dp({ id: "of-dp-09", art: "Artículo quince",
    cita: "en escrito razonado en papel común y en el plazo máximo de un año, contado a partir del momento en que tuviera conocimiento de los hechos objeto de la misma",
    clave: "un año",
    e: "Conforme al artículo 15.1 de la Ley Orgánica 3/1981, la queja al Defensor del Pueblo debe presentarse en el plazo máximo de:",
    ok: "Un año desde que se tuvo conocimiento de los hechos.", mal: ["Tres meses desde los hechos.", "Seis meses desde la resolución administrativa.", "Dos años desde los hechos."], d: 2 }),
  dp({ id: "of-dp-10", art: "Artículo quince",
    cita: "Todas las actuaciones del Defensor del Pueblo son gratuitas para el interesado y no será preceptiva la asistencia de Letrado ni de Procurador.",
    clave: "gratuitas",
    e: "Según el artículo 15.2 de la Ley Orgánica 3/1981, las actuaciones del Defensor del Pueblo:",
    ok: "Son gratuitas para el interesado y no requieren Letrado ni Procurador.",
    mal: ["Exigen el pago de una tasa reducida.", "Requieren la asistencia de abogado.", "Solo son sin coste para quien acredite insuficiencia de recursos."], d: 1 }),
  dp({ id: "of-dp-11", art: "Artículo treinta y dos",
    cita: "El Defensor del Pueblo dará cuenta anualmente a las Cortes Generales de la gestión realizada en un informe",
    clave: "anualmente a las Cortes Generales",
    e: "Conforme al artículo 32.1 de la Ley Orgánica 3/1981, el Defensor del Pueblo da cuenta de su gestión:",
    ok: "Anualmente a las Cortes Generales, en un informe.", mal: ["Semestralmente al Gobierno.", "Anualmente al Tribunal Constitucional.", "Cada cinco años al Rey."], d: 1 }),
];

export const AGE: PreguntaOficial[] = [
  age({ id: "of-age-01", art: "Artículo 54",
    cita: "así como los de descentralización funcional y desconcentración funcional y territorial",
    clave: "desconcentración funcional y territorial",
    e: "Además de los principios del artículo 3, según el artículo 54.1 de la Ley 40/2015 la Administración General del Estado actúa y se organiza de acuerdo con los de descentralización funcional y:",
    ok: "Desconcentración funcional y territorial.", mal: ["Centralización territorial.", "Autonomía política.", "Subsidiariedad europea."], d: 2 }),
  age({ id: "of-age-02", art: "Artículo 55",
    cita: "división funcional en Departamentos ministeriales y de gestión territorial integrada en Delegaciones del Gobierno en las Comunidades Autónomas",
    clave: "gestión territorial integrada en Delegaciones del Gobierno",
    e: "Según el artículo 55.1 de la Ley 40/2015, la organización de la Administración General del Estado responde a los principios de división funcional en Departamentos ministeriales y de:",
    ok: "Gestión territorial integrada en Delegaciones del Gobierno en las Comunidades Autónomas.",
    mal: ["Gestión territorial a través de las Diputaciones Provinciales.", "Delegación de competencias en los Ayuntamientos.", "Gestión descentralizada en las Comunidades Autónomas."], d: 2 }),
  age({ id: "of-age-03", art: "Artículo 55",
    cita: "c) La Administración General del Estado en el exterior.",
    clave: "en el exterior",
    e: "Además de la Organización Central y la Organización Territorial, el artículo 55.2 de la Ley 40/2015 incluye en la Administración General del Estado:",
    ok: "La Administración General del Estado en el exterior.", mal: ["Las Comunidades Autónomas.", "Las Entidades Locales.", "Las Cortes Generales."], d: 1 }),
  age({ id: "of-age-04", art: "Artículo 55",
    cita: "2.º Los Secretarios de Estado.",
    clave: "Secretarios de Estado",
    e: "Según el artículo 55.3 de la Ley 40/2015, en la organización central son órganos superiores los Ministros y:",
    ok: "Los Secretarios de Estado.", mal: ["Los Subsecretarios.", "Los Directores generales.", "Los Secretarios generales técnicos."],
    j: "Subsecretarios, Secretarios generales, Secretarios generales técnicos, Directores generales y Subdirectores generales son órganos directivos.", m: "Superiores: solo dos, Ministros y Secretarios de Estado.", d: 1 }),
  age({ id: "of-age-05", art: "Artículo 55",
    cita: "3.º Los Subdirectores generales.",
    clave: "Subdirectores generales",
    e: "¿Cuál de los siguientes es un órgano directivo de la organización central según el artículo 55.3 de la Ley 40/2015?",
    ok: "Los Subdirectores generales.", mal: ["Los Ministros.", "Los Secretarios de Estado.", "Los Jefes de Servicio."], d: 2 }),
  age({ id: "of-age-06", art: "Artículo 55",
    cita: "como los Subdelegados del Gobierno en las provincias, los cuales tendrán nivel de Subdirector general",
    clave: "nivel de Subdirector general",
    e: "Según el artículo 55.4 de la Ley 40/2015, los Subdelegados del Gobierno en las provincias tienen:",
    ok: "Nivel de Subdirector general.", mal: ["Rango de Subsecretario.", "Categoría de Director general.", "Rango de Secretario de Estado."], d: 2 }),
  age({ id: "of-age-07", art: "Artículo 55",
    cita: "Los órganos superiores y directivos tienen además la condición de alto cargo, excepto los Subdirectores generales y asimilados",
    clave: "excepto los Subdirectores generales y asimilados",
    e: "Conforme al artículo 55.6 de la Ley 40/2015, los órganos superiores y directivos tienen la condición de alto cargo:",
    ok: "Excepto los Subdirectores generales y asimilados.", mal: ["Excepto los Secretarios de Estado.", "Excepto los Delegados del Gobierno.", "Solo los Ministros."], d: 3 }),
  age({ id: "of-age-08", art: "Artículo 55",
    cita: "Corresponde a los órganos superiores establecer los planes de actuación de la organización situada bajo su responsabilidad y a los órganos directivos su desarrollo y ejecución.",
    clave: "su desarrollo y ejecución",
    e: "Según el artículo 55.9 de la Ley 40/2015, a los órganos directivos les corresponde, respecto de los planes de actuación que establecen los órganos superiores:",
    ok: "Su desarrollo y ejecución.", mal: ["Su aprobación definitiva.", "Su control parlamentario.", "Su elaboración y aprobación."], d: 2 }),
  age({ id: "of-age-09", art: "Artículo 56",
    cita: "Las unidades administrativas son los elementos organizativos básicos de las estructuras orgánicas.",
    clave: "elementos organizativos básicos",
    e: "El artículo 56.1 de la Ley 40/2015 define las unidades administrativas como:",
    ok: "Los elementos organizativos básicos de las estructuras orgánicas.", mal: ["Los órganos superiores de cada Ministerio.", "Los organismos públicos dependientes.", "Las delegaciones territoriales del Estado."], d: 1 }),
  age({ id: "of-age-10", art: "Artículo 56",
    cita: "Las unidades administrativas se establecen mediante las relaciones de puestos de trabajo",
    clave: "relaciones de puestos de trabajo",
    e: "Conforme al artículo 56.3 de la Ley 40/2015, las unidades administrativas se establecen mediante:",
    ok: "Las relaciones de puestos de trabajo.", mal: ["Real Decreto del Consejo de Ministros.", "Orden del Ministro de Hacienda.", "Ley de Presupuestos Generales del Estado."], d: 2 }),
  age({ id: "of-age-11", art: "Artículo 57",
    cita: "La determinación del número, la denominación y el ámbito de competencia respectivo de los Ministerios y las Secretarías de Estado se establecen mediante Real Decreto del Presidente del Gobierno.",
    clave: "Real Decreto del Presidente del Gobierno",
    e: "Según el artículo 57.3 de la Ley 40/2015, el número, la denominación y el ámbito de competencia de los Ministerios y las Secretarías de Estado se establecen mediante:",
    ok: "Real Decreto del Presidente del Gobierno.", mal: ["Ley de las Cortes Generales.", "Real Decreto acordado en Consejo de Ministros.", "Orden del Ministro de la Presidencia."], d: 2 }),
  age({ id: "of-age-12", art: "Artículo 58",
    cita: "Los Ministerios contarán, en todo caso, con una Subsecretaría, y dependiendo de ella una Secretaría General Técnica, para la gestión de los servicios comunes",
    clave: "una Subsecretaría",
    e: "Conforme al artículo 58.2 de la Ley 40/2015, todos los Ministerios cuentan en todo caso con:",
    ok: "Una Subsecretaría y, dependiendo de ella, una Secretaría General Técnica.", mal: ["Una Secretaría de Estado.", "Una Secretaría General y una Delegación territorial.", "Un Gabinete técnico dependiente del Presidente del Gobierno."], d: 2 }),
  age({ id: "of-age-13", art: "Artículo 58",
    cita: "Las Direcciones Generales son los órganos de gestión de una o varias áreas funcionalmente homogéneas.",
    clave: "áreas funcionalmente homogéneas",
    e: "Según el artículo 58.3 de la Ley 40/2015, las Direcciones Generales son los órganos de gestión de:",
    ok: "Una o varias áreas funcionalmente homogéneas.", mal: ["Los servicios comunes del Ministerio.", "Un sector de actividad de ámbito internacional.", "Todas las Subsecretarías del Departamento."], d: 2 }),
  age({ id: "of-age-14", art: "Artículo 59",
    cita: "se crean, modifican y suprimen por Real Decreto del Consejo de Ministros, a iniciativa del Ministro interesado y a propuesta del Ministro de Hacienda y Administraciones Públicas",
    clave: "Real Decreto del Consejo de Ministros",
    e: "Según el artículo 59.1 de la Ley 40/2015, las Subsecretarías, Secretarías Generales, Direcciones Generales y Subdirecciones Generales se crean, modifican y suprimen por:",
    ok: "Real Decreto del Consejo de Ministros, a iniciativa del Ministro interesado.", mal: ["Orden del Ministro respectivo.", "Ley orgánica.", "Resolución del Subsecretario."], d: 2 }),
  age({ id: "of-age-15", art: "Artículo 59",
    cita: "Los órganos de nivel inferior a Subdirección General se crean, modifican y suprimen por orden del Ministro respectivo",
    clave: "orden del Ministro respectivo",
    e: "Conforme al artículo 59.2 de la Ley 40/2015, los órganos de nivel inferior a Subdirección General se crean, modifican y suprimen por:",
    ok: "Orden del Ministro respectivo, previa autorización del Ministro de Hacienda.", mal: ["Real Decreto del Consejo de Ministros.", "Real Decreto del Presidente del Gobierno.", "Las relaciones de puestos de trabajo, exclusivamente."], d: 2 }),
  age({ id: "of-age-16", art: "Artículo 60",
    cita: "Los Ministros son los jefes superiores del Departamento y superiores jerárquicos directos de los Secretarios de Estado y Subsecretarios.",
    clave: "jefes superiores del Departamento",
    e: "Según el artículo 60.1 de la Ley 40/2015, los Ministros son:",
    ok: "Los jefes superiores del Departamento y superiores jerárquicos directos de los Secretarios de Estado y Subsecretarios.",
    mal: ["Órganos directivos con rango de Subsecretario.", "Superiores jerárquicos directos de los Directores generales, exclusivamente.", "Órganos dependientes del Secretario de Estado."], d: 1 }),
  age({ id: "of-age-17", art: "Artículo 60",
    cita: "Los Secretarios generales tienen categoría de Subsecretario y los Secretarios Generales Técnicos tienen categoría de Director general.",
    clave: "categoría de Director general",
    e: "Conforme al artículo 60.2 de la Ley 40/2015, los Secretarios Generales Técnicos tienen:",
    ok: "Categoría de Director general.", mal: ["Categoría de Subsecretario.", "Rango de Secretario de Estado.", "Nivel de Subdirector general."], d: 2 }),
  age({ id: "of-age-18", art: "Artículo 61",
    cita: "a) Ejercer la potestad reglamentaria en las materias propias de su Departamento.",
    clave: "potestad reglamentaria",
    e: "¿Cuál de las siguientes funciones corresponde a los Ministros según el artículo 61 de la Ley 40/2015?",
    ok: "Ejercer la potestad reglamentaria en las materias propias de su Departamento.", mal: ["Representar al Estado en las Comunidades Autónomas.", "Nombrar a los Delegados del Gobierno.", "Aprobar los Presupuestos Generales del Estado."], d: 2 }),
  age({ id: "of-age-19", art: "Artículo 62",
    cita: "Los Secretarios de Estado son directamente responsables de la ejecución de la acción del Gobierno en un sector de actividad específica.",
    clave: "sector de actividad específica",
    e: "Según el artículo 62.1 de la Ley 40/2015, los Secretarios de Estado son directamente responsables de la ejecución de la acción del Gobierno:",
    ok: "En un sector de actividad específica.", mal: ["En una Comunidad Autónoma.", "En los servicios comunes del Ministerio.", "En las relaciones con las Cortes Generales, exclusivamente."], d: 2 }),
  age({ id: "of-age-20", art: "Artículo 63",
    cita: "Los Subsecretarios ostentan la representación ordinaria del Ministerio, dirigen los servicios comunes",
    clave: "representación ordinaria del Ministerio",
    e: "Conforme al artículo 63.1 de la Ley 40/2015, los Subsecretarios:",
    ok: "Ostentan la representación ordinaria del Ministerio y dirigen los servicios comunes.", mal: ["Son órganos superiores del Ministerio.", "Ejercen la potestad reglamentaria del Departamento.", "Representan al Gobierno en las Comunidades Autónomas."], d: 2 }),
  age({ id: "of-age-21", art: "Artículo 65",
    cita: "en todo caso, las relativas a producción normativa, asistencia jurídica y publicaciones",
    clave: "producción normativa, asistencia jurídica y publicaciones",
    e: "Según el artículo 65.1 de la Ley 40/2015, los Secretarios generales técnicos tienen en todo caso competencias relativas a:",
    ok: "Producción normativa, asistencia jurídica y publicaciones.", mal: ["Política exterior y cooperación.", "Seguridad ciudadana y protección civil.", "Gestión de personal y nóminas, exclusivamente."], d: 2 }),
  age({ id: "of-age-22", art: "Artículo 67",
    cita: "Los Subdirectores generales serán nombrados, respetando los principios de igualdad, mérito y capacidad, y cesados por el Ministro, Secretario de Estado o Subsecretario del que dependan.",
    clave: "Ministro, Secretario de Estado o Subsecretario",
    e: "Conforme al artículo 67.2 de la Ley 40/2015, los Subdirectores generales son nombrados y cesados por:",
    ok: "El Ministro, Secretario de Estado o Subsecretario del que dependan.", mal: ["Real Decreto del Consejo de Ministros.", "El Presidente del Gobierno.", "El Director general, por libre designación."], d: 3 }),
  age({ id: "of-age-23", art: "Artículo 69",
    cita: "Existirá una Delegación del Gobierno en cada una de las Comunidades Autónomas.",
    clave: "en cada una de las Comunidades Autónomas",
    e: "Según el artículo 69.1 de la Ley 40/2015, existirá una Delegación del Gobierno:",
    ok: "En cada una de las Comunidades Autónomas.", mal: ["En cada provincia.", "Solo en las Comunidades Autónomas pluriprovinciales.", "En cada isla con Cabildo o Consejo Insular."], d: 1 }),
  age({ id: "of-age-24", art: "Artículo 69",
    cita: "Las Delegaciones del Gobierno tendrán su sede en la localidad donde radique el Consejo de Gobierno de la Comunidad Autónoma",
    clave: "Consejo de Gobierno de la Comunidad Autónoma",
    e: "Conforme al artículo 69.2 de la Ley 40/2015, como regla general las Delegaciones del Gobierno tienen su sede en la localidad donde radique:",
    ok: "El Consejo de Gobierno de la Comunidad Autónoma.", mal: ["El Tribunal Superior de Justicia.", "La capital de la provincia más poblada.", "El Parlamento autonómico, en todo caso."], d: 2 }),
  age({ id: "of-age-25", art: "Artículo 69",
    cita: "En cada una de las provincias de las Comunidades Autónomas pluriprovinciales, existirá un Subdelegado del Gobierno, que estará bajo la inmediata dependencia del Delegado del Gobierno.",
    clave: "inmediata dependencia del Delegado del Gobierno",
    e: "Según el artículo 69.4 de la Ley 40/2015, en cada provincia de las Comunidades Autónomas pluriprovinciales existirá un Subdelegado del Gobierno:",
    ok: "Bajo la inmediata dependencia del Delegado del Gobierno.", mal: ["Bajo la dependencia directa del Ministro del Interior.", "Elegido por la Diputación Provincial.", "Dependiente del Presidente de la Comunidad Autónoma."], d: 1 }),
  age({ id: "of-age-26", art: "Artículo 72",
    cita: "sin perjuicio de la representación ordinaria del Estado en las mismas a través de sus respectivos Presidentes",
    clave: "representación ordinaria del Estado",
    e: "Según el artículo 72.1 de la Ley 40/2015, los Delegados del Gobierno representan al Gobierno de la Nación en la Comunidad Autónoma, sin perjuicio de que sus Presidentes ostenten:",
    ok: "La representación ordinaria del Estado en las mismas.", mal: ["La dirección de la Administración General del Estado en su territorio.", "El mando de las Fuerzas y Cuerpos de Seguridad del Estado.", "La jefatura de los servicios periféricos estatales."], d: 3 }),
  age({ id: "of-age-27", art: "Artículo 72",
    cita: "Los Delegados del Gobierno son órganos directivos con rango de Subsecretario que dependen orgánicamente del Presidente del Gobierno y funcionalmente del Ministerio competente por razón de la materia.",
    clave: "orgánicamente del Presidente del Gobierno",
    e: "Conforme al artículo 72.3 de la Ley 40/2015, los Delegados del Gobierno dependen:",
    ok: "Orgánicamente del Presidente del Gobierno y funcionalmente del Ministerio competente por razón de la materia.",
    mal: ["Orgánica y funcionalmente del Ministerio del Interior.", "Funcionalmente del Presidente de la Comunidad Autónoma.", "Orgánicamente del Consejo de Ministros y funcionalmente de las Cortes."], d: 3 }),
  age({ id: "of-age-28", art: "Artículo 72",
    cita: "Los Delegados del Gobierno serán nombrados y separados por Real Decreto del Consejo de Ministros, a propuesta del Presidente del Gobierno.",
    clave: "a propuesta del Presidente del Gobierno",
    e: "Según el artículo 72.4 de la Ley 40/2015, los Delegados del Gobierno son nombrados y separados por Real Decreto del Consejo de Ministros:",
    ok: "A propuesta del Presidente del Gobierno.", mal: ["A propuesta del Ministro del Interior.", "A propuesta del Presidente de la Comunidad Autónoma.", "Previa votación de la Asamblea autonómica."], d: 2 }),
  age({ id: "of-age-29", art: "Artículo 74",
    cita: "que será nombrado por aquél mediante el procedimiento de libre designación entre funcionarios de carrera del Estado, de las Comunidades Autónomas o de las Entidades Locales, pertenecientes a Cuerpos o Escalas clasificados como Subgrupo A1",
    clave: "libre designación",
    e: "Según el artículo 74 de la Ley 40/2015, el Subdelegado del Gobierno es nombrado por el Delegado del Gobierno mediante:",
    ok: "Libre designación entre funcionarios de carrera del Subgrupo A1.", mal: ["Concurso de méritos entre funcionarios del Subgrupo A2.", "Elección por la Diputación Provincial.", "Real Decreto del Consejo de Ministros a propuesta del Ministro del Interior."], d: 2 }),
  age({ id: "of-age-30", art: "Artículo 74",
    cita: "En las Comunidades Autónomas uniprovinciales en las que no exista Subdelegado, el Delegado del Gobierno asumirá las competencias que esta Ley atribuye a los Subdelegados del Gobierno en las provincias.",
    clave: "el Delegado del Gobierno asumirá las competencias",
    e: "En las Comunidades Autónomas uniprovinciales en las que no exista Subdelegado, según el artículo 74 de la Ley 40/2015:",
    ok: "El Delegado del Gobierno asumirá las competencias de los Subdelegados.", mal: ["Las competencias pasan al Presidente de la Comunidad Autónoma.", "Se nombra un Director Insular.", "Las competencias las asume el Secretario General de la Delegación."], d: 2 }),
];
