// Administrativo del Estado: fuentes del Derecho administrativo (tema 16:
// Código Civil, Ley 39/2015 título VI, Ley 50/1997) y presupuesto del Estado
// (tema 33: Ley 47/2003, General Presupuestaria).
import type { Destino, NormaOficial, PreguntaOficial } from "./tipos";

const T16: Destino[] = [["administrativo-estado", 16]];
const T33: Destino[] = [["administrativo-estado", 33]];
const f = (norma: NormaOficial) => (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma, destinos: T16, ...x });
const cc = f("CC");
const lp = f("LPAC");
const lg = f("LG");
const gp = (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma: "LGP", destinos: T33, ...x });

export const FUENTES: PreguntaOficial[] = [
  cc({ id: "of-fu-01", art: "Art 1",
    cita: "Las fuentes del ordenamiento jurídico español son la ley, la costumbre y los principios generales del derecho.",
    clave: "la ley, la costumbre y los principios generales del derecho",
    e: "Según el artículo 1.1 del Código Civil, las fuentes del ordenamiento jurídico español son:",
    ok: "La ley, la costumbre y los principios generales del derecho.", mal: ["La ley, la jurisprudencia y la doctrina.", "La Constitución, los tratados y los reglamentos.", "La ley, la costumbre y la jurisprudencia."], d: 1 }),
  cc({ id: "of-fu-02", art: "Art 1",
    cita: "Carecerán de validez las disposiciones que contradigan otra de rango superior.",
    clave: "rango superior",
    e: "Conforme al artículo 1.2 del Código Civil, carecerán de validez las disposiciones que contradigan otra de:",
    ok: "Rango superior.", mal: ["Fecha anterior.", "Igual rango y fecha posterior.", "Ámbito territorial distinto."], d: 1 }),
  cc({ id: "of-fu-03", art: "Art 1",
    cita: "La costumbre sólo regirá en defecto de ley aplicable, siempre que no sea contraria a la moral o al orden público, y que resulte probada.",
    clave: "en defecto de ley aplicable",
    e: "Según el artículo 1.3 del Código Civil, la costumbre sólo regirá:",
    ok: "En defecto de ley aplicable, si no es contraria a la moral o al orden público y resulta probada.", mal: ["Con preferencia a la ley si es más antigua.", "Solo en el ámbito mercantil.", "Cuando la reconozca el Tribunal Supremo."], d: 1 }),
  cc({ id: "of-fu-04", art: "Art 1",
    cita: "Los principios generales del derecho se aplicarán en defecto de ley o costumbre, sin perjuicio de su carácter informador del ordenamiento jurídico.",
    clave: "en defecto de ley o costumbre",
    e: "Conforme al artículo 1.4 del Código Civil, los principios generales del derecho se aplicarán:",
    ok: "En defecto de ley o costumbre, sin perjuicio de su carácter informador del ordenamiento.", mal: ["Con preferencia a la costumbre.", "Solo cuando lo autorice la ley expresamente.", "Únicamente en el orden penal."], d: 1 }),
  cc({ id: "of-fu-05", art: "Art 1",
    cita: "no serán de aplicación directa en España en tanto no hayan pasado a formar parte del ordenamiento interno mediante su publicación íntegra en el «Boletín Oficial del Estado»",
    clave: "publicación íntegra",
    e: "Según el artículo 1.5 del Código Civil, las normas contenidas en los tratados internacionales serán de aplicación directa en España una vez que hayan pasado a formar parte del ordenamiento interno mediante:",
    ok: "Su publicación íntegra en el «Boletín Oficial del Estado».", mal: ["Su firma por el Ministro de Asuntos Exteriores.", "Una ley orgánica de desarrollo en todo caso.", "Su ratificación por el Tribunal Constitucional."], d: 2 }),
  cc({ id: "of-fu-06", art: "Art 1",
    cita: "6. La jurisprudencia complementará el ordenamiento jurídico",
    clave: "complementará el ordenamiento jurídico",
    e: "Conforme al artículo 1.6 del Código Civil, la jurisprudencia:",
    ok: "Complementará el ordenamiento jurídico.", mal: ["Es una fuente del Derecho de aplicación preferente a la costumbre.", "Deroga las leyes que contradiga.", "Solo vincula al tribunal que la dicta."], d: 2 }),
  cc({ id: "of-fu-07", art: "Art 2",
    cita: "Las leyes entrarán en vigor a los veinte días de su completa publicación en el «Boletín Oficial del Estado», si en ellas no se dispone otra cosa.",
    clave: "veinte días",
    e: "Según el artículo 2.1 del Código Civil, salvo que dispongan otra cosa, las leyes entran en vigor:",
    ok: "A los veinte días de su completa publicación en el BOE.", mal: ["Al día siguiente de su publicación.", "A los quince días de su sanción por el Rey.", "Al mes de su aprobación por las Cortes."], m: "Vacatio legis general: 20 días.", d: 1 }),
  cc({ id: "of-fu-08", art: "Art 2",
    cita: "Por la simple derogación de una ley no recobran vigencia las que ésta hubiere derogado.",
    clave: "no recobran vigencia",
    e: "Conforme al artículo 2.2 del Código Civil, por la simple derogación de una ley, las leyes que esta hubiere derogado:",
    ok: "No recobran vigencia.", mal: ["Recobran vigencia automáticamente.", "Recobran vigencia si así lo declara el Gobierno.", "Recobran vigencia a los veinte días."], d: 2 }),
  cc({ id: "of-fu-09", art: "Art 2",
    cita: "Las leyes no tendrán efecto retroactivo, si no dispusieren lo contrario.",
    clave: "si no dispusieren lo contrario",
    e: "Según el artículo 2.3 del Código Civil, las leyes no tendrán efecto retroactivo:",
    ok: "Si no dispusieren lo contrario.", mal: ["En ningún caso.", "Salvo que lo acuerde un tribunal.", "Salvo en materia penal desfavorable."], d: 1 }),
  cc({ id: "of-fu-10", art: "Art 3",
    cita: "atendiendo fundamentalmente al espíritu y finalidad de aquellas",
    clave: "espíritu y finalidad",
    e: "El artículo 3.1 del Código Civil dispone que las normas se interpretarán según el sentido propio de sus palabras, en relación con el contexto, los antecedentes y la realidad social, atendiendo fundamentalmente:",
    ok: "Al espíritu y finalidad de aquellas.", mal: ["A la voluntad del Gobierno que las propuso.", "A la opinión de la doctrina mayoritaria.", "Al tenor literal exclusivamente."], d: 2 }),
  cc({ id: "of-fu-11", art: "Art 4",
    cita: "Las leyes penales, las excepcionales y las de ámbito temporal no se aplicarán a supuestos ni en momentos distintos de los comprendidos expresamente en ellas.",
    clave: "Las leyes penales, las excepcionales y las de ámbito temporal",
    e: "Según el artículo 4.2 del Código Civil, ¿qué leyes no se aplicarán a supuestos ni en momentos distintos de los comprendidos expresamente en ellas (no admiten analogía)?",
    ok: "Las leyes penales, las excepcionales y las de ámbito temporal.", mal: ["Las leyes orgánicas y las ordinarias.", "Las leyes civiles y mercantiles.", "Los reglamentos de las Comunidades Autónomas."], d: 2 }),
  cc({ id: "of-fu-12", art: "Art 6",
    cita: "La ignorancia de las leyes no excusa de su cumplimiento.",
    clave: "no excusa de su cumplimiento",
    e: "Conforme al artículo 6.1 del Código Civil, la ignorancia de las leyes:",
    ok: "No excusa de su cumplimiento.", mal: ["Excusa de su cumplimiento si es invencible.", "Permite solicitar una prórroga.", "Anula los actos realizados de buena fe."], d: 1 }),
  cc({ id: "of-fu-13", art: "Art 6",
    cita: "se considerarán ejecutados en fraude de ley y no impedirán la debida aplicación de la norma que se hubiere tratado de eludir",
    clave: "fraude de ley",
    e: "Según el artículo 6.4 del Código Civil, los actos realizados al amparo del texto de una norma que persigan un resultado prohibido por el ordenamiento se considerarán ejecutados:",
    ok: "En fraude de ley, y no impedirán aplicar la norma que se hubiere tratado de eludir.", mal: ["Con abuso de derecho, y serán válidos.", "De buena fe, y producirán plenos efectos.", "En error de derecho, y serán anulables."], d: 2 }),
  lp({ id: "of-fu-14", art: "Artículo 127",
    cita: "mediante la elaboración y aprobación de los anteproyectos de Ley y la ulterior remisión de los proyectos de ley a las Cortes Generales",
    clave: "anteproyectos de Ley",
    e: "Según el artículo 127 de la Ley 39/2015, el Gobierno de la Nación ejerce la iniciativa legislativa mediante:",
    ok: "La elaboración y aprobación de los anteproyectos de Ley y la remisión de los proyectos de ley a las Cortes Generales.", mal: ["La presentación de proposiciones de ley en el Senado.", "La aprobación de reglamentos ejecutivos.", "La convocatoria de referéndum."], d: 2 }),
  lp({ id: "of-fu-15", art: "Artículo 128",
    cita: "El ejercicio de la potestad reglamentaria corresponde al Gobierno de la Nación, a los órganos de Gobierno de las Comunidades Autónomas",
    clave: "Gobierno de la Nación",
    e: "Conforme al artículo 128.1 de la Ley 39/2015, el ejercicio de la potestad reglamentaria corresponde, entre otros, a:",
    ok: "El Gobierno de la Nación, los órganos de Gobierno de las Comunidades Autónomas y los órganos de gobierno locales.", mal: ["Las Cortes Generales.", "El Tribunal Supremo.", "El Consejo de Estado."], d: 1 }),
  lp({ id: "of-fu-16", art: "Artículo 128",
    cita: "no podrán tipificar delitos, faltas o infracciones administrativas, establecer penas o sanciones, así como tributos",
    clave: "no podrán tipificar delitos",
    e: "Según el artículo 128.2 de la Ley 39/2015, sin perjuicio de su función de colaboración con la ley, los reglamentos:",
    ok: "No podrán tipificar delitos, faltas o infracciones administrativas, ni establecer penas o sanciones ni tributos.", mal: ["Pueden tipificar infracciones si lo autoriza el Ministro.", "Pueden crear tributos locales.", "Pueden establecer penas de multa."], d: 2 }),
  lp({ id: "of-fu-17", art: "Artículo 129",
    cita: "las Administraciones Públicas actuarán de acuerdo con los principios de necesidad, eficacia, proporcionalidad, seguridad jurídica, transparencia, y eficiencia",
    clave: "necesidad, eficacia, proporcionalidad, seguridad jurídica, transparencia, y eficiencia",
    e: "Según el artículo 129.1 de la Ley 39/2015, en el ejercicio de la iniciativa legislativa y la potestad reglamentaria las Administraciones actuarán de acuerdo con los principios de:",
    ok: "Necesidad, eficacia, proporcionalidad, seguridad jurídica, transparencia, y eficiencia.", mal: ["Jerarquía, competencia, publicidad y temporalidad.", "Legalidad, oportunidad y discrecionalidad.", "Unidad, universalidad y especialidad."], m: "Buena regulación: «NEPSTE» (Necesidad, Eficacia, Proporcionalidad, Seguridad jurídica, Transparencia, Eficiencia).", d: 2 }),
  lp({ id: "of-fu-18", art: "Artículo 131",
    cita: "habrán de publicarse en el diario oficial correspondiente para que entren en vigor y produzcan efectos jurídicos",
    clave: "diario oficial correspondiente",
    e: "Conforme al artículo 131 de la Ley 39/2015, las normas con rango de ley, los reglamentos y disposiciones administrativas, para que entren en vigor y produzcan efectos, habrán de publicarse en:",
    ok: "El diario oficial correspondiente.", mal: ["El tablón de anuncios del órgano que las dicta.", "Un periódico de difusión nacional.", "El portal de transparencia, exclusivamente."], d: 1 }),
  lg({ id: "of-fu-19", art: "Artículo 23",
    cita: "preverán el comienzo de su vigencia el 2 de enero o el 1 de julio siguientes a su aprobación",
    clave: "el 2 de enero o el 1 de julio",
    e: "Según el artículo 23 de la Ley 50/1997, las leyes o reglamentos que impongan nuevas obligaciones a quienes desempeñen una actividad económica o profesional preverán el comienzo de su vigencia:",
    ok: "El 2 de enero o el 1 de julio siguientes a su aprobación.", mal: ["El 1 de enero siguiente a su aprobación.", "A los veinte días de su publicación, en todo caso.", "El primer día del trimestre siguiente."], d: 3 }),
  lg({ id: "of-fu-20", art: "Artículo 25",
    cita: "El Gobierno aprobará anualmente un Plan Normativo que contendrá las iniciativas legislativas o reglamentarias que vayan a ser elevadas para su aprobación en el año siguiente.",
    clave: "Plan Normativo",
    e: "Según el artículo 25.1 de la Ley 50/1997, el Gobierno aprobará anualmente, con las iniciativas legislativas o reglamentarias que se elevarán para su aprobación el año siguiente:",
    ok: "Un Plan Normativo.", mal: ["Un Libro Blanco de la legislación.", "Un Código de buenas prácticas.", "Un Informe de evaluación normativa obligatorio."], d: 2 }),
  lg({ id: "of-fu-21", art: "Artículo 26",
    cita: "Se sustanciará una consulta pública, a través del portal web del departamento competente, con carácter previo a la elaboración del texto",
    clave: "consulta pública",
    e: "Según el artículo 26.2 de la Ley 50/1997, con carácter previo a la elaboración del texto de un anteproyecto de ley o de un reglamento, se sustanciará a través del portal web del departamento:",
    ok: "Una consulta pública.", mal: ["Un referéndum consultivo.", "Una votación en el Consejo de Ministros.", "Un dictamen del Consejo Económico y Social."], d: 2 }),
];

export const PRESUPUESTO: PreguntaOficial[] = [
  gp({ id: "of-gp-01", art: "Artículo 26",
    cita: "La programación presupuestaria se regirá por los principios de estabilidad presupuestaria, sostenibilidad financiera, plurianualidad, transparencia",
    clave: "estabilidad presupuestaria, sostenibilidad financiera",
    e: "Según el artículo 26.1 de la Ley General Presupuestaria, la programación presupuestaria se regirá, entre otros, por los principios de:",
    ok: "Estabilidad presupuestaria, sostenibilidad financiera, plurianualidad y transparencia.", mal: ["Unidad de caja, no afectación y anualidad estricta.", "Déficit permitido, endeudamiento libre y opacidad.", "Centralización, uniformidad y secreto."], d: 2 }),
  gp({ id: "of-gp-02", art: "Artículo 27",
    cita: "La gestión del sector público estatal está sometida al régimen de presupuesto anual aprobado por las Cortes Generales y enmarcado en los límites de un escenario plurianual.",
    clave: "escenario plurianual",
    e: "Conforme al artículo 27.1 de la Ley General Presupuestaria, la gestión del sector público estatal está sometida al régimen de presupuesto anual aprobado por las Cortes Generales y enmarcado en los límites de:",
    ok: "Un escenario plurianual.", mal: ["Un plan quinquenal.", "Un presupuesto bienal.", "Un acuerdo del Consejo de Política Fiscal y Financiera."], d: 2 }),
  gp({ id: "of-gp-03", art: "Artículo 29",
    cita: "se desarrollarán en programas plurianuales, referidos a los tres ejercicios siguientes",
    clave: "tres ejercicios siguientes",
    e: "Según el artículo 29.1 de la Ley General Presupuestaria, los escenarios presupuestarios plurianuales se desarrollarán en programas plurianuales referidos a:",
    ok: "Los tres ejercicios siguientes.", mal: ["Los dos ejercicios siguientes.", "Los cinco ejercicios siguientes.", "Toda la legislatura."], d: 2 }),
  gp({ id: "of-gp-04", art: "Artículo 35",
    cita: "Son créditos presupuestarios cada una de las asignaciones individualizadas de gasto",
    clave: "asignaciones individualizadas de gasto",
    e: "Según el artículo 35.1 de la Ley General Presupuestaria, son créditos presupuestarios:",
    ok: "Cada una de las asignaciones individualizadas de gasto que figuran en los presupuestos.", mal: ["Los préstamos que el Estado concede a las Comunidades Autónomas.", "Las previsiones de ingresos tributarios.", "Los avales concedidos por el Tesoro."], d: 1 }),
  gp({ id: "of-gp-05", art: "Artículo 38",
    cita: "se considerarán automáticamente prorrogados los presupuestos iniciales del ejercicio anterior hasta la aprobación y publicación de los nuevos",
    clave: "presupuestos iniciales del ejercicio anterior",
    e: "Si la Ley de Presupuestos no se aprueba antes del primer día del ejercicio, el artículo 38.1 de la Ley General Presupuestaria dispone que se prorrogan automáticamente:",
    ok: "Los presupuestos iniciales del ejercicio anterior.", mal: ["Los presupuestos liquidados del ejercicio anterior, con sus modificaciones.", "El proyecto de presupuestos presentado por el Gobierno.", "Los presupuestos de hace dos ejercicios."], d: 2 }),
  gp({ id: "of-gp-06", art: "Artículo 38",
    cita: "La prórroga no afectará a los créditos para gastos correspondientes a programas o actuaciones que terminen en el ejercicio cuyos presupuestos se prorrogan",
    clave: "programas o actuaciones que terminen en el ejercicio",
    e: "Según el artículo 38.2 de la Ley General Presupuestaria, la prórroga presupuestaria no afectará a los créditos para gastos correspondientes a:",
    ok: "Programas o actuaciones que terminen en el ejercicio cuyos presupuestos se prorrogan.", mal: ["Gastos de personal.", "Intereses de la Deuda Pública.", "Pensiones de Clases Pasivas."], d: 3 }),
  gp({ id: "of-gp-07", art: "Artículo 42",
    cita: "Los créditos para gastos se destinarán exclusivamente a la finalidad específica para la que hayan sido autorizados",
    clave: "finalidad específica",
    e: "Conforme al artículo 42 de la Ley General Presupuestaria (especialidad cualitativa), los créditos para gastos se destinarán exclusivamente:",
    ok: "A la finalidad específica para la que hayan sido autorizados.", mal: ["A cualquier gasto del mismo Ministerio.", "Al gasto que decida el centro gestor durante el ejercicio.", "A gastos corrientes, en todo caso."], d: 1 }),
  gp({ id: "of-gp-08", art: "Artículo 46",
    cita: "Los créditos para gastos son limitativos.",
    clave: "limitativos",
    e: "Según el artículo 46 de la Ley General Presupuestaria, los créditos para gastos son:",
    ok: "Limitativos.", mal: ["Estimativos.", "Orientativos.", "Ampliables en todo caso."], d: 1 }),
  gp({ id: "of-gp-09", art: "Artículo 46",
    cita: "siendo nulos de pleno derecho los actos administrativos y las disposiciones generales con rango inferior a ley que incumplan esta limitación",
    clave: "nulos de pleno derecho",
    e: "Conforme al artículo 46 de la Ley General Presupuestaria, los actos administrativos y disposiciones de rango inferior a ley que comprometan gasto por encima de los créditos autorizados son:",
    ok: "Nulos de pleno derecho.", mal: ["Anulables a instancia de parte.", "Válidos si se convalidan al cierre del ejercicio.", "Irregulares sin consecuencias jurídicas."], d: 2 }),
  gp({ id: "of-gp-10", art: "Artículo 47",
    cita: "El número de ejercicios a que pueden aplicarse los gastos no será superior a cuatro.",
    clave: "cuatro",
    e: "Según el artículo 47.2 de la Ley General Presupuestaria, en los compromisos de gasto plurianuales el número de ejercicios a que pueden aplicarse los gastos no será superior a:",
    ok: "Cuatro.", mal: ["Tres.", "Cinco.", "Seis."], d: 2 }),
  gp({ id: "of-gp-11", art: "Artículo 47",
    cita: "en el ejercicio inmediato siguiente, el 70  por ciento, en el segundo ejercicio, el 60 por ciento, y en los ejercicios tercero y cuarto, el 50 por ciento",
    clave: "el 70 por ciento",
    e: "En los gastos plurianuales, el artículo 47.2 de la Ley General Presupuestaria limita el gasto imputable al ejercicio inmediato siguiente a:",
    ok: "El 70 por ciento del crédito inicial.", mal: ["El 60 por ciento del crédito inicial.", "El 50 por ciento del crédito inicial.", "El 100 por ciento del crédito inicial."], m: "Plurianuales: 70 – 60 – 50 – 50.", d: 3 }),
  gp({ id: "of-gp-12", art: "Artículo 49",
    cita: "quedarán anulados de pleno derecho",
    clave: "quedarán anulados de pleno derecho",
    e: "Según el artículo 49.2 de la Ley General Presupuestaria, los créditos para gastos que el último día del ejercicio no estén afectados al cumplimiento de obligaciones ya reconocidas:",
    ok: "Quedarán anulados de pleno derecho, salvo lo previsto en el artículo 58.", mal: ["Se incorporan automáticamente al ejercicio siguiente.", "Se transfieren al Fondo de Contingencia.", "Se mantienen vigentes hasta su liquidación."], d: 2 }),
  gp({ id: "of-gp-13", art: "Artículo 51",
    cita: "b) Generaciones.",
    clave: "Generaciones",
    e: "¿Cuál de las siguientes es una modificación presupuestaria prevista en el artículo 51 de la Ley General Presupuestaria?",
    ok: "Generaciones de crédito.", mal: ["Reducciones fiscales.", "Anticipos de tesorería.", "Avales del Estado."], d: 2 }),
  gp({ id: "of-gp-14", art: "Artículo 52",
    cita: "Las transferencias son traspasos de dotaciones entre créditos.",
    clave: "traspasos de dotaciones entre créditos",
    e: "Según el artículo 52.1 de la Ley General Presupuestaria, las transferencias de crédito son:",
    ok: "Traspasos de dotaciones entre créditos.", mal: ["Aumentos de crédito financiados con nuevos ingresos.", "Créditos nuevos para gastos imprevistos.", "Pagos del Estado a otras Administraciones."], d: 1 }),
  gp({ id: "of-gp-15", art: "Artículo 52",
    cita: "No podrán realizarse entre créditos de distintas secciones presupuestarias.",
    clave: "distintas secciones presupuestarias",
    e: "Entre las restricciones de las transferencias de crédito, el artículo 52.1.b) de la Ley General Presupuestaria establece que no podrán realizarse entre créditos de:",
    ok: "Distintas secciones presupuestarias, salvo el programa de contratación centralizada.", mal: ["Un mismo programa.", "Un mismo servicio presupuestario.", "Igual clasificación económica."], d: 3 }),
  gp({ id: "of-gp-16", art: "Artículo 54",
    cita: "Excepcionalmente tendrán la condición de ampliables los créditos destinados al pago de pensiones de Clases Pasivas del Estado",
    clave: "pensiones de Clases Pasivas",
    e: "Según el artículo 54.1 de la Ley General Presupuestaria, tienen excepcionalmente la condición de ampliables, entre otros, los créditos destinados al pago de:",
    ok: "Pensiones de Clases Pasivas del Estado.", mal: ["Subvenciones nominativas a partidos políticos.", "Gastos protocolarios de los Ministerios.", "Retribuciones de altos cargos."], d: 2 }),
  gp({ id: "of-gp-17", art: "Artículo 55",
    cita: "deberá procederse a la tramitación de un crédito extraordinario o suplementario del inicialmente previsto",
    clave: "crédito extraordinario o suplementario",
    e: "Si debe realizarse un gasto que no puede demorarse al ejercicio siguiente y no existe crédito adecuado, o es insuficiente y no ampliable, el artículo 55.1 de la Ley General Presupuestaria prevé tramitar:",
    ok: "Un crédito extraordinario o suplementario.", mal: ["Una transferencia entre secciones.", "Una incorporación de remanentes.", "Un anticipo de caja fija."], d: 2 }),
];
