// GSI tema 5, ciberseguridad: Esquema Nacional de Seguridad (RD 311/2022,
// BOE-A-2022-7191) y seguridad de las redes y sistemas de información
// (RDL 12/2018, BOE-A-2018-12257). No repite los artículos del ENS que ya
// llegan de TAI (5, 6, 12, 31 y 40).
import type { Destino, NormaOficial, PreguntaOficial } from "./tipos";

const T5: Destino[] = [["gestion-sistemas-informacion", 5]];
const f = (norma: NormaOficial) => (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma, destinos: T5, ...x });
const en = f("ENS");
const nis = f("RDL12");

export const CIBER: PreguntaOficial[] = [
  en({ id: "of-ci-01", art: "Artículo 1",
    cita: "establecido en el artículo 156.2 de la Ley 40/2015",
    clave: "artículo 156.2 de la Ley 40/2015",
    e: "Según el artículo 1.1 del Real Decreto 311/2022, el Esquema Nacional de Seguridad está establecido en:",
    ok: "El artículo 156.2 de la Ley 40/2015, de Régimen Jurídico del Sector Público.", mal: ["El artículo 18.4 de la Constitución.", "El Reglamento (UE) 2016/679.", "La Ley 9/2014, General de Telecomunicaciones."], d: 2 }),
  en({ id: "of-ci-02", art: "Artículo 1",
    cita: "El ENS está constituido por los principios básicos y requisitos mínimos necesarios para una protección adecuada de la información tratada y los servicios prestados",
    clave: "principios básicos y requisitos mínimos",
    e: "Conforme al artículo 1.2 del Real Decreto 311/2022, el ENS está constituido por:",
    ok: "Los principios básicos y requisitos mínimos necesarios para una protección adecuada de la información y los servicios.", mal: ["Un catálogo de productos de seguridad obligatorios.", "Las sanciones por incidentes de seguridad.", "La lista de prestadores cualificados de confianza."], d: 1 }),
  en({ id: "of-ci-03", art: "Artículo 2",
    cita: "El presente real decreto es de aplicación a todo el sector público, en los términos en que este se define por el artículo 2 de la Ley 40/2015",
    clave: "todo el sector público",
    e: "Según el artículo 2.1 del Real Decreto 311/2022, el ENS es de aplicación a:",
    ok: "Todo el sector público, en los términos del artículo 2 de la Ley 40/2015.", mal: ["Solo la Administración General del Estado.", "Solo las empresas privadas de servicios esenciales.", "Solo las Comunidades Autónomas que se adhieran."], d: 1 }),
  en({ id: "of-ci-04", art: "Artículo 2",
    cita: "este real decreto será de aplicación a los sistemas que tratan información clasificada, pudiendo resultar necesario adoptar medidas complementarias de seguridad",
    clave: "información clasificada",
    e: "Conforme al artículo 2.2 del Real Decreto 311/2022, sin perjuicio de la Ley de Secretos Oficiales, el ENS se aplica también a los sistemas que tratan:",
    ok: "Información clasificada, pudiendo exigirse medidas complementarias de seguridad.", mal: ["Únicamente información pública.", "Datos de redes sociales.", "Solo datos de carácter personal."], d: 2 }),
  en({ id: "of-ci-05", art: "Artículo 7",
    cita: "El análisis y la gestión de los riesgos es parte esencial del proceso de seguridad, debiendo constituir una actividad continua y permanentemente actualizada.",
    clave: "actividad continua y permanentemente actualizada",
    e: "Según el artículo 7.1 del Real Decreto 311/2022, el análisis y la gestión de los riesgos deben constituir:",
    ok: "Una actividad continua y permanentemente actualizada.", mal: ["Una actividad puntual al implantar el sistema.", "Una auditoría cada cinco años.", "Una tarea opcional para sistemas de categoría básica."], d: 1 }),
  en({ id: "of-ci-06", art: "Artículo 7",
    cita: "La gestión de los riesgos permitirá el mantenimiento de un entorno controlado, minimizando los riesgos a niveles aceptables.",
    clave: "niveles aceptables",
    e: "Conforme al artículo 7.2 del Real Decreto 311/2022, la gestión de los riesgos permitirá mantener un entorno controlado, minimizando los riesgos a:",
    ok: "Niveles aceptables.", mal: ["Cero en todo caso.", "Niveles fijados por el proveedor.", "Niveles máximos tolerables por la ley penal."], d: 1 }),
  en({ id: "of-ci-07", art: "Artículo 8",
    cita: "La seguridad del sistema debe contemplar las acciones relativas a los aspectos de prevención, detección y respuesta",
    clave: "prevención, detección y respuesta",
    e: "Según el artículo 8.1 del Real Decreto 311/2022, la seguridad del sistema debe contemplar las acciones relativas a los aspectos de:",
    ok: "Prevención, detección y respuesta.", mal: ["Compra, instalación y retirada.", "Diseño, venta y facturación.", "Publicidad, difusión y archivo."], d: 1 }),
  en({ id: "of-ci-08", art: "Artículo 9",
    cita: "El sistema de información ha de disponer de una estrategia de protección constituida por múltiples capas de seguridad",
    clave: "múltiples capas de seguridad",
    e: "Conforme al artículo 9.1 del Real Decreto 311/2022 (líneas de defensa), el sistema de información debe disponer de una estrategia de protección constituida por:",
    ok: "Múltiples capas de seguridad.", mal: ["Un único cortafuegos perimetral.", "Una sola contraseña robusta.", "Un antivirus en cada equipo, exclusivamente."], d: 1 }),
  en({ id: "of-ci-09", art: "Artículo 9",
    cita: "Las líneas de defensa han de estar constituidas por medidas de naturaleza organizativa, física y lógica.",
    clave: "organizativa, física y lógica",
    e: "Según el artículo 9.2 del Real Decreto 311/2022, las líneas de defensa han de estar constituidas por medidas de naturaleza:",
    ok: "Organizativa, física y lógica.", mal: ["Exclusivamente lógica.", "Jurídica y económica.", "Física y comercial."], d: 2 }),
  en({ id: "of-ci-10", art: "Artículo 10",
    cita: "La vigilancia continua permitirá la detección de actividades o comportamientos anómalos y su oportuna respuesta.",
    clave: "comportamientos anómalos",
    e: "Conforme al artículo 10.1 del Real Decreto 311/2022, la vigilancia continua permitirá:",
    ok: "La detección de actividades o comportamientos anómalos y su oportuna respuesta.", mal: ["Sustituir las copias de seguridad.", "Eliminar la necesidad de auditorías.", "Controlar el horario del personal."], d: 1 }),
  en({ id: "of-ci-11", art: "Artículo 11",
    cita: "En los sistemas de información se diferenciará el responsable de la información, el responsable del servicio, el responsable de la seguridad y el responsable del sistema.",
    clave: "el responsable de la seguridad y el responsable del sistema",
    e: "Según el artículo 11.1 del Real Decreto 311/2022, en los sistemas de información se diferenciará el responsable de la información, el responsable del servicio,",
    ok: "El responsable de la seguridad y el responsable del sistema.", mal: ["El responsable de compras y el responsable jurídico.", "El delegado de protección de datos y el auditor externo.", "El jefe de personal y el interventor."], m: "Cuatro responsables: Información, Servicio, Seguridad y Sistema.", d: 2 }),
  en({ id: "of-ci-12", art: "Artículo 11",
    cita: "La responsabilidad de la seguridad de los sistemas de información estará diferenciada de la responsabilidad sobre la explotación de los sistemas de información concernidos.",
    clave: "diferenciada de la responsabilidad sobre la explotación",
    e: "Conforme al artículo 11.2 del Real Decreto 311/2022, la responsabilidad de la seguridad de los sistemas de información estará:",
    ok: "Diferenciada de la responsabilidad sobre la explotación de esos sistemas.", mal: ["Unida a la explotación de los sistemas en la misma persona.", "Atribuida en exclusiva al proveedor externo.", "Asignada al usuario final."], d: 2 }),
  en({ id: "of-ci-13", art: "Artículo 13",
    cita: "La seguridad de los sistemas de información deberá comprometer a todos los miembros de la organización.",
    clave: "todos los miembros de la organización",
    e: "Según el artículo 13.1 del Real Decreto 311/2022, la seguridad de los sistemas de información deberá comprometer a:",
    ok: "Todos los miembros de la organización.", mal: ["Solo al personal técnico de sistemas.", "Solo a la alta dirección.", "Solo a los proveedores externos."], d: 1 }),
  en({ id: "of-ci-14", art: "Artículo 14",
    cita: "Cada organización que desarrolle e implante sistemas para el tratamiento de la información o la prestación de servicios realizará su propia gestión de riesgos.",
    clave: "su propia gestión de riesgos",
    e: "Conforme al artículo 14.1 del Real Decreto 311/2022, cada organización que desarrolle e implante sistemas de información:",
    ok: "Realizará su propia gestión de riesgos.", mal: ["Utilizará la gestión de riesgos del CCN sin adaptarla.", "Está exenta de gestionar riesgos si usa la nube.", "Delegará siempre la gestión de riesgos en el proveedor."], d: 1 }),
  en({ id: "of-ci-15", art: "Artículo 14",
    cita: "se empleará alguna metodología reconocida internacionalmente",
    clave: "metodología reconocida internacionalmente",
    e: "Según el artículo 14.2 del Real Decreto 311/2022, para el análisis y tratamiento de los riesgos se empleará:",
    ok: "Alguna metodología reconocida internacionalmente.", mal: ["Una metodología propia sin referencias externas.", "Solo la intuición del responsable de seguridad.", "Un sorteo de amenazas."], d: 2 }),
  en({ id: "of-ci-16", art: "Artículo 15",
    cita: "deberá ser formado e informado de sus deberes, obligaciones y responsabilidades en materia de seguridad",
    clave: "formado e informado",
    e: "Conforme al artículo 15.1 del Real Decreto 311/2022, el personal, propio o ajeno, relacionado con los sistemas de información deberá ser:",
    ok: "Formado e informado de sus deberes, obligaciones y responsabilidades en materia de seguridad.", mal: ["Habilitado por el Ministerio del Interior.", "Funcionario de carrera en todo caso.", "Ajeno a cualquier procedimiento de seguridad."], d: 1 }),
  en({ id: "of-ci-17", art: "Artículo 16",
    cita: "estará atendida y será revisada y auditada por personal cualificado, dedicado e instruido en todas las fases de su ciclo de vida",
    clave: "personal cualificado, dedicado e instruido",
    e: "Según el artículo 16.1 del Real Decreto 311/2022, la seguridad de los sistemas de información estará atendida, revisada y auditada por:",
    ok: "Personal cualificado, dedicado e instruido en todas las fases del ciclo de vida.", mal: ["Cualquier usuario del sistema.", "Personal de limpieza y mantenimiento.", "Los ciudadanos usuarios del servicio."], d: 1 }),
  en({ id: "of-ci-18", art: "Artículo 17",
    cita: "deberá estar limitado a los usuarios, procesos, dispositivos u otros sistemas de información, debidamente autorizados, y exclusivamente a las funciones permitidas",
    clave: "exclusivamente a las funciones permitidas",
    e: "Conforme al artículo 17 del Real Decreto 311/2022 (autorización y control de los accesos), el acceso a los sistemas deberá estar limitado a los usuarios, procesos o dispositivos debidamente autorizados y:",
    ok: "Exclusivamente a las funciones permitidas.", mal: ["A cualquier función mientras estén identificados.", "A todas las funciones en horario laboral.", "A las funciones que el usuario solicite."], d: 2 }),
  en({ id: "of-ci-19", art: "Artículo 18",
    cita: "Los sistemas de información y su infraestructura de comunicaciones asociada deberán permanecer en áreas controladas",
    clave: "áreas controladas",
    e: "Según el artículo 18 del Real Decreto 311/2022 (protección de las instalaciones), los sistemas de información y su infraestructura de comunicaciones deberán permanecer en:",
    ok: "Áreas controladas con mecanismos de acceso adecuados y proporcionales.", mal: ["Domicilios particulares del personal.", "Espacios abiertos al público.", "Cualquier lugar, si el cifrado está activado."], d: 1 }),
  en({ id: "of-ci-20", art: "Artículo 19",
    cita: "aquellos que tengan certificada la funcionalidad de seguridad relacionada con el objeto de su adquisición",
    clave: "certificada la funcionalidad de seguridad",
    e: "Conforme al artículo 19.1 del Real Decreto 311/2022, en la adquisición de productos o contratación de servicios de seguridad TIC se utilizarán, de forma proporcionada, los que tengan:",
    ok: "Certificada la funcionalidad de seguridad relacionada con el objeto de su adquisición.", mal: ["El menor precio del mercado.", "Origen nacional exclusivamente.", "Código fuente cerrado obligatoriamente."], d: 2 }),
  en({ id: "of-ci-21", art: "Artículo 20",
    cita: "Los sistemas de información deben diseñarse y configurarse otorgando los mínimos privilegios necesarios para su correcto desempeño",
    clave: "mínimos privilegios",
    e: "Según el artículo 20 del Real Decreto 311/2022, los sistemas de información deben diseñarse y configurarse otorgando:",
    ok: "Los mínimos privilegios necesarios para su correcto desempeño.", mal: ["Privilegios de administrador a todos los usuarios.", "Los privilegios que pida cada usuario.", "Acceso total durante el primer año."], d: 1 }),
  en({ id: "of-ci-22", art: "Artículo 21",
    cita: "La inclusión de cualquier elemento físico o lógico en el catálogo actualizado de activos del sistema, o su modificación, requerirá autorización formal previa.",
    clave: "autorización formal previa",
    e: "Conforme al artículo 21.1 del Real Decreto 311/2022, la inclusión o modificación de cualquier elemento físico o lógico en el catálogo de activos del sistema requerirá:",
    ok: "Autorización formal previa.", mal: ["Simple comunicación posterior.", "Ningún trámite si lo hace un técnico.", "Informe del Tribunal de Cuentas."], d: 2 }),
  en({ id: "of-ci-23", art: "Artículo 22",
    cita: "se prestará especial atención a la información almacenada o en tránsito a través de los equipos o dispositivos portátiles o móviles",
    clave: "dispositivos portátiles o móviles",
    e: "Según el artículo 22.1 del Real Decreto 311/2022, en la organización e implantación de la seguridad se prestará especial atención a la información almacenada o en tránsito en, entre otros:",
    ok: "Los equipos o dispositivos portátiles o móviles.", mal: ["Las impresoras en red, exclusivamente.", "Los documentos en papel archivados.", "Las centralitas telefónicas analógicas."], d: 2 }),
  en({ id: "of-ci-24", art: "Artículo 23",
    cita: "Se protegerá el perímetro del sistema de información, especialmente, si se conecta a redes públicas",
    clave: "si se conecta a redes públicas",
    e: "Conforme al artículo 23 del Real Decreto 311/2022, se protegerá el perímetro del sistema de información especialmente:",
    ok: "Si se conecta a redes públicas.", mal: ["Si solo funciona sin conexión.", "Si lo usan menos de diez usuarios.", "Si se ubica en un edificio de la Administración."], d: 1 }),
  en({ id: "of-ci-25", art: "Artículo 24",
    cita: "se registrarán las actividades de los usuarios, reteniendo la información estrictamente necesaria para monitorizar, analizar, investigar y documentar actividades indebidas o no autorizadas",
    clave: "estrictamente necesaria",
    e: "Según el artículo 24.1 del Real Decreto 311/2022, se registrarán las actividades de los usuarios reteniendo la información:",
    ok: "Estrictamente necesaria para monitorizar, analizar, investigar y documentar actividades indebidas.", mal: ["Completa de toda su navegación personal sin límite.", "Que decida libremente el administrador.", "Solo cuando lo autorice un juez en cada caso."], d: 2 }),
  en({ id: "of-ci-26", art: "Artículo 26",
    cita: "Los sistemas dispondrán de copias de seguridad y se establecerán los mecanismos necesarios para garantizar la continuidad de las operaciones en caso de pérdida de los medios habituales.",
    clave: "copias de seguridad",
    e: "Conforme al artículo 26 del Real Decreto 311/2022, para garantizar la continuidad de la actividad los sistemas dispondrán de:",
    ok: "Copias de seguridad y mecanismos para continuar las operaciones si se pierden los medios habituales.", mal: ["Un único servidor sin respaldo.", "Una póliza de seguro, exclusivamente.", "Un plan de comunicación en redes sociales."], d: 1 }),
  en({ id: "of-ci-27", art: "Artículo 27",
    cita: "El proceso integral de seguridad implantado deberá ser actualizado y mejorado de forma continua.",
    clave: "mejorado de forma continua",
    e: "Según el artículo 27 del Real Decreto 311/2022, el proceso integral de seguridad implantado deberá ser actualizado y:",
    ok: "Mejorado de forma continua.", mal: ["Congelado una vez certificado.", "Revisado solo tras un incidente grave.", "Sustituido cada diez años."], d: 1 }),
  en({ id: "of-ci-28", art: "Artículo 28",
    cita: "adoptarán las medidas y refuerzos de seguridad correspondientes indicados en el anexo II",
    clave: "anexo II",
    e: "Conforme al artículo 28.1 del Real Decreto 311/2022, para cumplir los requisitos mínimos las entidades adoptarán las medidas y refuerzos de seguridad indicados en:",
    ok: "El anexo II.", mal: ["El anexo I.", "El anexo IV.", "La disposición adicional primera."],
    j: "El anexo I regula las categorías de seguridad de los sistemas y el anexo II las medidas de seguridad.", d: 2 }),
  en({ id: "of-ci-29", art: "Artículo 30",
    cita: "se podrán implementar perfiles de cumplimiento específicos",
    clave: "perfiles de cumplimiento específicos",
    e: "Según el artículo 30.1 del Real Decreto 311/2022, en virtud del principio de proporcionalidad y para determinadas entidades o sectores se podrán implementar:",
    ok: "Perfiles de cumplimiento específicos.", mal: ["Exenciones totales del ENS.", "Certificados de seguridad caducados.", "Sanciones atenuadas."], d: 2 }),
  en({ id: "of-ci-30", art: "Artículo 33",
    cita: "El CCN articulará la respuesta a los incidentes de seguridad en torno a la estructura denominada CCN-CERT",
    clave: "CCN-CERT",
    e: "Conforme al artículo 33.1 del Real Decreto 311/2022, el Centro Criptológico Nacional articula la respuesta a los incidentes de seguridad en torno a la estructura denominada:",
    ok: "CCN-CERT.", mal: ["INCIBE-CERT.", "ESPDEF-CERT.", "Mando Conjunto del Ciberespacio."], d: 1 }),
  en({ id: "of-ci-31", art: "Artículo 34",
    cita: "actuará con la máxima celeridad ante cualquier agresión recibida en los sistemas de información afectados",
    clave: "máxima celeridad",
    e: "Según el artículo 34.1.a) del Real Decreto 311/2022, el CCN-CERT, a través de su servicio de apoyo técnico y de coordinación, actuará ante cualquier agresión recibida en los sistemas afectados:",
    ok: "Con la máxima celeridad.", mal: ["Solo tras autorización judicial.", "En el plazo de un mes.", "Solo si la entidad paga el servicio."], d: 2 }),
  en({ id: "of-ci-32", art: "Artículo 35",
    cita: "El CCN es el órgano competente para garantizar la debida interoperabilidad en materia de ciberseguridad y criptografía",
    clave: "El CCN",
    e: "Conforme al artículo 35.2 del Real Decreto 311/2022, ¿qué órgano es competente para garantizar la debida interoperabilidad en materia de ciberseguridad y criptografía?",
    ok: "El CCN (Centro Criptológico Nacional).", mal: ["La Agencia Española de Protección de Datos.", "La Comisión Nacional de los Mercados y la Competencia.", "La Secretaría de Estado de Seguridad."], d: 2 }),
  en({ id: "of-ci-33", art: "Artículo 36",
    cita: "Las especificaciones de seguridad se incluirán en el ciclo de vida de los servicios y sistemas, acompañadas de los correspondientes procedimientos de control.",
    clave: "ciclo de vida",
    e: "Según el artículo 36 del Real Decreto 311/2022, las especificaciones de seguridad se incluirán:",
    ok: "En el ciclo de vida de los servicios y sistemas, con sus procedimientos de control.", mal: ["Solo en el contrato de mantenimiento.", "Al final del proyecto, tras su puesta en producción.", "En un anexo opcional del pliego."], d: 1 }),
  en({ id: "of-ci-34", art: "Artículo 38",
    cita: "los sistemas de categoría MEDIA o ALTA precisarán de una auditoría para la certificación de su conformidad",
    clave: "auditoría para la certificación",
    e: "Conforme al artículo 38.1 del Real Decreto 311/2022, para determinar su conformidad con el ENS los sistemas de categoría MEDIA o ALTA precisarán de:",
    ok: "Una auditoría para la certificación de su conformidad.", mal: ["Una simple autoevaluación.", "Ningún procedimiento de conformidad.", "Una declaración del proveedor."], d: 2 }),
  en({ id: "of-ci-35", art: "Artículo 38",
    cita: "mientras que los sistemas de categoría BÁSICA solo requerirán de una autoevaluación para su declaración de la conformidad",
    clave: "autoevaluación",
    e: "Según el artículo 38.1 del Real Decreto 311/2022, los sistemas de categoría BÁSICA, para su declaración de conformidad con el ENS, solo requerirán:",
    ok: "Una autoevaluación.", mal: ["Una auditoría de certificación anual.", "Una inspección del CCN in situ.", "Un informe del Consejo de Estado."], m: "BÁSICA → autoevaluación; MEDIA y ALTA → auditoría de certificación.", d: 2 }),
  en({ id: "of-ci-36", art: "Artículo 41",
    cita: "la determinación de la categoría de seguridad del sistema corresponderá al responsable o responsables de la seguridad",
    clave: "responsable o responsables de la seguridad",
    e: "Conforme al artículo 41.2 del Real Decreto 311/2022, con base en las valoraciones de la información y los servicios, la determinación de la categoría de seguridad del sistema corresponde:",
    ok: "Al responsable o responsables de la seguridad.", mal: ["Al responsable del sistema.", "Al usuario final.", "Al proveedor del servicio en la nube."],
    j: "Las valoraciones de la información y de los servicios corresponden a sus responsables (artículo 41.1).", d: 3 }),
  en({ id: "of-ci-37", art: "Artículo 41",
    cita: "La facultad para efectuar las valoraciones a las que se refiere el artículo 40, así como, en su caso, su posterior modificación, corresponderá al responsable o responsables de la información o servicios afectados.",
    clave: "responsable o responsables de la información o servicios",
    e: "Según el artículo 41.1 del Real Decreto 311/2022, la facultad para efectuar las valoraciones de impacto del artículo 40 corresponde:",
    ok: "Al responsable o responsables de la información o servicios afectados.", mal: ["Al responsable de la seguridad, exclusivamente.", "Al Centro Criptológico Nacional.", "Al auditor externo."], d: 3 }),
  nis({ id: "of-ci-38", art: "Artículo 1",
    cita: "regular la seguridad de las redes y sistemas de información utilizados para la provisión de los servicios esenciales y de los servicios digitales, y establecer un sistema de notificación de incidentes",
    clave: "sistema de notificación de incidentes",
    e: "Según el artículo 1.1 del Real Decreto-ley 12/2018, su objeto es regular la seguridad de las redes y sistemas de información de los servicios esenciales y digitales y establecer:",
    ok: "Un sistema de notificación de incidentes.", mal: ["Un registro de dominios de internet.", "Un régimen de precios de las telecomunicaciones.", "El catálogo de productos certificados."], d: 1 }),
  nis({ id: "of-ci-39", art: "Artículo 2",
    cita: "que sean mercados en línea, motores de búsqueda en línea y servicios de computación en nube",
    clave: "motores de búsqueda en línea",
    e: "Conforme al artículo 2.1.b) del Real Decreto-ley 12/2018, los servicios digitales incluidos en su ámbito son:",
    ok: "Mercados en línea, motores de búsqueda en línea y servicios de computación en nube.", mal: ["Redes sociales, videojuegos y correo electrónico.", "Banca en línea, seguros y bolsa.", "Televisión, radio y prensa digital."], d: 2 }),
  nis({ id: "of-ci-40", art: "Artículo 2",
    cita: "Los servicios esenciales dependientes de las redes y sistemas de información comprendidos en los sectores estratégicos definidos en el anexo de la Ley 8/2011",
    clave: "sectores estratégicos",
    e: "Según el artículo 2.1.a) del Real Decreto-ley 12/2018, se aplica a los servicios esenciales dependientes de redes y sistemas de información comprendidos en:",
    ok: "Los sectores estratégicos definidos en el anexo de la Ley 8/2011, de infraestructuras críticas.", mal: ["El catálogo de la Agencia Tributaria.", "Los sectores con más de 250 trabajadores.", "Las empresas cotizadas en bolsa."], d: 2 }),
  nis({ id: "of-ci-41", art: "Artículo 5",
    cita: "Lo dispuesto en este real decreto-ley se entenderá sin perjuicio de las acciones emprendidas para salvaguardar la seguridad nacional y las funciones estatales esenciales",
    clave: "seguridad nacional",
    e: "Conforme al artículo 5 del Real Decreto-ley 12/2018, lo dispuesto en él se entiende sin perjuicio de las acciones emprendidas para salvaguardar:",
    ok: "La seguridad nacional y las funciones estatales esenciales.", mal: ["Los beneficios de los operadores.", "La libre competencia en los mercados digitales.", "Los derechos de autor en la red."], d: 2 }),
  nis({ id: "of-ci-42", art: "Artículo 6",
    cita: "La relación de los servicios esenciales y de los operadores de dichos servicios se actualizará, para cada sector, con una frecuencia bienal",
    clave: "bienal",
    e: "Según el artículo 6.1 del Real Decreto-ley 12/2018, la relación de los servicios esenciales y de sus operadores se actualizará, para cada sector, con una frecuencia:",
    ok: "Bienal.", mal: ["Anual.", "Quinquenal.", "Mensual."], d: 2 }),
  nis({ id: "of-ci-43", art: "Artículo 7",
    cita: "Los proveedores de servicios digitales señalados en el artículo 2 deberán comunicar su actividad a la autoridad competente en el plazo de tres meses desde que la inicien",
    clave: "tres meses",
    e: "Conforme al artículo 7 del Real Decreto-ley 12/2018, los proveedores de servicios digitales deben comunicar su actividad a la autoridad competente en el plazo de:",
    ok: "Tres meses desde que la inicien.", mal: ["Un mes desde que la inicien.", "Seis meses desde que la inicien.", "Diez días antes de iniciarla."], d: 2 }),
  nis({ id: "of-ci-44", art: "Artículo 8",
    cita: "La Estrategia de Ciberseguridad Nacional, al amparo y alineada con la Estrategia de Seguridad Nacional",
    clave: "Estrategia de Seguridad Nacional",
    e: "Según el artículo 8 del Real Decreto-ley 12/2018, la Estrategia de Ciberseguridad Nacional está al amparo y alineada con:",
    ok: "La Estrategia de Seguridad Nacional.", mal: ["El Plan Anual Normativo.", "La Agenda Digital Europea, exclusivamente.", "El Plan de Recuperación, Transformación y Resiliencia."], d: 2 }),
  nis({ id: "of-ci-45", art: "Artículo 9",
    cita: "la Secretaría de Estado de Seguridad, del Ministerio del Interior, a través del Centro Nacional de Protección de Infraestructuras y Ciberseguridad",
    clave: "Centro Nacional de Protección de Infraestructuras y Ciberseguridad",
    e: "Para los operadores de servicios esenciales que además sean operadores críticos, el artículo 9.1.a) del Real Decreto-ley 12/2018 designa como autoridad competente a la Secretaría de Estado de Seguridad a través de:",
    ok: "El Centro Nacional de Protección de Infraestructuras y Ciberseguridad (CNPIC).", mal: ["La Agencia Española de Protección de Datos.", "El Instituto Nacional de Estadística.", "La Dirección General de la Policía, exclusivamente."], d: 3 }),
  nis({ id: "of-ci-46", art: "Artículo 11",
    cita: "El CCN-CERT, del Centro Criptológico Nacional, al que corresponde la comunidad de referencia constituida por las entidades del ámbito subjetivo de aplicación de la Ley 40/2015",
    clave: "CCN-CERT",
    e: "Según el artículo 11.1.a) del Real Decreto-ley 12/2018, el CSIRT de referencia para las entidades del ámbito subjetivo de la Ley 40/2015 (sector público) es:",
    ok: "El CCN-CERT, del Centro Criptológico Nacional.", mal: ["El INCIBE-CERT.", "El ESPDEF-CERT del Ministerio de Defensa.", "El CSIRT de la CNMC."], d: 2 }),
  nis({ id: "of-ci-47", art: "Artículo 11",
    cita: "2.º El INCIBE-CERT, del Instituto Nacional de Ciberseguridad de España",
    clave: "INCIBE-CERT",
    e: "Además del CCN-CERT, ¿qué otro CSIRT de referencia para los operadores de servicios esenciales recoge el artículo 11.1.a) del Real Decreto-ley 12/2018?",
    ok: "El INCIBE-CERT, del Instituto Nacional de Ciberseguridad de España.", mal: ["El CERT de la Unión Internacional de Telecomunicaciones.", "El CSIRT del Banco de España, en todo caso.", "El CERT de la Guardia Civil."], d: 2 }),
  nis({ id: "of-ci-48", art: "Artículo 13",
    cita: "El Consejo de Seguridad Nacional ejercerá, a través del Departamento de Seguridad Nacional, una función de enlace",
    clave: "Departamento de Seguridad Nacional",
    e: "Conforme al artículo 13 del Real Decreto-ley 12/2018, el Consejo de Seguridad Nacional ejerce la función de enlace para la cooperación transfronteriza a través de:",
    ok: "El Departamento de Seguridad Nacional.", mal: ["El Ministerio de Asuntos Exteriores.", "La Agencia de la Unión Europea para la Ciberseguridad.", "El Centro Nacional de Inteligencia, exclusivamente."], d: 3 }),
  nis({ id: "of-ci-49", art: "Artículo 16",
    cita: "deberán adoptar medidas técnicas y de organización, adecuadas y proporcionadas, para gestionar los riesgos",
    clave: "adecuadas y proporcionadas",
    e: "Según el artículo 16.1 del Real Decreto-ley 12/2018, los operadores de servicios esenciales y los proveedores de servicios digitales deberán adoptar medidas técnicas y de organización:",
    ok: "Adecuadas y proporcionadas, para gestionar los riesgos para la seguridad de sus redes y sistemas.", mal: ["Las que establezca cada cliente.", "Solo de carácter jurídico.", "Idénticas para todos los sectores, sin graduación."], d: 1 }),
  nis({ id: "of-ci-50", art: "Artículo 19",
    cita: "Los operadores de servicios esenciales notificarán a la autoridad competente, a través del CSIRT de referencia, los incidentes que puedan tener efectos perturbadores significativos en dichos servicios.",
    clave: "a través del CSIRT de referencia",
    e: "Conforme al artículo 19.1 del Real Decreto-ley 12/2018, los operadores de servicios esenciales notifican los incidentes con efectos perturbadores significativos a la autoridad competente:",
    ok: "A través del CSIRT de referencia.", mal: ["A través de una nota de prensa.", "Directamente a la Comisión Europea, exclusivamente.", "A través de los usuarios afectados."], d: 2 }),
  nis({ id: "of-ci-51", art: "Artículo 20",
    cita: "Las notificaciones consideradas en este título no sujetarán a la entidad que las efectúe a una mayor responsabilidad.",
    clave: "no sujetarán a la entidad que las efectúe a una mayor responsabilidad",
    e: "Según el artículo 20.1 del Real Decreto-ley 12/2018, las notificaciones de incidentes:",
    ok: "No sujetarán a la entidad que las efectúe a una mayor responsabilidad.", mal: ["Suponen la apertura automática de un expediente sancionador.", "Obligan a indemnizar a todos los usuarios.", "Se publican siempre en el BOE."], d: 2 }),
  nis({ id: "of-ci-52", art: "Artículo 20",
    cita: "no podrán sufrir consecuencias adversas en su puesto de trabajo o con la empresa, salvo en los supuestos en que se acredite mala fe en su actuación",
    clave: "salvo en los supuestos en que se acredite mala fe",
    e: "Conforme al artículo 20.2 del Real Decreto-ley 12/2018, los empleados que informen sobre incidentes no podrán sufrir consecuencias adversas en su puesto de trabajo:",
    ok: "Salvo en los supuestos en que se acredite mala fe en su actuación.", mal: ["Salvo que el incidente afecte a más de mil usuarios.", "Salvo que no lo comuniquen antes a su superior.", "En ningún caso, aunque actúen de mala fe."], d: 2 }),
  nis({ id: "of-ci-53", art: "Artículo 21",
    cita: "b) La duración del incidente.",
    clave: "La duración del incidente",
    e: "¿Cuál de los siguientes factores se tiene en cuenta, según el artículo 21.1 del Real Decreto-ley 12/2018, para determinar la importancia de un incidente en un servicio esencial?",
    ok: "La duración del incidente.", mal: ["El país de origen del atacante.", "El sistema operativo afectado.", "La antigüedad de los equipos."], d: 1 }),
  nis({ id: "of-ci-54", art: "Artículo 22",
    cita: "Los operadores de servicios esenciales deberán realizar una primera notificación de los incidentes a los que se refiere el artículo 19.1 sin dilación indebida.",
    clave: "sin dilación indebida",
    e: "Según el artículo 22.1 del Real Decreto-ley 12/2018, los operadores de servicios esenciales deben realizar la primera notificación de los incidentes significativos:",
    ok: "Sin dilación indebida.", mal: ["En el plazo de un mes.", "Una vez resuelto el incidente.", "Solo si lo solicita la autoridad competente."], d: 2 }),
  nis({ id: "of-ci-55", art: "Artículo 26",
    cita: "La autoridad competente podrá exigir a los operadores de servicios esenciales o a los proveedores de servicios digitales que informen al público o a terceros potencialmente interesados sobre los incidentes",
    clave: "informen al público",
    e: "Conforme al artículo 26.1 del Real Decreto-ley 12/2018, la autoridad competente puede exigir a los operadores y proveedores que:",
    ok: "Informen al público o a terceros potencialmente interesados sobre los incidentes, cuando sea necesario.", mal: ["Cierren temporalmente su servicio.", "Indemnicen a la Administración.", "Cambien de proveedor de nube."], d: 2 }),
  nis({ id: "of-ci-56", art: "Artículo 30",
    cita: "su tratamiento se restringirá a los que sean estrictamente adecuados, pertinentes y limitados a lo necesario en relación con la finalidad",
    clave: "estrictamente adecuados, pertinentes y limitados",
    e: "Según el artículo 30 del Real Decreto-ley 12/2018, si la gestión de un incidente requiere comunicar datos personales, su tratamiento se restringirá a los que sean:",
    ok: "Estrictamente adecuados, pertinentes y limitados a lo necesario para la finalidad.", mal: ["Todos los que tenga el operador.", "Los que pida la prensa.", "Los que autorice el propio atacante."], d: 2 }),
  nis({ id: "of-ci-57", art: "Artículo 33",
    cita: "sólo inspeccionará el cumplimiento de las obligaciones derivadas de este real decreto-ley cuando tenga noticia de algún incumplimiento",
    clave: "cuando tenga noticia de algún incumplimiento",
    e: "Conforme al artículo 33.1 del Real Decreto-ley 12/2018, la autoridad competente para la supervisión de los servicios digitales sólo inspeccionará el cumplimiento de las obligaciones:",
    ok: "Cuando tenga noticia de algún incumplimiento, incluida petición razonada o denuncia.", mal: ["De forma periódica cada año en todo caso.", "Nunca, porque los servicios digitales están exentos.", "Solo a petición del propio proveedor."], d: 3 }),
  nis({ id: "of-ci-58", art: "Artículo 36",
    cita: "Las infracciones de los preceptos de este real decreto-ley se clasifican en muy graves, graves y leves.",
    clave: "muy graves, graves y leves",
    e: "Según el artículo 36.1 del Real Decreto-ley 12/2018, sus infracciones se clasifican en:",
    ok: "Muy graves, graves y leves.", mal: ["Graves y leves.", "Penales, civiles y administrativas.", "Muy graves y graves."], d: 1 }),
];
