// Ley Orgánica 3/2018, de Protección de Datos Personales y garantía de los
// derechos digitales (BOE-A-2018-16673): GSI tema 5 (ciberseguridad) y
// Correos tema 10 (normativa postal y protección de datos). No repite los
// artículos 5, 7, 32 y 37, que ya pregunta el banco BOE de TAI.
import type { Destino, PreguntaOficial } from "./tipos";

const D: Destino[] = [["gestion-sistemas-informacion", 5], ["correos", 10]];
const pd = (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma: "LOPDGDD", destinos: D, ...x });

export const DATOS: PreguntaOficial[] = [
  pd({ id: "of-pd-01", art: "Artículo 1",
    cita: "Adaptar el ordenamiento jurídico español al Reglamento (UE) 2016/679",
    clave: "2016/679",
    e: "Según su artículo 1.a), la Ley Orgánica 3/2018 tiene por objeto adaptar el ordenamiento jurídico español al Reglamento (UE):",
    ok: "2016/679, general de protección de datos.", mal: ["910/2014, de identificación electrónica.", "2022/2065, de servicios digitales.", "2024/1689, de inteligencia artificial."], d: 1 }),
  pd({ id: "of-pd-02", art: "Artículo 3",
    cita: "Las personas vinculadas al fallecido por razones familiares o de hecho así como sus herederos podrán dirigirse al responsable o encargado del tratamiento al objeto de solicitar el acceso a los datos personales de aquella",
    clave: "herederos",
    e: "Según el artículo 3.1 de la Ley Orgánica 3/2018, ¿quiénes pueden solicitar al responsable el acceso a los datos personales de una persona fallecida y, en su caso, su rectificación o supresión?",
    ok: "Las personas vinculadas al fallecido por razones familiares o de hecho y sus herederos.", mal: ["Solo el Ministerio Fiscal.", "Cualquier persona que lo solicite.", "Solo la Agencia Española de Protección de Datos."], d: 2 }),
  pd({ id: "of-pd-03", art: "Artículo 3",
    cita: "cuando la persona fallecida lo hubiese prohibido expresamente o así lo establezca una ley",
    clave: "prohibido expresamente",
    e: "Conforme al artículo 3.1 de la Ley Orgánica 3/2018, los familiares y herederos no podrán acceder a los datos del fallecido ni pedir su rectificación o supresión cuando:",
    ok: "La persona fallecida lo hubiese prohibido expresamente o así lo establezca una ley.", mal: ["Hayan pasado más de seis meses desde el fallecimiento.", "El responsable sea una Administración Pública.", "Los datos estén en soporte electrónico."], d: 2 }),
  pd({ id: "of-pd-04", art: "Artículo 6",
    cita: "toda manifestación de voluntad libre, específica, informada e inequívoca por la que este acepta, ya sea mediante una declaración o una clara acción afirmativa",
    clave: "libre, específica, informada e inequívoca",
    e: "Según el artículo 6.1 de la Ley Orgánica 3/2018, el consentimiento del afectado es toda manifestación de voluntad:",
    ok: "Libre, específica, informada e inequívoca, mediante una declaración o una clara acción afirmativa.", mal: ["Tácita, que se presume si el afectado no se opone.", "Verbal o por silencio, indistintamente.", "Genérica para cualquier finalidad futura."], d: 1 }),
  pd({ id: "of-pd-05", art: "Artículo 9",
    cita: "el solo consentimiento del afectado no bastará para levantar la prohibición del tratamiento de datos cuya finalidad principal sea identificar su ideología, afiliación sindical, religión, orientación sexual, creencias u origen racial o étnico",
    clave: "no bastará",
    e: "Conforme al artículo 9.1 de la Ley Orgánica 3/2018, para levantar la prohibición del tratamiento de datos cuya finalidad principal sea identificar la ideología, religión u origen racial de una persona, el solo consentimiento del afectado:",
    ok: "No bastará.", mal: ["Es suficiente en todo caso.", "Basta si se presta por escrito.", "Basta si el afectado es mayor de catorce años."], d: 2 }),
  pd({ id: "of-pd-06", art: "Artículo 11",
    cita: "facilitando al afectado la información básica a la que se refiere el apartado siguiente e indicándole una dirección electrónica u otro medio que permita acceder de forma sencilla e inmediata a la restante información",
    clave: "información básica",
    e: "Según el artículo 11.1 de la Ley Orgánica 3/2018, cuando los datos se obtienen del afectado, el responsable puede cumplir el deber de información facilitando:",
    ok: "La información básica e indicando un medio para acceder de forma sencilla e inmediata al resto.", mal: ["Únicamente un enlace a la ley.", "La información solo si el afectado la pide por escrito.", "Una copia íntegra del registro de actividades."], d: 2 }),
  pd({ id: "of-pd-07", art: "Artículo 12",
    cita: "podrán ejercerse directamente o por medio de representante legal o voluntario",
    clave: "representante legal o voluntario",
    e: "Conforme al artículo 12.1 de la Ley Orgánica 3/2018, los derechos de los artículos 15 a 22 del Reglamento general de protección de datos podrán ejercerse:",
    ok: "Directamente o por medio de representante legal o voluntario.", mal: ["Solo personalmente y en presencia física.", "Solo a través de abogado.", "Solo mediante la Agencia Española de Protección de Datos."], d: 1 }),
  pd({ id: "of-pd-08", art: "Artículo 14",
    cita: "el afectado deberá indicar en su solicitud a qué datos se refiere y la corrección que haya de realizarse",
    clave: "la corrección que haya de realizarse",
    e: "Al ejercer el derecho de rectificación, según el artículo 14 de la Ley Orgánica 3/2018, el afectado deberá indicar en su solicitud:",
    ok: "A qué datos se refiere y la corrección que haya de realizarse.", mal: ["El motivo por el que quiere borrar todos sus datos.", "El nombre del empleado que introdujo el dato.", "Solo su DNI, sin más."], d: 2 }),
  pd({ id: "of-pd-09", art: "Artículo 15",
    cita: "el responsable podrá conservar los datos identificativos del afectado necesarios con el fin de impedir tratamientos futuros para fines de mercadotecnia directa",
    clave: "mercadotecnia directa",
    e: "Cuando la supresión deriva del ejercicio del derecho de oposición, el artículo 15.2 de la Ley Orgánica 3/2018 permite al responsable conservar los datos identificativos necesarios para:",
    ok: "Impedir tratamientos futuros para fines de mercadotecnia directa.", mal: ["Enviar publicidad personalizada.", "Venderlos a terceros.", "Elaborar perfiles comerciales."], d: 3 }),
  pd({ id: "of-pd-10", art: "Artículo 16",
    cita: "El hecho de que el tratamiento de los datos personales esté limitado debe constar claramente en los sistemas de información del responsable.",
    clave: "debe constar claramente",
    e: "Según el artículo 16.2 de la Ley Orgánica 3/2018, el hecho de que el tratamiento de unos datos esté limitado:",
    ok: "Debe constar claramente en los sistemas de información del responsable.", mal: ["Debe publicarse en el BOE.", "Obliga a borrar los datos de inmediato.", "Solo debe comunicarse verbalmente al afectado."], d: 2 }),
  pd({ id: "of-pd-11", art: "Artículo 22",
    cita: "con la finalidad de preservar la seguridad de las personas y bienes, así como de sus instalaciones",
    clave: "preservar la seguridad de las personas y bienes",
    e: "Conforme al artículo 22.1 de la Ley Orgánica 3/2018, el tratamiento de imágenes mediante sistemas de cámaras o videocámaras puede llevarse a cabo con la finalidad de:",
    ok: "Preservar la seguridad de las personas y bienes, así como de sus instalaciones.", mal: ["Controlar la vida privada de los vecinos.", "Elaborar perfiles comerciales de los transeúntes.", "Difundir imágenes en redes sociales."], d: 1 }),
  pd({ id: "of-pd-12", art: "Artículo 22",
    cita: "Solo podrán captarse imágenes de la vía pública en la medida en que resulte imprescindible para la finalidad mencionada en el apartado anterior.",
    clave: "imprescindible",
    e: "Según el artículo 22.2 de la Ley Orgánica 3/2018, solo podrán captarse imágenes de la vía pública:",
    ok: "En la medida en que resulte imprescindible para preservar la seguridad.", mal: ["Sin limitación, si el sistema es privado.", "Siempre que se avise en el portal de la entidad.", "Durante el horario nocturno, exclusivamente."], d: 2 }),
  pd({ id: "of-pd-13", art: "Artículo 23",
    cita: "Será lícito el tratamiento de datos personales que tenga por objeto evitar el envío de comunicaciones comerciales a quienes hubiesen manifestado su negativa u oposición a recibirlas.",
    clave: "evitar el envío de comunicaciones comerciales",
    e: "Conforme al artículo 23.1 de la Ley Orgánica 3/2018, es lícito el tratamiento de datos que tenga por objeto:",
    ok: "Evitar el envío de comunicaciones comerciales a quienes hayan manifestado su oposición a recibirlas.", mal: ["Enviar publicidad sin consentimiento a cualquier persona.", "Vender listas de correo a terceros.", "Rastrear la navegación de los usuarios sin aviso."], d: 2 }),
  pd({ id: "of-pd-14", art: "Artículo 28",
    cita: "determinarán las medidas técnicas y organizativas apropiadas que deben aplicar a fin de garantizar y acreditar que el tratamiento es conforme",
    clave: "medidas técnicas y organizativas apropiadas",
    e: "Según el artículo 28.1 de la Ley Orgánica 3/2018, los responsables y encargados determinarán, para garantizar y acreditar que el tratamiento es conforme a la normativa:",
    ok: "Las medidas técnicas y organizativas apropiadas que deben aplicar.", mal: ["El precio de sus servicios de tratamiento.", "La lista de empleados con acceso a internet.", "Las sanciones aplicables a sus clientes."], d: 1 }),
  pd({ id: "of-pd-15", art: "Artículo 31",
    cita: "deberán mantener el registro de actividades de tratamiento al que se refiere el artículo 30 del Reglamento (UE) 2016/679",
    clave: "registro de actividades de tratamiento",
    e: "Conforme al artículo 31.1 de la Ley Orgánica 3/2018, los responsables y encargados del tratamiento, salvo la excepción prevista, deberán mantener:",
    ok: "El registro de actividades de tratamiento.", mal: ["Un registro de visitantes de su sede.", "El libro de actas de su consejo de administración.", "Un inventario de mobiliario."], d: 1 }),
  pd({ id: "of-pd-16", art: "Artículo 33",
    cita: "no se considerará comunicación de datos siempre que se cumpla lo establecido en el Reglamento (UE) 2016/679",
    clave: "no se considerará comunicación de datos",
    e: "Según el artículo 33.1 de la Ley Orgánica 3/2018, el acceso por un encargado del tratamiento a los datos necesarios para prestar un servicio al responsable:",
    ok: "No se considerará comunicación de datos, si se cumple la normativa.", mal: ["Es siempre una cesión ilícita de datos.", "Requiere el consentimiento expreso de cada afectado.", "Debe autorizarlo la Agencia en cada caso."], d: 2 }),
  pd({ id: "of-pd-17", art: "Artículo 36",
    cita: "El delegado de protección de datos actuará como interlocutor del responsable o encargado del tratamiento ante la Agencia Española de Protección de Datos",
    clave: "interlocutor",
    e: "Conforme al artículo 36.1 de la Ley Orgánica 3/2018, el delegado de protección de datos actuará, ante la Agencia Española de Protección de Datos y las autoridades autonómicas, como:",
    ok: "Interlocutor del responsable o encargado del tratamiento.", mal: ["Representante legal de los afectados.", "Instructor de los procedimientos sancionadores.", "Auditor externo independiente de la Agencia."], d: 2 }),
  pd({ id: "of-pd-18", art: "Artículo 38",
    cita: "serán vinculantes para quienes se adhieran a los mismos",
    clave: "vinculantes para quienes se adhieran",
    e: "Según el artículo 38.1 de la Ley Orgánica 3/2018, los códigos de conducta en materia de protección de datos serán:",
    ok: "Vinculantes para quienes se adhieran a los mismos.", mal: ["Obligatorios para todas las empresas del sector.", "Meras recomendaciones sin efecto alguno.", "Vinculantes solo para la Administración."], d: 2 }),
  pd({ id: "of-pd-19", art: "Artículo 39",
    cita: "podrá ser llevada a cabo por la Entidad Nacional de Acreditación (ENAC)",
    clave: "Entidad Nacional de Acreditación",
    e: "Conforme al artículo 39 de la Ley Orgánica 3/2018, la acreditación de las instituciones de certificación en materia de protección de datos podrá llevarla a cabo:",
    ok: "La Entidad Nacional de Acreditación (ENAC).", mal: ["El Centro Criptológico Nacional.", "La Fábrica Nacional de Moneda y Timbre.", "El Defensor del Pueblo."], d: 2 }),
  pd({ id: "of-pd-20", art: "Artículo 44",
    cita: "La Agencia Española de Protección de Datos es una autoridad administrativa independiente de ámbito estatal",
    clave: "autoridad administrativa independiente",
    e: "Según el artículo 44.1 de la Ley Orgánica 3/2018, la Agencia Española de Protección de Datos es:",
    ok: "Una autoridad administrativa independiente de ámbito estatal.", mal: ["Un órgano directivo del Ministerio del Interior.", "Una sociedad mercantil estatal.", "Una dirección general del Ministerio de Justicia."], d: 1 }),
  pd({ id: "of-pd-21", art: "Artículo 52",
    cita: "Las Administraciones Públicas, incluidas las tributarias y de la Seguridad Social, y los particulares estarán obligados a proporcionar a la Agencia Española de Protección de Datos los datos, informes, antecedentes y justificantes necesarios para llevar a cabo su actividad de investigación.",
    clave: "estarán obligados a proporcionar",
    e: "Conforme al artículo 52.1 de la Ley Orgánica 3/2018, respecto de la actividad de investigación de la Agencia Española de Protección de Datos, las Administraciones Públicas y los particulares:",
    ok: "Estarán obligados a proporcionar los datos, informes, antecedentes y justificantes necesarios.", mal: ["Pueden negarse si los datos son tributarios.", "Solo colaboran si media orden judicial.", "Solo deben facilitar información estadística agregada."], d: 2 }),
  pd({ id: "of-pd-22", art: "Artículo 70",
    cita: "b) Los encargados de los tratamientos.",
    clave: "encargados de los tratamientos",
    e: "Además de los responsables de los tratamientos, ¿quiénes están sujetos al régimen sancionador según el artículo 70.1 de la Ley Orgánica 3/2018?",
    ok: "Los encargados de los tratamientos, entre otros.", mal: ["Los afectados cuyos datos se tratan.", "Los delegados de protección de datos, personalmente.", "Los usuarios de redes sociales particulares."], d: 2 }),
  pd({ id: "of-pd-23", art: "Artículo 72",
    cita: "se consideran muy graves y prescribirán a los tres años las infracciones",
    clave: "tres años",
    e: "Según el artículo 72.1 de la Ley Orgánica 3/2018, las infracciones muy graves prescriben a los:",
    ok: "Tres años.", mal: ["Dos años.", "Cinco años.", "Un año."], m: "Infracciones LOPDGDD: muy graves 3, graves 2, leves 1 año.", d: 2 }),
  pd({ id: "of-pd-24", art: "Artículo 73",
    cita: "se consideran graves y prescribirán a los dos años las infracciones",
    clave: "dos años",
    e: "Conforme al artículo 73 de la Ley Orgánica 3/2018, las infracciones graves prescriben a los:",
    ok: "Dos años.", mal: ["Tres años.", "Seis meses.", "Cuatro años."], d: 2 }),
  pd({ id: "of-pd-25", art: "Artículo 74",
    cita: "Se consideran leves y prescribirán al año las restantes infracciones de carácter meramente formal",
    clave: "al año",
    e: "Según el artículo 74 de la Ley Orgánica 3/2018, las infracciones leves, de carácter meramente formal, prescriben:",
    ok: "Al año.", mal: ["A los seis meses.", "A los dos años.", "A los tres meses."], d: 2 }),
  pd({ id: "of-pd-26", art: "Artículo 78",
    cita: "Las sanciones por importe igual o inferior a 40.000 euros, prescriben en el plazo de un año.",
    clave: "40.000 euros",
    e: "Conforme al artículo 78.1 de la Ley Orgánica 3/2018, prescriben en el plazo de un año las sanciones por importe igual o inferior a:",
    ok: "40.000 euros.", mal: ["300.000 euros.", "10.000 euros.", "100.000 euros."], d: 3 }),
];
