// GSI tema 4, identificación y firma electrónica: Ley 39/2015 (arts. 9-11),
// Ley 40/2015 (arts. 38-46), Ley 6/2020 de servicios electrónicos de
// confianza y Reglamento de actuación por medios electrónicos (RD 203/2021).
import type { Destino, NormaOficial, PreguntaOficial } from "./tipos";

const T4: Destino[] = [["gestion-sistemas-informacion", 4]];
const f = (norma: NormaOficial) => (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma, destinos: T4, ...x });
const lp = f("LPAC");
const lr = f("LRJSP");
const lc = f("LCONF");
const rd = f("RD203");

export const FIRMA: PreguntaOficial[] = [
  lp({ id: "of-fi-01", art: "Artículo 9",
    cita: "Las Administraciones Públicas están obligadas a verificar la identidad de los interesados en el procedimiento administrativo",
    clave: "verificar la identidad",
    e: "Según el artículo 9.1 de la Ley 39/2015, las Administraciones Públicas están obligadas a:",
    ok: "Verificar la identidad de los interesados en el procedimiento administrativo.", mal: ["Firmar electrónicamente las solicitudes de los interesados.", "Expedir certificados electrónicos a los interesados.", "Conservar copia de la huella dactilar de los interesados."], d: 1 }),
  lp({ id: "of-fi-02", art: "Artículo 9",
    cita: "b) Sistemas basados en certificados electrónicos cualificados de sello electrónico expedidos por prestadores incluidos en la ‘‘Lista de confianza de prestadores de servicios de certificación’’.",
    clave: "sello electrónico",
    e: "Además de los certificados cualificados de firma, el artículo 9.2 de la Ley 39/2015 admite para la identificación electrónica sistemas basados en certificados electrónicos cualificados de:",
    ok: "Sello electrónico expedidos por prestadores incluidos en la Lista de confianza.", mal: ["Autenticación biométrica sin prestador.", "Correo electrónico no verificado.", "Firma manuscrita digitalizada."], d: 2 }),
  lp({ id: "of-fi-03", art: "Artículo 9",
    cita: "De forma previa a la eficacia jurídica del sistema, habrán de transcurrir dos meses desde dicha comunicación",
    clave: "dos meses",
    e: "Cuando una Administración comunica a la Secretaría General de Administración Digital otro sistema de identificación del artículo 9.2.c) de la Ley 39/2015, antes de su eficacia jurídica deben transcurrir:",
    ok: "Dos meses desde dicha comunicación.", mal: ["Diez días desde la comunicación.", "Seis meses desde la comunicación.", "Un año desde su puesta en producción."], d: 3 }),
  lp({ id: "of-fi-04", art: "Artículo 10",
    cita: "Los interesados podrán firmar a través de cualquier medio que permita acreditar la autenticidad de la expresión de su voluntad y consentimiento, así como la integridad e inalterabilidad del documento.",
    clave: "integridad e inalterabilidad del documento",
    e: "Según el artículo 10.1 de la Ley 39/2015, los interesados pueden firmar a través de cualquier medio que permita acreditar la autenticidad de su voluntad y consentimiento, así como:",
    ok: "La integridad e inalterabilidad del documento.", mal: ["La confidencialidad absoluta del contenido.", "La fecha de caducidad del documento.", "La gratuidad del trámite."], d: 2 }),
  lp({ id: "of-fi-05", art: "Artículo 11",
    cita: "será suficiente con que los interesados acrediten previamente su identidad a través de cualquiera de los medios de identificación previstos en esta Ley",
    clave: "acrediten previamente su identidad",
    e: "Con carácter general, según el artículo 11.1 de la Ley 39/2015, para realizar cualquier actuación del procedimiento basta con que los interesados:",
    ok: "Acrediten previamente su identidad por cualquiera de los medios previstos.", mal: ["Firmen con certificado cualificado en todo caso.", "Comparezcan presencialmente.", "Aporten copia compulsada del DNI."], d: 2 }),
  lp({ id: "of-fi-06", art: "Artículo 11",
    cita: "c) Interponer recursos.",
    clave: "Interponer recursos",
    e: "¿En cuál de los siguientes casos pueden las Administraciones exigir el uso obligatorio de firma según el artículo 11.2 de la Ley 39/2015?",
    ok: "Para interponer recursos.", mal: ["Para consultar el estado de un expediente.", "Para acceder a la información general del portal.", "Para descargar un formulario."],
    j: "El uso obligatorio de firma se limita a formular solicitudes, presentar declaraciones responsables o comunicaciones, interponer recursos, desistir de acciones y renunciar a derechos.", d: 2 }),
  lr({ id: "of-fi-07", art: "Artículo 38",
    cita: "La sede electrónica es aquella dirección electrónica, disponible para los ciudadanos a través de redes de telecomunicaciones, cuya titularidad corresponde a una Administración Pública",
    clave: "dirección electrónica",
    e: "Según el artículo 38.1 de la Ley 40/2015, la sede electrónica es:",
    ok: "La dirección electrónica disponible para los ciudadanos cuya titularidad corresponde a una Administración Pública u organismo público.", mal: ["El edificio físico de la oficina de registro.", "La cuenta de correo corporativa de cada empleado.", "El servidor donde se alojan las bases de datos."], d: 1 }),
  lr({ id: "of-fi-08", art: "Artículo 38",
    cita: "El establecimiento de una sede electrónica conlleva la responsabilidad del titular respecto de la integridad, veracidad y actualización de la información y los servicios a los que pueda accederse a través de la misma.",
    clave: "integridad, veracidad y actualización",
    e: "Conforme al artículo 38.2 de la Ley 40/2015, establecer una sede electrónica conlleva la responsabilidad del titular respecto de:",
    ok: "La integridad, veracidad y actualización de la información y los servicios accesibles a través de ella.", mal: ["El funcionamiento de los equipos de los ciudadanos.", "Los contenidos de páginas web enlazadas de terceros.", "La conectividad a internet de los usuarios."], d: 2 }),
  lr({ id: "of-fi-09", art: "Artículo 39",
    cita: "Se entiende por portal de internet el punto de acceso electrónico cuya titularidad corresponda a una Administración Pública",
    clave: "punto de acceso electrónico",
    e: "Según el artículo 39 de la Ley 40/2015, el portal de internet es:",
    ok: "El punto de acceso electrónico de titularidad pública que permite acceder a la información publicada y, en su caso, a la sede electrónica.", mal: ["La sede electrónica con plenos efectos jurídicos.", "El registro electrónico general.", "La red interna de una Administración."], d: 2 }),
  lr({ id: "of-fi-10", art: "Artículo 40",
    cita: "Estos certificados electrónicos incluirán el número de identificación fiscal y la denominación correspondiente",
    clave: "número de identificación fiscal",
    e: "Conforme al artículo 40.1 de la Ley 40/2015, los certificados de sello electrónico con que se identifican las Administraciones Públicas incluirán:",
    ok: "El número de identificación fiscal y la denominación correspondiente.", mal: ["El DNI del Ministro competente.", "La dirección IP del servidor.", "El número de registro de personal del funcionario."], d: 2 }),
  lr({ id: "of-fi-11", art: "Artículo 41",
    cita: "realizada íntegramente a través de medios electrónicos por una Administración Pública en el marco de un procedimiento administrativo y en la que no haya intervenido de forma directa un empleado público",
    clave: "no haya intervenido de forma directa un empleado público",
    e: "Según el artículo 41.1 de la Ley 40/2015, es actuación administrativa automatizada cualquier acto o actuación realizada íntegramente por medios electrónicos en un procedimiento y en la que:",
    ok: "No haya intervenido de forma directa un empleado público.", mal: ["Haya firmado un funcionario con certificado cualificado.", "Intervenga un empleado público a través de una aplicación.", "Participe el interesado mediante firma manuscrita."], d: 2 }),
  lr({ id: "of-fi-12", art: "Artículo 41",
    cita: "Asimismo, se indicará el órgano que debe ser considerado responsable a efectos de impugnación.",
    clave: "responsable a efectos de impugnación",
    e: "En la actuación administrativa automatizada, el artículo 41.2 de la Ley 40/2015 exige establecer previamente, además de los órganos competentes para su programación y control:",
    ok: "El órgano que debe ser considerado responsable a efectos de impugnación.", mal: ["El nombre del programador del código.", "El proveedor de la nube que aloja el sistema.", "La lista de interesados afectados."], d: 2 }),
  lr({ id: "of-fi-13", art: "Artículo 42",
    cita: "b) Código seguro de verificación vinculado a la Administración Pública, órgano, organismo público o entidad de Derecho Público",
    clave: "Código seguro de verificación",
    e: "Según el artículo 42 de la Ley 40/2015, en la actuación administrativa automatizada puede utilizarse como sistema de firma electrónica, además del sello electrónico:",
    ok: "El código seguro de verificación vinculado a la Administración u organismo.", mal: ["La firma manuscrita escaneada del titular del órgano.", "El certificado personal del ciudadano interesado.", "La contraseña de acceso del empleado público."], d: 1 }),
  lr({ id: "of-fi-14", art: "Artículo 43",
    cita: "se realizará mediante firma electrónica del titular del órgano o empleado público",
    clave: "firma electrónica del titular del órgano o empleado público",
    e: "Conforme al artículo 43.1 de la Ley 40/2015, la actuación de una Administración que utilice medios electrónicos, fuera de los casos de sello y actuación automatizada, se realiza mediante:",
    ok: "Firma electrónica del titular del órgano o empleado público.", mal: ["Firma electrónica del ciudadano interesado.", "Sello de tiempo, exclusivamente.", "Firma del proveedor tecnológico."], d: 2 }),
  lr({ id: "of-fi-15", art: "Artículo 43",
    cita: "Por razones de seguridad pública los sistemas de firma electrónica podrán referirse sólo el número de identificación profesional del empleado público.",
    clave: "número de identificación profesional",
    e: "Según el artículo 43.2 de la Ley 40/2015, por razones de seguridad pública los sistemas de firma electrónica del personal podrán referirse solo a:",
    ok: "El número de identificación profesional del empleado público.", mal: ["El nombre de pila del empleado.", "El código postal del centro de trabajo.", "El DNI completo del empleado en todo caso."], d: 2 }),
  lr({ id: "of-fi-16", art: "Artículo 44",
    cita: "Los documentos electrónicos transmitidos en entornos cerrados de comunicaciones establecidos entre Administraciones Públicas",
    clave: "entornos cerrados de comunicaciones",
    e: "Según el artículo 44.1 de la Ley 40/2015, se consideran válidos a efectos de autenticación e identificación de emisores y receptores los documentos electrónicos transmitidos en:",
    ok: "Entornos cerrados de comunicaciones entre Administraciones, en las condiciones de ese artículo.", mal: ["Redes sociales oficiales.", "Correo electrónico personal de los empleados.", "Mensajería instantánea comercial sin garantías."], d: 2 }),
  lr({ id: "of-fi-17", art: "Artículo 46",
    cita: "Todos los documentos utilizados en las actuaciones administrativas se almacenarán por medios electrónicos, salvo cuando no sea posible.",
    clave: "salvo cuando no sea posible",
    e: "Conforme al artículo 46.1 de la Ley 40/2015, los documentos utilizados en las actuaciones administrativas se almacenarán por medios electrónicos:",
    ok: "Salvo cuando no sea posible.", mal: ["Solo si lo solicita el interesado.", "Solo los de más de cinco años de antigüedad.", "Únicamente en procedimientos sancionadores."], d: 1 }),
  lc({ id: "of-fi-18", art: "Artículo 1",
    cita: "como complemento del Reglamento (UE) n.º 910/2014",
    clave: "910/2014",
    e: "Según su artículo 1, la Ley 6/2020 regula determinados aspectos de los servicios electrónicos de confianza como complemento del Reglamento (UE):",
    ok: "910/2014 (eIDAS), relativo a la identificación electrónica y los servicios de confianza.", mal: ["2016/679, de protección de datos.", "2024/1689, de inteligencia artificial.", "2022/2554, de resiliencia operativa digital."], d: 1 }),
  lc({ id: "of-fi-19", art: "Artículo 3",
    cita: "Los documentos electrónicos públicos, administrativos y privados, tienen el valor y la eficacia jurídica que corresponda a su respectiva naturaleza",
    clave: "que corresponda a su respectiva naturaleza",
    e: "Conforme al artículo 3.1 de la Ley 6/2020, los documentos electrónicos públicos, administrativos y privados tienen el valor y la eficacia jurídica:",
    ok: "Que corresponda a su respectiva naturaleza, según la legislación aplicable.", mal: ["Inferior a la de los documentos en papel.", "De simple principio de prueba en todo caso.", "Solo si se imprimen y se firman a mano."], d: 2 }),
  lc({ id: "of-fi-20", art: "Artículo 4",
    cita: "El período de vigencia de los certificados cualificados no será superior a cinco años.",
    clave: "cinco años",
    e: "Según el artículo 4.2 de la Ley 6/2020, el período de vigencia de los certificados cualificados no será superior a:",
    ok: "Cinco años.", mal: ["Tres años.", "Dos años.", "Diez años."], d: 1 }),
  lc({ id: "of-fi-21", art: "Artículo 4",
    cita: "Los certificados electrónicos se extinguen por caducidad a la expiración de su período de vigencia, o mediante revocación",
    clave: "caducidad",
    e: "Conforme al artículo 4.1 de la Ley 6/2020, los certificados electrónicos se extinguen:",
    ok: "Por caducidad al expirar su vigencia o por revocación del prestador.", mal: ["Solo por resolución judicial.", "Por el cambio de domicilio del titular.", "Al año de no utilizarlos."], d: 1 }),
  lc({ id: "of-fi-22", art: "Artículo 5",
    cita: "c) Resolución judicial o administrativa que lo ordene.",
    clave: "Resolución judicial o administrativa",
    e: "¿Cuál de los siguientes es un supuesto de revocación de un certificado electrónico según el artículo 5.1 de la Ley 6/2020?",
    ok: "Una resolución judicial o administrativa que lo ordene.", mal: ["El cambio del sistema operativo del titular.", "La renovación del DNI con el mismo número.", "La falta de uso durante tres meses."], d: 2 }),
  lc({ id: "of-fi-23", art: "Artículo 6",
    cita: "o a través de un pseudónimo que conste como tal de manera inequívoca",
    clave: "pseudónimo",
    e: "Según el artículo 6.1.a) de la Ley 6/2020, en los certificados de firma de personas físicas la identidad del titular puede consignarse, además de con nombre, apellidos y DNI, NIE o NIF:",
    ok: "Mediante un pseudónimo que conste como tal de manera inequívoca.", mal: ["Mediante el número de teléfono móvil.", "Mediante la dirección de correo electrónico.", "Mediante el número de la tarjeta sanitaria."], d: 2 }),
  lc({ id: "of-fi-24", art: "Artículo 7",
    cita: "La identificación de la persona física que solicite un certificado cualificado exigirá su personación ante los encargados de verificarla",
    clave: "personación",
    e: "Conforme al artículo 7.1 de la Ley 6/2020, la identificación de la persona física que solicita un certificado cualificado exige, como regla general:",
    ok: "Su personación ante los encargados de verificarla.", mal: ["Una videollamada grabada en todo caso.", "El envío de una fotocopia del DNI por correo.", "Una declaración responsable en línea."],
    j: "Puede prescindirse de la personación si la firma de la solicitud se legitima ante notario; la identificación a distancia se regula por orden ministerial.", d: 2 }),
  lc({ id: "of-fi-25", art: "Artículo 7",
    cita: "Podrá prescindirse de la personación de la persona física que solicite un certificado cualificado si su firma en la solicitud de expedición de un certificado cualificado ha sido legitimada en presencia notarial.",
    clave: "legitimada en presencia notarial",
    e: "Según el artículo 7.1 de la Ley 6/2020, podrá prescindirse de la personación del solicitante de un certificado cualificado si su firma en la solicitud:",
    ok: "Ha sido legitimada en presencia notarial.", mal: ["Se ha escaneado en alta resolución.", "La ha validado un funcionario por teléfono.", "Se ha enviado por correo certificado."], d: 2 }),
  lc({ id: "of-fi-26", art: "Artículo 8",
    cita: "Los prestadores de servicios electrónicos de confianza que consignen un pseudónimo en un certificado electrónico deberán constatar la verdadera identidad del titular del certificado y conservar la documentación que la acredite.",
    clave: "constatar la verdadera identidad",
    e: "Conforme al artículo 8.2 de la Ley 6/2020, los prestadores que consignen un pseudónimo en un certificado electrónico deberán:",
    ok: "Constatar la verdadera identidad del titular y conservar la documentación que la acredite.", mal: ["Publicar la identidad real del titular en su web.", "Negarse a revelar la identidad incluso a los órganos judiciales.", "Sustituir el pseudónimo cada año."], d: 2 }),
  lc({ id: "of-fi-27", art: "Artículo 9",
    cita: "No almacenar ni copiar, por sí o a través de un tercero, los datos de creación de firma, sello o autenticación de sitio web de la persona física o jurídica a la que hayan prestado sus servicios, salvo en caso de su gestión en nombre del titular.",
    clave: "No almacenar ni copiar",
    e: "Entre las obligaciones de los prestadores de servicios electrónicos de confianza, el artículo 9.1.b) de la Ley 6/2020 establece:",
    ok: "No almacenar ni copiar los datos de creación de firma del titular, salvo su gestión en nombre de este.", mal: ["Guardar copia de la clave privada de todos sus clientes.", "Ceder los datos de creación de firma a la Administración.", "Publicar las claves privadas caducadas."], d: 2 }),
  lc({ id: "of-fi-28", art: "Artículo 10",
    cita: "asumirán toda la responsabilidad frente a terceros por la actuación de las personas u otros prestadores en los que deleguen la ejecución de alguna o algunas de las funciones necesarias",
    clave: "toda la responsabilidad frente a terceros",
    e: "Según el artículo 10 de la Ley 6/2020, cuando un prestador delega en otras personas funciones necesarias para prestar sus servicios, como la comprobación de identidad:",
    ok: "Asume toda la responsabilidad frente a terceros por su actuación.", mal: ["Queda exento de responsabilidad.", "La responsabilidad pasa al Ministerio supervisor.", "Responde solo si hay dolo del delegado."], d: 2 }),
  lc({ id: "of-fi-29", art: "Artículo 12",
    cita: "Los prestadores de servicios de confianza no cualificados no necesitan verificación administrativa previa de cumplimiento de requisitos para iniciar su actividad",
    clave: "no necesitan verificación administrativa previa",
    e: "Conforme al artículo 12 de la Ley 6/2020, los prestadores de servicios de confianza no cualificados:",
    ok: "No necesitan verificación administrativa previa para iniciar su actividad, pero deben comunicarla en tres meses.", mal: ["Necesitan autorización previa del Ministerio para iniciar su actividad.", "No pueden prestar servicios en España.", "Deben inscribirse en la lista de confianza de cualificados."], d: 2 }),
  lc({ id: "of-fi-30", art: "Artículo 12",
    cita: "deberán comunicar su actividad al Ministerio de Asuntos Económicos y Transformación Digital en el plazo de tres meses desde que la inicien",
    clave: "tres meses",
    e: "Según el artículo 12 de la Ley 6/2020, los prestadores de servicios de confianza no cualificados deben comunicar su actividad al Ministerio competente en el plazo de:",
    ok: "Tres meses desde que la inicien.", mal: ["Un mes desde que la inicien.", "Seis meses desde que la inicien.", "Diez días antes de iniciarla."], d: 2 }),
  lc({ id: "of-fi-31", art: "Artículo 13",
    cita: "Los prestadores de servicios tienen la obligación de tomar las medidas necesarias para resolver los incidentes de seguridad que les afecten.",
    clave: "resolver los incidentes de seguridad",
    e: "Conforme al artículo 13.2 de la Ley 6/2020, los prestadores de servicios electrónicos de confianza tienen la obligación de tomar las medidas necesarias para:",
    ok: "Resolver los incidentes de seguridad que les afecten.", mal: ["Ocultar los incidentes a sus clientes.", "Trasladar al usuario el coste de los incidentes.", "Suspender toda actividad durante un año tras un incidente."], d: 1 }),
  lc({ id: "of-fi-32", art: "Artículo 16",
    cita: "establecerá, mantendrá y publicará la lista de confianza con información relativa a los prestadores cualificados de servicios de confianza",
    clave: "lista de confianza",
    e: "Según el artículo 16.1 de la Ley 6/2020, el Ministerio competente establecerá, mantendrá y publicará:",
    ok: "La lista de confianza de los prestadores cualificados de servicios de confianza.", mal: ["El registro de todos los certificados expedidos con sus claves.", "La lista de ciudadanos con DNI electrónico.", "El censo de sedes electrónicas municipales."], d: 1 }),
  lc({ id: "of-fi-33", art: "Artículo 16",
    cita: "será de 6 meses, transcurridos los cuales se podrá entender desestimada la solicitud",
    clave: "desestimada",
    e: "En el procedimiento de verificación previa de requisitos para ser prestador cualificado, si transcurren 6 meses sin resolución, según el artículo 16.2 de la Ley 6/2020 la solicitud se podrá entender:",
    ok: "Desestimada.", mal: ["Estimada.", "Caducada sin efectos.", "Estimada provisionalmente durante un año."], d: 3 }),
  lc({ id: "of-fi-34", art: "Artículo 18",
    cita: "Las infracciones de los preceptos del Reglamento (UE) 910/2014 y de esta Ley se clasifican en muy graves, graves y leves.",
    clave: "muy graves, graves y leves",
    e: "Según el artículo 18.1 de la Ley 6/2020, las infracciones en materia de servicios electrónicos de confianza se clasifican en:",
    ok: "Muy graves, graves y leves.", mal: ["Graves y leves.", "Penales y administrativas.", "Leves y muy leves."], d: 1 }),
  rd({ id: "of-fi-35", art: "Artículo 2",
    cita: "a) Los principios de neutralidad tecnológica y de adaptabilidad al progreso de las tecnologías y sistemas de comunicaciones electrónicas",
    clave: "neutralidad tecnológica",
    e: "¿Cuál de los siguientes principios debe respetar el sector público en sus actuaciones electrónicas según el artículo 2 del Real Decreto 203/2021?",
    ok: "Neutralidad tecnológica y adaptabilidad al progreso de las tecnologías.", mal: ["Uso obligatorio de un único fabricante de software.", "Exclusividad del formato propietario.", "Preferencia por el papel frente al documento electrónico."], d: 1 }),
  rd({ id: "of-fi-36", art: "Artículo 9",
    cita: "Mediante dicha sede electrónica se realizarán todas las actuaciones y trámites referidos a procedimientos o a servicios que requieran la identificación de la Administración Pública y, en su caso, la identificación o firma electrónica de las personas interesadas.",
    clave: "todas las actuaciones y trámites",
    e: "Según el artículo 9.1 del Real Decreto 203/2021, mediante la sede electrónica se realizarán:",
    ok: "Todas las actuaciones y trámites que requieran la identificación de la Administración y, en su caso, de los interesados.", mal: ["Solo la publicación de noticias institucionales.", "Únicamente los pagos de tasas.", "La difusión de información sin efectos jurídicos."], d: 2 }),
  rd({ id: "of-fi-37", art: "Artículo 10",
    cita: "La sede electrónica asociada tendrá consideración de sede electrónica a todos los efectos.",
    clave: "a todos los efectos",
    e: "Conforme al artículo 10.1 del Real Decreto 203/2021, la sede electrónica asociada:",
    ok: "Tiene consideración de sede electrónica a todos los efectos.", mal: ["Es un simple portal informativo sin efectos jurídicos.", "Solo sirve para notificaciones.", "Necesita convalidación de la sede principal en cada trámite."], d: 2 }),
  rd({ id: "of-fi-38", art: "Artículo 10",
    cita: "El acto o resolución de creación o supresión de una sede electrónica o sede electrónica asociada será publicado en el boletín oficial que corresponda",
    clave: "boletín oficial que corresponda",
    e: "Según el artículo 10.2 del Real Decreto 203/2021, el acto de creación o supresión de una sede electrónica o sede asociada se publicará en:",
    ok: "El boletín oficial que corresponda y en el directorio del Punto de Acceso General Electrónico.", mal: ["Solo en la propia sede.", "Un diario de difusión nacional.", "El tablón de anuncios físico del órgano."], d: 2 }),
  rd({ id: "of-fi-39", art: "Artículo 11",
    cita: "b) La identificación del acto o disposición de creación y el acceso al mismo, directamente o mediante enlace a su publicación en el Boletín Oficial correspondiente.",
    clave: "acto o disposición de creación",
    e: "Entre el contenido mínimo de toda sede electrónica, el artículo 11.1 del Real Decreto 203/2021 incluye:",
    ok: "La identificación del acto o disposición de creación y el acceso a él.", mal: ["El currículum del responsable técnico.", "Las claves privadas de los certificados de la sede.", "La lista de visitantes de la sede."], d: 2 }),
  rd({ id: "of-fi-40", art: "Artículo 13",
    cita: "En el ámbito estatal la determinación de una actuación administrativa como automatizada se autorizará por resolución del titular del órgano administrativo competente por razón de la materia",
    clave: "competente por razón de la materia",
    e: "En el ámbito estatal, según el artículo 13.2 del Real Decreto 203/2021, la determinación de una actuación como automatizada se autoriza por resolución del titular del órgano administrativo:",
    ok: "Competente por razón de la materia, publicada en la sede electrónica.", mal: ["Responsable de la seguridad de la información.", "Competente en materia de personal.", "Que preste el soporte informático."], d: 3 }),
  rd({ id: "of-fi-41", art: "Artículo 18",
    cita: "utilizarán, para identificarse y garantizar una comunicación segura con las mismas, certificados cualificados de autenticación de sitio web o medio equivalente",
    clave: "certificados cualificados de autenticación de sitio web",
    e: "Según el artículo 18.1 del Real Decreto 203/2021, las sedes electrónicas utilizarán para identificarse y garantizar una comunicación segura:",
    ok: "Certificados cualificados de autenticación de sitio web o medio equivalente.", mal: ["Certificados autofirmados.", "Contraseñas compartidas.", "Certificados personales del Ministro."], d: 2 }),
  rd({ id: "of-fi-42", art: "Artículo 21",
    cita: "mediante un procedimiento de verificación directo y gratuito para las personas interesadas",
    clave: "directo y gratuito",
    e: "Conforme al artículo 21.1 del Real Decreto 203/2021, el código seguro de verificación debe permitir comprobar la integridad del documento en la sede electrónica mediante un procedimiento de verificación:",
    ok: "Directo y gratuito para las personas interesadas.", mal: ["Previo pago de una tasa.", "Presencial en la oficina de registro.", "Reservado a los funcionarios."], d: 2 }),
  rd({ id: "of-fi-43", art: "Artículo 27",
    cita: "deberán contener como atributos, al menos, su nombre y apellidos y su número de Documento Nacional de Identidad, Número de Identificación de Extranjero, Número de Identificación Consular Central o Número de Identificación Fiscal",
    clave: "nombre y apellidos",
    e: "Según el artículo 27.1 del Real Decreto 203/2021, los certificados cualificados de firma admitidos para identificar a una persona física deben contener como atributos, al menos:",
    ok: "Su nombre y apellidos y su número de DNI, NIE, Número de Identificación Consular Central o NIF.", mal: ["Su fotografía y su domicilio.", "Su correo electrónico y teléfono.", "Su número de afiliación a la Seguridad Social."], d: 2 }),
  rd({ id: "of-fi-44", art: "Artículo 28",
    cita: "deberán ajustarse a lo previsto en el Esquema Nacional de Seguridad",
    clave: "Esquema Nacional de Seguridad",
    e: "Conforme al artículo 28.1 del Real Decreto 203/2021, los sistemas de clave concertada admitidos para identificar a personas físicas deberán ajustarse a lo previsto en:",
    ok: "El Esquema Nacional de Seguridad.", mal: ["El Reglamento de Contratación.", "La Ley de Enjuiciamiento Civil.", "El Estatuto de los Trabajadores."], d: 1 }),
  rd({ id: "of-fi-45", art: "Artículo 30",
    cita: "estas podrán ser válidamente realizadas por personal funcionario público habilitado mediante el uso del sistema de firma electrónica del que esté dotado para ello",
    clave: "personal funcionario público habilitado",
    e: "Si un interesado no obligado a relacionarse electrónicamente no dispone de los medios necesarios para identificarse o firmar, según el artículo 30.1 del Real Decreto 203/2021 estas actuaciones podrán realizarse por:",
    ok: "Personal funcionario público habilitado, con su propio sistema de firma.", mal: ["Un familiar del interesado con su certificado.", "Cualquier empleado público sin habilitación.", "Una empresa privada autorizada."], d: 2 }),
  rd({ id: "of-fi-46", art: "Artículo 42",
    cita: "debiendo quedar constancia de la fecha y hora del acceso al contenido",
    clave: "fecha y hora del acceso",
    e: "Según el artículo 42.1 del Real Decreto 203/2021, en las notificaciones electrónicas por comparecencia en sede o en la Dirección Electrónica Habilitada única debe quedar constancia de:",
    ok: "La fecha y hora del acceso al contenido.", mal: ["La dirección IP del ordenador del interesado, exclusivamente.", "El nombre del funcionario que la redactó.", "El navegador utilizado."], d: 2 }),
  rd({ id: "of-fi-47", art: "Artículo 51",
    cita: "El foliado de los expedientes administrativos electrónicos se llevará a cabo mediante un índice electrónico autenticado que garantizará la integridad del expediente",
    clave: "índice electrónico autenticado",
    e: "Conforme al artículo 51.1 del Real Decreto 203/2021, el foliado de los expedientes administrativos electrónicos se lleva a cabo mediante:",
    ok: "Un índice electrónico autenticado que garantiza la integridad del expediente.", mal: ["La numeración manual de cada página impresa.", "Una hoja de cálculo sin firma.", "El sello de registro de entrada."], d: 2 }),
  rd({ id: "of-fi-48", art: "Artículo 51",
    cita: "Un mismo documento electrónico podrá formar parte de distintos expedientes administrativos.",
    clave: "distintos expedientes administrativos",
    e: "Según el artículo 51.2 del Real Decreto 203/2021, un mismo documento electrónico:",
    ok: "Podrá formar parte de distintos expedientes administrativos.", mal: ["Solo puede pertenecer a un expediente.", "Debe duplicarse en papel para cada expediente.", "Pierde su validez si se usa en otro expediente."], d: 1 }),
];
