// Ley 9/2017, de Contratos del Sector Público (BOE-A-2017-12902).
// Administrativo del Estado, tema 19, y GSI, tema 1. No repite los artículos
// que ya preguntan las 50 preguntas de GSI tema 1 que hay en la base de datos.
import type { Destino, PreguntaOficial } from "./tipos";

const AMBOS: Destino[] = [["administrativo-estado", 19], ["gestion-sistemas-informacion", 1]];
const GSI: Destino[] = [["gestion-sistemas-informacion", 1]];
const a = (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma: "LCSP", destinos: AMBOS, ...x });
const g = (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma: "LCSP", destinos: GSI, ...x });

export const LCSP: PreguntaOficial[] = [
  a({ id: "of-cs-01", art: "Artículo 2",
    cita: "Se entenderá que un contrato tiene carácter oneroso en los casos en que el contratista obtenga algún tipo de beneficio económico, ya sea de forma directa o indirecta.",
    clave: "algún tipo de beneficio económico",
    e: "Según el artículo 2.1 de la LCSP, un contrato tiene carácter oneroso cuando el contratista obtiene:",
    ok: "Algún tipo de beneficio económico, directo o indirecto.", mal: ["Un precio pagado siempre en dinero por la Administración.", "Un beneficio superior al 6 % del precio.", "Una subvención pública finalista."], d: 2 }),
  a({ id: "of-cs-02", art: "Artículo 3",
    cita: "c) Los Organismos Autónomos, las Universidades Públicas y las autoridades administrativas independientes.",
    clave: "Universidades Públicas",
    e: "¿Cuál de las siguientes entidades forma parte del sector público a efectos de la LCSP según su artículo 3.1?",
    ok: "Las Universidades Públicas.", mal: ["Los partidos políticos.", "Las confesiones religiosas.", "Las empresas privadas concesionarias."], d: 1 }),
  a({ id: "of-cs-03", art: "Artículo 25",
    cita: "Tendrán carácter administrativo los contratos siguientes, siempre que se celebren por una Administración Pública:",
    clave: "siempre que se celebren por una Administración Pública",
    e: "Según el artículo 25.1 de la LCSP, los contratos de obra, concesión de obra, concesión de servicios, suministro y servicios tienen carácter administrativo:",
    ok: "Siempre que se celebren por una Administración Pública, con las excepciones previstas.", mal: ["Siempre que su valor estimado supere 40.000 euros.", "Cuando los celebre cualquier entidad del sector público, incluidas las sociedades mercantiles.", "Solo si están sujetos a regulación armonizada."], d: 2 }),
  a({ id: "of-cs-04", art: "Artículo 27",
    cita: "Serán competencia del orden jurisdiccional contencioso-administrativo las siguientes cuestiones:",
    clave: "contencioso-administrativo",
    e: "Según el artículo 27.1 de la LCSP, las cuestiones relativas a la preparación, adjudicación, efectos, modificación y extinción de los contratos administrativos son competencia del orden jurisdiccional:",
    ok: "Contencioso-administrativo.", mal: ["Civil.", "Social.", "Mercantil."],
    j: "El artículo 27.1 atribuye estas cuestiones al orden contencioso-administrativo.", d: 1 }),
  a({ id: "of-cs-05", art: "Artículo 28",
    cita: "Las entidades del sector público no podrán celebrar otros contratos que aquellos que sean necesarios para el cumplimiento y realización de sus fines institucionales.",
    clave: "fines institucionales",
    e: "Conforme al artículo 28.1 de la LCSP, las entidades del sector público solo podrán celebrar los contratos que sean necesarios para:",
    ok: "El cumplimiento y realización de sus fines institucionales.", mal: ["Agotar el crédito presupuestario disponible.", "Mantener la actividad de las empresas locales.", "Cualquier finalidad que apruebe el órgano de contratación."], d: 1 }),
  a({ id: "of-cs-06", art: "Artículo 29",
    cita: "En ningún caso podrá producirse la prórroga por el consentimiento tácito de las partes.",
    clave: "consentimiento tácito",
    e: "Según el artículo 29.2 de la LCSP, la prórroga de un contrato:",
    ok: "En ningún caso podrá producirse por el consentimiento tácito de las partes.", mal: ["Se produce automáticamente si ninguna parte la denuncia.", "Solo puede acordarla el contratista.", "Puede pactarse verbalmente."], d: 2 }),
  a({ id: "of-cs-07", art: "Artículo 29",
    cita: "siempre que su preaviso se produzca al menos con dos meses de antelación a la finalización del plazo de duración del contrato",
    clave: "dos meses",
    e: "Conforme al artículo 29.2 de la LCSP, la prórroga acordada por el órgano de contratación es obligatoria para el empresario siempre que el preaviso se produzca, salvo que el pliego fije uno mayor, al menos con:",
    ok: "Dos meses de antelación a la finalización del contrato.", mal: ["Un mes de antelación.", "Quince días de antelación.", "Seis meses de antelación."], d: 2 }),
  a({ id: "of-cs-08", art: "Artículo 29",
    cita: "Los contratos de suministros y de servicios de prestación sucesiva tendrán un plazo máximo de duración de cinco años, incluyendo las posibles prórrogas",
    clave: "cinco años",
    e: "Con carácter general, según el artículo 29.4 de la LCSP, los contratos de suministros y de servicios de prestación sucesiva tendrán un plazo máximo de duración, incluidas las prórrogas, de:",
    ok: "Cinco años.", mal: ["Cuatro años.", "Diez años.", "Tres años."], d: 1 }),
  a({ id: "of-cs-09", art: "Artículo 39",
    cita: "Son causas de nulidad de derecho administrativo las indicadas en el artículo 47 de la Ley 39/2015",
    clave: "artículo 47 de la Ley 39/2015",
    e: "Según el artículo 39.1 de la LCSP, son causas de nulidad de derecho administrativo de los contratos, en primer lugar:",
    ok: "Las indicadas en el artículo 47 de la Ley 39/2015.", mal: ["Las indicadas en el artículo 48 de la Ley 39/2015.", "Las que determine libremente el órgano de contratación.", "Las del Código Civil exclusivamente."], d: 2 }),
  a({ id: "of-cs-10", art: "Artículo 64",
    cita: "Los órganos de contratación deberán tomar las medidas adecuadas para luchar contra el fraude, el favoritismo y la corrupción",
    clave: "el fraude, el favoritismo y la corrupción",
    e: "Conforme al artículo 64.1 de la LCSP, los órganos de contratación deben tomar las medidas adecuadas para luchar contra:",
    ok: "El fraude, el favoritismo y la corrupción, y prevenir los conflictos de intereses.", mal: ["La competencia entre licitadores.", "La publicidad excesiva de las licitaciones.", "La participación de pymes."], d: 1 }),
  a({ id: "of-cs-11", art: "Artículo 69",
    cita: "sin que sea necesaria la formalización de las mismas en escritura pública hasta que se haya efectuado la adjudicación del contrato a su favor",
    clave: "hasta que se haya efectuado la adjudicación",
    e: "Según el artículo 69.1 de la LCSP, las uniones temporales de empresarios pueden contratar con el sector público sin necesidad de formalizarse en escritura pública:",
    ok: "Hasta que se haya efectuado la adjudicación del contrato a su favor.", mal: ["En ningún momento del procedimiento.", "Hasta la recepción del contrato.", "Solo si el contrato es menor."], d: 2 }),
  a({ id: "of-cs-12", art: "Artículo 99",
    cita: "No podrá fraccionarse un contrato con la finalidad de disminuir la cuantía del mismo y eludir así los requisitos de publicidad o los relativos al procedimiento de adjudicación que correspondan.",
    clave: "disminuir la cuantía",
    e: "Conforme al artículo 99.2 de la LCSP, no podrá fraccionarse un contrato con la finalidad de:",
    ok: "Disminuir la cuantía y eludir los requisitos de publicidad o de procedimiento de adjudicación.", mal: ["Facilitar la participación de pymes mediante lotes.", "Cumplir las prescripciones técnicas.", "Adaptarse a la anualidad presupuestaria."], d: 1 }),
  a({ id: "of-cs-13", art: "Artículo 99",
    cita: "deberá preverse la realización independiente de cada una de sus partes mediante su división en lotes",
    clave: "división en lotes",
    e: "Según el artículo 99.3 de la LCSP, siempre que la naturaleza o el objeto del contrato lo permitan, deberá preverse:",
    ok: "La realización independiente de cada una de sus partes mediante su división en lotes.", mal: ["Su adjudicación a un único licitador en todo caso.", "Su tramitación como contrato menor.", "Su ejecución directa por la Administración."], d: 1 }),
  a({ id: "of-cs-14", art: "Artículo 100",
    cita: "por presupuesto base de licitación se entenderá el límite máximo de gasto que en virtud del contrato puede comprometer el órgano de contratación, incluido el Impuesto sobre el Valor Añadido",
    clave: "incluido el Impuesto sobre el Valor Añadido",
    e: "Según el artículo 100.1 de la LCSP, el presupuesto base de licitación es el límite máximo de gasto que puede comprometer el órgano de contratación:",
    ok: "Incluido el Impuesto sobre el Valor Añadido, salvo disposición en contrario.", mal: ["Excluido el IVA en todo caso.", "Excluidas las posibles prórrogas y modificaciones, pero con IVA reducido.", "Calculado sobre la media de las ofertas recibidas."], d: 2 }),
  a({ id: "of-cs-15", art: "Artículo 101",
    cita: "el órgano de contratación tomará el importe total, sin incluir el Impuesto sobre el Valor Añadido, pagadero según sus estimaciones",
    clave: "sin incluir el Impuesto sobre el Valor Añadido",
    e: "Conforme al artículo 101.1.a) de la LCSP, en los contratos de obras, suministros y servicios el valor estimado se determina tomando el importe total pagadero:",
    ok: "Sin incluir el Impuesto sobre el Valor Añadido.", mal: ["Con el IVA incluido.", "Con el IVA y las tasas incluidas.", "Sobre el precio del contrato anterior."],
    j: "A diferencia del presupuesto base de licitación (artículo 100), el valor estimado se calcula sin IVA.", d: 2 }),
  a({ id: "of-cs-16", art: "Artículo 102",
    cita: "Los contratos del sector público tendrán siempre un precio cierto",
    clave: "precio cierto",
    e: "Según el artículo 102.1 de la LCSP, los contratos del sector público tendrán siempre:",
    ok: "Un precio cierto, que se abonará en función de la prestación realmente ejecutada.", mal: ["Un precio revisable cada año.", "Un precio fijado por el contratista tras la ejecución.", "Un precio expresado en la moneda que elija el licitador."], d: 1 }),
  a({ id: "of-cs-17", art: "Artículo 116",
    cita: "que se iniciará por el órgano de contratación motivando la necesidad del contrato",
    clave: "motivando la necesidad del contrato",
    e: "Conforme al artículo 116.1 de la LCSP, el expediente de contratación se iniciará por el órgano de contratación:",
    ok: "Motivando la necesidad del contrato, y deberá publicarse en el perfil de contratante.", mal: ["Sin necesidad de motivación si el contrato es de servicios.", "A propuesta de los licitadores interesados.", "Por acuerdo del Consejo de Ministros en todo caso."], d: 2 }),
  a({ id: "of-cs-18", art: "Artículo 119",
    cita: "Podrán ser objeto de tramitación urgente los expedientes correspondientes a los contratos cuya celebración responda a una necesidad inaplazable",
    clave: "necesidad inaplazable",
    e: "Según el artículo 119.1 de la LCSP, pueden tramitarse por urgencia los expedientes de contratos cuya celebración responda a:",
    ok: "Una necesidad inaplazable, o cuya adjudicación sea preciso acelerar por razones de interés público.", mal: ["Un acontecimiento catastrófico que exige actuar de inmediato.", "Un valor estimado inferior a 15.000 euros.", "La petición del contratista."],
    j: "Actuar de manera inmediata por acontecimientos catastróficos es la tramitación de emergencia del artículo 120.", d: 2 }),
  a({ id: "of-cs-19", art: "Artículo 120",
    cita: "Cuando la Administración tenga que actuar de manera inmediata a causa de acontecimientos catastróficos, de situaciones que supongan grave peligro o de necesidades que afecten a la defensa nacional",
    clave: "acontecimientos catastróficos",
    e: "Conforme al artículo 120.1 de la LCSP, se aplica el régimen excepcional de tramitación de emergencia cuando la Administración tenga que actuar de manera inmediata a causa de:",
    ok: "Acontecimientos catastróficos, situaciones de grave peligro o necesidades que afecten a la defensa nacional.", mal: ["Una necesidad inaplazable de cualquier tipo.", "El final del ejercicio presupuestario.", "La falta de licitadores en un procedimiento abierto."], d: 2 }),
  a({ id: "of-cs-20", art: "Artículo 122",
    cita: "solo podrán ser modificados con posterioridad por error material, de hecho o aritmético",
    clave: "error material, de hecho o aritmético",
    e: "Según el artículo 122.1 de la LCSP, los pliegos de cláusulas administrativas particulares, una vez aprobados, solo podrán modificarse con posterioridad por:",
    ok: "Error material, de hecho o aritmético; en otro caso, se retrotraen las actuaciones.", mal: ["Acuerdo entre el órgano de contratación y los licitadores.", "Decisión de la mesa de contratación.", "Cualquier causa de interés público sobrevenida."], d: 2 }),
  a({ id: "of-cs-21", art: "Artículo 132",
    cita: "Los órganos de contratación darán a los licitadores y candidatos un tratamiento igualitario y no discriminatorio y ajustarán su actuación a los principios de transparencia y proporcionalidad.",
    clave: "tratamiento igualitario y no discriminatorio",
    e: "Conforme al artículo 132.1 de la LCSP, los órganos de contratación darán a los licitadores y candidatos:",
    ok: "Un tratamiento igualitario y no discriminatorio, con transparencia y proporcionalidad.", mal: ["Preferencia a las empresas de su territorio.", "Un trato diferenciado según su tamaño.", "Acceso prioritario a la información si ya fueron contratistas."], d: 1 }),
  a({ id: "of-cs-22", art: "Artículo 133",
    cita: "los órganos de contratación no podrán divulgar la información facilitada por los empresarios que estos hayan designado como confidencial en el momento de presentar su oferta",
    clave: "designado como confidencial",
    e: "Según el artículo 133.1 de la LCSP, los órganos de contratación no podrán divulgar la información facilitada por los empresarios que:",
    ok: "Estos hayan designado como confidencial al presentar su oferta.", mal: ["Supere las diez páginas.", "Se refiera al precio ofertado.", "Haya sido valorada por la mesa de contratación."], d: 2 }),
  a({ id: "of-cs-23", art: "Artículo 135",
    cita: "En los contratos celebrados por la Administración General del Estado, o por las entidades vinculadas a la misma que gocen de la naturaleza de Administraciones Públicas, el anuncio de licitación se publicará además en el «Boletín Oficial del Estado».",
    clave: "Boletín Oficial del Estado",
    e: "Conforme al artículo 135.1 de la LCSP, en los contratos de la Administración General del Estado, además del perfil de contratante, el anuncio de licitación se publicará en:",
    ok: "El «Boletín Oficial del Estado».", mal: ["El boletín oficial de la provincia.", "Un diario de difusión nacional.", "El tablón de la Delegación del Gobierno."], d: 2 }),
  a({ id: "of-cs-24", art: "Artículo 139",
    cita: "su presentación supone la aceptación incondicionada por el empresario del contenido de la totalidad de sus cláusulas o condiciones, sin salvedad o reserva alguna",
    clave: "aceptación incondicionada",
    e: "Según el artículo 139.1 de la LCSP, la presentación de una proposición supone:",
    ok: "La aceptación incondicionada por el empresario de la totalidad de las cláusulas, sin salvedad ni reserva.", mal: ["La adjudicación provisional del contrato.", "La aceptación de las cláusulas que el licitador marque como aceptadas.", "Un compromiso que puede retirarse libremente hasta la adjudicación."], d: 2 }),
  a({ id: "of-cs-25", art: "Artículo 139",
    cita: "2. Las proposiciones serán secretas",
    clave: "secretas",
    e: "Conforme al artículo 139.2 de la LCSP, hasta el momento de la licitación pública las proposiciones serán:",
    ok: "Secretas.", mal: ["Públicas desde su presentación.", "Accesibles a los demás licitadores.", "Publicadas en el perfil de contratante."], d: 1 }),
  a({ id: "of-cs-26", art: "Artículo 145",
    cita: "La adjudicación de los contratos se realizará utilizando una pluralidad de criterios de adjudicación en base a la mejor relación calidad-precio.",
    clave: "mejor relación calidad-precio",
    e: "Según el artículo 145.1 de la LCSP, la adjudicación de los contratos se realizará utilizando una pluralidad de criterios en base a:",
    ok: "La mejor relación calidad-precio.", mal: ["El precio más bajo, exclusivamente.", "La antigüedad de las empresas.", "El sorteo entre las ofertas válidas."], d: 1 }),
  a({ id: "of-cs-27", art: "Artículo 149",
    cita: "solo podrá excluirla del procedimiento de licitación previa tramitación del procedimiento que establece este artículo",
    clave: "previa tramitación del procedimiento",
    e: "Cuando el órgano de contratación presume que una oferta es anormalmente baja, según el artículo 149.1 de la LCSP:",
    ok: "Solo podrá excluirla previa tramitación del procedimiento que establece ese artículo.", mal: ["Debe excluirla automáticamente.", "Debe adjudicarle el contrato por ser la más barata.", "Puede excluirla sin trámite alguno si así lo decide la mesa."], d: 2 }),
  a({ id: "of-cs-28", art: "Artículo 151",
    cita: "La resolución de adjudicación deberá ser motivada y se notificará a los candidatos y licitadores, debiendo ser publicada en el perfil de contratante en el plazo de 15 días.",
    clave: "15 días",
    e: "Según el artículo 151.1 de la LCSP, la resolución de adjudicación, que deberá ser motivada, se publicará en el perfil de contratante en el plazo de:",
    ok: "15 días.", mal: ["10 días.", "30 días.", "5 días."], d: 2 }),
  a({ id: "of-cs-29", art: "Artículo 153",
    cita: "deberán formalizarse en documento administrativo que se ajuste con exactitud a las condiciones de la licitación, constituyendo dicho documento título suficiente para acceder a cualquier registro público",
    clave: "documento administrativo",
    e: "Conforme al artículo 153.1 de la LCSP, los contratos de las Administraciones Públicas deberán formalizarse en:",
    ok: "Documento administrativo ajustado a las condiciones de la licitación.", mal: ["Escritura pública en todo caso.", "Contrato privado firmado ante notario.", "Acta de la mesa de contratación."],
    j: "El contratista puede pedir que se eleve a escritura pública, a su costa.", d: 1 }),
  a({ id: "of-cs-30", art: "Artículo 189",
    cita: "Los contratos deberán cumplirse a tenor de sus cláusulas, sin perjuicio de las prerrogativas establecidas por la legislación en favor de las Administraciones Públicas.",
    clave: "a tenor de sus cláusulas",
    e: "Según el artículo 189 de la LCSP, los contratos deberán cumplirse:",
    ok: "A tenor de sus cláusulas, sin perjuicio de las prerrogativas de las Administraciones Públicas.", mal: ["Según las instrucciones verbales del responsable del contrato.", "Conforme a lo que acuerden las partes durante la ejecución.", "Según el criterio del contratista."], d: 1 }),
  a({ id: "of-cs-31", art: "Artículo 197",
    cita: "La ejecución del contrato se realizará a riesgo y ventura del contratista",
    clave: "riesgo y ventura del contratista",
    e: "Conforme al artículo 197 de la LCSP, la ejecución del contrato se realizará:",
    ok: "A riesgo y ventura del contratista.", mal: ["A riesgo de la Administración contratante.", "A riesgo compartido al 50 %.", "A riesgo del responsable del contrato."], d: 1 }),
  g({ id: "of-cs-32", art: "Artículo 30",
    cita: "cuyo empleo suponga una economía superior al 5 por 100 del importe del presupuesto del contrato",
    clave: "5 por 100",
    e: "Según el artículo 30.1.b) de la LCSP, la Administración puede ejecutar obras con sus propios servicios cuando posea elementos auxiliares utilizables cuyo empleo suponga una economía superior al:",
    ok: "5 por 100 del importe del presupuesto del contrato.", mal: ["10 por 100 del importe del presupuesto.", "20 por 100 del importe del presupuesto.", "1 por 100 del importe del presupuesto."], d: 3 }),
  g({ id: "of-cs-33", art: "Artículo 31",
    cita: "sin que el resultado de esa cooperación pueda calificarse de contractual",
    clave: "calificarse de contractual",
    e: "Según el artículo 31.1 de la LCSP, cuando las entidades del sector público cooperan entre sí mediante medios propios o convenios, el resultado de esa cooperación:",
    ok: "No puede calificarse de contractual.", mal: ["Es siempre un contrato administrativo.", "Es un contrato privado.", "Es un contrato sujeto a regulación armonizada."],
    j: "El texto dice «sin que el resultado de esa cooperación pueda calificarse de contractual».", d: 2 }),
  g({ id: "of-cs-34", art: "Artículo 32",
    cita: "siempre y cuando la persona jurídica que utilicen merezca la calificación jurídica de medio propio personificado respecto de ellos",
    clave: "medio propio personificado",
    e: "Según el artículo 32.1 de la LCSP, los poderes adjudicadores pueden ejecutar de manera directa prestaciones propias de los contratos valiéndose de otra persona jurídica, previo encargo, cuando esta merezca la calificación de:",
    ok: "Medio propio personificado respecto de ellos.", mal: ["Contratista habitual.", "Empresa clasificada.", "Entidad colaboradora."], d: 2 }),
  g({ id: "of-cs-35", art: "Artículo 35",
    cita: "a) La identificación de las partes.",
    clave: "La identificación de las partes",
    e: "¿Cuál de las siguientes menciones debe incluir necesariamente el documento de formalización de un contrato según el artículo 35.1 de la LCSP?",
    ok: "La identificación de las partes.", mal: ["El listado de licitadores excluidos.", "El acta de apertura de proposiciones.", "La opinión del responsable del contrato."], d: 1 }),
  g({ id: "of-cs-36", art: "Artículo 103",
    cita: "Los precios de los contratos del sector público solo podrán ser objeto de revisión periódica y predeterminada en los términos establecidos en este Capítulo.",
    clave: "periódica y predeterminada",
    e: "Según el artículo 103.1 de la LCSP, los precios de los contratos del sector público solo podrán ser objeto de revisión:",
    ok: "Periódica y predeterminada, en los términos de ese capítulo.", mal: ["Libre, cuando lo pida el contratista.", "Anual según el IPC en todo caso.", "En cualquier momento por acuerdo de las partes."], d: 2 }),
  g({ id: "of-cs-37", art: "Artículo 108",
    cita: "En efectivo o en valores, que en todo caso serán de Deuda Pública",
    clave: "Deuda Pública",
    e: "Conforme al artículo 108.1.a) de la LCSP, cuando la garantía definitiva se presta en valores, estos serán en todo caso de:",
    ok: "Deuda Pública.", mal: ["Renta variable cotizada.", "Fondos de inversión.", "Pagarés de empresa."], d: 2 }),
  g({ id: "of-cs-38", art: "Artículo 115",
    cita: "Los órganos de contratación podrán realizar estudios de mercado y dirigir consultas a los operadores económicos que estuvieran activos en el mismo con la finalidad de preparar correctamente la licitación",
    clave: "preparar correctamente la licitación",
    e: "Según el artículo 115.1 de la LCSP, las consultas preliminares del mercado a los operadores económicos tienen la finalidad de:",
    ok: "Preparar correctamente la licitación e informar a los operadores de los planes y requisitos.", mal: ["Adjudicar directamente el contrato al operador consultado.", "Negociar el precio final con un licitador.", "Sustituir el anuncio de licitación."], d: 2 }),
  g({ id: "of-cs-39", art: "Artículo 124",
    cita: "los pliegos y documentos que contengan las prescripciones técnicas particulares que hayan de regir la realización de la prestación y definan sus calidades",
    clave: "prescripciones técnicas particulares",
    e: "Según el artículo 124 de la LCSP, antes de la licitación el órgano de contratación aprobará los pliegos y documentos que contengan las:",
    ok: "Prescripciones técnicas particulares que rijan la prestación y definan sus calidades.", mal: ["Ofertas económicas de los licitadores.", "Actas de la mesa de contratación.", "Resoluciones de adjudicación."], d: 1 }),
  g({ id: "of-cs-40", art: "Artículo 140",
    cita: "una declaración responsable que se ajustará al formulario de documento europeo único de contratación",
    clave: "documento europeo único de contratación",
    e: "Según el artículo 140.1.a) de la LCSP, las proposiciones en el procedimiento abierto deben ir acompañadas de una declaración responsable que se ajustará al formulario de:",
    ok: "Documento europeo único de contratación.", mal: ["Certificado de clasificación empresarial.", "Plan de seguridad y salud.", "Memoria técnica de la oferta."], d: 2 }),
  g({ id: "of-cs-41", art: "Artículo 142",
    cita: "el órgano de contratación podrá tomar en consideración las variantes que ofrezcan los licitadores, siempre que las variantes se prevean en los pliegos",
    clave: "se prevean en los pliegos",
    e: "Conforme al artículo 142.1 de la LCSP, cuando haya criterios de adjudicación distintos del precio, el órgano de contratación podrá considerar las variantes de los licitadores siempre que:",
    ok: "Las variantes se prevean en los pliegos.", mal: ["El licitador las justifique en su oferta.", "Supongan un menor precio.", "Las autorice la mesa durante la licitación."], d: 2 }),
  g({ id: "of-cs-42", art: "Artículo 143",
    cita: "podrá celebrarse una subasta electrónica, articulada como un proceso electrónico repetitivo, que tiene lugar tras una primera evaluación completa de las ofertas",
    clave: "tras una primera evaluación completa de las ofertas",
    e: "Según el artículo 143.1 de la LCSP, la subasta electrónica es un proceso electrónico repetitivo que tiene lugar:",
    ok: "Tras una primera evaluación completa de las ofertas.", mal: ["Antes de abrir cualquier oferta.", "Después de formalizado el contrato.", "En sustitución de la evaluación de las ofertas."], d: 2 }),
  g({ id: "of-cs-43", art: "Artículo 147",
    cita: "criterios de adjudicación específicos para el desempate en los casos en que, tras la aplicación de los criterios de adjudicación, se produzca un empate entre dos o más ofertas",
    clave: "desempate",
    e: "Conforme al artículo 147.1 de la LCSP, los pliegos pueden establecer criterios de adjudicación específicos para:",
    ok: "El desempate entre dos o más ofertas tras aplicar los criterios de adjudicación.", mal: ["Excluir a las pymes.", "Fijar el precio máximo del contrato.", "Determinar la clasificación exigible."], d: 1 }),
  g({ id: "of-cs-44", art: "Artículo 152",
    cita: "La decisión de no adjudicar o celebrar el contrato o el desistimiento del procedimiento podrán acordarse por el órgano de contratación antes de la formalización.",
    clave: "antes de la formalización",
    e: "Según el artículo 152.2 de la LCSP, la decisión de no adjudicar o celebrar el contrato o el desistimiento del procedimiento pueden acordarse por el órgano de contratación:",
    ok: "Antes de la formalización.", mal: ["En cualquier momento de la ejecución.", "Solo antes del anuncio de licitación.", "Solo con el consentimiento de todos los licitadores."], d: 2 }),
  g({ id: "of-cs-45", art: "Artículo 157",
    cita: "La Mesa de contratación calificará la documentación a que se refiere el artículo 140, que deberá presentarse por los licitadores en sobre o archivo electrónico distinto al que contenga la proposición.",
    clave: "sobre o archivo electrónico distinto",
    e: "Conforme al artículo 157.1 de la LCSP, la documentación acreditativa de los requisitos previos debe presentarse por los licitadores:",
    ok: "En sobre o archivo electrónico distinto al que contenga la proposición.", mal: ["En el mismo sobre que la oferta económica.", "Solo después de la adjudicación, en todo caso.", "Por correo postal ordinario."], d: 2 }),
  g({ id: "of-cs-46", art: "Artículo 159",
    cita: "Que su valor estimado sea igual o inferior a 2.000.000 de euros en el caso de contratos de obras",
    clave: "2.000.000 de euros",
    e: "Según el artículo 159.1.a) de la LCSP, en los contratos de obras puede utilizarse el procedimiento abierto simplificado cuando su valor estimado sea igual o inferior a:",
    ok: "2.000.000 de euros.", mal: ["40.000 euros.", "5.538.000 euros.", "1.000.000 de euros."], d: 3 }),
  g({ id: "of-cs-47", art: "Artículo 167",
    cita: "Cuando para dar satisfacción a las necesidades del órgano de contratación resulte imprescindible que la prestación, tal y como se encuentra disponible en el mercado, sea objeto de un trabajo previo de diseño o de adaptación por parte de los licitadores.",
    clave: "trabajo previo de diseño o de adaptación",
    e: "¿Cuál de los siguientes es un supuesto del artículo 167 de la LCSP para utilizar el procedimiento de licitación con negociación?",
    ok: "Que la prestación disponible en el mercado necesite un trabajo previo de diseño o de adaptación por los licitadores.", mal: ["Que el valor estimado sea inferior a 15.000 euros.", "Que haya un único licitador posible por razones artísticas.", "Que se trate de un acontecimiento catastrófico."], d: 3 }),
  g({ id: "of-cs-48", art: "Artículo 174",
    cita: "Los órganos de contratación darán a conocer sus necesidades y requisitos en el anuncio de licitación y los definirán en dicho anuncio o en un documento descriptivo, que no podrá ser modificado posteriormente.",
    clave: "documento descriptivo",
    e: "En el diálogo competitivo, según el artículo 174.1 de la LCSP, los órganos de contratación dan a conocer sus necesidades y requisitos en el anuncio de licitación y los definen en dicho anuncio o en:",
    ok: "Un documento descriptivo, que no podrá ser modificado posteriormente.", mal: ["El pliego de prescripciones técnicas, modificable durante el diálogo.", "Un acta de negociación firmada con cada candidato.", "El perfil del contratante, sin formalidad alguna."], d: 3 }),
  g({ id: "of-cs-49", art: "Artículo 178",
    cita: "El plazo mínimo para la recepción de las solicitudes de participación será de treinta días a partir de la fecha de envío del anuncio de licitación, cuando el contrato esté sujeto a regulación armonizada.",
    clave: "treinta días",
    e: "En la asociación para la innovación sujeta a regulación armonizada, el artículo 178.2 de la LCSP fija como plazo mínimo para recibir las solicitudes de participación:",
    ok: "Treinta días desde el envío del anuncio de licitación.", mal: ["Quince días desde la publicación.", "Diez días hábiles.", "Dos meses desde la publicación en el BOE."], d: 3 }),
  g({ id: "of-cs-50", art: "Artículo 191",
    cita: "En los procedimientos que se instruyan para la adopción de acuerdos relativos a las prerrogativas establecidas en el artículo anterior, deberá darse audiencia al contratista.",
    clave: "audiencia al contratista",
    e: "Según el artículo 191.1 de la LCSP, en los procedimientos para adoptar acuerdos relativos a las prerrogativas de la Administración deberá darse:",
    ok: "Audiencia al contratista.", mal: ["Información pública por veinte días.", "Audiencia a los demás licitadores.", "Intervención del Tribunal de Cuentas."], d: 2 }),
  g({ id: "of-cs-51", art: "Artículo 193",
    cita: "La constitución en mora del contratista no precisará intimación previa por parte de la Administración.",
    clave: "no precisará intimación previa",
    e: "Conforme al artículo 193.2 de la LCSP, la constitución en mora del contratista:",
    ok: "No precisará intimación previa por parte de la Administración.", mal: ["Exige requerimiento notarial previo.", "Requiere un apercibimiento por escrito con un mes de antelación.", "Solo se produce por resolución judicial."], d: 2 }),
  g({ id: "of-cs-52", art: "Artículo 193",
    cita: "por la imposición de las penalidades diarias en la proporción de 0,60 euros por cada 1.000 euros del precio del contrato, IVA excluido",
    clave: "0,60 euros por cada 1.000 euros",
    e: "Si el contratista incurre en demora por causas imputables a él, según el artículo 193.3 de la LCSP la Administración puede imponer, salvo que el pliego prevea otras, penalidades diarias de:",
    ok: "0,60 euros por cada 1.000 euros del precio del contrato, IVA excluido.", mal: ["1 euro por cada 1.000 euros del precio, IVA incluido.", "0,20 euros por cada 1.000 euros del precio.", "El 5 % del precio por cada día de retraso."], d: 3 }),
  g({ id: "of-cs-53", art: "Artículo 196",
    cita: "Será obligación del contratista indemnizar todos los daños y perjuicios que se causen a terceros como consecuencia de las operaciones que requiera la ejecución del contrato.",
    clave: "obligación del contratista",
    e: "Según el artículo 196.1 de la LCSP, los daños y perjuicios causados a terceros como consecuencia de las operaciones que requiera la ejecución del contrato:",
    ok: "Son obligación del contratista indemnizarlos.", mal: ["Los indemniza siempre la Administración.", "Los cubre el Consorcio de Compensación de Seguros.", "No dan derecho a indemnización."],
    j: "La Administración solo responde cuando los daños derivan de una orden suya inmediata y directa o de vicios del proyecto.", d: 2 }),
  g({ id: "of-cs-54", art: "Artículo 200",
    cita: "Para que la cesión del derecho de cobro sea efectiva frente a la Administración, será requisito imprescindible la notificación fehaciente a la misma del acuerdo de cesión.",
    clave: "notificación fehaciente",
    e: "Conforme al artículo 200.2 de la LCSP, para que la cesión del derecho de cobro del contratista sea efectiva frente a la Administración es requisito imprescindible:",
    ok: "La notificación fehaciente a la Administración del acuerdo de cesión.", mal: ["La autorización previa del Consejo de Ministros.", "La inscripción en el Registro Mercantil.", "El consentimiento de los subcontratistas."], d: 2 }),
  g({ id: "of-cs-55", art: "Artículo 208",
    cita: "se extenderá un acta, de oficio o a solicitud del contratista, en la que se consignarán las circunstancias que la han motivado y la situación de hecho en la ejecución de aquel",
    clave: "se extenderá un acta",
    e: "Según el artículo 208.1 de la LCSP, cuando la Administración acuerde la suspensión del contrato:",
    ok: "Se extenderá un acta con las circunstancias que la han motivado y la situación de hecho en la ejecución.", mal: ["El contrato queda resuelto automáticamente.", "El contratista pierde la garantía definitiva.", "Se adjudica el contrato al siguiente licitador."], d: 2 }),
  g({ id: "of-cs-56", art: "Artículo 210",
    cita: "un acto formal y positivo de recepción o conformidad dentro del mes siguiente a la entrega o realización del objeto del contrato",
    clave: "dentro del mes siguiente",
    e: "Conforme al artículo 210.2 de la LCSP, la constatación del cumplimiento del contrato exige un acto formal y positivo de recepción o conformidad, salvo otro plazo en el pliego:",
    ok: "Dentro del mes siguiente a la entrega o realización del objeto.", mal: ["Dentro de los diez días siguientes.", "Dentro de los tres meses siguientes.", "Al finalizar el plazo de garantía."], d: 2 }),
  g({ id: "of-cs-57", art: "Artículo 215",
    cita: "El contratista podrá concertar con terceros la realización parcial de la prestación con sujeción a lo que dispongan los pliegos",
    clave: "realización parcial de la prestación",
    e: "Según el artículo 215.1 de la LCSP, mediante la subcontratación el contratista puede concertar con terceros:",
    ok: "La realización parcial de la prestación, con sujeción a lo que dispongan los pliegos.", mal: ["La cesión total del contrato sin autorización.", "La realización de toda la prestación en todo caso.", "La sustitución de la Administración contratante."], d: 1 }),
  g({ id: "of-cs-58", art: "Artículo 219",
    cita: "La duración de un acuerdo marco no podrá exceder de cuatro años, salvo en casos excepcionales, debidamente justificados.",
    clave: "cuatro años",
    e: "Conforme al artículo 219.2 de la LCSP, la duración de un acuerdo marco no podrá exceder, salvo casos excepcionales debidamente justificados, de:",
    ok: "Cuatro años.", mal: ["Dos años.", "Cinco años.", "Seis años."], d: 2 }),
  g({ id: "of-cs-59", art: "Artículo 223",
    cita: "El sistema dinámico de adquisición es un proceso totalmente electrónico, con una duración limitada y determinada en los pliegos",
    clave: "totalmente electrónico",
    e: "Según el artículo 223.2 de la LCSP, el sistema dinámico de adquisición es un proceso:",
    ok: "Totalmente electrónico, con duración limitada y abierto a cualquier empresa que cumpla los criterios de selección.", mal: ["En papel, cerrado a las empresas iniciales.", "Mixto, con fase presencial obligatoria.", "Indefinido y reservado a las grandes empresas."], d: 2 }),
  g({ id: "of-cs-60", art: "Artículo 227",
    cita: "Las entidades del sector público podrán centralizar la contratación de obras, servicios y suministros, atribuyéndola a servicios especializados.",
    clave: "servicios especializados",
    e: "Conforme al artículo 227.1 de la LCSP, las entidades del sector público podrán centralizar la contratación de obras, servicios y suministros atribuyéndola a:",
    ok: "Servicios especializados.", mal: ["Empresas privadas de intermediación.", "La Intervención General.", "El Tribunal de Cuentas."], d: 1 }),
  g({ id: "of-cs-61", art: "Artículo 300",
    cita: "el adjudicatario no tendrá derecho a indemnización por causa de pérdidas, averías o perjuicios ocasionados en los bienes antes de su entrega a la Administración, salvo que esta hubiere incurrido en mora al recibirlos",
    clave: "incurrido en mora al recibirlos",
    e: "En el contrato de suministro, según el artículo 300.2 de la LCSP, el adjudicatario no tiene derecho a indemnización por pérdidas o averías de los bienes antes de su entrega:",
    ok: "Salvo que la Administración hubiere incurrido en mora al recibirlos.", mal: ["Salvo que el bien sea de valor superior a 15.000 euros.", "En ningún caso, ni siquiera con mora de la Administración.", "Salvo que lo autorice el responsable del contrato."], d: 3 }),
  g({ id: "of-cs-62", art: "Artículo 308",
    cita: "llevarán aparejada la cesión de este a la Administración contratante",
    clave: "a la Administración contratante",
    e: "Según el artículo 308.1 de la LCSP, salvo que se disponga otra cosa, los contratos de servicios que tengan por objeto desarrollar productos protegidos por propiedad intelectual o industrial llevarán aparejada:",
    ok: "La cesión de ese derecho a la Administración contratante.", mal: ["La reserva del derecho al contratista en todo caso.", "La copropiedad al 50 % entre contratista y Administración.", "La publicación del producto con licencia libre obligatoria."], d: 2 }),
];
