// Ley 39/2015, del Procedimiento Administrativo Común (BOE-A-2015-10565).
// Auxiliar Administrativo, tema 11, y Administrativo del Estado, tema 18.
import type { Destino, PreguntaOficial } from "./tipos";

const D: Destino[] = [["auxiliar-administrativo", 11], ["administrativo-estado", 18]];
const p = (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma: "LPAC", destinos: D, ...x });

export const LPAC: PreguntaOficial[] = [
  p({ id: "of-lpac-01", art: "Artículo 1",
    cita: "así como los principios a los que se ha de ajustar el ejercicio de la iniciativa legislativa y la potestad reglamentaria",
    clave: "iniciativa legislativa y la potestad reglamentaria",
    e: "Además de los requisitos de validez y eficacia de los actos y del procedimiento común, el artículo 1.1 de la Ley 39/2015 incluye en su objeto regular los principios del ejercicio de:",
    ok: "La iniciativa legislativa y la potestad reglamentaria.",
    mal: ["La potestad jurisdiccional y la arbitral.", "La función inspectora y la recaudatoria.", "La contratación pública y las subvenciones."], d: 2 }),
  p({ id: "of-lpac-02", art: "Artículo 3",
    cita: "Los menores de edad para el ejercicio y defensa de aquellos de sus derechos e intereses cuya actuación esté permitida por el ordenamiento jurídico sin la asistencia de la persona que ejerza la patria potestad, tutela o curatela.",
    clave: "Los menores de edad",
    e: "Según el artículo 3 de la Ley 39/2015, además de quienes la tengan conforme a las normas civiles, tienen capacidad de obrar ante las Administraciones Públicas:",
    ok: "Los menores de edad, para los derechos e intereses cuya actuación permita el ordenamiento sin la asistencia de quien ejerza la patria potestad, tutela o curatela.",
    mal: ["Únicamente las personas mayores de dieciocho años.", "Solo las personas jurídicas inscritas en un registro público.", "Cualquier persona, con independencia de su edad y del derecho que ejercite."], d: 2 }),
  p({ id: "of-lpac-03", art: "Artículo 4",
    cita: "Quienes lo promuevan como titulares de derechos o intereses legítimos individuales o colectivos.",
    clave: "Quienes lo promuevan",
    e: "¿Cuál de los siguientes se considera interesado en el procedimiento administrativo según el artículo 4.1 de la Ley 39/2015?",
    ok: "Quienes lo promuevan como titulares de derechos o intereses legítimos individuales o colectivos.",
    mal: ["Cualquier ciudadano que tenga conocimiento del procedimiento.", "El funcionario que lo instruye.", "Únicamente quien haya presentado una denuncia."], d: 1 }),
  p({ id: "of-lpac-04", art: "Artículo 5",
    cita: "Los interesados con capacidad de obrar podrán actuar por medio de representante, entendiéndose con éste las actuaciones administrativas, salvo manifestación expresa en contra del interesado.",
    clave: "salvo manifestación expresa en contra del interesado",
    e: "Cuando un interesado actúa por medio de representante, según el artículo 5.1 de la Ley 39/2015, las actuaciones administrativas se entienden con el representante:",
    ok: "Salvo manifestación expresa en contra del interesado.",
    mal: ["Solo si el representante es abogado colegiado.", "Únicamente en los procedimientos iniciados de oficio.", "Solo para los actos de mero trámite."], d: 2 }),
  p({ id: "of-lpac-05", art: "Artículo 6",
    cita: "En el ámbito estatal, este registro será el Registro Electrónico de Apoderamientos de la Administración General del Estado.",
    clave: "Registro Electrónico de Apoderamientos",
    e: "Según el artículo 6.1 de la Ley 39/2015, en el ámbito estatal el registro electrónico general de apoderamientos es:",
    ok: "El Registro Electrónico de Apoderamientos de la Administración General del Estado.",
    mal: ["El Registro Civil.", "El Registro Mercantil Central.", "El Registro Central de Personal."], d: 1 }),
  p({ id: "of-lpac-06", art: "Artículo 14",
    cita: "a) Las personas jurídicas.",
    clave: "Las personas jurídicas",
    e: "¿Quiénes están obligados en todo caso a relacionarse electrónicamente con las Administraciones Públicas según el artículo 14.2 de la Ley 39/2015?",
    ok: "Las personas jurídicas, entre otros sujetos.",
    mal: ["Todas las personas físicas mayores de edad.", "Los pensionistas de la Seguridad Social.", "Los extranjeros residentes en España."], d: 1 }),
  p({ id: "of-lpac-07", art: "Artículo 14",
    cita: "Las personas físicas podrán elegir en todo momento si se comunican con las Administraciones Públicas para el ejercicio de sus derechos y obligaciones a través de medios electrónicos o no",
    clave: "elegir en todo momento",
    e: "Conforme al artículo 14.1 de la Ley 39/2015, las personas físicas no obligadas a relacionarse electrónicamente:",
    ok: "Podrán elegir en todo momento si se comunican con las Administraciones por medios electrónicos o no.",
    mal: ["Deben usar siempre medios electrónicos desde 2018.", "Solo pueden elegir el medio al iniciar el procedimiento, sin poder cambiarlo.", "Deben comunicarse siempre en papel."], d: 1 }),
  p({ id: "of-lpac-08", art: "Artículo 16",
    cita: "Cada Administración dispondrá de un Registro Electrónico General, en el que se hará el correspondiente asiento de todo documento que sea presentado o que se reciba en cualquier órgano administrativo",
    clave: "Registro Electrónico General",
    e: "Según el artículo 16.1 de la Ley 39/2015, el asiento de todo documento presentado o recibido en cualquier órgano administrativo se hará en:",
    ok: "El Registro Electrónico General de cada Administración.",
    mal: ["El Boletín Oficial del Estado.", "El archivo de oficina de cada unidad.", "La sede del Defensor del Pueblo."], d: 1 }),
  p({ id: "of-lpac-09", art: "Artículo 21",
    cita: "La Administración está obligada a dictar resolución expresa y a notificarla en todos los procedimientos cualquiera que sea su forma de iniciación.",
    clave: "cualquiera que sea su forma de iniciación",
    e: "Según el artículo 21.1 de la Ley 39/2015, la Administración está obligada a dictar resolución expresa y a notificarla:",
    ok: "En todos los procedimientos, cualquiera que sea su forma de iniciación.",
    mal: ["Solo en los procedimientos iniciados a solicitud del interesado.", "Solo en los procedimientos sancionadores.", "Solo cuando el interesado lo pida por escrito."], d: 1 }),
  p({ id: "of-lpac-10", art: "Artículo 21",
    cita: "Este plazo no podrá exceder de seis meses salvo que una norma con rango de Ley establezca uno mayor o así venga previsto en el Derecho de la Unión Europea.",
    clave: "seis meses",
    e: "Conforme al artículo 21.2 de la Ley 39/2015, el plazo máximo para notificar la resolución expresa, salvo norma con rango de ley o Derecho de la Unión Europea, no podrá exceder de:",
    ok: "Seis meses.",
    mal: ["Tres meses.", "Un año.", "Dos meses."], d: 1 }),
  p({ id: "of-lpac-11", art: "Artículo 21",
    cita: "Cuando las normas reguladoras de los procedimientos no fijen el plazo máximo, éste será de tres meses.",
    clave: "tres meses",
    e: "Si la norma reguladora de un procedimiento no fija el plazo máximo para resolver, según el artículo 21.3 de la Ley 39/2015 este será de:",
    ok: "Tres meses.",
    mal: ["Seis meses.", "Un mes.", "Diez días."], m: "Plazo para resolver: máximo 6 meses; si nada se dice, 3.", d: 1 }),
  p({ id: "of-lpac-12", art: "Artículo 24",
    cita: "el vencimiento del plazo máximo sin haberse notificado resolución expresa, legitima al interesado o interesados para entenderla estimada por silencio administrativo",
    clave: "estimada por silencio administrativo",
    e: "Como regla general, en los procedimientos iniciados a solicitud del interesado, el vencimiento del plazo máximo sin notificación de resolución expresa permite, según el artículo 24.1 de la Ley 39/2015, entender la solicitud:",
    ok: "Estimada por silencio administrativo.",
    mal: ["Denegada definitivamente, sin posibilidad de recurso.", "Caducada.", "Archivada sin efectos."], d: 2 }),
  p({ id: "of-lpac-13", art: "Artículo 25",
    cita: "los interesados que hubieren comparecido podrán entender desestimadas sus pretensiones por silencio administrativo",
    clave: "desestimadas",
    e: "En los procedimientos iniciados de oficio de los que pudiera derivarse el reconocimiento de derechos, si vence el plazo sin resolución, según el artículo 25.1.a) de la Ley 39/2015 los interesados que hubieren comparecido podrán entender sus pretensiones:",
    ok: "Desestimadas por silencio administrativo.",
    mal: ["Estimadas por silencio administrativo.", "Pendientes hasta que se dicte resolución, sin efecto alguno.", "Caducadas de forma automática."], d: 3 }),
  p({ id: "of-lpac-14", art: "Artículo 30",
    cita: "cuando los plazos se señalen por días, se entiende que éstos son hábiles, excluyéndose del cómputo los sábados, los domingos y los declarados festivos",
    clave: "los sábados, los domingos y los declarados festivos",
    e: "Según el artículo 30.2 de la Ley 39/2015, cuando los plazos se señalen por días se entiende que son hábiles, excluyéndose del cómputo:",
    ok: "Los sábados, los domingos y los declarados festivos.",
    mal: ["Solo los domingos y los festivos.", "Solo los festivos nacionales.", "Los días del mes de agosto."], d: 1 }),
  p({ id: "of-lpac-15", art: "Artículo 30",
    cita: "no podrán tener una duración superior a veinticuatro horas, en cuyo caso se expresarán en días",
    clave: "veinticuatro horas",
    e: "Conforme al artículo 30.1 de la Ley 39/2015, los plazos expresados por horas no podrán tener una duración superior a:",
    ok: "Veinticuatro horas; si la superan, se expresarán en días.",
    mal: ["Cuarenta y ocho horas.", "Setenta y dos horas.", "Doce horas."], d: 2 }),
  p({ id: "of-lpac-16", art: "Artículo 30",
    cita: "Cuando el último día del plazo sea inhábil, se entenderá prorrogado al primer día hábil siguiente.",
    clave: "primer día hábil siguiente",
    e: "Según el artículo 30.5 de la Ley 39/2015, cuando el último día del plazo sea inhábil:",
    ok: "Se entenderá prorrogado al primer día hábil siguiente.",
    mal: ["El plazo vence el día hábil anterior.", "El plazo se amplía en la mitad de su duración.", "El plazo vence ese mismo día inhábil."], d: 1 }),
  p({ id: "of-lpac-17", art: "Artículo 30",
    cita: "Cuando un día fuese hábil en el municipio o Comunidad Autónoma en que residiese el interesado, e inhábil en la sede del órgano administrativo, o a la inversa, se considerará inhábil en todo caso.",
    clave: "inhábil en todo caso",
    e: "Si un día es hábil en el municipio de residencia del interesado e inhábil en la sede del órgano administrativo, el artículo 30.6 de la Ley 39/2015 dispone que se considerará:",
    ok: "Inhábil en todo caso.",
    mal: ["Hábil en todo caso.", "Hábil a efectos del interesado e inhábil para la Administración.", "Según lo que elija el interesado."], d: 2 }),
  p({ id: "of-lpac-18", art: "Artículo 32",
    cita: "una ampliación de los plazos establecidos, que no exceda de la mitad de los mismos",
    clave: "la mitad",
    e: "Conforme al artículo 32.1 de la Ley 39/2015, la ampliación de los plazos establecidos, si las circunstancias lo aconsejan y no perjudica derechos de tercero, no podrá exceder de:",
    ok: "La mitad de los mismos.",
    mal: ["El doble de los mismos.", "Un tercio de los mismos.", "Diez días en todo caso."], d: 2 }),
  p({ id: "of-lpac-19", art: "Artículo 35",
    cita: "a) Los actos que limiten derechos subjetivos o intereses legítimos.",
    clave: "Los actos que limiten derechos subjetivos o intereses legítimos",
    e: "¿Cuál de los siguientes actos debe ser motivado según el artículo 35.1 de la Ley 39/2015?",
    ok: "Los actos que limiten derechos subjetivos o intereses legítimos.",
    mal: ["Los actos de mero trámite que no deciden el fondo.", "Las comunicaciones internas entre unidades.", "Los acuses de recibo del registro."],
    j: "Deben motivarse, con sucinta referencia de hechos y fundamentos de derecho, los actos que enumera el artículo 35.1.", d: 1 }),
  p({ id: "of-lpac-20", art: "Artículo 36",
    cita: "Los actos administrativos se producirán por escrito a través de medios electrónicos, a menos que su naturaleza exija otra forma más adecuada de expresión y constancia.",
    clave: "por escrito a través de medios electrónicos",
    e: "Según el artículo 36.1 de la Ley 39/2015, los actos administrativos se producirán, como regla general:",
    ok: "Por escrito a través de medios electrónicos.",
    mal: ["De forma verbal, salvo que el interesado pida constancia escrita.", "En papel, con firma manuscrita.", "Mediante publicación en el diario oficial."], d: 1 }),
  p({ id: "of-lpac-21", art: "Artículo 37",
    cita: "Las resoluciones administrativas de carácter particular no podrán vulnerar lo establecido en una disposición de carácter general, aunque aquéllas procedan de un órgano de igual o superior jerarquía al que dictó la disposición general.",
    clave: "igual o superior jerarquía",
    e: "El principio de inderogabilidad singular del artículo 37.1 de la Ley 39/2015 establece que una resolución de carácter particular no puede vulnerar una disposición general:",
    ok: "Aunque proceda de un órgano de igual o superior jerarquía al que dictó la disposición general.",
    mal: ["Salvo que proceda de un órgano de superior jerarquía.", "Salvo que la resolución sea favorable al interesado.", "Salvo que lo autorice el Consejo de Ministros."], d: 2 }),
  p({ id: "of-lpac-22", art: "Artículo 39",
    cita: "se presumirán válidos y producirán efectos desde la fecha en que se dicten, salvo que en ellos se disponga otra cosa",
    clave: "desde la fecha en que se dicten",
    e: "Según el artículo 39.1 de la Ley 39/2015, los actos de las Administraciones Públicas sujetos al Derecho Administrativo se presumirán válidos y producirán efectos:",
    ok: "Desde la fecha en que se dicten, salvo que en ellos se disponga otra cosa.",
    mal: ["Desde su publicación en el Boletín Oficial del Estado.", "A los veinte días de su notificación.", "Desde que adquieren firmeza."], d: 1 }),
  p({ id: "of-lpac-23", art: "Artículo 40",
    cita: "Toda notificación deberá ser cursada dentro del plazo de diez días a partir de la fecha en que el acto haya sido dictado",
    clave: "diez días",
    e: "Conforme al artículo 40.2 de la Ley 39/2015, toda notificación deberá ser cursada dentro del plazo de:",
    ok: "Diez días a partir de la fecha en que el acto haya sido dictado.",
    mal: ["Quince días a partir de la fecha en que el acto haya sido dictado.", "Un mes a partir de la firma del acto.", "Cinco días hábiles desde su registro."], d: 1 }),
  p({ id: "of-lpac-24", art: "Artículo 43",
    cita: "se entenderá rechazada cuando hayan transcurrido diez días naturales desde la puesta a disposición de la notificación sin que se acceda a su contenido",
    clave: "diez días naturales",
    e: "Cuando la notificación electrónica es obligatoria o la eligió el interesado, el artículo 43.2 de la Ley 39/2015 la tiene por rechazada si no se accede a su contenido transcurridos:",
    ok: "Diez días naturales desde su puesta a disposición.",
    mal: ["Diez días hábiles desde su puesta a disposición.", "Quince días naturales desde su envío.", "Un mes desde su puesta a disposición."], d: 2 }),
  p({ id: "of-lpac-25", art: "Artículo 44",
    cita: "la notificación se hará por medio de un anuncio publicado en el «Boletín Oficial del Estado»",
    clave: "Boletín Oficial del Estado",
    e: "Si los interesados son desconocidos o, intentada la notificación, no se pudo practicar, según el artículo 44 de la Ley 39/2015 la notificación se hará mediante anuncio publicado en:",
    ok: "El «Boletín Oficial del Estado».",
    mal: ["El tablón de edictos del ayuntamiento, exclusivamente.", "Un periódico de difusión nacional.", "La sede del órgano que dictó el acto, exclusivamente."], d: 1 }),
  p({ id: "of-lpac-26", art: "Artículo 47",
    cita: "c) Los que tengan un contenido imposible.",
    clave: "contenido imposible",
    e: "¿Cuál de los siguientes es un supuesto de nulidad de pleno derecho según el artículo 47.1 de la Ley 39/2015?",
    ok: "Los actos que tengan un contenido imposible.",
    mal: ["Los actos dictados fuera del plazo establecido, en todo caso.", "Los actos con un defecto de forma que no cause indefensión.", "Los actos que incurran en desviación de poder."],
    j: "La desviación de poder y los defectos de forma o de plazo son, en su caso, causas de anulabilidad (artículo 48).", d: 2 }),
  p({ id: "of-lpac-27", art: "Artículo 48",
    cita: "Son anulables los actos de la Administración que incurran en cualquier infracción del ordenamiento jurídico, incluso la desviación de poder.",
    clave: "desviación de poder",
    e: "Según el artículo 48.1 de la Ley 39/2015, son anulables los actos de la Administración que incurran en cualquier infracción del ordenamiento jurídico, incluso:",
    ok: "La desviación de poder.",
    mal: ["La incompetencia manifiesta por razón de la materia.", "La lesión de derechos susceptibles de amparo.", "El contenido imposible."], d: 2 }),
  p({ id: "of-lpac-28", art: "Artículo 54",
    cita: "Los procedimientos podrán iniciarse de oficio o a solicitud del interesado.",
    clave: "de oficio o a solicitud del interesado",
    e: "Según el artículo 54 de la Ley 39/2015, los procedimientos podrán iniciarse:",
    ok: "De oficio o a solicitud del interesado.",
    mal: ["Solo de oficio.", "Solo a solicitud del interesado.", "Solo por denuncia o por orden superior."], d: 1 }),
  p({ id: "of-lpac-29", art: "Artículo 58",
    cita: "bien por propia iniciativa o como consecuencia de orden superior, a petición razonada de otros órganos o por denuncia",
    clave: "orden superior",
    e: "Conforme al artículo 58 de la Ley 39/2015, los procedimientos se inician de oficio por acuerdo del órgano competente por propia iniciativa o como consecuencia de:",
    ok: "Orden superior, petición razonada de otros órganos o denuncia.",
    mal: ["Una solicitud del interesado.", "Una sentencia del Tribunal Constitucional, exclusivamente.", "Un acuerdo del Consejo de Ministros, exclusivamente."], d: 2 }),
  p({ id: "of-lpac-30", art: "Artículo 68",
    cita: "se requerirá al interesado para que, en un plazo de diez días, subsane la falta o acompañe los documentos preceptivos, con indicación de que, si así no lo hiciera, se le tendrá por desistido de su petición",
    clave: "tendrá por desistido",
    e: "Si una solicitud no reúne los requisitos exigidos y el interesado no la subsana en el plazo de diez días, según el artículo 68.1 de la Ley 39/2015:",
    ok: "Se le tendrá por desistido de su petición, previa resolución.",
    mal: ["Se entenderá estimada por silencio.", "Se tramitará igualmente con los datos aportados.", "Se le impondrá una sanción leve."], d: 1 }),
  p({ id: "of-lpac-31", art: "Artículo 69",
    cita: "se entenderá por declaración responsable el documento suscrito por un interesado en el que éste manifiesta, bajo su responsabilidad, que cumple con los requisitos establecidos en la normativa vigente",
    clave: "bajo su responsabilidad",
    e: "Según el artículo 69.1 de la Ley 39/2015, la declaración responsable es el documento suscrito por un interesado en el que manifiesta:",
    ok: "Bajo su responsabilidad, que cumple los requisitos de la normativa vigente para obtener el reconocimiento de un derecho o facultad o para su ejercicio.",
    mal: ["Su intención de iniciar una actividad en el plazo de un año.", "Su conformidad con la resolución dictada.", "La renuncia a interponer recursos."], d: 2 }),
  p({ id: "of-lpac-32", art: "Artículo 77",
    cita: "por un plazo no superior a treinta días ni inferior a diez",
    clave: "no superior a treinta días ni inferior a diez",
    e: "Cuando el instructor acuerda la apertura de un período de prueba, el artículo 77.2 de la Ley 39/2015 fija un plazo:",
    ok: "No superior a treinta días ni inferior a diez.",
    mal: ["No superior a quince días ni inferior a cinco.", "De un mes improrrogable.", "No superior a veinte días ni inferior a diez."], d: 2 }),
  p({ id: "of-lpac-33", art: "Artículo 80",
    cita: "Salvo disposición expresa en contrario, los informes serán facultativos y no vinculantes.",
    clave: "facultativos y no vinculantes",
    e: "Según el artículo 80.1 de la Ley 39/2015, salvo disposición expresa en contrario, los informes serán:",
    ok: "Facultativos y no vinculantes.",
    mal: ["Preceptivos y vinculantes.", "Preceptivos y no vinculantes.", "Facultativos y vinculantes."], m: "Por defecto, informes F-N: Facultativos y No vinculantes.", d: 1 }),
  p({ id: "of-lpac-34", art: "Artículo 82",
    cita: "Los interesados, en un plazo no inferior a diez días ni superior a quince, podrán alegar y presentar los documentos y justificaciones que estimen pertinentes.",
    clave: "no inferior a diez días ni superior a quince",
    e: "En el trámite de audiencia, el artículo 82.2 de la Ley 39/2015 concede a los interesados para alegar y presentar documentos un plazo:",
    ok: "No inferior a diez días ni superior a quince.",
    mal: ["No inferior a cinco días ni superior a diez.", "De veinte días como mínimo.", "De un mes improrrogable."], d: 2 }),
  p({ id: "of-lpac-35", art: "Artículo 83",
    cita: "determinará el plazo para formular alegaciones, que en ningún caso podrá ser inferior a veinte días",
    clave: "veinte días",
    e: "En el período de información pública, según el artículo 83.2 de la Ley 39/2015, el plazo para formular alegaciones en ningún caso podrá ser inferior a:",
    ok: "Veinte días.",
    mal: ["Diez días.", "Quince días.", "Un mes."], d: 2 }),
  p({ id: "of-lpac-36", art: "Artículo 95",
    cita: "la Administración le advertirá que, transcurridos tres meses, se producirá la caducidad del procedimiento",
    clave: "tres meses",
    e: "Si un procedimiento iniciado a solicitud del interesado se paraliza por causa imputable a este, según el artículo 95.1 de la Ley 39/2015 la Administración le advertirá de que se producirá la caducidad transcurridos:",
    ok: "Tres meses.",
    mal: ["Seis meses.", "Un mes.", "Diez días."], d: 2 }),
  p({ id: "of-lpac-37", art: "Artículo 107",
    cita: "La declaración de lesividad no podrá adoptarse una vez transcurridos cuatro años desde que se dictó el acto administrativo",
    clave: "cuatro años",
    e: "Según el artículo 107.2 de la Ley 39/2015, la declaración de lesividad de un acto favorable anulable no podrá adoptarse una vez transcurridos:",
    ok: "Cuatro años desde que se dictó el acto administrativo.",
    mal: ["Dos años desde que se dictó el acto.", "Cinco años desde su notificación.", "Seis meses desde su firmeza."], d: 2 }),
  p({ id: "of-lpac-38", art: "Artículo 109",
    cita: "rectificar en cualquier momento, de oficio o a instancia de los interesados, los errores materiales, de hecho o aritméticos existentes en sus actos",
    clave: "en cualquier momento",
    e: "Conforme al artículo 109.2 de la Ley 39/2015, las Administraciones Públicas pueden rectificar los errores materiales, de hecho o aritméticos existentes en sus actos:",
    ok: "En cualquier momento, de oficio o a instancia de los interesados.",
    mal: ["Solo dentro del plazo de un mes desde la notificación.", "Solo a instancia de los interesados.", "Solo previo dictamen del Consejo de Estado."], d: 1 }),
  p({ id: "of-lpac-39", art: "Artículo 122",
    cita: "El plazo para la interposición del recurso de alzada será de un mes, si el acto fuera expreso.",
    clave: "un mes",
    e: "Según el artículo 122.1 de la Ley 39/2015, si el acto es expreso, el plazo para interponer el recurso de alzada es de:",
    ok: "Un mes.",
    mal: ["Dos meses.", "Tres meses.", "Quince días."], d: 1 }),
  p({ id: "of-lpac-40", art: "Artículo 122",
    cita: "El plazo máximo para dictar y notificar la resolución será de tres meses.",
    clave: "tres meses",
    e: "Conforme al artículo 122.2 de la Ley 39/2015, el plazo máximo para dictar y notificar la resolución del recurso de alzada es de:",
    ok: "Tres meses.",
    mal: ["Un mes.", "Seis meses.", "Dos meses."], m: "Alzada: 1 mes para recurrir, 3 para resolver. Reposición: 1 y 1.", d: 2 }),
  p({ id: "of-lpac-41", art: "Artículo 123",
    cita: "podrán ser recurridos potestativamente en reposición ante el mismo órgano que los hubiera dictado o ser impugnados directamente ante el orden jurisdiccional contencioso-administrativo",
    clave: "ante el mismo órgano que los hubiera dictado",
    e: "Según el artículo 123.1 de la Ley 39/2015, los actos que pongan fin a la vía administrativa podrán ser recurridos potestativamente en reposición:",
    ok: "Ante el mismo órgano que los hubiera dictado.",
    mal: ["Ante el órgano superior jerárquico del que los dictó.", "Ante el Defensor del Pueblo.", "Ante el Consejo de Estado."], d: 1 }),
  p({ id: "of-lpac-42", art: "Artículo 124",
    cita: "El plazo máximo para dictar y notificar la resolución del recurso será de un mes.",
    clave: "un mes",
    e: "Conforme al artículo 124.2 de la Ley 39/2015, el plazo máximo para dictar y notificar la resolución del recurso de reposición es de:",
    ok: "Un mes.",
    mal: ["Tres meses.", "Dos meses.", "Quince días."], d: 2 }),
];
