// Estatuto Básico del Empleado Público (RDLeg 5/2015, BOE-A-2015-11719):
// Auxiliar tema 13 y Administrativo tema 23. Información y atención al
// ciudadano (RD 208/1996, BOE-A-1996-4997): Auxiliar tema 17.
import type { Destino, PreguntaOficial } from "./tipos";

const PERSONAL: Destino[] = [["auxiliar-administrativo", 13], ["administrativo-estado", 23]];
const ATENCION: Destino[] = [["auxiliar-administrativo", 17]];
const eb = (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma: "TREBEP", destinos: PERSONAL, ...x });
const at = (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma: "RD208", destinos: ATENCION, ...x });

export const TREBEP: PreguntaOficial[] = [
  eb({ id: "of-eb-01", art: "Artículo 8",
    cita: "Son empleados públicos quienes desempeñan funciones retribuidas en las Administraciones Públicas al servicio de los intereses generales.",
    clave: "funciones retribuidas",
    e: "Según el artículo 8.1 del TREBEP, son empleados públicos quienes desempeñan en las Administraciones Públicas, al servicio de los intereses generales:",
    ok: "Funciones retribuidas.", mal: ["Cualquier función, retribuida o no.", "Funciones de dirección política.", "Funciones voluntarias de colaboración."], d: 1 }),
  eb({ id: "of-eb-02", art: "Artículo 8",
    cita: "d) Personal eventual.",
    clave: "Personal eventual",
    e: "Además de funcionarios de carrera, funcionarios interinos y personal laboral, el artículo 8.2 del TREBEP clasifica a los empleados públicos en:",
    ok: "Personal eventual.", mal: ["Personal directivo de libre designación.", "Altos cargos.", "Personal en prácticas."], d: 2 }),
  eb({ id: "of-eb-03", art: "Artículo 9",
    cita: "están vinculados a una Administración Pública por una relación estatutaria regulada por el Derecho Administrativo para el desempeño de servicios profesionales retribuidos de carácter permanente",
    clave: "relación estatutaria",
    e: "Según el artículo 9.1 del TREBEP, los funcionarios de carrera están vinculados a una Administración Pública por:",
    ok: "Una relación estatutaria regulada por el Derecho Administrativo.", mal: ["Un contrato de trabajo regulado por el Estatuto de los Trabajadores.", "Un contrato administrativo de servicios.", "Un nombramiento temporal renovable cada año."], d: 1 }),
  eb({ id: "of-eb-04", art: "Artículo 9",
    cita: "el ejercicio de las funciones que impliquen la participación directa o indirecta en el ejercicio de las potestades públicas o en la salvaguardia de los intereses generales del Estado y de las Administraciones Públicas corresponden exclusivamente a los funcionarios públicos",
    clave: "exclusivamente a los funcionarios públicos",
    e: "Conforme al artículo 9.2 del TREBEP, las funciones que impliquen la participación directa o indirecta en el ejercicio de las potestades públicas corresponden:",
    ok: "Exclusivamente a los funcionarios públicos.", mal: ["Indistintamente a funcionarios y personal laboral.", "Al personal eventual de confianza.", "Al personal laboral fijo, exclusivamente."], d: 2 }),
  eb({ id: "of-eb-05", art: "Artículo 10",
    cita: "por razones expresamente justificadas de necesidad y urgencia, son nombrados como tales con carácter temporal para el desempeño de funciones propias de funcionarios de carrera",
    clave: "necesidad y urgencia",
    e: "Según el artículo 10.1 del TREBEP, los funcionarios interinos son nombrados con carácter temporal para funciones propias de funcionarios de carrera por razones expresamente justificadas de:",
    ok: "Necesidad y urgencia.", mal: ["Confianza o asesoramiento especial.", "Reestructuración organizativa.", "Promoción interna."], d: 1 }),
  eb({ id: "of-eb-06", art: "Artículo 10",
    cita: "La existencia de plazas vacantes, cuando no sea posible su cobertura por funcionarios de carrera, por un máximo de tres años",
    clave: "tres años",
    e: "Cuando un funcionario interino se nombra por la existencia de plazas vacantes no cubribles por funcionarios de carrera, el artículo 10.1.a) del TREBEP fija un máximo de:",
    ok: "Tres años.", mal: ["Dos años.", "Cinco años.", "Un año."], d: 2 }),
  eb({ id: "of-eb-07", art: "Artículo 11",
    cita: "Es personal laboral el que en virtud de contrato de trabajo formalizado por escrito",
    clave: "contrato de trabajo formalizado por escrito",
    e: "Según el artículo 11.1 del TREBEP, el personal laboral presta servicios retribuidos por las Administraciones Públicas en virtud de:",
    ok: "Contrato de trabajo formalizado por escrito.", mal: ["Nombramiento legal publicado en el diario oficial.", "Contrato verbal en cualquier modalidad.", "Relación estatutaria de carácter permanente."], d: 1 }),
  eb({ id: "of-eb-08", art: "Artículo 12",
    cita: "sólo realiza funciones expresamente calificadas como de confianza o asesoramiento especial",
    clave: "confianza o asesoramiento especial",
    e: "Según el artículo 12.1 del TREBEP, el personal eventual solo realiza funciones expresamente calificadas como de:",
    ok: "Confianza o asesoramiento especial.", mal: ["Dirección profesional.", "Ejercicio de potestades públicas.", "Sustitución de funcionarios de carrera."], d: 1 }),
  eb({ id: "of-eb-09", art: "Artículo 12",
    cita: "El nombramiento y cese serán libres.",
    clave: "serán libres",
    e: "Conforme al artículo 12.3 del TREBEP, el nombramiento y cese del personal eventual:",
    ok: "Serán libres.", mal: ["Exigen concurso público.", "Requieren informe de la Junta de Personal.", "Solo pueden producirse al final de la legislatura."], d: 1 }),
  eb({ id: "of-eb-10", art: "Artículo 13",
    cita: "Su designación atenderá a principios de mérito y capacidad y a criterios de idoneidad, y se llevará a cabo mediante procedimientos que garanticen la publicidad y concurrencia.",
    clave: "criterios de idoneidad",
    e: "Según el artículo 13.2 del TREBEP, la designación del personal directivo atenderá a principios de mérito y capacidad y a:",
    ok: "Criterios de idoneidad, mediante procedimientos que garanticen la publicidad y concurrencia.", mal: ["La confianza política del órgano que lo nombra.", "La antigüedad en el cuerpo de procedencia.", "El sorteo entre funcionarios del Subgrupo A1."], d: 2 }),
  eb({ id: "of-eb-11", art: "Artículo 14",
    cita: "a) A la inamovilidad en la condición de funcionario de carrera.",
    clave: "inamovilidad",
    e: "¿Cuál de los siguientes es un derecho individual de los empleados públicos según el artículo 14 del TREBEP?",
    ok: "La inamovilidad en la condición de funcionario de carrera.", mal: ["La elección libre del puesto de trabajo.", "La exención de la evaluación del desempeño.", "La percepción de horas extraordinarias sin límite."], d: 1 }),
  eb({ id: "of-eb-12", art: "Artículo 50",
    cita: "unas vacaciones retribuidas de veintidós días hábiles",
    clave: "veintidós días hábiles",
    e: "Según el artículo 50.1 del TREBEP, los funcionarios públicos tienen derecho a disfrutar durante cada año natural de unas vacaciones retribuidas de:",
    ok: "Veintidós días hábiles.", mal: ["Treinta días naturales.", "Veinticinco días hábiles.", "Un mes natural."], d: 1 }),
  eb({ id: "of-eb-13", art: "Artículo 50",
    cita: "no se considerarán como días hábiles los sábados",
    clave: "los sábados",
    e: "A efectos de las vacaciones de los funcionarios, el artículo 50.1 del TREBEP dispone que no se considerarán días hábiles:",
    ok: "Los sábados, sin perjuicio de las adaptaciones para horarios especiales.", mal: ["Los lunes.", "Los días de asuntos propios.", "Los días del mes de agosto."], d: 2 }),
  eb({ id: "of-eb-14", art: "Artículo 52",
    cita: "deberán actuar con arreglo a los siguientes principios: objetividad, integridad, neutralidad, responsabilidad, imparcialidad, confidencialidad",
    clave: "neutralidad",
    e: "¿Cuál de los siguientes figura entre los principios con arreglo a los cuales deben actuar los empleados públicos según el artículo 52 del TREBEP?",
    ok: "Neutralidad.", mal: ["Discrecionalidad.", "Oportunidad política.", "Lealtad al partido de gobierno."], d: 1 }),
  eb({ id: "of-eb-15", art: "Artículo 56",
    cita: "c) Tener cumplidos dieciséis años y no exceder, en su caso, de la edad máxima de jubilación forzosa.",
    clave: "dieciséis años",
    e: "Según el artículo 56.1.c) del TREBEP, para participar en los procesos selectivos es necesario tener cumplidos:",
    ok: "Dieciséis años y no exceder, en su caso, de la edad máxima de jubilación forzosa.", mal: ["Dieciocho años y no superar los sesenta y cinco.", "Dieciocho años, sin límite máximo.", "Veintiún años y no superar los cincuenta y cinco."], d: 1 }),
  eb({ id: "of-eb-16", art: "Artículo 57",
    cita: "Los nacionales de los Estados miembros de la Unión Europea podrán acceder, como personal funcionario, en igualdad de condiciones que los españoles a los empleos públicos",
    clave: "en igualdad de condiciones que los españoles",
    e: "Según el artículo 57.1 del TREBEP, los nacionales de los Estados miembros de la Unión Europea pueden acceder como personal funcionario a los empleos públicos:",
    ok: "En igualdad de condiciones que los españoles, salvo los que impliquen participación en el ejercicio del poder público.", mal: ["Únicamente como personal laboral.", "Solo tras cinco años de residencia en España.", "En ningún caso como personal funcionario."], d: 2 }),
  eb({ id: "of-eb-17", art: "Artículo 61",
    cita: "Los procesos selectivos tendrán carácter abierto y garantizarán la libre concurrencia",
    clave: "libre concurrencia",
    e: "Conforme al artículo 61.1 del TREBEP, los procesos selectivos tendrán carácter abierto y garantizarán:",
    ok: "La libre concurrencia, sin perjuicio de la promoción interna y de las medidas de discriminación positiva.", mal: ["La preferencia de los aspirantes de la misma Comunidad Autónoma.", "La reserva de plazas para el personal interino.", "El acceso exclusivo de quienes tengan experiencia previa."], d: 1 }),
  eb({ id: "of-eb-18", art: "Artículo 62",
    cita: "c) Acto de acatamiento de la Constitución y, en su caso, del Estatuto de Autonomía correspondiente y del resto del Ordenamiento Jurídico.",
    clave: "acatamiento de la Constitución",
    e: "Entre los requisitos que, según el artículo 62.1 del TREBEP, deben cumplirse sucesivamente para adquirir la condición de funcionario de carrera figura:",
    ok: "El acto de acatamiento de la Constitución y, en su caso, del Estatuto de Autonomía.", mal: ["La superación de un período de prueba de seis meses.", "La afiliación a una organización sindical.", "La declaración de bienes ante el Tribunal de Cuentas."], d: 2 }),
  eb({ id: "of-eb-19", art: "Artículo 62",
    cita: "d) Toma de posesión dentro del plazo que se establezca.",
    clave: "Toma de posesión",
    e: "Según el artículo 62.1 del TREBEP, ¿cuál es el último de los requisitos sucesivos para adquirir la condición de funcionario de carrera?",
    ok: "La toma de posesión dentro del plazo que se establezca.", mal: ["El nombramiento publicado en el Diario Oficial.", "La superación del proceso selectivo.", "La firma del contrato de trabajo."],
    j: "El orden es: superación del proceso selectivo, nombramiento publicado en el Diario Oficial, acto de acatamiento de la Constitución y toma de posesión.", d: 2 }),
  eb({ id: "of-eb-20", art: "Artículo 63",
    cita: "b) La pérdida de la nacionalidad.",
    clave: "pérdida de la nacionalidad",
    e: "¿Cuál de las siguientes es una causa de pérdida de la condición de funcionario de carrera según el artículo 63 del TREBEP?",
    ok: "La pérdida de la nacionalidad.", mal: ["La suspensión provisional de funciones.", "El paso a la situación de excedencia voluntaria.", "La sanción de traslado forzoso."], d: 1 }),
  eb({ id: "of-eb-21", art: "Artículo 76",
    cita: "Para el acceso a los cuerpos o escalas de este Grupo se exigirá estar en posesión del título universitario de Grado.",
    clave: "título universitario de Grado",
    e: "Según el artículo 76 del TREBEP, para el acceso a los cuerpos o escalas del Grupo A se exigirá:",
    ok: "El título universitario de Grado, salvo que la ley exija otro título universitario.", mal: ["El título de Técnico Superior.", "El título de Bachiller.", "El título de Doctor en todo caso."], d: 1 }),
  eb({ id: "of-eb-22", art: "Artículo 85",
    cita: "e) Suspensión de funciones.",
    clave: "Suspensión de funciones",
    e: "¿Cuál de las siguientes es una situación administrativa de los funcionarios de carrera según el artículo 85.1 del TREBEP?",
    ok: "Suspensión de funciones.", mal: ["Comisión de servicios.", "Interinidad.", "Jubilación parcial."], d: 2 }),
  eb({ id: "of-eb-23", art: "Artículo 95",
    cita: "Las faltas disciplinarias pueden ser muy graves, graves y leves.",
    clave: "muy graves, graves y leves",
    e: "Según el artículo 95.1 del TREBEP, las faltas disciplinarias pueden ser:",
    ok: "Muy graves, graves y leves.", mal: ["Graves y leves.", "Muy graves y graves.", "Penales y administrativas."], d: 1 }),
  eb({ id: "of-eb-24", art: "Artículo 96",
    cita: "c) Suspensión firme de funciones, o de empleo y sueldo en el caso del personal laboral, con una duración máxima de 6 años.",
    clave: "6 años",
    e: "Conforme al artículo 96.1.c) del TREBEP, la sanción de suspensión firme de funciones tiene una duración máxima de:",
    ok: "6 años.", mal: ["3 años.", "1 año.", "10 años."], d: 2 }),
  eb({ id: "of-eb-25", art: "Artículo 97",
    cita: "Las infracciones muy graves prescribirán a los tres años, las graves a los dos años y las leves a los seis meses",
    clave: "las leves a los seis meses",
    e: "Según el artículo 97.1 del TREBEP, las faltas disciplinarias prescriben:",
    ok: "Las muy graves a los tres años, las graves a los dos años y las leves a los seis meses.", mal: ["Las muy graves a los cinco años, las graves a los tres y las leves al año.", "Todas a los cuatro años.", "Las muy graves a los dos años, las graves al año y las leves a los tres meses."], d: 2 }),
];

export const ATENCION_CIUDADANO: PreguntaOficial[] = [
  at({ id: "of-at-01", art: "Artículo 1",
    cita: "La información encomendada a las unidades y oficinas a las que se refiere el capítulo II de este Real Decreto podrá ser general o particular.",
    clave: "general o particular",
    e: "Según el artículo 1 del Real Decreto 208/1996, la información administrativa que facilitan las unidades y oficinas de información podrá ser:",
    ok: "General o particular.", mal: ["Pública o reservada.", "Verbal o escrita, exclusivamente.", "Oficial u oficiosa."], d: 1 }),
  at({ id: "of-at-02", art: "Artículo 2",
    cita: "La información general se facilitará obligatoriamente a los ciudadanos, sin exigir para ello la acreditación de legitimación alguna.",
    clave: "sin exigir para ello la acreditación de legitimación alguna",
    e: "Conforme al artículo 2.2 del Real Decreto 208/1996, la información general se facilitará obligatoriamente a los ciudadanos:",
    ok: "Sin exigir para ello la acreditación de legitimación alguna.", mal: ["Previa acreditación de la condición de interesado.", "Solo a quienes estén empadronados en el municipio.", "Previo pago de la tasa correspondiente."], d: 1 }),
  at({ id: "of-at-03", art: "Artículo 2",
    cita: "Es la información administrativa relativa a la identificación, fines, competencia, estructura, funcionamiento y localización de organismos y unidades administrativas",
    clave: "información administrativa relativa a la identificación, fines, competencia, estructura",
    e: "Según el artículo 2.1 del Real Decreto 208/1996, la información general es, entre otras:",
    ok: "La información administrativa relativa a la identificación, fines, competencia, estructura, funcionamiento y localización de organismos y unidades.",
    mal: ["La relativa al estado de tramitación de un procedimiento concreto.", "La relativa a los datos personales de otros ciudadanos.", "La interpretación vinculante de las normas."], d: 2 }),
  at({ id: "of-at-04", art: "Artículo 3",
    cita: "Es la concerniente al estado o contenido de los procedimientos en tramitación",
    clave: "estado o contenido de los procedimientos en tramitación",
    e: "Conforme al artículo 3.1 del Real Decreto 208/1996, la información particular es la concerniente, entre otros aspectos, a:",
    ok: "El estado o contenido de los procedimientos en tramitación.", mal: ["La localización de las oficinas públicas.", "Los requisitos generales de los servicios públicos.", "Los horarios de atención al público."], d: 2 }),
  at({ id: "of-at-05", art: "Artículo 3",
    cita: "Esta información sólo podrá ser facilitada a las personas que tengan la condición de interesados en cada procedimiento o a sus representantes legales",
    clave: "condición de interesados",
    e: "Según el artículo 3.1 del Real Decreto 208/1996, la información particular sobre un procedimiento solo podrá facilitarse:",
    ok: "A quienes tengan la condición de interesados en él o a sus representantes legales.", mal: ["A cualquier ciudadano que la solicite.", "A los medios de comunicación acreditados.", "Solo al órgano judicial que la requiera."], d: 1 }),
  at({ id: "of-at-06", art: "Artículo 4",
    cita: "De recepción y acogida a los ciudadanos, al objeto de facilitarles la orientación y ayuda que precisen en el momento inicial de su visita",
    clave: "recepción y acogida",
    e: "¿Cuál de las siguientes funciones comprende la atención personalizada al ciudadano según el artículo 4 del Real Decreto 208/1996?",
    ok: "La recepción y acogida, para orientar y ayudar al ciudadano en el momento inicial de su visita.", mal: ["La resolución de los procedimientos administrativos.", "La imposición de sanciones por incumplimientos.", "La interpretación vinculante de las normas."], d: 1 }),
  at({ id: "of-at-07", art: "Artículo 4",
    cita: "en ningún caso podrá entrañar una interpretación normativa",
    clave: "interpretación normativa",
    e: "Conforme al artículo 4.b) del Real Decreto 208/1996, la función de orientación e información al ciudadano en ningún caso podrá entrañar:",
    ok: "Una interpretación normativa.", mal: ["Una ayuda de índole práctica.", "La explicación de requisitos y documentación.", "La localización de dependencias."], d: 2 }),
  at({ id: "of-at-08", art: "Artículo 10",
    cita: "la creación de oficinas integradas de información con participación de varias Administraciones públicas",
    clave: "oficinas integradas de información",
    e: "Según el artículo 10 del Real Decreto 208/1996, mediante convenio de colaboración entre Administraciones públicas puede acordarse, entre otras cosas:",
    ok: "La creación de oficinas integradas de información con participación de varias Administraciones públicas.", mal: ["La cesión de datos personales sin consentimiento.", "La supresión de las oficinas de registro.", "La unificación de las sedes electrónicas en una sola web privada."], d: 2 }),
];
