// Correos: Reglamento de los servicios postales (RD 437/2024,
// BOE-A-2024-10010) y Ley 43/2010 del servicio postal universal
// (BOE-A-2010-20139), solo en los artículos que no preguntan ya las 50
// preguntas de Correos tema 1 de la base de datos.
// Temas: 1 productos y servicios postales, 2 paquetería y logística,
// 5 clasificación y reparto, 10 normativa postal y protección de datos.
import type { Destino, NormaOficial, PreguntaOficial } from "./tipos";

const T = (tema: number): Destino[] => [["correos", tema]];
const f = (norma: NormaOficial, tema: number) => (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma, destinos: T(tema), ...x });
const r1 = f("RPOSTAL", 1);
const r2 = f("RPOSTAL", 2);
const r5 = f("RPOSTAL", 5);
const r10 = f("RPOSTAL", 10);
const l1 = f("LPOSTAL", 1);
const l2 = f("LPOSTAL", 2);
const l5 = f("LPOSTAL", 5);
const l10 = f("LPOSTAL", 10);

export const POSTAL: PreguntaOficial[] = [
  // ── Tema 5: clasificación y reparto ──
  r5({ id: "of-po-01", art: "Artículo 2",
    cita: "a) Recogida: la actividad consistente en la retirada de los envíos postales depositados en los puntos de acceso a la red postal del operador.",
    clave: "retirada de los envíos postales depositados",
    e: "Según el artículo 2.2.a) del Reglamento de los servicios postales (RD 437/2024), la recogida es la actividad consistente en:",
    ok: "La retirada de los envíos postales depositados en los puntos de acceso a la red postal del operador.", mal: ["El reparto en las direcciones indicadas en los envíos.", "El traslado de los envíos hasta su punto de distribución final.", "La ordenación de los envíos para encaminarlos."], d: 1 }),
  r5({ id: "of-po-02", art: "Artículo 2",
    cita: "c) Clasificación: la actividad consistente en el conjunto de operaciones cuyo fin es ordenar los envíos postales para encaminarlos desde los puntos de acceso a la red postal del operador hasta la distribución y entrega.",
    clave: "ordenar los envíos postales para encaminarlos",
    e: "Conforme al artículo 2.2.c) del Reglamento de los servicios postales, la clasificación es el conjunto de operaciones cuyo fin es:",
    ok: "Ordenar los envíos postales para encaminarlos desde los puntos de acceso hasta la distribución y entrega.", mal: ["Recibir del remitente el envío que se le confía.", "Repartir los envíos en las direcciones indicadas.", "Retirar los envíos de los buzones."], d: 1 }),
  r5({ id: "of-po-03", art: "Artículo 2",
    cita: "d) Transporte: la actividad consistente en el traslado por cualquier tipo de medios de los envíos postales hasta su punto de distribución final.",
    clave: "traslado por cualquier tipo de medios",
    e: "Según el artículo 2.2.d) del Reglamento de los servicios postales, el transporte es la actividad consistente en:",
    ok: "El traslado por cualquier tipo de medios de los envíos postales hasta su punto de distribución final.", mal: ["La entrega al destinatario en mano.", "La admisión de los envíos en la oficina.", "La ordenación de los envíos por códigos postales."], d: 1 }),
  r5({ id: "of-po-04", art: "Artículo 2",
    cita: "e) Distribución: la actividad consistente en cualquier operación realizada en los locales de destino del operador postal a donde ha sido transportado el envío postal de forma inmediatamente previa a su entrega final al destinatario del mismo.",
    clave: "inmediatamente previa a su entrega final",
    e: "Conforme al artículo 2.2.e) del Reglamento de los servicios postales, la distribución es cualquier operación realizada en los locales de destino del operador:",
    ok: "De forma inmediatamente previa a su entrega final al destinatario.", mal: ["En el momento de la admisión del envío.", "Durante el transporte internacional.", "Después de que el destinatario haya recibido el envío."], d: 2 }),
  r5({ id: "of-po-05", art: "Artículo 2",
    cita: "f) Entrega: la actividad consistente en el reparto en las direcciones indicadas en los envíos postales, con las salvedades que se establecen en este reglamento.",
    clave: "reparto en las direcciones indicadas",
    e: "Según el artículo 2.2.f) del Reglamento de los servicios postales, la entrega es la actividad consistente en:",
    ok: "El reparto en las direcciones indicadas en los envíos postales, con las salvedades del reglamento.", mal: ["El traslado de los envíos entre centros de tratamiento.", "La recepción del envío en la oficina de admisión.", "La retirada de los envíos de los buzones."], d: 1 }),
  r5({ id: "of-po-06", art: "Artículo 17",
    cita: "Se procurará la entrega de aquellos envíos postales cuya dirección, aun siendo incompleta permita la identificación del destinatario",
    clave: "aun siendo incompleta",
    e: "Conforme al artículo 17 del Reglamento de los servicios postales, se procurará la entrega de los envíos cuya dirección:",
    ok: "Aun siendo incompleta, permita la identificación del destinatario.", mal: ["Esté escrita a mano.", "No incluya el código postal, en ningún caso.", "Sea ilegible pero tenga el nombre del remitente."], d: 2 }),
  r5({ id: "of-po-07", art: "Artículo 18",
    cita: "cualquier persona que se encuentre en la dirección que figure en la cubierta del envío, haga constar su identidad y se haga cargo de ellos",
    clave: "haga constar su identidad y se haga cargo de ellos",
    e: "Según el artículo 18 del Reglamento de los servicios postales, salvo prohibición expresa, se entiende autorizada por el destinatario para recibir los envíos:",
    ok: "Cualquier persona que se encuentre en la dirección, haga constar su identidad y se haga cargo de ellos.", mal: ["Solo el destinatario en persona.", "Cualquier vecino del inmueble, aunque no se identifique.", "Solo quien tenga un poder notarial."], d: 2 }),
  r5({ id: "of-po-08", art: "Artículo 18",
    cita: "mediante la exhibición de su documento nacional de identidad, pasaporte, permiso de conducción o tarjeta de residencia, salvo notorio conocimiento del mismo por parte del empleado postal",
    clave: "salvo notorio conocimiento",
    e: "Conforme al artículo 18 del Reglamento de los servicios postales, quien se haga cargo de un envío debe identificarse ante el empleado mediante DNI, pasaporte, permiso de conducción o tarjeta de residencia:",
    ok: "Salvo notorio conocimiento de esa persona por parte del empleado postal.", mal: ["En ningún caso, basta con firmar.", "Solo si el envío es un paquete.", "Salvo que el envío sea de publicidad."], d: 2 }),
  r5({ id: "of-po-09", art: "Artículo 19",
    cita: "e) Código postal: el asignado a cada dirección postal.",
    clave: "Código postal",
    e: "¿Cuál de los siguientes es uno de los elementos que componen el domicilio a efectos de entrega según el artículo 19 del Reglamento de los servicios postales?",
    ok: "El código postal asignado a cada dirección postal.", mal: ["El número de teléfono del destinatario.", "El NIF del destinatario.", "La referencia catastral del inmueble, exclusivamente."], d: 1 }),
  r5({ id: "of-po-10", art: "Artículo 19",
    cita: "a) El número de casillero domiciliario postal a continuación de las letras «CD».",
    clave: "«CD»",
    e: "Según el artículo 19.a) del Reglamento de los servicios postales, el número de casillero domiciliario postal se indica a continuación de las letras:",
    ok: "«CD».", mal: ["«AP».", "«CP».", "«BZ»."], d: 3 }),
  r5({ id: "of-po-11", art: "Artículo 20",
    cita: "Los envíos certificados sólo podrán entregarse, previa firma, a los respectivos destinatarios o a otra persona autorizada por los mismos.",
    clave: "previa firma",
    e: "Conforme al artículo 20 del Reglamento de los servicios postales, los envíos certificados solo podrán entregarse:",
    ok: "Previa firma, a sus destinatarios o a otra persona autorizada por ellos.", mal: ["Dejándolos en el casillero domiciliario.", "A cualquier persona del edificio sin firma.", "Solo en la oficina de admisión."], d: 1 }),
  r5({ id: "of-po-12", art: "Artículo 20",
    cita: "Si el destinatario de un envío certificado, o la persona autorizada, no pudieran o no supieran firmar, lo hará en su lugar un testigo, debidamente identificado.",
    clave: "testigo",
    e: "Si el destinatario de un envío certificado no puede o no sabe firmar, según el artículo 20 del Reglamento de los servicios postales:",
    ok: "Firmará en su lugar un testigo debidamente identificado.", mal: ["El envío se devuelve al remitente.", "El envío se entrega sin dejar constancia.", "Firma el propio empleado postal en nombre del destinatario."], d: 2 }),
  r5({ id: "of-po-13", art: "Artículo 21",
    cita: "Los usuarios podrán recibir sus envíos por este sistema cuando expresamente lo soliciten y en las condiciones contractuales pactadas.",
    clave: "cuando expresamente lo soliciten",
    e: "Según el artículo 21 del Reglamento de los servicios postales, los usuarios pueden recibir sus envíos a través de apartados postales:",
    ok: "Cuando expresamente lo soliciten y en las condiciones contractuales pactadas.", mal: ["Siempre que lo decida el operador.", "Solo si viven en zonas rurales.", "Obligatoriamente si no tienen casillero."], d: 2 }),
  r5({ id: "of-po-14", art: "Artículo 22",
    cita: "la dirección de la oficina o de la dependencia propia o designada por los operadores postales, horario y el plazo de permanencia en la misma para su retirada",
    clave: "plazo de permanencia",
    e: "Cuando un envío no se ha podido entregar por ausencia y queda en oficina, el aviso de llegada que se deja al destinatario debe indicar, según el artículo 22 del Reglamento de los servicios postales, además del remitente:",
    ok: "La dirección de la oficina o dependencia, el horario y el plazo de permanencia para su retirada.", mal: ["El contenido del envío.", "El nombre del empleado que intentó la entrega.", "El precio pagado por el remitente."], d: 2 }),
  r5({ id: "of-po-15", art: "Artículo 23",
    cita: "El aviso de llegada en casillero podrá ser sustituido, si así lo acuerdan las partes, por la comunicación al destinatario, por cualquier medio electrónico pactado, de la puesta a disposición del envío.",
    clave: "medio electrónico pactado",
    e: "Conforme al artículo 23 del Reglamento de los servicios postales, el aviso de llegada en el casillero podrá sustituirse, si así lo acuerdan las partes, por:",
    ok: "La comunicación al destinatario, por cualquier medio electrónico pactado, de la puesta a disposición del envío.", mal: ["Una llamada al remitente.", "La publicación en el tablón de la oficina.", "Un segundo intento de entrega en todo caso."], d: 2 }),
  r5({ id: "of-po-16", art: "Artículo 25",
    cita: "el número de casilleros será, al menos, igual al número de locales y viviendas susceptibles de aprovechamiento independiente, con otro más debidamente señalizado para la devolución de envíos",
    clave: "otro más debidamente señalizado para la devolución",
    e: "En los inmuebles en régimen de propiedad horizontal, según el artículo 25.2 del Reglamento de los servicios postales, el número de casilleros será al menos igual al de locales y viviendas independientes:",
    ok: "Con otro más debidamente señalizado para la devolución de envíos.", mal: ["Sin casillero adicional alguno.", "Más dos casilleros para paquetería.", "Con un casillero común para todos los vecinos."], d: 2 }),
  r5({ id: "of-po-17", art: "Artículo 25",
    cita: "debiendo situarse correlativamente de izquierda a derecha y de arriba abajo",
    clave: "de izquierda a derecha y de arriba abajo",
    e: "Conforme al artículo 25.2 del Reglamento de los servicios postales, los casilleros domiciliarios, a partir del de devoluciones, deben situarse correlativamente:",
    ok: "De izquierda a derecha y de arriba abajo.", mal: ["De derecha a izquierda y de abajo arriba.", "Por orden alfabético de los vecinos.", "Sin orden predeterminado."], d: 3 }),
  r5({ id: "of-po-18", art: "Artículo 26",
    cita: "la entrega de los envíos dirigidos a sus vecinos se realizará en la oficina que corresponda",
    clave: "en la oficina que corresponda",
    e: "Si un operador postal detecta un inmueble sin casilleros domiciliarios o mal acondicionados, según el artículo 26.1 del Reglamento de los servicios postales, mientras se instalan la entrega de los envíos se realizará:",
    ok: "En la oficina que corresponda.", mal: ["En el domicilio del presidente de la comunidad.", "En la puerta del inmueble.", "Mediante devolución inmediata al remitente."], d: 2 }),
  r5({ id: "of-po-19", art: "Artículo 26",
    cita: "La gestión del casillero de devoluciones corresponderá al operador designado para la prestación del servicio postal universal",
    clave: "operador designado",
    e: "Según el artículo 26.2 del Reglamento de los servicios postales, la gestión del casillero de devoluciones corresponde:",
    ok: "Al operador designado para la prestación del servicio postal universal.", mal: ["A la comunidad de propietarios.", "A cualquier operador que reparta en el edificio, por turnos.", "Al ayuntamiento."], d: 2 }),
  r5({ id: "of-po-20", art: "Artículo 31",
    cita: "que disten más de 250 metros de la vía pública habitualmente utilizada por los servicios públicos colectivos",
    clave: "250 metros",
    e: "En entornos especiales, según el artículo 31.1.a) del Reglamento de los servicios postales, el reparto mediante buzones individuales o agrupados al paso se aplica a viviendas aisladas o diseminadas que disten de la vía pública habitualmente utilizada por los servicios públicos colectivos más de:",
    ok: "250 metros.", mal: ["100 metros.", "500 metros.", "1 kilómetro."], d: 3 }),
  r5({ id: "of-po-21", art: "Artículo 32",
    cita: "requerirá que previamente se recabe autorización expresa del remitente de estos envíos; en caso contrario serán devueltos a sus remitentes",
    clave: "autorización expresa del remitente",
    e: "Las cartas y tarjetas postales dirigidas a personas fallecidas, por su carácter actual y personal, solo se entregarán a sus herederos, según el artículo 32.a) del Reglamento de los servicios postales, si:",
    ok: "Previamente se recaba autorización expresa del remitente; si no, se devuelven.", mal: ["Los herederos presentan el certificado de defunción, sin más.", "Han pasado seis meses del fallecimiento.", "Lo autoriza un juez en todo caso."], d: 3 }),
  r5({ id: "of-po-22", art: "Artículo 33",
    cita: "El destinatario o la persona autorizada podrán rehusar el envío postal en el momento de la entrega y antes de abrirlo.",
    clave: "antes de abrirlo",
    e: "Según el artículo 33.1 del Reglamento de los servicios postales, el destinatario o la persona autorizada pueden rehusar el envío postal en el momento de la entrega y:",
    ok: "Antes de abrirlo.", mal: ["Después de leer su contenido.", "En los quince días siguientes.", "Solo si el remitente lo autoriza."], d: 1 }),
  r5({ id: "of-po-23", art: "Artículo 34",
    cita: "disponiendo para ello de un plazo máximo de cinco días desde la fecha en que dicha circunstancia se produce",
    clave: "cinco días",
    e: "Cuando no es posible entregar un envío, el operador puede devolverlo o comunicar al remitente la circunstancia que lo impide. Según el artículo 34.1 del Reglamento de los servicios postales, dispone para ello de un plazo máximo de:",
    ok: "Cinco días desde que se produce la circunstancia.", mal: ["Diez días.", "Un mes.", "Tres meses."], d: 2 }),
  r5({ id: "of-po-24", art: "Artículo 35",
    cita: "estos envíos postales permanecerán en depósito durante un plazo de tres meses a contar desde que hayan sido considerados abandonados",
    clave: "tres meses",
    e: "Según el artículo 35.1 del Reglamento de los servicios postales, con carácter general los envíos considerados abandonados permanecerán en depósito durante:",
    ok: "Tres meses desde que se consideren abandonados; después se consideran caducados.", mal: ["Un mes.", "Seis meses.", "Un año."], d: 2 }),
  // ── Tema 1: productos y servicios postales ──
  r1({ id: "of-po-25", art: "Artículo 2",
    cita: "a) Carta: todo envío cerrado cuyo contenido no se indique ni pueda conocerse, así como toda comunicación materializada en forma escrita sobre soporte físico de cualquier naturaleza, que tenga carácter actual y personal.",
    clave: "carácter actual y personal",
    e: "Según el artículo 2.3.a) del Reglamento de los servicios postales, es carta todo envío cerrado cuyo contenido no se indique ni pueda conocerse, así como toda comunicación escrita sobre soporte físico que tenga:",
    ok: "Carácter actual y personal.", mal: ["Un peso inferior a 2 kilos.", "Valor comercial.", "Formato normalizado A4."], d: 1 }),
  r1({ id: "of-po-26", art: "Artículo 2",
    cita: "En todo caso, tendrán la consideración de carta los envíos de recibos, facturas, documentos de negocios, estados financieros y cualesquiera otros mensajes que no sean idénticos.",
    clave: "recibos, facturas",
    e: "Conforme al artículo 2.3.a) del Reglamento de los servicios postales, ¿cuál de los siguientes envíos tiene en todo caso la consideración de carta?",
    ok: "Los recibos, facturas, documentos de negocios y estados financieros.", mal: ["Los folletos publicitarios idénticos.", "Los libros y catálogos.", "Las muestras de productos."], d: 2 }),
  r1({ id: "of-po-27", art: "Artículo 2",
    cita: "b) Tarjeta postal: toda pieza rectangular de cartulina consistente o material similar, lleve o no el título de tarjeta postal, que circule al descubierto y que contenga un mensaje de carácter actual y personal.",
    clave: "circule al descubierto",
    e: "Según el artículo 2.3.b) del Reglamento de los servicios postales, la tarjeta postal es toda pieza rectangular de cartulina consistente o material similar que:",
    ok: "Circule al descubierto y contenga un mensaje de carácter actual y personal.", mal: ["Circule siempre dentro de un sobre cerrado.", "Contenga exclusivamente publicidad.", "Pese más de 100 gramos."], d: 1 }),
  r1({ id: "of-po-28", art: "Artículo 2",
    cita: "3.º Que en su cubierta figure la expresión «P.D.» a efectos de facilitar la identificación de estos envíos.",
    clave: "«P.D.»",
    e: "Para que un envío se considere de publicidad directa, el artículo 2.3.d) del Reglamento de los servicios postales exige, entre otros requisitos, que en su cubierta figure la expresión:",
    ok: "«P.D.».", mal: ["«PUBL.».", "«S.P.U.».", "«C.D.»."], d: 2 }),
  r1({ id: "of-po-29", art: "Artículo 2",
    cita: "2.º Que circule en sobre abierto o que permita la apertura para facilitar la inspección postal.",
    clave: "sobre abierto",
    e: "Según el artículo 2.3.d) del Reglamento de los servicios postales, uno de los requisitos para que un envío sea de publicidad directa es que circule:",
    ok: "En sobre abierto o que permita la apertura para facilitar la inspección postal.", mal: ["En sobre cerrado y lacrado.", "Siempre como certificado.", "Con valor declarado."], d: 2 }),
  r1({ id: "of-po-30", art: "Artículo 2",
    cita: "1.º Que se remita a una pluralidad de destinatarios.",
    clave: "pluralidad de destinatarios",
    e: "¿Cuál de los siguientes es un requisito para que un envío se considere de publicidad directa según el artículo 2.3.d) del Reglamento de los servicios postales?",
    ok: "Que se remita a una pluralidad de destinatarios.", mal: ["Que vaya dirigido a un único destinatario.", "Que contenga facturas.", "Que se entregue en mano."], d: 1 }),
  r1({ id: "of-po-31", art: "Artículo 8",
    cita: "Todos los operadores postales tienen la obligación de identificarse de forma legible en el anverso de la cubierta del envío y en el resguardo o justificante de admisión de éste, con indicación de la fecha en que se hagan cargo del mismo.",
    clave: "anverso de la cubierta del envío",
    e: "Según el artículo 8 del Reglamento de los servicios postales, todos los operadores postales deben identificarse de forma legible en:",
    ok: "El anverso de la cubierta del envío y el resguardo de admisión, con la fecha en que se hagan cargo.", mal: ["El reverso del envío, exclusivamente.", "Solo en su página web.", "En el interior del envío."], d: 2 }),
  r1({ id: "of-po-32", art: "Artículo 12",
    cita: "cada una de estas actividades, excepto si consiste exclusivamente en una actividad de mero transporte, es susceptible de constituir, por sí misma, un servicio postal",
    clave: "mero transporte",
    e: "Según el artículo 12.2 del Reglamento de los servicios postales, cada una de las actividades postales (recogida, admisión, clasificación, transporte, distribución y entrega) puede constituir por sí misma un servicio postal, excepto si consiste exclusivamente en:",
    ok: "Una actividad de mero transporte.", mal: ["La entrega en mano.", "La clasificación de envíos.", "La admisión en oficina."], d: 3 }),
  r1({ id: "of-po-33", art: "Artículo 13",
    cita: "De acuerdo con su régimen de prestación los servicios postales se clasifican en servicios prestados en régimen ordinario y servicios prestados en régimen de servicio especial.",
    clave: "régimen ordinario y servicios prestados en régimen de servicio especial",
    e: "Conforme al artículo 13.1 del Reglamento de los servicios postales, según su régimen de prestación los servicios postales se clasifican en servicios prestados en:",
    ok: "Régimen ordinario y servicios prestados en régimen de servicio especial.", mal: ["Régimen nacional y régimen internacional.", "Régimen público y régimen privado.", "Régimen urgente y régimen económico."], d: 2 }),
  r1({ id: "of-po-34", art: "Artículo 13",
    cita: "a) Compromiso de entrega en una fecha u hora determinada.",
    clave: "Compromiso de entrega en una fecha u hora determinada",
    e: "¿Cuál de las siguientes prestaciones, pactada contractualmente, hace que un servicio postal se preste en régimen de servicio especial según el artículo 13.3 del Reglamento de los servicios postales?",
    ok: "Compromiso de entrega en una fecha u hora determinada.", mal: ["Uso de sellos de correo.", "Depósito en un buzón de la vía pública.", "Envío de publicidad directa."], d: 2 }),
  r1({ id: "of-po-35", art: "Artículo 13",
    cita: "Los servicios prestados en régimen ordinario no verán alterado su régimen de prestación cuando vayan acompañados de los servicios accesorios de certificado y valor declarado.",
    clave: "alterado su régimen de prestación",
    e: "Según el artículo 13.2 del Reglamento de los servicios postales, cuando un servicio prestado en régimen ordinario va acompañado de los servicios accesorios de certificado y valor declarado:",
    ok: "No verá alterado su régimen de prestación.", mal: ["Pasa automáticamente a régimen de servicio especial.", "Deja de ser un servicio postal.", "Queda excluido del servicio postal universal."], d: 3 }),
  r1({ id: "of-po-36", art: "Artículo 14",
    cita: "El franqueo es la forma de acreditar el pago de los servicios postales consistente en la adhesión o estampación de efectos o signos sobre los envíos postales",
    clave: "acreditar el pago",
    e: "Según el artículo 14.1 del Reglamento de los servicios postales, el franqueo es:",
    ok: "La forma de acreditar el pago de los servicios postales mediante la adhesión o estampación de efectos o signos.", mal: ["El peso máximo de un envío.", "El seguimiento de un envío.", "La firma del destinatario en la entrega."], d: 1 }),
  r1({ id: "of-po-37", art: "Artículo 14",
    cita: "únicamente podrán ser utilizados por el operador designado para la prestación del servicio postal universal",
    clave: "únicamente podrán ser utilizados por el operador designado",
    e: "Conforme al artículo 14.2 del Reglamento de los servicios postales, los sellos de correo y demás signos de franqueo oficiales:",
    ok: "Únicamente podrán ser utilizados por el operador designado para el servicio postal universal.", mal: ["Pueden ser usados por cualquier operador postal.", "Solo pueden usarse en envíos internacionales.", "Los emite cada operador privado libremente."], d: 2 }),
  r1({ id: "of-po-38", art: "Artículo 16",
    cita: "Los operadores postales admitirán los envíos postales siempre que se presenten debidamente acondicionados y se satisfaga el precio correspondiente",
    clave: "debidamente acondicionados",
    e: "Según el artículo 16 del Reglamento de los servicios postales, los operadores admitirán los envíos postales siempre que se presenten:",
    ok: "Debidamente acondicionados y se satisfaga el precio correspondiente.", mal: ["Con seguro contratado en todo caso.", "En días laborables, exclusivamente.", "Con el DNI del destinatario."], d: 1 }),
  r1({ id: "of-po-39", art: "Artículo 53",
    cita: "El sello de excelencia está destinado a distinguir a los operadores postales que destaquen en su gestión en materia medioambiental, social, laboral y, en general, por su responsabilidad social corporativa",
    clave: "responsabilidad social corporativa",
    e: "Según el artículo 53.1 del Reglamento de los servicios postales, el sello de excelencia distingue a los operadores postales que destaquen en su gestión medioambiental, social, laboral y, en general, por:",
    ok: "Su responsabilidad social corporativa.", mal: ["Su volumen de facturación.", "Su número de oficinas.", "El precio más bajo del mercado."], d: 2 }),
  r1({ id: "of-po-40", art: "Artículo 55",
    cita: "La concesión del sello de excelencia comporta el derecho a usar, durante tres años desde su concesión, el distintivo acreditativo del mismo",
    clave: "tres años",
    e: "Conforme al artículo 55.1 del Reglamento de los servicios postales, la concesión del sello de excelencia da derecho a usar su distintivo durante:",
    ok: "Tres años desde su concesión.", mal: ["Un año.", "Cinco años.", "Indefinidamente."], d: 2 }),
  r1({ id: "of-po-41", art: "Artículo 55",
    cita: "En ningún caso la concesión del sello comportará compensación económica alguna.",
    clave: "compensación económica",
    e: "Según el artículo 55.3 del Reglamento de los servicios postales, la concesión del sello de excelencia:",
    ok: "En ningún caso comportará compensación económica alguna.", mal: ["Conlleva una subvención anual.", "Da derecho a una reducción de tasas.", "Exime del régimen sancionador."], d: 2 }),
  // ── Tema 2: paquetería ──
  r2({ id: "of-po-42", art: "Artículo 2",
    cita: "c) Paquete postal: todo envío que contenga cualquier objeto, producto o materia, con o sin valor comercial, cuya circulación por la red postal no esté prohibida.",
    clave: "con o sin valor comercial",
    e: "Según el artículo 2.3.c) del Reglamento de los servicios postales, es paquete postal todo envío que contenga cualquier objeto, producto o materia:",
    ok: "Con o sin valor comercial, cuya circulación por la red postal no esté prohibida.", mal: ["Solo con valor comercial superior a 20 euros.", "Que pese más de 2 kilos.", "Que vaya siempre como certificado."], d: 1 }),
  r2({ id: "of-po-43", art: "Artículo 2",
    cita: "Cuando estos envíos contengan además comunicaciones de carácter actual y personal, deberá manifestarse expresamente, en su cubierta, dicha circunstancia.",
    clave: "manifestarse expresamente",
    e: "Si un paquete postal contiene además comunicaciones de carácter actual y personal, según el artículo 2.3.c) del Reglamento de los servicios postales:",
    ok: "Deberá manifestarse expresamente esa circunstancia en su cubierta.", mal: ["Está prohibido enviarlo.", "Debe enviarse en dos envíos separados.", "No es necesario indicarlo."], d: 2 }),
  r2({ id: "of-po-44", art: "Artículo 2",
    cita: "No podrán constituir paquetes postales los lotes o agrupaciones de las cartas o cualquier otra clase de correspondencia actual y personal.",
    clave: "No podrán constituir paquetes postales",
    e: "Conforme al artículo 2.3.c) del Reglamento de los servicios postales, los lotes o agrupaciones de cartas o de otra correspondencia actual y personal:",
    ok: "No podrán constituir paquetes postales.", mal: ["Se consideran paquetes postales si pesan más de 1 kilo.", "Son paquetes postales con tarifa reducida.", "Se tratan como publicidad directa."], d: 2 }),
  r2({ id: "of-po-45", art: "Artículo 33",
    cita: "Se podrá rehusar por el destinatario o persona autorizada los envíos de paquetes postales después de examinarlo interiormente, siempre en el momento de la entrega y en presencia del empleado postal",
    clave: "después de examinarlo interiormente",
    e: "Según el artículo 33.2 del Reglamento de los servicios postales, cuando existan indicios exteriores de que el contenido de un paquete pudiera estar dañado, el destinatario puede rehusarlo:",
    ok: "Después de examinarlo interiormente, en el momento de la entrega y en presencia del empleado postal.", mal: ["En los treinta días siguientes a la entrega.", "Solo antes de abrirlo, sin excepción.", "Únicamente en la oficina de admisión."], d: 3 }),
  r2({ id: "of-po-46", art: "Artículo 24",
    cita: "aquellos cuya circulación no se permita por motivos de seguridad, de salud pública, de utilidad general y de protección de los servicios postales",
    clave: "seguridad, de salud pública",
    e: "Según el artículo 24.1 del Reglamento de los servicios postales, se consideran objetos prohibidos para circular como envíos postales aquellos cuya circulación no se permita por motivos de:",
    ok: "Seguridad, de salud pública, de utilidad general y de protección de los servicios postales.", mal: ["Peso y tamaño, exclusivamente.", "Precio del envío.", "Preferencias comerciales del operador."], d: 2 }),
  r2({ id: "of-po-47", art: "Artículo 24",
    cita: "salvo si se envían con fines terapéuticos y acompañados de autorización oficial",
    clave: "fines terapéuticos",
    e: "Conforme al artículo 24.1.b) del Reglamento de los servicios postales, los medicamentos sujetos a prescripción no pueden incluirse en envíos postales salvo si se envían:",
    ok: "Con fines terapéuticos y acompañados de autorización oficial.", mal: ["Como certificado con acuse de recibo.", "En cantidad inferior a cinco unidades.", "Dentro de un paquete urgente."], d: 3 }),
  r2({ id: "of-po-48", art: "Artículo 36",
    cita: "se invitará al remitente a que lo abra, y si este no lo hiciese se denegará su admisión",
    clave: "se invitará al remitente a que lo abra",
    e: "Cuando se sospeche racionalmente en la oficina de admisión que un envío contiene un objeto prohibido, según el artículo 36.1 del Reglamento de los servicios postales:",
    ok: "Se invitará al remitente a que lo abra y, si no lo hace, se denegará su admisión.", mal: ["El empleado lo abre sin avisar al remitente.", "Se admite y se avisa al destinatario.", "Se destruye inmediatamente."], d: 2 }),
  r2({ id: "of-po-49", art: "Artículo 37",
    cita: "c) Los objetos relacionados con el apartado d), del artículo 24, serán entregados a la Guardia Civil.",
    clave: "Guardia Civil",
    e: "Según el artículo 37.1.c) del Reglamento de los servicios postales, cuando los operadores detectan armas (objetos del artículo 24.d) en un envío, estas serán entregadas a:",
    ok: "La Guardia Civil.", mal: ["El remitente.", "El Ayuntamiento.", "La Comisión Nacional de los Mercados y la Competencia."], d: 3 }),
  r2({ id: "of-po-50", art: "Artículo 35",
    cita: "podrán aplicarse medidas de inspección tales como escáneres u otras técnicas similares",
    clave: "escáneres",
    e: "Para los envíos postales abandonados, el artículo 35.2 del Reglamento de los servicios postales permite aplicar medidas de inspección tales como:",
    ok: "Escáneres u otras técnicas similares, sin menoscabo del secreto de las comunicaciones.", mal: ["La apertura y lectura de las cartas.", "La venta pública inmediata del contenido.", "La entrega del contenido a cualquier vecino."], d: 3 }),
  // ── Tema 10: normativa postal ──
  r10({ id: "of-po-51", art: "Artículo 7",
    cita: "la absoluta prohibición para los operadores postales y para sus empleados de facilitar dato alguno relativo a la existencia del envío postal, a su clase, a sus circunstancias exteriores, a la identidad del remitente y del destinatario o a sus direcciones",
    clave: "absoluta prohibición",
    e: "Según el artículo 7.2 del Reglamento de los servicios postales, el secreto de las comunicaciones postales implica, para los operadores y sus empleados:",
    ok: "La absoluta prohibición de facilitar dato alguno sobre la existencia del envío, su clase, circunstancias exteriores, remitente, destinatario o direcciones.", mal: ["La prohibición de abrir los envíos, pero no de informar sobre ellos.", "La obligación de informar a cualquier vecino que pregunte.", "La posibilidad de facilitar datos a empresas de publicidad."], d: 2 }),
  r10({ id: "of-po-52", art: "Artículo 10",
    cita: "Los usuarios dispondrán de un plazo máximo de seis meses, desde la admisión del envío, para presentar reclamaciones.",
    clave: "seis meses",
    e: "Conforme al artículo 10.1 del Reglamento de los servicios postales, los usuarios disponen, para presentar reclamaciones por envíos nacionales, de un plazo máximo de:",
    ok: "Seis meses desde la admisión del envío.", mal: ["Un mes desde la entrega.", "Un año desde la admisión.", "Quince días desde la admisión."], d: 2 }),
  r10({ id: "of-po-53", art: "Artículo 38",
    cita: "los envíos postales sólo podrán ser detenidos e interceptados por resolución motivada de la autoridad judicial",
    clave: "resolución motivada de la autoridad judicial",
    e: "Según el artículo 38.1 del Reglamento de los servicios postales, salvo los derechos del remitente, los envíos postales solo podrán ser detenidos e interceptados por:",
    ok: "Resolución motivada de la autoridad judicial.", mal: ["Orden del jefe de la oficina postal.", "Decisión de la policía local.", "Solicitud de cualquier interesado."], d: 1 }),
  r10({ id: "of-po-54", art: "Artículo 47",
    cita: "El Registro constará de dos secciones denominadas A y B.",
    clave: "A y B",
    e: "Según el artículo 47.1 del Reglamento de los servicios postales, el Registro General de Empresas Prestadoras de Servicios Postales consta de:",
    ok: "Dos secciones, denominadas A y B.", mal: ["Una sección única.", "Tres secciones, A, B y C.", "Una sección por cada Comunidad Autónoma."], d: 2 }),
  r10({ id: "of-po-55", art: "Artículo 47",
    cita: "En la sección B se inscribirá la información relativa a los operadores que presten servicios postales incluidos en el ámbito del servicio postal universal, habilitados mediante una autorización administrativa singular.",
    clave: "autorización administrativa singular",
    e: "Conforme al artículo 47.2 del Reglamento de los servicios postales, en la sección B del Registro se inscriben los operadores que presten servicios incluidos en el servicio postal universal, habilitados mediante:",
    ok: "Una autorización administrativa singular.", mal: ["Una declaración responsable.", "Una licencia municipal.", "Un contrato con el Ministerio."],
    j: "En la sección A se inscriben los operadores de servicios no incluidos en el servicio postal universal, habilitados mediante declaración responsable.", d: 3 }),
  r10({ id: "of-po-56", art: "Artículo 50",
    cita: "Las inscripciones registrales deberán renovarse anualmente.",
    clave: "anualmente",
    e: "Según el artículo 50.1 del Reglamento de los servicios postales, las inscripciones en el Registro General de Empresas Prestadoras de Servicios Postales deben renovarse:",
    ok: "Anualmente.", mal: ["Cada cinco años.", "Cada dos años.", "Solo cuando cambien sus datos."], d: 2 }),
  l10({ id: "of-po-57", art: "Artículo 7",
    cita: "La obligación de protección de los datos incluirá el deber de secreto de los de carácter personal, la confidencialidad de la información transmitida o almacenada y la protección de la intimidad.",
    clave: "confidencialidad de la información transmitida o almacenada",
    e: "Según el artículo 7.2 de la Ley 43/2010, la obligación de protección de los datos de los operadores postales incluirá el deber de secreto de los datos personales, la protección de la intimidad y:",
    ok: "La confidencialidad de la información transmitida o almacenada.", mal: ["La publicación de los datos de los remitentes.", "La cesión de datos a empresas colaboradoras.", "El registro de las conversaciones de los clientes."], d: 2 }),
  l1({ id: "of-po-58", art: "Artículo 8",
    cita: "Los usuarios tendrán derecho a la prestación de un servicio postal universal de calidad prestado de forma permanente, en todo el territorio nacional y a precios asequibles.",
    clave: "a precios asequibles",
    e: "Según el artículo 8 de la Ley 43/2010, los usuarios tienen derecho a un servicio postal universal de calidad prestado de forma permanente, en todo el territorio nacional y:",
    ok: "A precios asequibles.", mal: ["Gratuito en todo caso.", "Solo en las capitales de provincia.", "Con entrega en 24 horas garantizada."], d: 1 }),
  l10({ id: "of-po-59", art: "Artículo 9",
    cita: "deberán informar a los usuarios, de manera completa, veraz y puntual, de los servicios postales que presten",
    clave: "completa, veraz y puntual",
    e: "Conforme al artículo 9.1 de la Ley 43/2010, todos los operadores postales deben informar a los usuarios de los servicios que presten de manera:",
    ok: "Completa, veraz y puntual.", mal: ["Resumida y voluntaria.", "Solo si lo solicitan por escrito.", "En lengua inglesa obligatoriamente."], d: 2 }),
  l1({ id: "of-po-60", art: "Artículo 13",
    cita: "quien podrá, mediante el pago del precio correspondiente, recuperarlos o modificar su dirección, salvo en los supuestos de imposibilidad material",
    clave: "recuperarlos o modificar su dirección",
    e: "Según el artículo 13 de la Ley 43/2010, mientras el envío no llegue al destinatario, el remitente puede, mediante el pago del precio correspondiente:",
    ok: "Recuperarlos o modificar su dirección, salvo imposibilidad material.", mal: ["Exigir su destrucción gratuita.", "Abrirlos en la oficina de destino.", "Cambiar el destinatario sin coste alguno."], d: 2 }),
  l1({ id: "of-po-61", art: "Artículo 15",
    cita: "Los usuarios tendrán derecho a que, en la cubierta del envío, se identifique el operador postal que se hace cargo del mismo, así como la fecha en que se produce.",
    clave: "se identifique el operador postal",
    e: "Conforme al artículo 15 de la Ley 43/2010, los usuarios tienen derecho a que en la cubierta del envío:",
    ok: "Se identifique el operador postal que se hace cargo de él y la fecha en que se produce.", mal: ["Figure el contenido declarado.", "Conste el precio pagado.", "Aparezca el nombre del cartero."], d: 1 }),
  l5({ id: "of-po-62", art: "Artículo 17",
    cita: "El destinatario podrá solicitar la reexpedición de sus envíos postales mediante el pago de la contraprestación económica que corresponda",
    clave: "reexpedición",
    e: "Según el artículo 17 de la Ley 43/2010, el destinatario puede solicitar, mediante el pago de la contraprestación económica que corresponda:",
    ok: "La reexpedición de sus envíos postales.", mal: ["La apertura de los envíos por el operador.", "La devolución del precio al remitente.", "La entrega en otra provincia sin coste."], d: 2 }),
  l5({ id: "of-po-63", art: "Artículo 17",
    cita: "En todo caso, el operador tendrá derecho a reclamar del remitente el pago de los gastos ocasionados.",
    clave: "reclamar del remitente el pago de los gastos ocasionados",
    e: "En caso de reexpedición o rehúse de un envío, según el artículo 17 de la Ley 43/2010, el operador tiene derecho en todo caso a:",
    ok: "Reclamar del remitente el pago de los gastos ocasionados.", mal: ["Quedarse con el contenido del envío.", "Cobrar al destinatario una sanción.", "Destruir el envío sin aviso."], d: 2 }),
  l10({ id: "of-po-64", art: "Artículo 19",
    cita: "sean plenamente accesibles a dichas personas, lo que incluye, especialmente, la eliminación de barreras arquitectónicas y de comunicación de las oficinas donde se presta el servicio",
    clave: "eliminación de barreras arquitectónicas",
    e: "Para garantizar que los derechos de información, reclamación, denuncia y presentación de escritos sean plenamente accesibles a las personas con discapacidad, el artículo 19 de la Ley 43/2010 incluye especialmente:",
    ok: "La eliminación de barreras arquitectónicas y de comunicación de las oficinas.", mal: ["La apertura de oficinas solo para personas con discapacidad.", "La gratuidad de todos los envíos.", "La entrega obligatoria a domicilio en 24 horas."], d: 2 }),
  l1({ id: "of-po-65", art: "Artículo 22",
    cita: "se regirán por los principios de equidad, no discriminación, continuidad, buena fe, y adaptación a las necesidades de los usuarios",
    clave: "equidad, no discriminación, continuidad, buena fe",
    e: "Según el artículo 22.1 de la Ley 43/2010, la prestación del servicio postal universal y las relaciones de los usuarios con el operador designado se rigen por los principios de:",
    ok: "Equidad, no discriminación, continuidad, buena fe y adaptación a las necesidades de los usuarios.", mal: ["Rentabilidad, exclusividad y discrecionalidad.", "Libre competencia y precio libre.", "Jerarquía, centralización y secreto."], d: 2 }),
  l1({ id: "of-po-66", art: "Artículo 22",
    cita: "a) Equidad: ofrecer a los usuarios que estén en condiciones similares el mismo tratamiento y prestaciones idénticas.",
    clave: "el mismo tratamiento y prestaciones idénticas",
    e: "Conforme al artículo 22.1.a) de la Ley 43/2010, el principio de equidad en el servicio postal universal consiste en:",
    ok: "Ofrecer a los usuarios en condiciones similares el mismo tratamiento y prestaciones idénticas.", mal: ["Cobrar el mismo precio por cualquier envío.", "No interrumpir el servicio.", "Adaptar el servicio a cada usuario según su gasto."], d: 2 }),
  l10({ id: "of-po-67", art: "Artículo 26",
    cita: "El operador designado deberá llevar una contabilidad analítica, que permita conocer el coste de la prestación de los diferentes servicios.",
    clave: "contabilidad analítica",
    e: "Según el artículo 26.1 de la Ley 43/2010, el operador designado para el servicio postal universal deberá llevar:",
    ok: "Una contabilidad analítica que permita conocer el coste de los diferentes servicios.", mal: ["Únicamente la contabilidad de caja.", "Una contabilidad pública presupuestaria.", "Ninguna contabilidad separada."], d: 2 }),
  l1({ id: "of-po-68", art: "Artículo 35",
    cita: "deberá respetar los principios de transparencia y no discriminación, tanto en lo que se refiere a los precios como a las condiciones asociadas",
    clave: "transparencia y no discriminación",
    e: "Cuando el operador designado aplica descuentos a los remitentes de envíos masivos, el artículo 35.1 de la Ley 43/2010 le obliga a respetar los principios de:",
    ok: "Transparencia y no discriminación, en precios y condiciones asociadas.", mal: ["Confidencialidad y exclusividad.", "Libre fijación sin publicidad.", "Preferencia por las grandes empresas."], d: 2 }),
  l2({ id: "of-po-69", art: "Artículo 36",
    cita: "podrá acordar con sus clientes cualesquiera otros sistemas de pago, tales como el pago diferido, el franqueo en destino y el prepago",
    clave: "el pago diferido, el franqueo en destino y el prepago",
    e: "Además de admitir todos los envíos con los medios de franqueo legales, según el artículo 36 de la Ley 43/2010 el operador designado puede acordar con sus clientes otros sistemas de pago como:",
    ok: "El pago diferido, el franqueo en destino y el prepago.", mal: ["El pago en especie con productos.", "El trueque de servicios.", "El pago exclusivo en efectivo."], d: 2 }),
  l10({ id: "of-po-70", art: "Artículo 40",
    cita: "deberán presentar previamente a la Comisión Nacional del Sector Postal una declaración responsable",
    clave: "declaración responsable",
    e: "Según el artículo 40.1 de la Ley 43/2010, quienes pretendan prestar servicios postales no incluidos en el ámbito del servicio postal universal deben presentar previamente:",
    ok: "Una declaración responsable.", mal: ["Una autorización administrativa singular.", "Un aval bancario de un millón de euros.", "Una concesión del Ministerio."],
    j: "Para los servicios incluidos en el ámbito del servicio postal universal se exige, en cambio, una autorización administrativa singular (artículo 42).", d: 2 }),
  l10({ id: "of-po-71", art: "Artículo 51",
    cita: "El Consejo Superior Postal es el máximo órgano de participación de las Administraciones Públicas, los usuarios, los prestadores de servicios postales",
    clave: "máximo órgano de participación",
    e: "Conforme al artículo 51.1 de la Ley 43/2010, el Consejo Superior Postal es:",
    ok: "El máximo órgano de participación de las Administraciones, usuarios, prestadores, sindicatos y asociaciones filatélicas en materia postal.", mal: ["El órgano sancionador del sector postal.", "El consejo de administración de Correos.", "Un tribunal arbitral de consumo."], d: 2 }),
];
