// Correos (continuación): más preguntas del Reglamento de los servicios
// postales (RD 437/2024) y de la Ley 43/2010 (artículos no preguntados en la
// base de datos). Ver postal.ts.
import type { Destino, NormaOficial, PreguntaOficial } from "./tipos";

const T = (tema: number): Destino[] => [["correos", tema]];
const f = (norma: NormaOficial, tema: number) => (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma, destinos: T(tema), ...x });
const r1 = f("RPOSTAL", 1);
const r2 = f("RPOSTAL", 2);
const r5 = f("RPOSTAL", 5);
const r10 = f("RPOSTAL", 10);
const l1 = f("LPOSTAL", 1);
const l10 = f("LPOSTAL", 10);

export const POSTAL2: PreguntaOficial[] = [
  r1({ id: "of-pq-01", art: "Artículo 4",
    cita: "se realizará en régimen de libre competencia de acuerdo con lo establecido en el título IV de dicha ley y en el presente reglamento",
    clave: "libre competencia",
    e: "Según el artículo 4.1 del Reglamento de los servicios postales, la prestación de los servicios postales se realiza en régimen de:",
    ok: "Libre competencia.", mal: ["Monopolio del operador designado.", "Concesión administrativa exclusiva.", "Gestión directa por el Ministerio."], d: 1 }),
  r1({ id: "of-pq-02", art: "Artículo 3",
    cita: "unas obligaciones que se regulan en el Plan de prestación del servicio postal universal",
    clave: "Plan de prestación del servicio postal universal",
    e: "Conforme al artículo 3.2 del Reglamento de los servicios postales, las obligaciones específicas de servicio postal universal encomendadas al operador designado se regulan en:",
    ok: "El Plan de prestación del servicio postal universal.", mal: ["El propio Reglamento de los servicios postales.", "El convenio colectivo de Correos.", "Una orden del Ministerio de Hacienda."], d: 2 }),
  r10({ id: "of-pq-03", art: "Artículo 5",
    cita: "deberán presentar a la Subdirección General de Régimen Postal del Ministerio de Transportes y Movilidad Sostenible con carácter previo al inicio de la actividad, la declaración responsable",
    clave: "con carácter previo al inicio de la actividad",
    e: "Según el artículo 5.1 del Reglamento de los servicios postales, quienes quieran prestar servicios postales no incluidos en el servicio postal universal deben presentar la declaración responsable:",
    ok: "Con carácter previo al inicio de la actividad, ante la Subdirección General de Régimen Postal.", mal: ["En el mes siguiente al inicio de la actividad.", "Solo si facturan más de un millón de euros.", "Ante el Ayuntamiento de su domicilio."], d: 2 }),
  r10({ id: "of-pq-04", art: "Artículo 6",
    cita: "deberán solicitar la correspondiente autorización administrativa singular a la Secretaría General Técnica del Ministerio de Transportes y Movilidad Sostenible",
    clave: "Secretaría General Técnica",
    e: "Conforme al artículo 6.1 del Reglamento de los servicios postales, los operadores distintos del designado que quieran prestar servicios incluidos en el servicio postal universal deben solicitar la autorización administrativa singular a:",
    ok: "La Secretaría General Técnica del Ministerio de Transportes y Movilidad Sostenible.", mal: ["La Comisión Nacional de los Mercados y la Competencia.", "El Consejo Superior Postal.", "La Delegación del Gobierno."], d: 3 }),
  r10({ id: "of-pq-05", art: "Artículo 11",
    cita: "Los operadores postales están sujetos a lo dispuesto en el Texto Refundido de la Ley General para la Defensa de los Consumidores y Usuarios",
    clave: "Defensa de los Consumidores y Usuarios",
    e: "Según el artículo 11 del Reglamento de los servicios postales, los operadores postales están sujetos, entre otras normas, al Texto Refundido de la Ley General para:",
    ok: "La Defensa de los Consumidores y Usuarios.", mal: ["La Seguridad Social.", "El Patrimonio de las Administraciones Públicas.", "La Contratación del Sector Público."], d: 1 }),
  r10({ id: "of-pq-06", art: "Artículo 28",
    cita: "se presentarán de forma individualizada en sobre abierto, con objeto de que en la cabecera de la primera hoja del documento que se quiera enviar, se haga constar, con claridad, el nombre de la oficina y la fecha, el lugar, la hora y minuto de su admisión",
    clave: "en sobre abierto",
    e: "Según el artículo 28.1 del Reglamento de los servicios postales, los escritos dirigidos a las Administraciones a través del operador del servicio postal universal se presentarán de forma individualizada:",
    ok: "En sobre abierto, para hacer constar en la primera hoja la oficina, fecha, lugar, hora y minuto de admisión.", mal: ["En sobre cerrado y lacrado.", "Sin sobre, plegados.", "En paquete certificado con valor declarado."], d: 2 }),
  r10({ id: "of-pq-07", art: "Artículo 28",
    cita: "el nombre de la oficina y la fecha, el lugar, la hora y minuto de su admisión",
    clave: "la hora y minuto de su admisión",
    e: "Conforme al artículo 28.1 del Reglamento de los servicios postales, al admitir un escrito dirigido a una Administración se hará constar en la cabecera de su primera hoja, además del nombre de la oficina, la fecha y el lugar:",
    ok: "La hora y minuto de su admisión.", mal: ["El nombre del empleado y su DNI.", "El precio del envío.", "El código postal del destinatario, exclusivamente."], d: 2 }),
  r10({ id: "of-pq-08", art: "Artículo 29",
    cita: "de acuerdo con lo previsto en el artículo 16.4.e) de la Ley 39/2015",
    clave: "artículo 16.4.e) de la Ley 39/2015",
    e: "Según el artículo 29 del Reglamento de los servicios postales, los operadores distintos del designado pueden admitir escritos dirigidos a las Administraciones con las condiciones que establezca la normativa específica, de acuerdo con:",
    ok: "El artículo 16.4.e) de la Ley 39/2015.", mal: ["El artículo 18.3 de la Constitución.", "El artículo 579 de la Ley de Enjuiciamiento Criminal.", "El artículo 1 del Código Civil."], d: 3 }),
  r10({ id: "of-pq-09", art: "Artículo 30",
    cita: "deberán adaptarse a las exigencias de la Ley 39/2015, de 1 de octubre, del Procedimiento Administrativo Común de las Administraciones Públicas",
    clave: "Ley 39/2015",
    e: "Conforme al artículo 30 del Reglamento de los servicios postales, los requisitos de plazo y forma de la entrega de notificaciones administrativas deberán adaptarse a:",
    ok: "La Ley 39/2015 y, en las judiciales, a la Ley Orgánica del Poder Judicial y la normativa procesal.", mal: ["Las condiciones comerciales del operador.", "El Código de Comercio.", "Los usos locales de cada municipio."], d: 2 }),
  r5({ id: "of-pq-10", art: "Artículo 31",
    cita: "1.º Que el número de habitantes censados sea igual o inferior a 25 por hectárea, considerando a estos efectos la superficie urbana.",
    clave: "25 por hectárea",
    e: "En entornos de gran desarrollo de construcción y mínima densidad de población, una de las condiciones del artículo 31.1.b) del Reglamento de los servicios postales para repartir mediante casilleros concentrados es que los habitantes censados sean iguales o inferiores a:",
    ok: "25 por hectárea.", mal: ["50 por hectárea.", "100 por hectárea.", "10 por hectárea."], d: 3 }),
  r5({ id: "of-pq-11", art: "Artículo 31",
    cita: "3.º Que el volumen de envíos ordinarios en el entorno no exceda de 5 envíos semanales, de media por domicilio y en cómputo anual.",
    clave: "5 envíos semanales",
    e: "Según el artículo 31.1.b) del Reglamento de los servicios postales, otra de las condiciones para el reparto por casilleros concentrados en entornos de baja densidad es que el volumen de envíos ordinarios no exceda, de media por domicilio, de:",
    ok: "5 envíos semanales, en cómputo anual.", mal: ["10 envíos diarios.", "20 envíos mensuales.", "1 envío semanal."], d: 3 }),
  r5({ id: "of-pq-12", art: "Artículo 31",
    cita: "la entrega de los envíos postales ordinarios, siempre que no incluyan los servicios accesorios de certificado y valor declarado, se realizarán en instalaciones apropiadas",
    clave: "siempre que no incluyan los servicios accesorios de certificado y valor declarado",
    e: "En los entornos especiales del artículo 31.1 del Reglamento de los servicios postales, la entrega mediante casilleros concentrados o buzones no domiciliarios se aplica a los envíos ordinarios:",
    ok: "Siempre que no incluyan los servicios accesorios de certificado y valor declarado.", mal: ["Incluidos los certificados y con valor declarado.", "Solo a los paquetes de más de 2 kilos.", "Solo a las notificaciones judiciales."], d: 2 }),
  r5({ id: "of-pq-13", art: "Artículo 32",
    cita: "se entregarán, en las condiciones normativamente establecidas, al administrador concursal o a las personas designadas al efecto por la autoridad competente",
    clave: "administrador concursal",
    e: "Según el artículo 32.b) del Reglamento de los servicios postales, los envíos dirigidos a personas en situación de concurso de acreedores se entregarán:",
    ok: "Al administrador concursal o a las personas designadas por la autoridad competente.", mal: ["Al acreedor principal.", "Siempre al propio deudor.", "Al Juzgado de guardia."], d: 2 }),
  r5({ id: "of-pq-14", art: "Artículo 32",
    cita: "d) Los envíos postales ordinarios dirigidos a clientes o residentes de hoteles, hospitales, pensiones, colegios y otros establecimientos análogos podrán entregarse, salvo que medie oposición expresa de los destinatarios de las mismas, a la persona autorizada en ellos para su recepción.",
    clave: "persona autorizada",
    e: "Conforme al artículo 32.d) del Reglamento de los servicios postales, los envíos ordinarios dirigidos a residentes de hoteles, hospitales o colegios podrán entregarse, salvo oposición expresa del destinatario:",
    ok: "A la persona autorizada en el establecimiento para su recepción.", mal: ["A cualquier otro residente.", "Solo en mano al destinatario.", "En la oficina postal más cercana, obligatoriamente."], d: 2 }),
  r5({ id: "of-pq-15", art: "Artículo 32",
    cita: "e) Los envíos postales ordinarios no certificados podrán entregarse a los porteros, encargados o gerentes de los respectivos complejos o de los edificios siempre que no se manifieste oposición expresa de los destinatarios de los mismos.",
    clave: "porteros, encargados o gerentes",
    e: "Según el artículo 32.e) del Reglamento de los servicios postales, los envíos ordinarios no certificados podrán entregarse, si no hay oposición expresa del destinatario, a:",
    ok: "Los porteros, encargados o gerentes de los complejos o edificios.", mal: ["Cualquier transeúnte que se ofrezca.", "Los vecinos del portal contiguo.", "El repartidor de otra empresa."], d: 1 }),
  r2({ id: "of-pq-16", art: "Artículo 36",
    cita: "Análogo procedimiento se seguirá, en cuanto sea posible, con los objetos depositados en los buzones.",
    clave: "depositados en los buzones",
    e: "Según el artículo 36.1 del Reglamento de los servicios postales, el procedimiento de invitar al remitente a abrir un envío sospechoso se seguirá también, en cuanto sea posible, con los objetos:",
    ok: "Depositados en los buzones.", mal: ["Ya entregados al destinatario.", "Enviados desde el extranjero, exclusivamente.", "Que viajen como certificado."], d: 3 }),
  r2({ id: "of-pq-17", art: "Artículo 37",
    cita: "b) Los envíos a que se refiere el apartado f) del artículo 24, cuando contengan animales vivos, se comunicarán a la autoridad que corresponda.",
    clave: "animales vivos",
    e: "Según el artículo 37.1.b) del Reglamento de los servicios postales, ¿qué contenido de un envío prohibido debe comunicarse a la autoridad que corresponda?",
    ok: "Animales vivos.", mal: ["Libros usados.", "Fotografías personales.", "Ropa nueva."], d: 2 }),
  r2({ id: "of-pq-18", art: "Artículo 37",
    cita: "En ningún caso se devolverán estos objetos prohibidos a la oficina de origen.",
    clave: "En ningún caso se devolverán",
    e: "Cuando se detectan objetos cuya importación está prohibida en el país de destino, según el artículo 37.1.f) del Reglamento de los servicios postales se retendrá el envío, se comunicará a la autoridad aduanera y:",
    ok: "En ningún caso se devolverán estos objetos a la oficina de origen.", mal: ["Se devolverán siempre al remitente.", "Se entregarán igualmente al destinatario.", "Se subastarán en la oficina de destino."], d: 3 }),
  r2({ id: "of-pq-19", art: "Artículo 37",
    cita: "serán devueltos a la oficina de origen, que dará seguidamente aviso al remitente para que los retire en los plazos reglamentarios",
    clave: "devueltos a la oficina de origen",
    e: "Según el artículo 37.3 del Reglamento de los servicios postales, los objetos de circulación prohibida sin un trato específico previsto:",
    ok: "Serán devueltos a la oficina de origen, que avisará al remitente para que los retire.", mal: ["Serán destruidos de inmediato.", "Se entregarán al destinatario con un aviso.", "Pasarán a ser propiedad del operador."], d: 2 }),
  r2({ id: "of-pq-20", art: "Artículo 38",
    cita: "limitándose a su reconocimiento externo, tanto de los mismos como de la documentación que los acompañe",
    clave: "reconocimiento externo",
    e: "Conforme al artículo 38.2 del Reglamento de los servicios postales, el alcance de la intervención judicial de los envíos postales no afectará al secreto de las comunicaciones y se limitará a:",
    ok: "Su reconocimiento externo y el de la documentación que los acompañe.", mal: ["La lectura de su contenido íntegro.", "La copia de los documentos internos.", "La destrucción del envío."], d: 2 }),
  r2({ id: "of-pq-21", art: "Artículo 38",
    cita: "Los operadores postales someterán a la fiscalización de las autoridades aduaneras los envíos de importación y exportación prohibidos",
    clave: "autoridades aduaneras",
    e: "Según el artículo 38.4 del Reglamento de los servicios postales, los envíos de importación y exportación prohibidos, o sujetos a derechos y formalidades de entrada o salida, se someterán a la fiscalización de:",
    ok: "Las autoridades aduaneras.", mal: ["La Policía Local.", "El Defensor del Pueblo.", "La Agencia Española de Protección de Datos."], d: 1 }),
  r10({ id: "of-pq-22", art: "Artículo 40",
    cita: "Los funcionarios de la inspección postal documentarán sus actuaciones mediante comunicaciones, requerimientos, informes, diligencias y actas.",
    clave: "comunicaciones, requerimientos, informes, diligencias y actas",
    e: "Conforme al artículo 40.1 del Reglamento de los servicios postales, los funcionarios de la inspección postal documentan sus actuaciones mediante:",
    ok: "Comunicaciones, requerimientos, informes, diligencias y actas.", mal: ["Sentencias y autos.", "Contratos y facturas.", "Notas de prensa."], d: 2 }),
  r10({ id: "of-pq-23", art: "Artículo 40",
    cita: "tienen naturaleza de documentos públicos y tendrán valor probatorio, salvo que se acredite lo contrario",
    clave: "documentos públicos",
    e: "Según el artículo 40.2 del Reglamento de los servicios postales, los informes, diligencias y actas de la inspección postal tienen:",
    ok: "Naturaleza de documentos públicos y valor probatorio, salvo prueba en contrario.", mal: ["Valor de simples opiniones.", "Carácter secreto e inaccesible para el interesado.", "Efectos solo si los firma un juez."], d: 2 }),
  r10({ id: "of-pq-24", art: "Artículo 42",
    cita: "En particular, constará en una diligencia el consentimiento del interesado para el acceso y permanencia del personal funcionario inspector en su domicilio constitucionalmente protegido.",
    clave: "domicilio constitucionalmente protegido",
    e: "Según el artículo 42.1 del Reglamento de los servicios postales, constará en una diligencia el consentimiento del interesado para el acceso y permanencia del inspector en:",
    ok: "Su domicilio constitucionalmente protegido.", mal: ["La vía pública.", "Las oficinas públicas de la Administración.", "Los buzones de su edificio."], d: 3 }),
  r10({ id: "of-pq-25", art: "Artículo 46",
    cita: "Dicho Registro tiene ámbito nacional, naturaleza administrativa y carácter público.",
    clave: "carácter público",
    e: "Según el artículo 46.1 del Reglamento de los servicios postales, el Registro General de Empresas Prestadoras de Servicios Postales tiene ámbito nacional, naturaleza administrativa y:",
    ok: "Carácter público.", mal: ["Carácter reservado.", "Carácter privado.", "Carácter secreto."], d: 1 }),
  r10({ id: "of-pq-26", art: "Artículo 48",
    cita: "La primera inscripción se practicará de oficio una vez otorgada la autorización administrativa singular o recibida la declaración responsable",
    clave: "de oficio",
    e: "Conforme al artículo 48.1 del Reglamento de los servicios postales, la primera inscripción de un operador en el Registro General se practica:",
    ok: "De oficio, una vez otorgada la autorización o recibida la declaración responsable.", mal: ["A instancia del operador, con un año de plazo.", "Por un notario.", "Solo tras una inspección favorable."], d: 2 }),
  r10({ id: "of-pq-27", art: "Artículo 49",
    cita: "en el plazo máximo de un mes desde el momento en que se produzca",
    clave: "un mes",
    e: "Según el artículo 49.1 del Reglamento de los servicios postales, tras la primera inscripción, los operadores deben comunicar cualquier modificación de sus datos en el plazo máximo de:",
    ok: "Un mes desde que se produzca.", mal: ["Tres meses.", "Quince días.", "Un año."], d: 2 }),
  r10({ id: "of-pq-28", art: "Artículo 52",
    cita: "a) A petición propia, mediante solicitud de baja, por cese de la actividad.",
    clave: "cese de la actividad",
    e: "¿Cuál de los siguientes es un supuesto de baja de un operador en el Registro General según el artículo 52.1 del Reglamento de los servicios postales?",
    ok: "A petición propia, por cese de la actividad.", mal: ["El cambio de domicilio social.", "La contratación de nuevos empleados.", "La apertura de una nueva oficina."], d: 1 }),
  r1({ id: "of-pq-29", art: "Artículo 54",
    cita: "El sello de excelencia será concedido por orden del Ministerio de Transportes y Movilidad Sostenible, a propuesta de un Jurado",
    clave: "a propuesta de un Jurado",
    e: "Conforme al artículo 54.1 del Reglamento de los servicios postales, el sello de excelencia se concede por orden del Ministerio de Transportes y Movilidad Sostenible:",
    ok: "A propuesta de un Jurado nombrado en las bases de la convocatoria.", mal: ["A propuesta de los usuarios mediante votación.", "De forma automática a todos los operadores.", "A propuesta del propio operador interesado."], d: 2 }),
  r1({ id: "of-pq-30", art: "Artículo 56",
    cita: "El listado de operadores con la distinción figurará también en el portal internet del Departamento.",
    clave: "portal",
    e: "Según el artículo 56 del Reglamento de los servicios postales, además del registro de sellos de excelencia, el listado de operadores con esa distinción figurará en:",
    ok: "El portal de internet del Ministerio (del Departamento).", mal: ["El Boletín Oficial del Registro Mercantil.", "Las oficinas de cada operador, exclusivamente.", "El tablón del Consejo Superior Postal."], d: 2 }),
  l1({ id: "of-pq-31", art: "Artículo 37",
    cita: "a) Servicios incluidos en el ámbito del servicio postal universal, de conformidad con lo establecido en el artículo 21 de la presente ley.",
    clave: "incluidos en el ámbito del servicio postal universal",
    e: "Según el artículo 37.2 de la Ley 43/2010, en función de las condiciones exigibles en su prestación, los servicios postales se clasifican en servicios no incluidos y servicios:",
    ok: "Incluidos en el ámbito del servicio postal universal.", mal: ["Prestados por Correos en exclusiva.", "Internacionales y nacionales.", "Urgentes y ordinarios."], d: 1 }),
  l1({ id: "of-pq-32", art: "Artículo 38",
    cita: "incluso para aquellos operadores que actúen en nombre, representación o por cuenta de otro u otros operadores postales",
    clave: "en nombre, representación o por cuenta",
    e: "Conforme al artículo 38.1 de la Ley 43/2010, las condiciones para prestar servicios postales se exigen también a los operadores que actúen:",
    ok: "En nombre, representación o por cuenta de otros operadores postales.", mal: ["Solo para envíos internacionales.", "Exclusivamente en régimen de autoprestación.", "Únicamente como empresas de transporte."], d: 2 }),
  l10({ id: "of-pq-33", art: "Artículo 53",
    cita: "serán considerados agentes de la autoridad en sus actos de servicio o con motivo de los mismos",
    clave: "agentes de la autoridad",
    e: "Según el artículo 53.1 de la Ley 43/2010, los funcionarios que desempeñan funciones de inspección postal serán considerados, en sus actos de servicio:",
    ok: "Agentes de la autoridad.", mal: ["Simples asesores técnicos.", "Empleados del operador inspeccionado.", "Mediadores privados."], d: 1 }),
  l10({ id: "of-pq-34", art: "Artículo 53",
    cita: "Los sujetos sometidos a investigación deberán atender a la inspección y le prestarán la debida colaboración en el desarrollo de sus funciones.",
    clave: "debida colaboración",
    e: "Conforme al artículo 53.2 de la Ley 43/2010, los sujetos sometidos a investigación por la inspección postal:",
    ok: "Deberán atenderla y prestarle la debida colaboración.", mal: ["Pueden negarse a recibir a los inspectores.", "Solo colaboran si hay orden judicial.", "Pueden exigir el pago de sus gastos."], d: 1 }),
  l10({ id: "of-pq-35", art: "Artículo 57",
    cita: "Serán responsables solidarios de las infracciones postales cometidas por los trabajadores, en el ámbito de actuación del poder de dirección y mando empresarial, los prestadores de los servicios postales de los que dependan.",
    clave: "responsables solidarios",
    e: "Según el artículo 57.1 de la Ley 43/2010, de las infracciones postales cometidas por los trabajadores en el ámbito del poder de dirección empresarial, los prestadores de servicios de los que dependan son:",
    ok: "Responsables solidarios.", mal: ["Ajenos a toda responsabilidad.", "Responsables solo si hubo dolo del trabajador.", "Responsables subsidiarios tras diez años."], d: 2 }),
  l10({ id: "of-pq-36", art: "Artículo 58",
    cita: "Las infracciones de las normas reguladoras de los servicios postales se clasifican en muy graves, graves y leves.",
    clave: "muy graves, graves y leves",
    e: "Conforme al artículo 58 de la Ley 43/2010, las infracciones de las normas reguladoras de los servicios postales se clasifican en:",
    ok: "Muy graves, graves y leves.", mal: ["Graves y leves.", "Penales y administrativas.", "Muy graves y graves."], d: 1 }),
  l10({ id: "of-pq-37", art: "Artículo 63",
    cita: "e) La reiteración en la comisión de infracciones en un periodo superior a un año e inferior a cinco.",
    clave: "reiteración",
    e: "¿Cuál de las siguientes circunstancias se tiene en cuenta para graduar las sanciones según el artículo 63 de la Ley 43/2010?",
    ok: "La reiteración en la comisión de infracciones en un periodo superior a un año e inferior a cinco.", mal: ["La nacionalidad del infractor.", "El número de oficinas del operador.", "La edad de los trabajadores."], d: 2 }),
  l10({ id: "of-pq-38", art: "Artículo 63",
    cita: "b) La cuantía del beneficio ilícitamente obtenido.",
    clave: "beneficio ilícitamente obtenido",
    e: "Además del daño causado y su repercusión, el artículo 63 de la Ley 43/2010 manda tener en cuenta para graduar la sanción:",
    ok: "La cuantía del beneficio ilícitamente obtenido.", mal: ["El capital social del operador.", "El número de clientes satisfechos.", "La antigüedad de la empresa."], d: 2 }),
  l10({ id: "of-pq-39", art: "Artículo 64",
    cita: "La cuantía de las sanciones pecuniarias impuestas se reducirá en un 25 por ciento cuando el infractor preste su conformidad a la propuesta de resolución.",
    clave: "25 por ciento",
    e: "Según el artículo 64.1 de la Ley 43/2010, la cuantía de las sanciones pecuniarias se reducirá cuando el infractor preste su conformidad a la propuesta de resolución en un:",
    ok: "25 por ciento.", mal: ["50 por ciento.", "10 por ciento.", "40 por ciento."], d: 2 }),
  l10({ id: "of-pq-40", art: "Artículo 66",
    cita: "La multa coercitiva se impondrá con periodicidad mínima mensual y no superará el 25 por ciento de la sanción máxima fijada para la infracción cometida.",
    clave: "periodicidad mínima mensual",
    e: "Conforme al artículo 66 de la Ley 43/2010, la multa coercitiva en materia postal se impondrá:",
    ok: "Con periodicidad mínima mensual, sin superar el 25 por ciento de la sanción máxima.", mal: ["Una sola vez, por el doble de la sanción.", "Cada día, sin límite de cuantía.", "Solo al final del procedimiento."], d: 3 }),
  l10({ id: "of-pq-41", art: "Artículo 67",
    cita: "Las medidas de carácter provisional podrán consistir, entre otras, en la detención de los envíos postales, en la clausura de las instalaciones en que se vengan ejerciendo las actividades, o en el precintado de los medios utilizados.",
    clave: "precintado de los medios utilizados",
    e: "Según el artículo 67.2 de la Ley 43/2010, las medidas provisionales durante la instrucción del procedimiento sancionador postal pueden consistir, entre otras, en:",
    ok: "La detención de los envíos, la clausura de las instalaciones o el precintado de los medios utilizados.", mal: ["La detención de los trabajadores.", "La disolución de la sociedad.", "La retirada del DNI al administrador."], d: 2 }),
  l10({ id: "of-pq-42", art: "Artículo 68",
    cita: "La responsabilidad derivada de las infracciones postales se extinguirá por fallecimiento del sujeto infractor y por el transcurso del plazo de prescripción",
    clave: "fallecimiento del sujeto infractor",
    e: "Conforme al artículo 68.1 de la Ley 43/2010, la responsabilidad derivada de las infracciones postales se extingue por:",
    ok: "El fallecimiento del sujeto infractor y el transcurso del plazo de prescripción.", mal: ["El pago de una tasa de cancelación.", "El cambio de nombre comercial del operador.", "La petición de perdón al usuario."], d: 2 }),
];
