// Correos tema 11, prevención de riesgos laborales: Ley 31/1995
// (BOE-A-1995-24292).
import type { Destino, PreguntaOficial } from "./tipos";

const T11: Destino[] = [["correos", 11]];
const pr = (x: Omit<PreguntaOficial, "norma" | "destinos">): PreguntaOficial => ({ norma: "LPRL", destinos: T11, ...x });

export const PRL: PreguntaOficial[] = [
  pr({ id: "of-pr-01", art: "Artículo 2",
    cita: "La presente Ley tiene por objeto promover la seguridad y la salud de los trabajadores mediante la aplicación de medidas y el desarrollo de las actividades necesarias para la prevención de riesgos derivados del trabajo.",
    clave: "promover la seguridad y la salud de los trabajadores",
    e: "Según el artículo 2.1 de la Ley 31/1995, de Prevención de Riesgos Laborales, su objeto es:",
    ok: "Promover la seguridad y la salud de los trabajadores mediante medidas y actividades de prevención.", mal: ["Regular los salarios mínimos.", "Fijar las vacaciones de los trabajadores.", "Sancionar a los trabajadores que tengan accidentes."], d: 1 }),
  pr({ id: "of-pr-02", art: "Artículo 3",
    cita: "como en el de las relaciones de carácter administrativo o estatutario del personal al servicio de las Administraciones Públicas",
    clave: "carácter administrativo o estatutario",
    e: "Según el artículo 3.1 de la Ley 31/1995, la ley se aplica en el ámbito de las relaciones laborales y también en el de las relaciones:",
    ok: "De carácter administrativo o estatutario del personal al servicio de las Administraciones Públicas.", mal: ["Mercantiles entre empresas, exclusivamente.", "Familiares en el servicio doméstico, en todo caso.", "De voluntariado sin relación de servicio."], d: 2 }),
  pr({ id: "of-pr-03", art: "Artículo 4",
    cita: "Se entenderá por «prevención» el conjunto de actividades o medidas adoptadas o previstas en todas las fases de actividad de la empresa con el fin de evitar o disminuir los riesgos derivados del trabajo.",
    clave: "en todas las fases de actividad de la empresa",
    e: "Según el artículo 4.1.º de la Ley 31/1995, se entiende por prevención el conjunto de actividades o medidas adoptadas o previstas:",
    ok: "En todas las fases de actividad de la empresa, para evitar o disminuir los riesgos derivados del trabajo.", mal: ["Solo después de producirse un accidente.", "Únicamente en la fase de contratación.", "Solo en las empresas de más de 50 trabajadores."], d: 1 }),
  pr({ id: "of-pr-04", art: "Artículo 4",
    cita: "Se entenderá como «riesgo laboral» la posibilidad de que un trabajador sufra un determinado daño derivado del trabajo.",
    clave: "la posibilidad de que un trabajador sufra un determinado daño",
    e: "Conforme al artículo 4.2.º de la Ley 31/1995, el riesgo laboral es:",
    ok: "La posibilidad de que un trabajador sufra un determinado daño derivado del trabajo.", mal: ["El daño ya sufrido por el trabajador.", "La sanción por incumplir las normas de seguridad.", "El coste económico de un accidente."], d: 1 }),
  pr({ id: "of-pr-05", art: "Artículo 4",
    cita: "se valorarán conjuntamente la probabilidad de que se produzca el daño y la severidad del mismo",
    clave: "la probabilidad de que se produzca el daño y la severidad",
    e: "Para calificar un riesgo desde el punto de vista de su gravedad, el artículo 4.2.º de la Ley 31/1995 manda valorar conjuntamente:",
    ok: "La probabilidad de que se produzca el daño y la severidad del mismo.", mal: ["La edad del trabajador y su antigüedad.", "El tamaño de la empresa y su facturación.", "El horario y el salario del trabajador."], d: 2 }),
  pr({ id: "of-pr-06", art: "Artículo 4",
    cita: "Se considerarán como «daños derivados del trabajo» las enfermedades, patologías o lesiones sufridas con motivo u ocasión del trabajo.",
    clave: "con motivo u ocasión del trabajo",
    e: "Según el artículo 4.3.º de la Ley 31/1995, son daños derivados del trabajo las enfermedades, patologías o lesiones sufridas:",
    ok: "Con motivo u ocasión del trabajo.", mal: ["En el tiempo libre del trabajador.", "Solo por accidente de tráfico.", "Exclusivamente dentro del centro de trabajo."], d: 1 }),
  pr({ id: "of-pr-07", art: "Artículo 4",
    cita: "aquel que resulte probable racionalmente que se materialice en un futuro inmediato y pueda suponer un daño grave para la salud de los trabajadores",
    clave: "futuro inmediato",
    e: "Conforme al artículo 4.4.º de la Ley 31/1995, el riesgo laboral grave e inminente es aquel que resulte probable racionalmente que se materialice en un:",
    ok: "Futuro inmediato y pueda suponer un daño grave para la salud de los trabajadores.", mal: ["Plazo de un año.", "Plazo indeterminado, aunque el daño sea leve.", "Momento posterior a la jubilación del trabajador."], d: 2 }),
  pr({ id: "of-pr-08", art: "Artículo 4",
    cita: "Se entenderá como «equipo de trabajo» cualquier máquina, aparato, instrumento o instalación utilizada en el trabajo.",
    clave: "cualquier máquina, aparato, instrumento o instalación",
    e: "Según el artículo 4.6.º de la Ley 31/1995, el equipo de trabajo es:",
    ok: "Cualquier máquina, aparato, instrumento o instalación utilizada en el trabajo.", mal: ["El conjunto de trabajadores de una sección.", "La ropa de calle del trabajador.", "Solo los vehículos de la empresa."], d: 1 }),
  pr({ id: "of-pr-09", art: "Artículo 4",
    cita: "cualquier equipo destinado a ser llevado o sujetado por el trabajador para que le proteja de uno o varios riesgos",
    clave: "llevado o sujetado por el trabajador",
    e: "Conforme al artículo 4.8.º de la Ley 31/1995, el equipo de protección individual es cualquier equipo destinado a ser:",
    ok: "Llevado o sujetado por el trabajador para protegerle de uno o varios riesgos.", mal: ["Instalado en el techo del local.", "Utilizado solo por los servicios de emergencia.", "Compartido por todos los trabajadores a la vez."], d: 1 }),
  pr({ id: "of-pr-10", art: "Artículo 4",
    cita: "Se entenderá como «condición de trabajo» cualquier característica del mismo que pueda tener una influencia significativa en la generación de riesgos para la seguridad y la salud del trabajador.",
    clave: "influencia significativa en la generación de riesgos",
    e: "Según el artículo 4.7.º de la Ley 31/1995, se entiende por condición de trabajo cualquier característica del mismo que pueda tener:",
    ok: "Una influencia significativa en la generación de riesgos para la seguridad y la salud.", mal: ["Relación con el salario del trabajador.", "Efectos sobre la productividad, exclusivamente.", "Carácter voluntario para el trabajador."], d: 2 }),
  pr({ id: "of-pr-11", art: "Artículo 14",
    cita: "Los trabajadores tienen derecho a una protección eficaz en materia de seguridad y salud en el trabajo.",
    clave: "protección eficaz",
    e: "Según el artículo 14.1 de la Ley 31/1995, los trabajadores tienen derecho a:",
    ok: "Una protección eficaz en materia de seguridad y salud en el trabajo.", mal: ["Elegir libremente si cumplen las medidas de seguridad.", "Una indemnización fija anual por riesgo.", "No recibir formación preventiva."], d: 1 }),
  pr({ id: "of-pr-12", art: "Artículo 14",
    cita: "El citado derecho supone la existencia de un correlativo deber del empresario de protección de los trabajadores frente a los riesgos laborales.",
    clave: "correlativo deber del empresario",
    e: "Conforme al artículo 14.1 de la Ley 31/1995, el derecho de los trabajadores a una protección eficaz supone la existencia de:",
    ok: "Un correlativo deber del empresario de protección frente a los riesgos laborales.", mal: ["Un deber exclusivo de la Inspección de Trabajo.", "Un seguro privado obligatorio para cada trabajador.", "Una obligación de los clientes de la empresa."], d: 1 }),
  pr({ id: "of-pr-13", art: "Artículo 15",
    cita: "a) Evitar los riesgos.",
    clave: "Evitar los riesgos",
    e: "¿Cuál es el primero de los principios de la acción preventiva que enumera el artículo 15.1 de la Ley 31/1995?",
    ok: "Evitar los riesgos.", mal: ["Contratar un seguro.", "Proporcionar equipos de protección individual.", "Sancionar a quien no cumpla."], d: 1 }),
  pr({ id: "of-pr-14", art: "Artículo 15",
    cita: "c) Combatir los riesgos en su origen.",
    clave: "en su origen",
    e: "Entre los principios de la acción preventiva del artículo 15.1 de la Ley 31/1995 figura combatir los riesgos:",
    ok: "En su origen.", mal: ["Solo cuando produzcan un accidente.", "Únicamente con equipos de protección individual.", "Mediante sanciones económicas."], d: 1 }),
  pr({ id: "of-pr-15", art: "Artículo 15",
    cita: "h) Adoptar medidas que antepongan la protección colectiva a la individual.",
    clave: "antepongan la protección colectiva a la individual",
    e: "Según el artículo 15.1.h) de la Ley 31/1995, el empresario debe adoptar medidas que:",
    ok: "Antepongan la protección colectiva a la individual.", mal: ["Antepongan la protección individual a la colectiva.", "Sustituyan toda protección por un seguro.", "Dejen la protección a elección de cada trabajador."], m: "Primero lo colectivo (barandilla), después lo individual (arnés).", d: 1 }),
  pr({ id: "of-pr-16", art: "Artículo 15",
    cita: "f) Sustituir lo peligroso por lo que entrañe poco o ningún peligro.",
    clave: "Sustituir lo peligroso",
    e: "¿Cuál de los siguientes es un principio de la acción preventiva según el artículo 15.1 de la Ley 31/1995?",
    ok: "Sustituir lo peligroso por lo que entrañe poco o ningún peligro.", mal: ["Mantener el peligro si es rentable.", "Trasladar el peligro a una subcontrata.", "Informar del peligro solo a los mandos."], d: 1 }),
  pr({ id: "of-pr-17", art: "Artículo 15",
    cita: "con miras, en particular, a atenuar el trabajo monótono y repetitivo y a reducir los efectos del mismo en la salud",
    clave: "trabajo monótono y repetitivo",
    e: "Al adaptar el trabajo a la persona, el artículo 15.1.d) de la Ley 31/1995 busca en particular atenuar:",
    ok: "El trabajo monótono y repetitivo y reducir sus efectos en la salud.", mal: ["El número de trabajadores de la plantilla.", "Los salarios elevados.", "La formación continua."], d: 2 }),
  pr({ id: "of-pr-18", art: "Artículo 15",
    cita: "La efectividad de las medidas preventivas deberá prever las distracciones o imprudencias no temerarias que pudiera cometer el trabajador.",
    clave: "imprudencias no temerarias",
    e: "Según el artículo 15.4 de la Ley 31/1995, la efectividad de las medidas preventivas deberá prever:",
    ok: "Las distracciones o imprudencias no temerarias que pudiera cometer el trabajador.", mal: ["Solo los actos dolosos del trabajador.", "Únicamente los fallos de las máquinas.", "Las imprudencias temerarias, exclusivamente."], d: 2 }),
  pr({ id: "of-pr-19", art: "Artículo 15",
    cita: "sólo los trabajadores que hayan recibido información suficiente y adecuada puedan acceder a las zonas de riesgo grave y específico",
    clave: "información suficiente y adecuada",
    e: "Conforme al artículo 15.3 de la Ley 31/1995, solo pueden acceder a las zonas de riesgo grave y específico los trabajadores que:",
    ok: "Hayan recibido información suficiente y adecuada.", mal: ["Tengan más de cinco años de antigüedad.", "Sean mandos intermedios.", "Lo soliciten voluntariamente."], d: 2 }),
  pr({ id: "of-pr-20", art: "Artículo 16",
    cita: "La prevención de riesgos laborales deberá integrarse en el sistema general de gestión de la empresa",
    clave: "sistema general de gestión de la empresa",
    e: "Según el artículo 16.1 de la Ley 31/1995, la prevención de riesgos laborales deberá integrarse en:",
    ok: "El sistema general de gestión de la empresa, en todas sus actividades y niveles jerárquicos.", mal: ["Un departamento aislado sin relación con la gestión.", "El departamento comercial, exclusivamente.", "Una empresa externa, sin implicación de la propia."], d: 1 }),
  pr({ id: "of-pr-21", art: "Artículo 16",
    cita: "a través de la implantación y aplicación de un plan de prevención de riesgos laborales",
    clave: "plan de prevención de riesgos laborales",
    e: "Conforme al artículo 16.1 de la Ley 31/1995, la prevención se integra en el sistema general de gestión de la empresa a través de la implantación y aplicación de:",
    ok: "Un plan de prevención de riesgos laborales.", mal: ["Un convenio colectivo.", "Un plan de igualdad.", "Un manual de bienvenida."], d: 1 }),
  pr({ id: "of-pr-22", art: "Artículo 17",
    cita: "El empresario adoptará las medidas necesarias con el fin de que los equipos de trabajo sean adecuados para el trabajo que deba realizarse y convenientemente adaptados a tal efecto",
    clave: "adecuados para el trabajo que deba realizarse",
    e: "Según el artículo 17.1 de la Ley 31/1995, el empresario adoptará las medidas necesarias para que los equipos de trabajo sean:",
    ok: "Adecuados para el trabajo que deba realizarse y convenientemente adaptados.", mal: ["Los más baratos del mercado.", "Elegidos por cada trabajador.", "De segunda mano, para reducir costes."], d: 1 }),
  pr({ id: "of-pr-23", art: "Artículo 18",
    cita: "el empresario adoptará las medidas adecuadas para que los trabajadores reciban todas las informaciones necesarias",
    clave: "todas las informaciones necesarias",
    e: "Conforme al artículo 18.1 de la Ley 31/1995, para cumplir el deber de protección el empresario adoptará las medidas adecuadas para que los trabajadores reciban:",
    ok: "Todas las informaciones necesarias sobre riesgos, medidas de protección y emergencias.", mal: ["Información solo si la piden por escrito.", "Información únicamente tras un accidente.", "Información solo para los mandos."], d: 1 }),
  pr({ id: "of-pr-24", art: "Artículo 19",
    cita: "el empresario deberá garantizar que cada trabajador reciba una formación teórica y práctica, suficiente y adecuada, en materia preventiva",
    clave: "formación teórica y práctica, suficiente y adecuada",
    e: "Según el artículo 19.1 de la Ley 31/1995, el empresario deberá garantizar que cada trabajador reciba:",
    ok: "Una formación teórica y práctica, suficiente y adecuada, en materia preventiva.", mal: ["Una formación solo teórica, una vez en su vida laboral.", "Una formación voluntaria y a su cargo.", "Una formación únicamente si cambia de empresa."], d: 1 }),
  pr({ id: "of-pr-25", art: "Artículo 19",
    cita: "tanto en el momento de su contratación, cualquiera que sea la modalidad o duración de ésta, como cuando se produzcan cambios en las funciones que desempeñe",
    clave: "en el momento de su contratación",
    e: "Conforme al artículo 19.1 de la Ley 31/1995, la formación preventiva debe darse al trabajador, entre otros momentos:",
    ok: "En el momento de su contratación, cualquiera que sea su modalidad o duración.", mal: ["Solo tras cinco años en la empresa.", "Solo si el contrato es indefinido.", "Solo cuando lo pida el comité de empresa."], d: 2 }),
  pr({ id: "of-pr-26", art: "Artículo 20",
    cita: "adoptar las medidas necesarias en materia de primeros auxilios, lucha contra incendios y evacuación de los trabajadores",
    clave: "primeros auxilios, lucha contra incendios y evacuación",
    e: "Según el artículo 20 de la Ley 31/1995, ante posibles situaciones de emergencia el empresario debe adoptar las medidas necesarias en materia de:",
    ok: "Primeros auxilios, lucha contra incendios y evacuación de los trabajadores.", mal: ["Publicidad y marketing.", "Contabilidad y fiscalidad.", "Vacaciones y permisos."], d: 1 }),
  pr({ id: "of-pr-27", art: "Artículo 21",
    cita: "Informar lo antes posible a todos los trabajadores afectados acerca de la existencia de dicho riesgo",
    clave: "lo antes posible",
    e: "Cuando los trabajadores estén o puedan estar expuestos a un riesgo grave e inminente, según el artículo 21.1.a) de la Ley 31/1995 el empresario está obligado a informar a todos los afectados:",
    ok: "Lo antes posible, sobre el riesgo y las medidas de protección.", mal: ["Al final de la jornada.", "En el informe anual de prevención.", "Solo si el riesgo se materializa."], d: 1 }),
  pr({ id: "of-pr-28", art: "Artículo 21",
    cita: "el trabajador tendrá derecho a interrumpir su actividad y abandonar el lugar de trabajo, en caso necesario, cuando considere que dicha actividad entraña un riesgo grave e inminente para su vida o su salud",
    clave: "interrumpir su actividad y abandonar el lugar de trabajo",
    e: "Según el artículo 21.2 de la Ley 31/1995, cuando el trabajador considere que su actividad entraña un riesgo grave e inminente para su vida o su salud, tendrá derecho a:",
    ok: "Interrumpir su actividad y abandonar el lugar de trabajo, en caso necesario.", mal: ["Seguir trabajando y reclamar después.", "Pedir un aumento de sueldo.", "Solo comunicarlo por escrito y continuar."], d: 1 }),
  pr({ id: "of-pr-29", art: "Artículo 22",
    cita: "El empresario garantizará a los trabajadores a su servicio la vigilancia periódica de su estado de salud en función de los riesgos inherentes al trabajo.",
    clave: "vigilancia periódica de su estado de salud",
    e: "Conforme al artículo 22.1 de la Ley 31/1995, el empresario garantizará a los trabajadores:",
    ok: "La vigilancia periódica de su estado de salud en función de los riesgos inherentes al trabajo.", mal: ["Un seguro médico privado completo.", "La atención sanitaria de sus familiares.", "Una revisión médica solo al jubilarse."], d: 1 }),
  pr({ id: "of-pr-30", art: "Artículo 22",
    cita: "Esta vigilancia sólo podrá llevarse a cabo cuando el trabajador preste su consentimiento.",
    clave: "preste su consentimiento",
    e: "Según el artículo 22.1 de la Ley 31/1995, con las excepciones previstas, la vigilancia de la salud solo podrá llevarse a cabo cuando el trabajador:",
    ok: "Preste su consentimiento.", mal: ["Lo pida su superior jerárquico.", "Tenga más de 45 años.", "Haya sufrido un accidente."], d: 1 }),
  pr({ id: "of-pr-31", art: "Artículo 23",
    cita: "El empresario deberá elaborar y conservar a disposición de la autoridad laboral la siguiente documentación",
    clave: "a disposición de la autoridad laboral",
    e: "Conforme al artículo 23.1 de la Ley 31/1995, el empresario deberá elaborar y conservar la documentación preventiva (plan de prevención, evaluación de riesgos…):",
    ok: "A disposición de la autoridad laboral.", mal: ["En el domicilio de cada trabajador.", "Solo durante seis meses.", "En poder del cliente principal."], d: 2 }),
  pr({ id: "of-pr-32", art: "Artículo 25",
    cita: "El empresario garantizará de manera específica la protección de los trabajadores que, por sus propias características personales o estado biológico conocido",
    clave: "de manera específica",
    e: "Según el artículo 25.1 de la Ley 31/1995, respecto de los trabajadores especialmente sensibles a determinados riesgos, el empresario garantizará su protección:",
    ok: "De manera específica, teniéndolo en cuenta en las evaluaciones de riesgos.", mal: ["Igual que la del resto, sin diferencias.", "Solo si lo pide el médico de familia.", "Mediante su despido para evitar el riesgo."], d: 2 }),
  pr({ id: "of-pr-33", art: "Artículo 26",
    cita: "la determinación de la naturaleza, el grado y la duración de la exposición de las trabajadoras en situación de embarazo o parto reciente",
    clave: "embarazo o parto reciente",
    e: "Conforme al artículo 26.1 de la Ley 31/1995, la evaluación de riesgos debe comprender la naturaleza, el grado y la duración de la exposición a agentes que puedan influir negativamente en la salud de las trabajadoras en situación de:",
    ok: "Embarazo o parto reciente, o del feto.", mal: ["Vacaciones.", "Excedencia voluntaria.", "Reducción de jornada por estudios."], d: 2 }),
  pr({ id: "of-pr-34", art: "Artículo 28",
    cita: "deberán disfrutar del mismo nivel de protección en materia de seguridad y salud que los restantes trabajadores de la empresa",
    clave: "mismo nivel de protección",
    e: "Según el artículo 28.1 de la Ley 31/1995, los trabajadores temporales o contratados por empresas de trabajo temporal deberán disfrutar:",
    ok: "Del mismo nivel de protección en seguridad y salud que los restantes trabajadores.", mal: ["De un nivel de protección reducido.", "De protección solo a partir del tercer mes.", "De la protección de la empresa de trabajo temporal, exclusivamente, sin obligaciones para la usuaria."], d: 1 }),
  pr({ id: "of-pr-35", art: "Artículo 29",
    cita: "Corresponde a cada trabajador velar, según sus posibilidades y mediante el cumplimiento de las medidas de prevención que en cada caso sean adoptadas, por su propia seguridad y salud en el trabajo",
    clave: "velar",
    e: "Conforme al artículo 29.1 de la Ley 31/1995, corresponde a cada trabajador, según sus posibilidades y cumpliendo las medidas de prevención:",
    ok: "Velar por su propia seguridad y salud y por la de las personas a las que pueda afectar su actividad.", mal: ["Elaborar el plan de prevención de la empresa.", "Pagar sus equipos de protección individual.", "Sancionar a sus compañeros."], d: 1 }),
  pr({ id: "of-pr-36", art: "Artículo 30",
    cita: "el empresario designará uno o varios trabajadores para ocuparse de dicha actividad, constituirá un servicio de prevención o concertará dicho servicio con una entidad especializada ajena a la empresa",
    clave: "entidad especializada ajena a la empresa",
    e: "Según el artículo 30.1 de la Ley 31/1995, para cumplir el deber de prevención el empresario designará trabajadores, constituirá un servicio de prevención propio o concertará el servicio con:",
    ok: "Una entidad especializada ajena a la empresa.", mal: ["El Ayuntamiento.", "La Inspección de Trabajo.", "Un sindicato, obligatoriamente."], d: 2 }),
  pr({ id: "of-pr-37", art: "Artículo 33",
    cita: "El empresario deberá consultar a los trabajadores, con la debida antelación, la adopción de las decisiones relativas a",
    clave: "con la debida antelación",
    e: "Conforme al artículo 33.1 de la Ley 31/1995, el empresario deberá consultar a los trabajadores las decisiones relativas, entre otras, a la planificación del trabajo y a la introducción de nuevas tecnologías:",
    ok: "Con la debida antelación.", mal: ["Después de aplicarlas.", "Solo si lo exige el convenio.", "Una vez al año, en todo caso."], d: 2 }),
  pr({ id: "of-pr-38", art: "Artículo 34",
    cita: "En las empresas o centros de trabajo que cuenten con seis o más trabajadores, la participación de éstos se canalizará a través de sus representantes",
    clave: "seis o más trabajadores",
    e: "Según el artículo 34.1 de la Ley 31/1995, la participación de los trabajadores en materia preventiva se canaliza a través de sus representantes en las empresas o centros de trabajo que cuenten con:",
    ok: "Seis o más trabajadores.", mal: ["Cincuenta o más trabajadores.", "Diez o más trabajadores.", "Cien o más trabajadores."], d: 2 }),
  pr({ id: "of-pr-39", art: "Artículo 35",
    cita: "Los Delegados de Prevención son los representantes de los trabajadores con funciones específicas en materia de prevención de riesgos en el trabajo.",
    clave: "funciones específicas en materia de prevención",
    e: "Conforme al artículo 35.1 de la Ley 31/1995, los Delegados de Prevención son:",
    ok: "Los representantes de los trabajadores con funciones específicas en materia de prevención de riesgos.", mal: ["Técnicos de prevención contratados por la empresa.", "Inspectores de trabajo destinados en la empresa.", "Médicos del servicio de prevención."], d: 1 }),
  pr({ id: "of-pr-40", art: "Artículo 35",
    cita: "Los Delegados de Prevención serán designados por y entre los representantes del personal",
    clave: "por y entre los representantes del personal",
    e: "Según el artículo 35.2 de la Ley 31/1995, los Delegados de Prevención son designados:",
    ok: "Por y entre los representantes del personal.", mal: ["Por el empresario libremente.", "Por la Inspección de Trabajo.", "Por sorteo entre toda la plantilla."], d: 2 }),
  pr({ id: "of-pr-41", art: "Artículo 35",
    cita: "De 50 a 100 trabajadores: 2 Delegados de Prevención.",
    clave: "2 Delegados",
    e: "Conforme a la escala del artículo 35.2 de la Ley 31/1995, en una empresa de 50 a 100 trabajadores corresponden:",
    ok: "2 Delegados de Prevención.", mal: ["1 Delegado de Prevención.", "3 Delegados de Prevención.", "4 Delegados de Prevención."], d: 2 }),
  pr({ id: "of-pr-42", art: "Artículo 35",
    cita: "De 4.001 en adelante: 8 Delegados de Prevención.",
    clave: "8 Delegados",
    e: "Según la escala del artículo 35.2 de la Ley 31/1995, en empresas de más de 4.000 trabajadores (de 4.001 en adelante) corresponden:",
    ok: "8 Delegados de Prevención.", mal: ["10 Delegados de Prevención.", "6 Delegados de Prevención.", "12 Delegados de Prevención."], d: 3 }),
  pr({ id: "of-pr-43", art: "Artículo 35",
    cita: "En las empresas de hasta treinta trabajadores el Delegado de Prevención será el Delegado de Personal.",
    clave: "el Delegado de Personal",
    e: "Conforme al artículo 35.2 de la Ley 31/1995, en las empresas de hasta treinta trabajadores el Delegado de Prevención será:",
    ok: "El Delegado de Personal.", mal: ["El propio empresario.", "Un técnico externo.", "El trabajador más antiguo."], d: 2 }),
  pr({ id: "of-pr-44", art: "Artículo 36",
    cita: "a) Colaborar con la dirección de la empresa en la mejora de la acción preventiva.",
    clave: "Colaborar con la dirección de la empresa",
    e: "¿Cuál de las siguientes es una competencia de los Delegados de Prevención según el artículo 36.1 de la Ley 31/1995?",
    ok: "Colaborar con la dirección de la empresa en la mejora de la acción preventiva.", mal: ["Imponer sanciones a la empresa.", "Aprobar el presupuesto de la empresa.", "Contratar al personal del servicio de prevención."], d: 1 }),
  pr({ id: "of-pr-45", art: "Artículo 38",
    cita: "El Comité de Seguridad y Salud es el órgano paritario y colegiado de participación destinado a la consulta regular y periódica de las actuaciones de la empresa en materia de prevención de riesgos.",
    clave: "paritario y colegiado",
    e: "Según el artículo 38.1 de la Ley 31/1995, el Comité de Seguridad y Salud es el órgano:",
    ok: "Paritario y colegiado de participación para la consulta regular y periódica en materia de prevención.", mal: ["Unipersonal de la dirección de la empresa.", "Sancionador dependiente de la Inspección.", "Sindical, sin presencia de la empresa."], d: 1 }),
  pr({ id: "of-pr-46", art: "Artículo 38",
    cita: "Se constituirá un Comité de Seguridad y Salud en todas las empresas o centros de trabajo que cuenten con 50 o más trabajadores.",
    clave: "50 o más trabajadores",
    e: "Conforme al artículo 38.2 de la Ley 31/1995, se constituirá un Comité de Seguridad y Salud en todas las empresas o centros de trabajo que cuenten con:",
    ok: "50 o más trabajadores.", mal: ["6 o más trabajadores.", "30 o más trabajadores.", "100 o más trabajadores."], d: 1 }),
  pr({ id: "of-pr-47", art: "Artículo 38",
    cita: "El Comité de Seguridad y Salud se reunirá trimestralmente y siempre que lo solicite alguna de las representaciones en el mismo.",
    clave: "trimestralmente",
    e: "Según el artículo 38.3 de la Ley 31/1995, el Comité de Seguridad y Salud se reunirá:",
    ok: "Trimestralmente y siempre que lo solicite alguna de las representaciones.", mal: ["Mensualmente.", "Una vez al año.", "Solo cuando haya un accidente."], d: 2 }),
  pr({ id: "of-pr-48", art: "Artículo 38",
    cita: "participarán, con voz pero sin voto, los Delegados Sindicales y los responsables técnicos de la prevención en la empresa",
    clave: "con voz pero sin voto",
    e: "Conforme al artículo 38.2 de la Ley 31/1995, en las reuniones del Comité de Seguridad y Salud los Delegados Sindicales y los responsables técnicos de prevención no incluidos en él participan:",
    ok: "Con voz pero sin voto.", mal: ["Con voz y voto.", "Sin voz ni voto, como oyentes.", "Con voto de calidad."], d: 2 }),
  pr({ id: "of-pr-49", art: "Artículo 24",
    cita: "Cuando en un mismo centro de trabajo desarrollen actividades trabajadores de dos o más empresas, éstas deberán cooperar en la aplicación de la normativa sobre prevención de riesgos laborales.",
    clave: "deberán cooperar",
    e: "Según el artículo 24.1 de la Ley 31/1995, cuando en un mismo centro de trabajo desarrollan actividades trabajadores de dos o más empresas, estas:",
    ok: "Deberán cooperar en la aplicación de la normativa de prevención de riesgos laborales.", mal: ["Quedan exentas de la normativa preventiva.", "Solo responde la empresa con más trabajadores.", "Deben fusionar sus servicios de prevención."], d: 1 }),
  pr({ id: "of-pr-50", art: "Artículo 31",
    cita: "el empresario deberá recurrir a uno o varios servicios de prevención propios o ajenos",
    clave: "servicios de prevención propios o ajenos",
    e: "Conforme al artículo 31.1 de la Ley 31/1995, si la designación de trabajadores es insuficiente para las actividades de prevención, el empresario deberá recurrir a:",
    ok: "Uno o varios servicios de prevención propios o ajenos.", mal: ["La Inspección de Trabajo para que haga la prevención.", "Un seguro de responsabilidad civil, exclusivamente.", "La autoprotección de cada trabajador."], d: 2 }),
  pr({ id: "of-pr-51", art: "Artículo 37",
    cita: "será considerado como de ejercicio de funciones de representación a efectos de la utilización del crédito de horas mensuales retribuidas",
    clave: "crédito de horas mensuales retribuidas",
    e: "Según el artículo 37.1 de la Ley 31/1995, el tiempo que los Delegados de Prevención dedican a sus funciones se considera de ejercicio de funciones de representación a efectos de:",
    ok: "La utilización del crédito de horas mensuales retribuidas.", mal: ["Su cómputo como vacaciones.", "Su descuento del salario.", "Su recuperación fuera del horario laboral."], d: 2 }),
  pr({ id: "of-pr-52", art: "Artículo 39",
    cita: "a) Participar en la elaboración, puesta en práctica y evaluación de los planes y programas de prevención de riesgos de la empresa.",
    clave: "Participar en la elaboración, puesta en práctica y evaluación",
    e: "¿Cuál de las siguientes es una competencia del Comité de Seguridad y Salud según el artículo 39.1 de la Ley 31/1995?",
    ok: "Participar en la elaboración, puesta en práctica y evaluación de los planes y programas de prevención.", mal: ["Imponer sanciones disciplinarias a los trabajadores.", "Fijar los salarios de la plantilla.", "Contratar y despedir al personal."], d: 1 }),
  pr({ id: "of-pr-53", art: "Artículo 41",
    cita: "están obligados a asegurar que éstos no constituyan una fuente de peligro para el trabajador",
    clave: "no constituyan una fuente de peligro",
    e: "Conforme al artículo 41.1 de la Ley 31/1995, los fabricantes, importadores y suministradores de maquinaria, equipos, productos y útiles de trabajo están obligados a asegurar que estos:",
    ok: "No constituyan una fuente de peligro para el trabajador, si se usan en las condiciones recomendadas.", mal: ["Sean los más baratos del mercado.", "Se vendan sin instrucciones.", "Solo los use personal de la propia marca."], d: 1 }),
  pr({ id: "of-pr-54", art: "Artículo 41",
    cita: "están obligados a envasar y etiquetar los mismos",
    clave: "etiquetar",
    e: "Según el artículo 41.1 de la Ley 31/1995, los fabricantes, importadores y suministradores de productos y sustancias químicas de uso en el trabajo están obligados a:",
    ok: "Envasarlos y etiquetarlos para permitir su conservación y manipulación seguras.", mal: ["Venderlos solo a granel.", "Ocultar su composición por secreto industrial.", "Entregarlos sin envase para facilitar su uso."], d: 2 }),
  pr({ id: "of-pr-55", art: "Artículo 42",
    cita: "dará lugar a responsabilidades administrativas, así como, en su caso, a responsabilidades penales y a las civiles por los daños y perjuicios que puedan derivarse de dicho incumplimiento",
    clave: "responsabilidades administrativas",
    e: "Conforme al artículo 42.1 de la Ley 31/1995, el incumplimiento por los empresarios de sus obligaciones preventivas dará lugar a:",
    ok: "Responsabilidades administrativas y, en su caso, penales y civiles.", mal: ["Solo una amonestación verbal.", "Únicamente responsabilidad del trabajador afectado.", "Ninguna responsabilidad si no hay accidente."], d: 1 }),
  pr({ id: "of-pr-56", art: "Artículo 44",
    cita: "podrá ordenar la paralización inmediata de tales trabajos o tareas",
    clave: "paralización inmediata",
    e: "Según el artículo 44.1 de la Ley 31/1995, cuando el Inspector de Trabajo comprueba que el incumplimiento de la normativa preventiva implica un riesgo grave e inminente, podrá ordenar:",
    ok: "La paralización inmediata de esos trabajos o tareas.", mal: ["El cierre definitivo de la empresa.", "La detención del empresario.", "El despido de los trabajadores afectados."], d: 2 }),
  pr({ id: "of-pr-57", art: "Artículo 4",
    cita: "aquellos que, en ausencia de medidas preventivas específicas, originen riesgos para la seguridad y la salud de los trabajadores que los desarrollan o utilizan",
    clave: "en ausencia de medidas preventivas específicas",
    e: "Según el artículo 4.5.º de la Ley 31/1995, se consideran «potencialmente peligrosos» los procesos, actividades, operaciones, equipos o productos que originen riesgos para la seguridad y la salud:",
    ok: "En ausencia de medidas preventivas específicas.", mal: ["Aunque se apliquen todas las medidas preventivas.", "Solo si son de importación.", "Únicamente si los usa personal temporal."], d: 2 }),
  pr({ id: "of-pr-58", art: "Artículo 15",
    cita: "e) Tener en cuenta la evolución de la técnica.",
    clave: "evolución de la técnica",
    e: "¿Cuál de los siguientes principios de la acción preventiva recoge el artículo 15.1 de la Ley 31/1995?",
    ok: "Tener en cuenta la evolución de la técnica.", mal: ["Mantener los equipos aunque estén obsoletos.", "Evitar invertir en seguridad.", "Reducir la formación para ahorrar costes."], d: 1 }),
  pr({ id: "of-pr-59", art: "Artículo 15",
    cita: "i) Dar las debidas instrucciones a los trabajadores.",
    clave: "debidas instrucciones",
    e: "Entre los principios de la acción preventiva del artículo 15.1 de la Ley 31/1995 figura:",
    ok: "Dar las debidas instrucciones a los trabajadores.", mal: ["Dejar que cada trabajador decida cómo protegerse.", "Informar solo a los delegados sindicales.", "Prohibir las preguntas sobre seguridad."], d: 1 }),
  pr({ id: "of-pr-60", art: "Artículo 22",
    cita: "respetando siempre el derecho a la intimidad y a la dignidad de la persona del trabajador y la confidencialidad de toda la información relacionada con su estado de salud",
    clave: "confidencialidad",
    e: "Según el artículo 22.2 de la Ley 31/1995, las medidas de vigilancia de la salud se llevarán a cabo respetando el derecho a la intimidad y a la dignidad del trabajador y:",
    ok: "La confidencialidad de toda la información relacionada con su estado de salud.", mal: ["La publicación de los resultados en el tablón.", "La entrega de los resultados a todos los compañeros.", "El envío de los datos médicos a los clientes."], d: 2 }),
  pr({ id: "of-pr-61", art: "Artículo 20",
    cita: "designando para ello al personal encargado de poner en práctica estas medidas y comprobando periódicamente, en su caso, su correcto funcionamiento",
    clave: "periódicamente",
    e: "Conforme al artículo 20 de la Ley 31/1995, en relación con las medidas de emergencia, el empresario designará al personal encargado de ponerlas en práctica y:",
    ok: "Comprobará periódicamente, en su caso, su correcto funcionamiento.", mal: ["No necesitará revisarlas nunca.", "Las delegará en los bomberos sin seguimiento.", "Solo las revisará tras un incendio."], d: 2 }),
];
