// Banco de 50 preguntas para el Tema 1 de Correos. Las primeras 28 están
// verificadas contra el texto consolidado de la Ley 43/2010, del servicio
// postal universal, de los derechos de los usuarios y del mercado postal,
// en el BOE (BOE-A-2010-20139). Las 22 restantes son de conocimiento
// operativo/comercial (tipos de envío, logística, puntos de recogida) sin
// base legal directa — ver la nota de content/correos-temario.ts sobre por
// qué el temario de Correos no está ligado en su totalidad a un único BOE.

export const CORREOS_TEMA1_PREGUNTAS = 
[
  // ===== PARTE A · Normativa postal (Ley 43/2010) =====
  {
    enunciado: "Conforme al artículo 1 de la Ley 43/2010, del servicio postal universal, de los derechos de los usuarios y del mercado postal, ¿cuál es el objeto de dicha ley?",
    opciones: [
      "La regulación de los servicios postales para garantizar la prestación del servicio postal universal, satisfacer las necesidades de comunicación postal y asegurar la libre competencia en el sector.",
      "La regulación exclusiva del régimen jurídico del personal al servicio de la Sociedad Estatal Correos y Telégrafos, S.A.",
      "El establecimiento del régimen de contratación pública aplicable a los operadores postales privados.",
      "La fijación de las tarifas de todos los envíos postales nacionales e internacionales.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El artículo 1.1 de la Ley 43/2010 fija como objeto la regulación de los servicios postales con el fin de garantizar la prestación del servicio postal universal, satisfacer las necesidades de comunicación postal dentro de España y de España con el extranjero, y asegurar la libre competencia en el sector en condiciones adecuadas de calidad, eficacia y eficiencia, con pleno respeto de los derechos de los usuarios y de los operadores postales y sus trabajadores.",
    mnemotecnia: "Art. 1 abre la ley con el PARA QUÉ: piensa en las 3 U/C del objeto — Universal, Uso (comunicación) y libre Competencia.",
    dificultad: 1,
  },
  {
    enunciado: "Según la Ley 43/2010, los servicios postales tienen la naturaleza de:",
    opciones: [
      "Servicios públicos de titularidad estatal prestados en régimen de monopolio por el operador designado.",
      "Servicios de interés económico general que se prestan en régimen de libre competencia.",
      "Servicios privados de mercado, sin que quepa imponer obligación de servicio público alguna.",
      "Servicios esenciales reservados en exclusiva a las Administraciones Públicas.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El artículo 2 de la Ley 43/2010 declara que los servicios postales son servicios de interés económico general que se prestan en régimen de libre competencia, sin perjuicio de que estén sometidos a obligaciones de servicio público los incluidos en el servicio postal universal encomendados al operador designado y los que se impongan a los titulares de autorizaciones administrativas singulares.",
    mnemotecnia: "Art. 2: 'dos caras de la misma moneda' — interés económico general Y libre competencia a la vez.",
    dificultad: 1,
  },
  {
    enunciado: "De acuerdo con las definiciones de la Ley 43/2010, los paquetes postales que contengan mercancías, con o sin valor comercial, tienen la consideración de envío postal:",
    opciones: [
      "Únicamente si su peso no supera los dos kilogramos.",
      "Únicamente si tienen valor comercial declarado.",
      "Cualquiera que sea su peso.",
      "Únicamente si se remiten bajo la modalidad de certificado.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "El artículo 3.2 de la Ley 43/2010 define el envío postal e incluye expresamente, además de los envíos de correspondencia, la publicidad directa, los libros, catálogos, diarios, publicaciones periódicas y los paquetes postales que contengan mercancías con o sin valor comercial, cualquiera que sea su peso.",
    mnemotecnia: "Art. 3.2 → 'sin báscula': sea cual sea el peso, si lleva mercancía es envío postal.",
    dificultad: 2,
  },
  {
    enunciado: "¿Cuál de los siguientes NO tiene la consideración de envío de correspondencia conforme a la Ley 43/2010?",
    opciones: [
      "Una carta comercial dirigida a un cliente.",
      "Una comunicación escrita sobre soporte físico con la dirección del destinatario en el envoltorio.",
      "Los libros, catálogos, diarios y publicaciones periódicas.",
      "Una carta manuscrita remitida a un particular.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "El artículo 3.3 de la Ley 43/2010 define el envío de correspondencia como la comunicación materializada en forma escrita sobre un soporte físico de cualquier naturaleza, y precisa expresamente que la publicidad directa, los libros, catálogos, diarios y publicaciones periódicas no tendrán la consideración de envíos de correspondencia.",
    mnemotecnia: "Recuerda el acrónimo PLCDP fuera de la correspondencia: Publicidad, Libros, Catálogos, Diarios, Publicaciones — lo que se LEE no es correspondencia.",
    dificultad: 2,
  },
  {
    enunciado: "Según la Ley 43/2010, el servicio de envío certificado se caracteriza porque:",
    opciones: [
      "Previo pago de una cantidad predeterminada a tanto alzado, comporta una garantía fija contra los riesgos de pérdida, robo o deterioro y facilita al remitente, a petición de este, prueba de depósito o de entrega.",
      "Garantiza siempre la entrega en un plazo máximo de veinticuatro horas en todo el territorio nacional.",
      "Permite asegurar el envío por el importe exacto declarado por el remitente.",
      "Exime al remitente del pago del franqueo por tratarse de una obligación de servicio público.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El artículo 3.4 de la Ley 43/2010 define el servicio de envío certificado como aquel que, previo pago de una cantidad predeterminada a tanto alzado, comporta una garantía fija contra los riesgos de pérdida, robo o deterioro, y que facilita al remitente, en su caso y a petición de este, una prueba de depósito del envío postal o de su entrega al destinatario.",
    mnemotecnia: "Certificado = 'CERTeza a precio fijo': tanto alzado + prueba de depósito y entrega.",
    dificultad: 1,
  },
  {
    enunciado: "Conforme a las definiciones de la Ley 43/2010, el servicio de envío con valor declarado es aquel que:",
    opciones: [
      "Obliga al destinatario a abonar un importe en el momento de la entrega.",
      "Acredita ante los tribunales el contenido literal del envío.",
      "Sustituye al servicio de certificado en los envíos transfronterizos.",
      "Permite asegurar el envío por el valor declarado por el remitente, en caso de pérdida, robo o deterioro.",
    ],
    respuestaCorrecta: 3,
    justificacionIa: "El artículo 3.5 de la Ley 43/2010 define el servicio de envío con valor declarado como aquel que permite asegurar el envío por el valor declarado por el remitente, en caso de pérdida, robo o deterioro.",
    mnemotecnia: "Valor declarado = 'lo que TÚ declares, eso te cubren' en caso de pérdida, robo o deterioro.",
    dificultad: 1,
  },
  {
    enunciado: "¿Qué quedan excluidos del ámbito de aplicación de la Ley 43/2010?",
    opciones: [
      "Los servicios realizados en régimen de autoprestación y los servicios relativos a los envíos sin dirección postal del destinatario.",
      "Los envíos transfronterizos con destino a países no pertenecientes a la Unión Europea.",
      "Los servicios de paquetería superiores a diez kilogramos de peso.",
      "Los envíos de publicidad directa y los catálogos comerciales.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El artículo 4 de la Ley 43/2010 excluye de su ámbito de aplicación los servicios realizados en régimen de autoprestación, así como los servicios relativos a los envíos sin dirección postal del destinatario, precisando cuándo se entiende que existe autoprestación.",
    mnemotecnia: "Art. 4 = 'fuera de juego': autoprestación (te lo envías tú mismo) y envíos sin dirección postal.",
    dificultad: 2,
  },
  {
    enunciado: "El deber de los operadores postales de prestar los servicios con plena garantía del secreto de las comunicaciones postales se establece en la Ley 43/2010 con remisión expresa a:",
    opciones: [
      "Los artículos 14 y 20 de la Constitución Española.",
      "El artículo 105 de la Constitución Española y la legislación de transparencia.",
      "Los artículos 18.3 y 55.2 de la Constitución Española y el artículo 579 de la Ley de Enjuiciamiento Criminal.",
      "El artículo 149.1.21.ª de la Constitución Española.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "El artículo 5 de la Ley 43/2010 dispone que los operadores postales deberán realizar la prestación de los servicios con plena garantía del secreto de las comunicaciones postales, de conformidad con lo dispuesto en los artículos 18.3 y 55.2 de la Constitución Española y en el artículo 579 de la Ley de Enjuiciamiento Criminal.",
    mnemotecnia: "Art. 5 = el candado triple del secreto postal: memoriza '18-55-579' (arts. 18.3 y 55.2 CE + art. 579 LECrim).",
    dificultad: 1,
  },
  {
    enunciado: "Conforme al principio de inviolabilidad de los envíos postales recogido en la Ley 43/2010, los envíos postales solo podrán ser detenidos o interceptados y, en su caso, abiertos:",
    opciones: [
      "Por resolución motivada de la autoridad judicial conforme a la ley.",
      "Por decisión del director de la oficina postal de destino cuando existan sospechas.",
      "Por acuerdo del órgano regulador cuando lo solicite el remitente.",
      "Por orden del Delegado del Gobierno en la comunidad autónoma correspondiente.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El artículo 6.2 de la Ley 43/2010 establece que, sin perjuicio del derecho a la propiedad de los envíos postales reconocido en el artículo 13, los envíos postales solo podrán ser detenidos o interceptados y, en su caso, abiertos por resolución motivada de la autoridad judicial conforme a la ley.",
    mnemotecnia: "Art. 6.2 = solo un JUEZ con resolución motivada puede abrir tu envío, nadie más.",
    dificultad: 1,
  },
  {
    enunciado: "Cuando el personal del organismo regulador que desempeña funciones de inspección postal interviene envíos por existir sospechas fundadas de que contienen un objeto prohibido, la Ley 43/2010 limita el alcance de esa intervención a:",
    opciones: [
      "La apertura del envío en presencia de dos testigos y del remitente.",
      "El reconocimiento externo, visual o mediante máquinas, tanto de los envíos como de la documentación que los acompañe, sin afectar en ningún caso al secreto e inviolabilidad de los envíos.",
      "La retención indefinida del envío hasta que el destinatario acredite su contenido.",
      "La destrucción inmediata del envío sin más trámite.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El artículo 6.3 de la Ley 43/2010 limita el alcance de dicha intervención al reconocimiento externo, visual o mediante máquinas, tanto de los envíos como de la documentación que los acompañe, precisando que no afectará en ningún caso al secreto e inviolabilidad de los envíos postales y que se garantizará la destrucción inmediata de las imágenes tomadas.",
    mnemotecnia: "Art. 6.3 = 'mirar sin tocar': solo reconocimiento externo, visual o con máquinas, nunca abrir el envío.",
    dificultad: 3,
  },
  {
    enunciado: "Según la Ley 43/2010, las reclamaciones que los usuarios presenten a los operadores postales deberán ser resueltas y notificadas a los interesados en un plazo máximo de:",
    opciones: [
      "Quince días hábiles desde la fecha de su presentación.",
      "Tres meses desde la fecha de su presentación.",
      "Un mes desde la fecha de su presentación.",
      "Seis meses desde la fecha de su presentación.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "El artículo 10.2 de la Ley 43/2010 exige procedimientos sencillos, gratuitos y no discriminatorios y dispone que, en todo caso, las reclamaciones deberán ser resueltas conforme a derecho y notificadas a los interesados en el plazo máximo de un mes desde la fecha de su presentación, de la que el prestador del servicio deberá dar siempre recibo al interesado.",
    mnemotecnia: "Art. 10.2 = 'diez... y un mes': las reclamaciones se resuelven y notifican en el plazo máximo de un mes.",
    dificultad: 2,
  },
  {
    enunciado: "Cuando el usuario acude al organismo regulador postal para plantear una controversia con un operador en el ámbito del servicio postal universal, y no la ha sometido a las Juntas Arbitrales de Consumo, la Ley 43/2010 establece que:",
    opciones: [
      "La reclamación podrá efectuarse en el plazo de tres meses y deberá resolverse en el plazo máximo de un año.",
      "La reclamación podrá efectuarse en el plazo de un mes desde la respuesta del operador o desde la finalización del plazo para responder, y deberá resolverse en el plazo máximo de tres meses desde su presentación.",
      "La reclamación solo cabe una vez agotada la vía judicial civil.",
      "La reclamación deberá presentarse en el plazo de quince días y se resolverá en el plazo de un mes.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El artículo 10.4 de la Ley 43/2010 atribuye al organismo regulador el conocimiento de las controversias entre usuarios y operadores en el ámbito del servicio postal universal siempre que no se hayan sometido a las Juntas Arbitrales de Consumo, y fija un plazo de un mes para reclamar desde la respuesta del operador o desde la finalización del plazo para responder, debiendo resolverse en el plazo máximo de tres meses desde su presentación.",
    mnemotecnia: "Art. 10.4 = el patrón '1 y 3': un mes para reclamar ante el regulador, tres meses para que lo resuelva.",
    dificultad: 3,
  },
  {
    enunciado: "Respecto del derecho a percibir indemnización reconocido en la Ley 43/2010, señale la afirmación correcta:",
    opciones: [
      "La indemnización procede en todo caso, incluso mediando fuerza mayor, y por cualquier clase de envío.",
      "En los envíos certificados la indemnización consiste en una cantidad predeterminada por el operador y en los envíos con valor declarado, en una cantidad proporcional a la declarada por el remitente.",
      "La indemnización solo procede cuando el envío se haya perdido, nunca cuando se haya deteriorado.",
      "La indemnización la fija libremente el usuario y es exigible directamente en vía ejecutiva.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El artículo 12.1 de la Ley 43/2010 reconoce a los usuarios el derecho, salvo caso de fuerza mayor, a percibir indemnización en caso de pérdida, robo, destrucción o deterioro de los envíos certificados o con valor declarado, mediante el pago de una cantidad predeterminada por el operador postal en el primer caso, y de una cantidad proporcional a la declarada por el remitente en el segundo.",
    mnemotecnia: "Art. 12.1 = certificado con precio FIJO, valor declarado PROPORCIONAL a lo declarado.",
    dificultad: 2,
  },
  {
    enunciado: "Conforme a la Ley 43/2010, los envíos postales serán de titularidad, a efectos postales:",
    opciones: [
      "Del remitente, en tanto no lleguen a poder del destinatario.",
      "Del operador postal desde su admisión hasta su entrega.",
      "Del destinatario desde el mismo momento del depósito del envío.",
      "Del Estado, por tratarse de un servicio de interés económico general.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El artículo 13 de la Ley 43/2010 establece que los envíos postales serán de titularidad del remitente a efectos postales en tanto no lleguen a poder del destinatario, quien podrá, mediante el pago del precio correspondiente, recuperarlos o modificar su dirección, salvo en los supuestos de imposibilidad material.",
    mnemotecnia: "Art. 13 = 'trece, tuyo hasta que llegue': el envío es del remitente hasta que llega a poder del destinatario.",
    dificultad: 1,
  },
  {
    enunciado: "El derecho de los usuarios a presentar solicitudes, escritos y comunicaciones dirigidas a las Administraciones Públicas con los efectos propios del registro del órgano administrativo destinatario se ejerce, según la Ley 43/2010:",
    opciones: [
      "A través de cualquier operador postal inscrito en el registro de empresas prestadoras.",
      "Únicamente de forma presencial en las oficinas de registro de la Administración.",
      "A través de las oficinas del operador designado para la prestación del servicio postal universal.",
      "Exclusivamente por medios electrónicos a través de la sede del organismo regulador.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "El artículo 14 de la Ley 43/2010 reconoce el derecho a presentar solicitudes, escritos y comunicaciones dirigidas a las Administraciones Públicas únicamente a través de las oficinas del operador designado para la prestación del servicio postal universal, que deberá recibirlos y dirigirlos al destinatario con carácter preferente y acreditar su presentación y entrega, surtiendo los mismos efectos que en el registro del órgano administrativo al que se dirijan.",
    mnemotecnia: "Art. 14 = la ventanilla postal: solo a través del operador designado tus escritos valen como registro de la Administración.",
    dificultad: 2,
  },
  {
    enunciado: "En relación con los envíos certificados, la Ley 43/2010 obliga al operador designado a facilitar al remitente, a petición de este y previo pago del importe que corresponda:",
    opciones: [
      "Una copia fotográfica del contenido del envío.",
      "Un resguardo acreditativo de su admisión, con constancia de la fecha y hora de presentación, y asimismo de su recepción por el destinatario.",
      "Un certificado notarial de depósito del envío.",
      "La devolución íntegra del franqueo si la entrega se demora.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El artículo 16 de la Ley 43/2010 obliga al operador designado a facilitar al remitente de cualquier envío certificado, a petición del mismo y previo pago del importe que corresponda, resguardo acreditativo de su admisión donde conste la fecha y hora de su presentación, y asimismo de su recepción por el destinatario.",
    mnemotecnia: "Art. 16 = doble resguardo: uno al admitir el certificado, otro al confirmarse su entrega.",
    dificultad: 1,
  },
  {
    enunciado: "¿Cómo define la Ley 43/2010 el servicio postal universal?",
    opciones: [
      "El conjunto de servicios postales prestados en exclusiva por el operador designado en régimen de monopolio legal.",
      "El conjunto de servicios de paquetería urgente prestados a las Administraciones Públicas.",
      "El conjunto de servicios postales cuyo precio es fijado libremente por el mercado en función de la demanda.",
      "El conjunto de servicios postales de calidad determinada en la ley y sus reglamentos de desarrollo, prestados en régimen ordinario y permanente en todo el territorio nacional y a precio asequible para todos los usuarios.",
    ],
    respuestaCorrecta: 3,
    justificacionIa: "El artículo 20 de la Ley 43/2010 define el servicio postal universal como el conjunto de servicios postales de calidad determinada en la ley y sus reglamentos de desarrollo, prestados en régimen ordinario y permanente en todo el territorio nacional y a precio asequible para todos los usuarios.",
    mnemotecnia: "Art. 20 = 'veinte, universal para todos': calidad tasada + régimen ordinario y permanente + precio asequible.",
    dificultad: 1,
  },
  {
    enunciado: "Dentro del ámbito del servicio postal universal, la Ley 43/2010 incluye las cartas y tarjetas postales que contengan comunicaciones escritas en cualquier tipo de soporte de hasta:",
    opciones: [
      "Un kilogramo de peso.",
      "Dos kilogramos de peso.",
      "Cinco kilogramos de peso.",
      "Diez kilogramos de peso.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El artículo 21.1.a) de la Ley 43/2010 incluye en el ámbito del servicio postal universal las cartas y tarjetas postales que contengan comunicaciones escritas en cualquier tipo de soporte de hasta dos kilogramos de peso.",
    mnemotecnia: "Art. 21.1.a): cartas hasta 2 kg — el '2' del kilo acompaña al '21' del artículo.",
    dificultad: 1,
  },
  {
    enunciado: "Los paquetes postales, con o sin valor comercial, quedan incluidos en el ámbito del servicio postal universal regulado en la Ley 43/2010 cuando su peso no supere:",
    opciones: [
      "Diez kilogramos.",
      "Quince kilogramos.",
      "Veinte kilogramos.",
      "Treinta kilogramos.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "El artículo 21.1.b) de la Ley 43/2010 incluye en el ámbito del servicio postal universal los paquetes postales, con o sin valor comercial, de hasta veinte kilogramos de peso, junto con los servicios accesorios de certificado y valor declarado.",
    mnemotecnia: "Art. 21.1.b): paquetes hasta 20 kg — mismo '2' que el artículo, pero con un cero más (20 en vez de 2).",
    dificultad: 1,
  },
  {
    enunciado: "En cuanto a las condiciones de recogida y admisión, la Ley 43/2010 obliga al operador designado a realizar, en los puntos de acceso a la red postal:",
    opciones: [
      "Al menos una recogida todos los días laborables, de lunes a viernes, con independencia de la densidad de población e incluso en zonas rurales.",
      "Al menos tres recogidas semanales, salvo en zonas rurales, donde bastará con una.",
      "Al menos una recogida diaria de lunes a domingo en todo el territorio nacional.",
      "Las recogidas que libremente determine el operador en función de la rentabilidad de cada zona.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El artículo 23.a) de la Ley 43/2010 obliga al operador u operadores designados a realizar, al menos, una recogida en los puntos de acceso a la red postal todos los días laborables, de lunes a viernes, con independencia de la densidad de población e incluso en zonas rurales.",
    mnemotecnia: "Art. 23 = recogida de lunes a viernes SIEMPRE, hasta en el pueblo más remoto: ni la ruralidad la libra.",
    dificultad: 1,
  },
  {
    enunciado: "Respecto de la distribución y entrega de los envíos postales, la Ley 43/2010 establece que las entregas se practicarán:",
    opciones: [
      "Al menos tres días por semana en todo el territorio nacional.",
      "Al menos todos los días laborables, de lunes a viernes, salvo en el caso de concurrir circunstancias o condiciones geográficas especiales.",
      "Todos los días del año, incluidos festivos, sin excepción alguna.",
      "Únicamente en las capitales de provincia y en los municipios de más de veinte mil habitantes.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El artículo 24 de la Ley 43/2010 dispone que las entregas se practicarán, al menos, todos los días laborables, de lunes a viernes, salvo en el caso de concurrir circunstancias o condiciones geográficas especiales, conforme a lo previsto en la ley y en su normativa de desarrollo.",
    mnemotecnia: "Art. 24 sigue al 23: si el 23 es recogida de lunes a viernes, el 24 es entrega de lunes a viernes (salvo geografía especial).",
    dificultad: 1,
  },
  {
    enunciado: "Según la Ley 43/2010, la actuación del operador designado goza de presunción de veracidad y fehaciencia en:",
    opciones: [
      "Cualquier contrato mercantil suscrito con sus clientes de paquetería.",
      "La distribución, entrega y recepción o rehúse o imposibilidad de entrega de notificaciones de órganos administrativos y judiciales, tanto por medios físicos como telemáticos.",
      "La determinación del contenido de los envíos certificados que transporta.",
      "La fijación unilateral de los precios de los servicios no incluidos en el servicio postal universal.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El artículo 22.4 de la Ley 43/2010 establece que la actuación del operador designado gozará de la presunción de veracidad y fehaciencia en la distribución, entrega y recepción o rehúse o imposibilidad de entrega de notificaciones de órganos administrativos y judiciales, tanto las realizadas por medios físicos como telemáticos.",
    mnemotecnia: "Art. 22.4 = el cartero de notificaciones 'no miente': presunción de veracidad y fehaciencia en la entrega judicial/administrativa.",
    dificultad: 2,
  },
  {
    enunciado: "Entre las garantías que la Ley 43/2010 reconoce al operador designado para asegurar la prestación del servicio postal universal figura:",
    opciones: [
      "La reserva en exclusiva de todos los envíos de correspondencia de hasta cincuenta gramos.",
      "La exención de someterse a la supervisión del organismo regulador postal.",
      "El derecho a la utilización exclusiva de la denominación «Correos», del término «España» y del emblema consistente en una cornamusa en la que figure además la corona de España.",
      "La facultad de fijar libremente los precios de los servicios sujetos a obligaciones de servicio público.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "El artículo 33.a) de la Ley 43/2010 garantiza al operador designado el derecho a la utilización exclusiva de la denominación «Correos», del término «España», del emblema consistente en una cornamusa en la que figure además la corona de España, o de cualquier otro signo que lo identifique o identifique el carácter de los servicios que preste en tal ámbito.",
    mnemotecnia: "Art. 33.a) = 'treinta y tres, la marca es mía': nombre 'Correos', 'España' y el cuerno (cornamusa) con corona, en exclusiva.",
    dificultad: 2,
  },
  {
    enunciado: "Conforme a la Ley 43/2010, los precios de los servicios postales prestados bajo régimen de obligaciones de servicio público deberán ser:",
    opciones: [
      "Uniformes e idénticos a los de los servicios prestados en libre competencia.",
      "Los que resulten de la subasta anual convocada por el órgano regulador.",
      "Asequibles, transparentes y no discriminatorios, y fijarse teniendo en cuenta los costes reales del servicio.",
      "Fijados libremente por el operador designado sin ningún control administrativo.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "El artículo 34.1 de la Ley 43/2010 dispone que los precios de los servicios postales prestados bajo régimen de obligaciones de servicio público deberán ser asequibles, transparentes y no discriminatorios y fijarse teniendo en cuenta los costes reales del servicio, de modo que ofrezcan incentivos para la prestación eficiente del mismo.",
    mnemotecnia: "Art. 34.1 = las tres T-A-N del precio del SPU: Transparente, Asequible, No discriminatorio.",
    dificultad: 1,
  },
  {
    enunciado: "Para prestar servicios postales incluidos en el ámbito del servicio postal universal, la Ley 43/2010 exige a los operadores:",
    opciones: [
      "La mera presentación de una declaración responsable previa al inicio de la actividad.",
      "Una autorización administrativa singular.",
      "Una concesión administrativa otorgada por subasta pública.",
      "La simple inscripción en el registro mercantil correspondiente.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El artículo 42 de la Ley 43/2010 exige autorización administrativa singular para la ejecución de cualesquiera prestaciones en relación con los servicios incluidos en el ámbito del servicio postal universal, en los términos definidos en el artículo 21.1; en cambio, el artículo 40.1 reserva la declaración responsable para quienes pretendan prestar servicios postales no incluidos en dicho ámbito.",
    mnemotecnia: "Art. 42 va con el 40: declaración responsable (art. 40, fuera del SPU) vs autorización singular (art. 42, dentro del SPU).",
    dificultad: 2,
  },
  {
    enunciado: "De acuerdo con la Ley 43/2010, la supervisión y regulación del mercado postal corresponde a:",
    opciones: [
      "La Comisión Nacional del Sector Postal, organismo cuyas funciones son ejercidas actualmente por la Comisión Nacional de los Mercados y la Competencia (CNMC).",
      "El propio operador designado, mediante autorregulación sectorial.",
      "El Tribunal de Cuentas, dentro de sus funciones fiscalizadoras.",
      "La Agencia Española de Protección de Datos.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El artículo 50 de la Ley 43/2010 configura como Autoridad Nacional de Reglamentación Postal al Gobierno, a los órganos superiores y directivos del ministerio competente y a la Comisión Nacional del Sector Postal, atribuyendo en su apartado 2 a esta última la supervisión y regulación del mercado postal. Las funciones de aquella Comisión fueron asumidas posteriormente por la Comisión Nacional de los Mercados y la Competencia, por lo que las referencias legales al organismo regulador postal deben entenderse hechas a la CNMC.",
    mnemotecnia: "Art. 50 = 'medio siglo de regulador': nació como Comisión Nacional del Sector Postal y hoy es la CNMC.",
    dificultad: 2,
  },
  {
    enunciado: "Según el cuadro sancionador de la Ley 43/2010, las infracciones muy graves se sancionan con multa de:",
    opciones: [
      "8.001 a 80.000 euros.",
      "200 a 8.000 euros.",
      "80.001 a 400.000 euros.",
      "400.001 a 1.000.000 de euros.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "El artículo 62.1 de la Ley 43/2010 establece que las infracciones leves se sancionarán con multa de 200 a 8.000 euros, las graves con multa de 8.001 a 80.000 euros y las muy graves con multa de 80.001 a 400.000 euros.",
    mnemotecnia: "Art. 62.1 = escalera de ceros: leve 200-8.000 € / grave 8.001-80.000 € / muy grave 80.001-400.000 € (cada tramo añade un cero).",
    dificultad: 3,
  },
  {
    enunciado: "Conforme a la Ley 43/2010, los plazos de prescripción de las infracciones postales son:",
    opciones: [
      "Cinco años las muy graves, tres años las graves y un año las leves.",
      "Tres años las muy graves, dos años las graves y seis meses las leves.",
      "Dos años las muy graves, un año las graves y tres meses las leves.",
      "Cuatro años todas ellas, con independencia de su calificación.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El artículo 68.2 de la Ley 43/2010 fija el plazo de prescripción de las infracciones en tres años para las muy graves, dos años para las graves y seis meses para las leves, computándose desde el día en que la infracción se hubiera cometido.",
    mnemotecnia: "Art. 68.2 = cuenta atrás 3-2-0,5: muy grave 3 años, grave 2 años, leve 6 meses de prescripción.",
    dificultad: 3,
  },

  // ===== PARTE B · Conocimiento operativo y comercial =====
  {
    enunciado: "La Sociedad Estatal Correos y Telégrafos, S.A., S.M.E., en cuanto a su naturaleza empresarial, se caracteriza por:",
    opciones: [
      "Ser una sociedad mercantil estatal cuyo capital pertenece al sector público a través de la Sociedad Estatal de Participaciones Industriales (SEPI).",
      "Ser una entidad de derecho privado participada mayoritariamente por capital extranjero.",
      "Ser un organismo autónomo integrado en la Administración General del Estado sin personalidad jurídica propia.",
      "Ser una fundación del sector público sin ánimo de lucro.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "Correos es una sociedad anónima mercantil estatal de capital íntegramente público, adscrita al sector público empresarial a través de la SEPI. Esa configuración explica que actúe en el mercado con forma societaria y en régimen de competencia, y al mismo tiempo asuma las obligaciones de servicio público propias del operador al que el Estado ha encomendado el servicio postal universal.",
    mnemotecnia: "Correos = empresa con traje de empresa pero dueño el Estado (vía SEPI): compite en el mercado y carga con el servicio universal.",
    dificultad: 1,
  },
  {
    enunciado: "Desde el punto de vista operativo, ¿cuál es la diferencia esencial entre una carta ordinaria y una carta certificada?",
    opciones: [
      "La carta certificada solo puede depositarse en buzones de la vía pública y la ordinaria únicamente en oficina.",
      "La carta certificada deja constancia registrada del depósito y de la entrega al destinatario, mientras que la ordinaria se deposita en el buzón domiciliario sin registro individualizado.",
      "La carta ordinaria admite mayor peso que la certificada.",
      "La carta certificada no requiere franqueo por tratarse de un servicio obligatorio.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "La diferencia operativa está en la trazabilidad y en la prueba: el envío certificado se registra en la admisión, genera un resguardo y su entrega se documenta con la firma o identificación de quien lo recibe. La carta ordinaria, en cambio, sigue un circuito de tratamiento masivo y se deposita en el buzón domiciliario sin dejar constancia individual de la entrega.",
    mnemotecnia: "Certificada = 'con recibo y firma', ordinaria = 'al buzón y adiós': la primera deja rastro, la segunda no.",
    dificultad: 1,
  },
  {
    enunciado: "En la clasificación comercial de los envíos, ¿qué añade la modalidad urgente respecto del régimen ordinario?",
    opciones: [
      "Convierte automáticamente el envío en certificado con valor declarado.",
      "Amplía el peso máximo admisible del envío.",
      "Da al envío un tratamiento y un encaminamiento prioritarios dentro de la red, con el objetivo de reducir el plazo de entrega respecto del régimen ordinario.",
      "Exime al remitente de indicar la dirección postal completa del destinatario.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "La modalidad urgente no cambia la naturaleza del envío ni sus límites de admisión: actúa sobre el proceso, dando prioridad en la clasificación, el transporte y el reparto para acortar el plazo respecto del circuito ordinario. Es una modalidad de tratamiento, compatible con otras como el certificado.",
    mnemotecnia: "Urgente = 'acelera, no agranda': da prioridad en el camino, no cambia peso ni naturaleza del envío.",
    dificultad: 1,
  },
  {
    enunciado: "El acuse de recibo, como servicio adicional asociado a un envío certificado, tiene por finalidad:",
    opciones: [
      "Devolver al remitente un documento acreditativo de la entrega firmado por el destinatario o persona autorizada.",
      "Asegurar económicamente el contenido del envío por el importe que declare el remitente.",
      "Permitir al destinatario rechazar el envío sin abrirlo.",
      "Garantizar la entrega en un plazo inferior al ordinario.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El acuse de recibo es un servicio adicional que se contrata sobre un envío registrado y cuya función es devolver al remitente la prueba documental de la entrega, con la firma o identificación de quien la recibe. No cubre el valor del contenido, que es la función del valor declarado, ni acelera el plazo, que es función de las modalidades urgentes.",
    mnemotecnia: "Acuse de recibo = la foto de la firma que vuelve a casa del remitente, como prueba de entrega.",
    dificultad: 2,
  },
  {
    enunciado: "La publicidad directa, como categoría de producto postal, se caracteriza operativamente por:",
    opciones: [
      "Tratarse siempre de envíos registrados con prueba de entrega individualizada.",
      "Consistir en comunicaciones comerciales difundidas de forma masiva y homogénea a un colectivo de destinatarios, con un tratamiento diferenciado del de la correspondencia individual.",
      "Ser un servicio reservado en exclusiva a las Administraciones Públicas.",
      "Admitirse únicamente en envíos superiores a veinte kilogramos.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "La publicidad directa es un producto de comunicación comercial masiva: el remitente entrega grandes volúmenes de piezas homogéneas destinadas a un colectivo amplio, lo que permite un tratamiento industrializado en admisión y reparto y una política comercial distinta de la de la correspondencia individual.",
    mnemotecnia: "Publicidad directa = 'buzoneo a lo grande': lo mismo para muchos destinatarios, no correspondencia individual.",
    dificultad: 2,
  },
  {
    enunciado: "En la clasificación de productos postales, ¿cuál es el criterio que distingue la línea de correspondencia de la línea de paquetería?",
    opciones: [
      "La nacionalidad del remitente.",
      "El momento del día en que se deposita el envío.",
      "El hecho de que el envío se pague por adelantado o a la entrega.",
      "La naturaleza del objeto enviado: la correspondencia vehicula comunicaciones y documentos, mientras que la paquetería transporta mercancías y bienes físicos.",
    ],
    respuestaCorrecta: 3,
    justificacionIa: "La distinción comercial básica es el contenido y, con él, todo el proceso asociado: la correspondencia transporta comunicaciones y documentación, con formatos planos y tratamiento altamente automatizado, mientras que la paquetería mueve mercancías, con formatos volumétricos, manipulación específica y una operativa de entrega distinta.",
    mnemotecnia: "Correspondencia = letras que se leen; paquetería = cosas que se usan.",
    dificultad: 1,
  },
  {
    enunciado: "Citypaq es, dentro de las soluciones logísticas de Correos:",
    opciones: [
      "Una red de terminales automatizados de paquetería (taquillas inteligentes) donde el usuario puede recoger y depositar sus paquetes.",
      "Una aplicación de seguimiento de envíos internacionales exclusiva para grandes clientes.",
      "Un servicio de transporte de mercancías paletizadas entre centros logísticos.",
      "Un sistema de franqueo digital para empresas emisoras de correspondencia masiva.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "Citypaq es la red de taquillas automatizadas de Correos: el usuario elige un terminal como dirección de entrega o de devolución y recoge o deposita el paquete cuando le conviene, mediante un código. Es una solución de entrega desatendida pensada para evitar las entregas fallidas por ausencia en el domicilio.",
    mnemotecnia: "Citypaq = taquilla inteligente en la ciudad: recógelo tú, cuando quieras, con un código.",
    dificultad: 1,
  },
  {
    enunciado: "En el ámbito del comercio electrónico, ¿qué se entiende por logística inversa?",
    opciones: [
      "El transporte de mercancías entre los centros de tratamiento del operador antes de su reparto final.",
      "La entrega de envíos en un horario distinto del habitual a petición del destinatario.",
      "El flujo de retorno de los productos desde el cliente final hacia el vendedor, que comprende devoluciones, cambios y recogidas.",
      "El sistema de facturación diferida aplicado a los clientes con contrato.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "La logística inversa es el flujo de mercancía en sentido contrario al habitual: del cliente final de vuelta al vendedor. Engloba devoluciones, cambios, recogidas a domicilio o en punto de conveniencia y su reintegración al circuito del remitente, y es un servicio clave para el comercio electrónico, donde la devolución forma parte de la experiencia de compra.",
    mnemotecnia: "Logística inversa = la marcha atrás del paquete: del cliente de vuelta a la tienda (devoluciones, cambios, recogidas).",
    dificultad: 1,
  },
  {
    enunciado: "En la cadena logística postal, la denominada última milla se refiere a:",
    opciones: [
      "El tramo de transporte entre el país de origen y el país de destino en los envíos transfronterizos.",
      "El tramo final del proceso, desde el último centro de distribución hasta la entrega al destinatario.",
      "La distancia máxima que puede recorrer un cartero en su jornada laboral.",
      "El proceso de clasificación automatizada de la correspondencia en los centros de tratamiento.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "La última milla es el tramo final de la cadena, desde el centro de distribución hasta el destinatario. Es el más atomizado y el que concentra mayor coste unitario, porque implica multitud de paradas y entregas individuales, y por eso es donde se concentran las soluciones alternativas como los puntos de recogida o las taquillas automatizadas.",
    mnemotecnia: "Última milla = el tramo final y el más caro del reparto: del centro de distribución a tu puerta.",
    dificultad: 2,
  },
  {
    enunciado: "Las oficinas colaboradoras y los puntos de conveniencia cumplen en la red postal la función de:",
    opciones: [
      "Sustituir íntegramente a la red de oficinas propias en las capitales de provincia.",
      "Asumir las funciones de supervisión del mercado postal en el ámbito local.",
      "Gestionar exclusivamente los envíos de publicidad directa de grandes clientes.",
      "Ampliar la capilaridad y los horarios de atención de la red, actuando como puntos de admisión y de recogida de envíos próximos al usuario.",
    ],
    respuestaCorrecta: 3,
    justificacionIa: "Los puntos de conveniencia y las oficinas colaboradoras son establecimientos de terceros integrados en la red que permiten admitir y entregar envíos. Su valor operativo está en la capilaridad y en la amplitud horaria: acercan el servicio al usuario y amplían las franjas de recogida sin necesidad de abrir nuevas oficinas propias.",
    mnemotecnia: "Puntos de conveniencia = 'Correos donde ya vas': más cerca, más horario, sin abrir oficina nueva.",
    dificultad: 2,
  },
  {
    enunciado: "Desde el punto de vista de la eficiencia del reparto, la principal ventaja de la entrega en punto de recogida frente a la entrega domiciliaria es que:",
    opciones: [
      "Elimina la necesidad de que el remitente franquee el envío.",
      "Agrupa varias entregas en una única parada y reduce las entregas fallidas por ausencia del destinatario.",
      "Permite prescindir del seguimiento informatizado del envío.",
      "Traslada al destinatario la responsabilidad legal sobre el contenido del envío.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "La entrega en punto de recogida consolida en una sola parada lo que en domicilio serían muchas entregas dispersas, y evita el principal motivo de fracaso del reparto, que es la ausencia del destinatario. Esa consolidación reduce los kilómetros por envío, las reentregas y el coste de la última milla.",
    mnemotecnia: "Punto de recogida = muchas entregas en una sola parada: menos reentregas por ausencia.",
    dificultad: 2,
  },
  {
    enunciado: "La distinción operativa entre zonas de reparto urbanas y rurales responde principalmente a:",
    opciones: [
      "Que en las zonas rurales no existe obligación alguna de prestar el servicio.",
      "Que en las zonas urbanas los envíos se entregan siempre en oficina.",
      "Que la dispersión de la población y la distancia entre domicilios obligan a organizar el reparto con medios y secciones distintas a las urbanas, aunque el servicio deba garantizarse igualmente.",
      "Que las zonas rurales solo admiten envíos de correspondencia y no de paquetería.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "La diferencia es de organización, no de derecho al servicio: en el medio rural la baja densidad y las largas distancias entre puntos de entrega obligan a diseñar secciones de reparto más extensas y con medios de locomoción distintos. La cobertura debe garantizarse igualmente, y es precisamente esa asimetría de costes la que justifica el carácter de obligación de servicio público.",
    mnemotecnia: "Zona rural = más kilómetros, mismos derechos: cambia el medio de reparto, no la obligación de servicio.",
    dificultad: 2,
  },
  {
    enunciado: "El apartado postal es, como modalidad de entrega:",
    opciones: [
      "Un casillero contratado por el usuario en una oficina postal, donde se depositan sus envíos para que los recoja, en lugar de entregarlos en su domicilio.",
      "Un buzón colectivo instalado en el portal de los edificios de viviendas.",
      "Un servicio de custodia temporal de paquetes voluminosos en almacén.",
      "Una dirección electrónica habilitada para recibir notificaciones administrativas.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El apartado postal es un casillero que el usuario contrata en una oficina y que actúa como dirección de destino: los envíos se depositan allí y el titular los recoge cuando le conviene. Es una alternativa a la entrega domiciliaria, habitual en empresas y en usuarios que reciben volúmenes elevados de correspondencia.",
    mnemotecnia: "Apartado postal = tu buzón dentro de la oficina: tú vas a buscarlo, no te lo llevan a casa.",
    dificultad: 1,
  },
  {
    enunciado: "El servicio de reembolso asociado a un envío consiste en:",
    opciones: [
      "Devolver al remitente el importe del franqueo si el envío se entrega fuera de plazo.",
      "Indemnizar al destinatario por el deterioro del contenido.",
      "Condicionar la entrega al cobro previo al destinatario de un importe indicado por el remitente, que posteriormente se le abona a este.",
      "Permitir al destinatario devolver el producto sin coste durante un plazo determinado.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "El reembolso es un servicio adicional de cobro: el operador no entrega el envío hasta que el destinatario abona la cantidad fijada por el remitente, y después liquida ese importe al remitente. Es un servicio de valor añadido vinculado a la venta a distancia, distinto de la indemnización y del aseguramiento del contenido.",
    mnemotecnia: "Reembolso = 'paga y te lo doy': se cobra al destinatario antes de entregar y luego se liquida al remitente.",
    dificultad: 2,
  },
  {
    enunciado: "El burofax se utiliza habitualmente en el tráfico jurídico y empresarial porque:",
    opciones: [
      "Es el envío más económico dentro de la línea de correspondencia.",
      "Permite acreditar de forma fehaciente el contenido de la comunicación remitida, además de su entrega al destinatario.",
      "Garantiza la entrega en cualquier país sin necesidad de dirección postal.",
      "Sustituye a la firma electrónica en los trámites con la Administración.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "Lo que distingue al burofax de un certificado ordinario es que, además de acreditar la entrega, permite certificar el texto exactamente remitido. Por eso se emplea en comunicaciones con efectos jurídicos, como requerimientos, reclamaciones o preavisos, donde interesa poder probar qué se dijo y no solo que se entregó.",
    mnemotecnia: "Burofax = lo que se dice queda escrito y probado: acredita contenido Y entrega, ideal para el tráfico jurídico.",
    dificultad: 2,
  },
  {
    enunciado: "El sistema de seguimiento y localización (tracking) de envíos permite fundamentalmente:",
    opciones: [
      "Conocer el contenido declarado del envío a cualquier persona que disponga del código.",
      "Modificar el importe del franqueo una vez admitido el envío.",
      "Consultar el estado y los hitos por los que ha pasado un envío registrado, desde su admisión hasta su entrega, mediante un código identificativo.",
      "Sustituir la firma del destinatario en el momento de la entrega.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "El seguimiento se apoya en un código único asociado al envío que se lee en cada hito del proceso (admisión, tratamiento, salida a reparto, entrega). Su función es dar visibilidad del estado del envío al remitente y al destinatario; no revela el contenido ni sustituye la acreditación de la entrega.",
    mnemotecnia: "Tracking = el código cuenta el viaje del envío, no revela su contenido.",
    dificultad: 1,
  },
  {
    enunciado: "Cuando un envío registrado no puede entregarse por ausencia del destinatario, la pauta operativa habitual consiste en:",
    opciones: [
      "Devolver el envío al remitente de forma inmediata y sin previo aviso.",
      "Depositar el envío en el buzón domiciliario con independencia de su naturaleza.",
      "Destruir el envío transcurridas veinticuatro horas.",
      "Dejar un aviso de llegada al destinatario y poner el envío a su disposición para su recogida en la oficina correspondiente durante un plazo determinado.",
    ],
    respuestaCorrecta: 3,
    justificacionIa: "Un envío registrado exige acreditar quién lo recibe, de modo que no puede dejarse en el buzón. La práctica operativa es dejar un aviso de llegada que informa al destinatario del intento de entrega y del lugar donde puede recoger el envío, quedando este depositado a su disposición durante un plazo antes de devolverlo al remitente.",
    mnemotecnia: "Sin nadie en casa = aviso de llegada y el envío espera en la oficina durante un plazo antes de devolverse.",
    dificultad: 1,
  },
  {
    enunciado: "El franqueo en destino, como sistema de pago de los servicios postales, se caracteriza porque:",
    opciones: [
      "El coste del envío lo asume el destinatario o el cliente que ha contratado la modalidad, en lugar de pagarlo quien deposita el envío.",
      "El envío se paga íntegramente en el momento del depósito mediante sellos adheridos.",
      "El importe se determina en función de la distancia recorrida por el envío.",
      "Se aplica exclusivamente a los envíos internacionales.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "En el franqueo en destino, quien deposita el envío no paga en el momento de la admisión: el coste lo soporta el cliente destinatario que ha contratado previamente esta modalidad con el operador. Es un sistema pensado para respuestas comerciales, encuestas o devoluciones, donde interesa que el remitente pueda enviar sin desembolso.",
    mnemotecnia: "Franqueo en destino = paga quien recibe, no quien manda.",
    dificultad: 3,
  },
  {
    enunciado: "El giro postal es un servicio que consiste en:",
    opciones: [
      "El transporte urgente de documentación bancaria entre sucursales.",
      "La ordenación de un pago de dinero a favor de una persona, por cuenta y encargo de otra, a través de la red postal.",
      "La reexpedición automática de la correspondencia a una nueva dirección.",
      "La custodia de valores y objetos preciosos en las oficinas postales.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El giro es un servicio de naturaleza financiera prestado a través de la red postal: el imponente entrega una cantidad en una oficina y el operador la pone a disposición del beneficiario. Su interés operativo es que aprovecha la capilaridad de la red postal para hacer llegar dinero a lugares y personas sin necesidad de intermediación bancaria.",
    mnemotecnia: "Giro postal = dinero que viaja como una carta, de un imponente a un beneficiario.",
    dificultad: 2,
  },
  {
    enunciado: "Dentro de las soluciones logísticas para empresas, el almacenamiento y preparación de pedidos (fulfillment) consiste en:",
    opciones: [
      "Asumir la facturación y el cobro de las ventas del comercio electrónico.",
      "Gestionar únicamente el transporte internacional de mercancía paletizada.",
      "Custodiar el inventario del cliente y, ante cada pedido, preparar, embalar y expedir la mercancía, integrando el almacén con la red de distribución.",
      "Diseñar las campañas de publicidad directa del cliente.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "El fulfillment integra el almacén en la cadena de entrega: el operador guarda el stock del cliente y, cuando entra un pedido, lo localiza, lo prepara, lo embala y lo introduce directamente en la red de distribución. Permite al vendedor externalizar toda la operativa física y acortar el tiempo entre la compra y la salida del envío.",
    mnemotecnia: "Fulfillment = el almacén se convierte en tienda: guarda el stock, prepara y despacha cada pedido.",
    dificultad: 3,
  },
  {
    enunciado: "El crecimiento del comercio electrónico ha tenido sobre el negocio postal el siguiente efecto estructural:",
    opciones: [
      "Un aumento sostenido del volumen de correspondencia ordinaria en detrimento de la paquetería.",
      "La desaparición de la obligación de cobertura territorial del servicio postal universal.",
      "La sustitución de la red de reparto por medios exclusivamente digitales.",
      "Un desplazamiento del peso del negocio desde la correspondencia, en descenso por la digitalización, hacia la paquetería y los servicios logísticos.",
    ],
    respuestaCorrecta: 3,
    justificacionIa: "La digitalización de las comunicaciones ha reducido de forma sostenida el volumen de correspondencia física, mientras que la compra en línea ha impulsado la paquetería y los servicios logísticos asociados. Ese cambio de mix explica la reorientación comercial de los operadores postales hacia la paquetería, los puntos de recogida y la logística de devoluciones.",
    mnemotecnia: "E-commerce = menos cartas, más cajas: el negocio postal gira de la correspondencia hacia la paquetería.",
    dificultad: 2,
  },
  {
    enunciado: "Los servicios de entrega flexible que permiten al destinatario modificar el día, el lugar o la forma de recepción de un envío responden operativamente a la necesidad de:",
    opciones: [
      "Reducir las entregas fallidas y las reentregas, que encarecen el tramo final del reparto.",
      "Eliminar el registro informático de los envíos para simplificar el proceso.",
      "Aumentar el peso máximo admisible de los paquetes.",
      "Trasladar al remitente la obligación de transportar el envío hasta el domicilio.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "Cada intento de entrega fallido obliga a repetir la visita o a gestionar un depósito en oficina, duplicando el coste del tramo más caro de la cadena. Permitir al destinatario reprogramar la fecha, cambiar a un punto de recogida o autorizar otra forma de entrega aumenta la tasa de éxito en el primer intento y reduce esas repeticiones.",
    mnemotecnia: "Entrega flexible = tú decides cuándo y dónde: menos reintentos, menos coste en la última milla.",
    dificultad: 3,
  },
]
;
