// Bancos de preguntas para los temas 2, 5, 10 y 11 de la oposición de
// Correos (Reparto y Atención al Cliente). Cada pregunta se apoya
// exclusivamente en los hechos ya redactados en los bloques de contenido
// de ese tema (ver content/correos-temario.ts y content/correos-temario-2.ts,
// tal y como los referencia seed.ts en seedTemarioCorreos), sin añadir cifras,
// artículos ni afirmaciones normativas que no figuren ya en ese texto.

export const CORREOS_TEMA2_PREGUNTAS = [
  {
    enunciado: "Dentro del servicio de paquetería de Correos, las distintas modalidades se diferencian, entre otros criterios, por:",
    opciones: [
      "El plazo de entrega (estándar, urgente, en el mismo día en determinadas zonas) y el nivel de seguimiento del envío.",
      "El tipo de vehículo utilizado exclusivamente para el transporte entre centros.",
      "La comunidad autónoma de origen del envío únicamente.",
      "El idioma en que figure la etiqueta del paquete.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El contenido del tema señala que la paquetería tiene modalidades diferenciadas por plazo de entrega (estándar, urgente, en el mismo día en determinadas zonas) y por el nivel de seguimiento (con o sin número de seguimiento, con o sin prueba de entrega firmada).",
    mnemotecnia: "Paquetería se distingue por CUÁNDO llega (plazo) y CUÁNTO se ve (seguimiento).",
    dificultad: 1,
  },
  {
    enunciado: "Según el proceso logístico descrito para un envío de paquetería, ¿en qué orden se suceden sus fases?",
    opciones: [
      "Transporte entre centros, admisión, clasificación, reparto final.",
      "Admisión, clasificación en el centro de tratamiento, transporte entre centros, reparto final.",
      "Clasificación, reparto final, admisión, transporte entre centros.",
      "Reparto final, transporte entre centros, admisión, clasificación.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El texto describe que un envío de paquetería recorre: admisión (en oficina o mediante recogida a domicilio), clasificación en el centro de tratamiento correspondiente según destino, transporte entre centros, y reparto final por parte del personal de reparto en la unidad de distribución de destino.",
    mnemotecnia: "ACTR: Admisión, Clasificación, Transporte, Reparto.",
    dificultad: 1,
  },
  {
    enunciado: "El transporte de un envío de paquetería entre centros de tratamiento puede realizarse:",
    opciones: [
      "Únicamente por carretera, sea cual sea la distancia o la urgencia.",
      "Por carretera, tren o avión, según la distancia y la urgencia del envío.",
      "Exclusivamente por vía aérea cuando el envío es certificado.",
      "Solo mediante puntos de conveniencia, sin transporte intermedio.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El contenido indica que el transporte entre centros se realiza por carretera, tren o avión según la distancia y la urgencia del envío.",
    mnemotecnia: "Carretera, tren o avión: el medio lo deciden distancia y prisa.",
    dificultad: 1,
  },
  {
    enunciado: "Los puntos de conveniencia (oficinas, comercios colaboradores, taquillas automáticas como Citypaq) cumplen la función de:",
    opciones: [
      "Sustituir por completo la red de oficinas propias de Correos.",
      "Permitir a la persona destinataria recoger su envío en el momento y lugar que prefiera, reduciendo los intentos de entrega fallidos y ampliando el horario efectivo de disponibilidad.",
      "Encargarse exclusivamente de la clasificación automatizada de la correspondencia.",
      "Fijar las tarifas postales aplicables a cada zona.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El texto explica que los puntos de conveniencia permiten a la persona destinataria recoger su envío en el momento y lugar que prefiera, reduciendo los intentos de entrega fallidos y ampliando el horario efectivo de disponibilidad del servicio.",
    mnemotecnia: "Punto de conveniencia = recoges TÚ, cuando TÚ quieras: menos fallos, más horario.",
    dificultad: 1,
  },
  {
    enunciado: "Según el tema, la denominada 'última milla' se define como:",
    opciones: [
      "El tramo final de la cadena logística, desde el centro de distribución hasta la puerta de la persona destinataria.",
      "El primer tramo de la cadena, desde la admisión del envío hasta su clasificación.",
      "El trayecto internacional entre distintos operadores postales.",
      "El tiempo que tarda el remitente en preparar el embalaje.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El contenido define la última milla como el tramo final de la cadena logística, desde el centro de distribución hasta la puerta de la persona destinataria, señalando que es habitualmente el tramo más costoso y complejo de toda la cadena.",
    mnemotecnia: "Última milla = el último paso, el más caro y el más difícil.",
    dificultad: 1,
  },
  {
    enunciado: "El crecimiento del comercio electrónico ha convertido la gestión eficiente de la última milla en un área estratégica mediante, entre otras herramientas:",
    opciones: [
      "La eliminación de los puntos de conveniencia.",
      "Rutas optimizadas, puntos de recogida alternativos y franjas horarias de entrega.",
      "La supresión del seguimiento de envíos para reducir costes.",
      "La reducción del número de centros de tratamiento automatizado.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El texto indica que el crecimiento del comercio electrónico ha convertido la gestión eficiente de la última milla (rutas optimizadas, puntos de recogida alternativos, franjas horarias de entrega) en un área estratégica para cualquier operador postal.",
    mnemotecnia: "Última milla estratégica = rutas + puntos alternativos + franjas horarias.",
    dificultad: 2,
  },
  {
    enunciado: "El seguimiento (tracking) de un envío de paquetería permite a remitente y destinatario conocer en cada momento:",
    opciones: [
      "El contenido exacto declarado por el remitente.",
      "La fase en que se encuentra el envío: admisión, en tránsito entre centros, en reparto o entregado.",
      "El nombre del conductor que transporta el envío.",
      "El precio final que pagará el destinatario por el envío.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El contenido explica que el seguimiento permite conocer en cada momento la fase en la que se encuentra un envío: admisión, en tránsito entre centros, en reparto o entregado.",
    mnemotecnia: "Tracking cuenta la FASE del viaje, no el contenido del paquete.",
    dificultad: 1,
  },
  {
    enunciado: "Cada escaneo del código de un envío en un punto de control (al recogerlo, al clasificarlo, al cargarlo en un vehículo, al entregarlo) genera:",
    opciones: [
      "Una nueva tarifa postal para ese envío.",
      "Automáticamente un evento visible en el sistema de seguimiento, accesible normalmente a través de la web o la aplicación móvil de Correos.",
      "La anulación del número de seguimiento anterior.",
      "Un cambio automático de destinatario.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El texto señala que cada escaneo del código del envío en un punto de control genera automáticamente un evento visible en el sistema de seguimiento, accesible normalmente a través de la web o la aplicación móvil de Correos introduciendo el número de envío.",
    mnemotecnia: "Cada escaneo = un evento nuevo visible en el tracking.",
    dificultad: 1,
  },
  {
    enunciado: "Cuando un envío de paquetería no puede entregarse en el primer intento por ausencia del destinatario, el protocolo descrito en el tema NO incluye:",
    opciones: [
      "Dejar un aviso indicando cómo y dónde recoger el envío.",
      "Reintentar la entrega en un momento posterior según la política vigente.",
      "Derivar el envío a un punto de conveniencia cercano.",
      "Destruir el envío de forma inmediata sin más trámite.",
    ],
    respuestaCorrecta: 3,
    justificacionIa: "El tema describe que ante la ausencia del destinatario el personal de reparto deja un aviso, reintenta la entrega o deriva el envío a un punto de conveniencia, y que si tras los intentos previstos sigue sin poder entregarse, se devuelve al remitente; la destrucción inmediata no figura como parte de ese protocolo.",
    mnemotecnia: "Sin nadie en casa: aviso, reintento o punto de conveniencia — nunca destrucción inmediata.",
    dificultad: 2,
  },
  {
    enunciado: "Los contratos de paquetería que suscriben los grandes clientes de comercio electrónico suelen incluir acuerdos de nivel de servicio (SLA) que fijan compromisos como:",
    opciones: [
      "El color corporativo del embalaje.",
      "El plazo máximo de entrega o el porcentaje admisible de incidencias, con penalizaciones si el operador no los cumple.",
      "El número exacto de oficinas que debe visitar el cliente al mes.",
      "La obligación del cliente de clasificar manualmente sus propios envíos.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El contenido explica que los contratos de los grandes clientes de comercio electrónico incluyen habitualmente acuerdos de nivel de servicio (SLA) que fijan compromisos concretos, como el plazo máximo de entrega o el porcentaje admisible de incidencias, y penalizaciones si el operador no los cumple.",
    mnemotecnia: "SLA = plazo + % incidencias + penalización si se incumple.",
    dificultad: 2,
  },
];

export const CORREOS_TEMA5_PREGUNTAS = [
  {
    enunciado: "En los centros de tratamiento automatizado, los lectores ópticos de caracteres (OCR) se emplean para:",
    opciones: [
      "Leer direcciones postales y códigos postales, clasificando grandes volúmenes de correspondencia a alta velocidad.",
      "Pesar automáticamente cada envío antes de su admisión.",
      "Firmar digitalmente en nombre del destinatario.",
      "Fijar el precio del franqueo de cada envío.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema explica que los centros de tratamiento automatizado usan lectores ópticos de caracteres (OCR) para leer direcciones postales y códigos postales, clasificando grandes volúmenes de correspondencia a alta velocidad.",
    mnemotecnia: "OCR = ojos rápidos que leen dirección y código postal.",
    dificultad: 1,
  },
  {
    enunciado: "¿Qué ocurre con los envíos que la máquina de clasificación no puede leer con fiabilidad?",
    opciones: [
      "Se devuelven automáticamente al remitente sin más trámite.",
      "Se derivan a clasificación manual (o a un puesto de clasificación manual, donde una persona operadora introduce o corrige los datos necesarios).",
      "Quedan retenidos indefinidamente en el centro de tratamiento.",
      "Se destruyen por motivos de seguridad.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El texto indica que los envíos que la máquina no puede leer con fiabilidad se derivan a clasificación manual, y que en un centro de tratamiento automatizado esos casos se derivan a un puesto de clasificación manual donde una persona operadora introduce o corrige los datos necesarios para completar el encaminamiento.",
    mnemotecnia: "Si el OCR no lee bien, entra la persona a corregir a mano.",
    dificultad: 1,
  },
  {
    enunciado: "El código postal español, tal como se describe en el tema, está compuesto por:",
    opciones: [
      "3 dígitos: uno para la provincia y dos para la zona de reparto.",
      "5 dígitos: los dos primeros identifican la provincia y los tres restantes concretan la zona de reparto dentro de ella.",
      "5 dígitos: los tres primeros identifican la provincia y los dos restantes la calle.",
      "4 dígitos, iguales en todo el territorio nacional.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El tema señala que el código postal español tiene 5 dígitos: los dos primeros identifican la provincia, y los tres restantes concretan la zona de reparto dentro de ella.",
    mnemotecnia: "5 dígitos: 2 de provincia + 3 de zona (2+3=5).",
    dificultad: 1,
  },
  {
    enunciado: "El código postal es, según el tema, la referencia principal que usan los sistemas automatizados de clasificación para:",
    opciones: [
      "Calcular el peso máximo admisible de cada envío.",
      "Encaminar cada envío a su unidad de distribución correspondiente.",
      "Determinar el precio del seguro del envío.",
      "Identificar al remitente del envío.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El texto indica que el código postal es la referencia principal que usan los sistemas automatizados de clasificación para encaminar cada envío a su unidad de distribución correspondiente.",
    mnemotecnia: "Código postal = la brújula automática hacia la unidad de destino.",
    dificultad: 1,
  },
  {
    enunciado: "El reparto, como fase final del proceso postal, incluye la gestión de incidencias habituales como:",
    opciones: [
      "Únicamente los envíos con valor declarado.",
      "Ausencia del destinatario, direcciones erróneas o incompletas, y devoluciones al remitente cuando el envío no puede entregarse tras los intentos previstos.",
      "Exclusivamente los retrasos en la clasificación automatizada.",
      "Solo las incidencias relacionadas con el franqueo insuficiente.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El tema describe el reparto como la entrega física de cada envío a su destinatario, e incluye la gestión de incidencias habituales: ausencia del destinatario, direcciones erróneas o incompletas, y devoluciones al remitente cuando el envío no puede entregarse tras los intentos previstos.",
    mnemotecnia: "Reparto = entrega + gestionar ausencias, direcciones malas y devoluciones.",
    dificultad: 1,
  },
  {
    enunciado: "Según el tema, el personal de reparto organiza y optimiza sus rutas según:",
    opciones: [
      "La zona asignada que conoce el propio personal de reparto.",
      "Un sorteo diario entre las distintas unidades de distribución.",
      "El orden alfabético de las calles, sin más criterio.",
      "La decisión exclusiva de cada destinatario.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema indica que el reparto es la fase final, organizada por rutas que el personal de reparto conoce y optimiza según la zona asignada.",
    mnemotecnia: "Rutas = zona conocida + optimización propia del reparto.",
    dificultad: 1,
  },
  {
    enunciado: "El personal de reparto usa habitualmente una terminal móvil (PDA o smartphone corporativo) para:",
    opciones: [
      "Fijar el precio del franqueo de cada envío entregado.",
      "Escanear cada envío en el momento de la entrega, registrar la firma o incidencia digitalmente, y actualizar en tiempo real el estado del envío en el sistema de seguimiento.",
      "Clasificar automáticamente la correspondencia antes de salir a reparto.",
      "Sustituir el código postal en el encaminamiento de los envíos.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El tema explica que el personal de reparto usa una terminal móvil para escanear cada envío en el momento de la entrega, registrar la firma o incidencia digitalmente, y actualizar en tiempo real el estado del envío en el sistema de seguimiento.",
    mnemotecnia: "Terminal móvil = escanea, firma digital y actualiza en tiempo real.",
    dificultad: 1,
  },
  {
    enunciado: "Un centro de tratamiento automatizado combina, según el tema, los siguientes elementos:",
    opciones: [
      "Cintas transportadoras, lectores ópticos de caracteres (OCR) y sistemas de clasificación mecánica.",
      "Únicamente personal de clasificación manual sin apoyo tecnológico.",
      "Vehículos de reparto y terminales móviles exclusivamente.",
      "Oficinas colaboradoras y puntos de conveniencia.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema describe que un centro de tratamiento automatizado combina cintas transportadoras, lectores ópticos de caracteres (OCR) y sistemas de clasificación mecánica para dirigir cada envío hacia la salida correspondiente a su destino.",
    mnemotecnia: "Centro automatizado = cintas + OCR + clasificación mecánica.",
    dificultad: 2,
  },
  {
    enunciado: "En la planificación de rutas de reparto, cada unidad de reparto tiene en cuenta, entre otros factores:",
    opciones: [
      "El volumen habitual de envíos de cada zona y las franjas horarias en que es más probable encontrar al destinatario.",
      "Únicamente la distancia entre la unidad de reparto y la capital de provincia.",
      "El número de reclamaciones presentadas ante la CNMC.",
      "El tipo de vehículo utilizado en el transporte entre centros.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema señala que la planificación de rutas tiene en cuenta el volumen habitual de envíos de cada zona, las franjas horarias en que es más probable encontrar al destinatario y herramientas informáticas de optimización que recalculan el orden de entrega más eficiente.",
    mnemotecnia: "Rutas se planifican con volumen + franjas horarias + optimización informática.",
    dificultad: 2,
  },
  {
    enunciado: "Los escaneos que el personal de reparto realiza en el momento de la entrega o de la incidencia alimentan indicadores de calidad de servicio como:",
    opciones: [
      "El porcentaje de entregas en primer intento, el tiempo medio de tránsito desde la admisión hasta la entrega, o las incidencias por zona.",
      "El número de puntos de conveniencia disponibles en cada provincia.",
      "El precio del franqueo aplicado a cada envío.",
      "La antigüedad del personal de reparto en la empresa.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema indica que cada escaneo alimenta indicadores de calidad de servicio: porcentaje de entregas en primer intento, tiempo medio de tránsito desde la admisión hasta la entrega, o incidencias por zona, permitiendo detectar rutas o centros con peor desempeño y priorizar allí las mejoras operativas.",
    mnemotecnia: "Indicadores de calidad: % primer intento + tiempo medio + incidencias por zona.",
    dificultad: 2,
  },
];

export const CORREOS_TEMA10_PREGUNTAS = [
  {
    enunciado: "Según el tema, la Ley 43/2010, del servicio postal universal, de los derechos de los usuarios y del mercado postal, regula el sector en España, entre otras cosas:",
    opciones: [
      "Definiendo el servicio postal universal, designando a Correos como operador encargado de prestarlo y estableciendo los derechos de las personas usuarias frente a cualquier operador postal, no solo Correos.",
      "Fijando exclusivamente el organigrama interno de la Sociedad Estatal Correos y Telégrafos.",
      "Regulando únicamente los envíos internacionales, sin efecto sobre los envíos nacionales.",
      "Estableciendo el régimen retributivo del personal de reparto.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema indica que la Ley 43/2010 define el servicio postal universal (prestaciones mínimas garantizadas a toda la población), designa a Correos como operador encargado de prestarlo, y establece los derechos de las personas usuarias frente a cualquier operador postal, no solo Correos.",
    mnemotecnia: "Ley 43/2010: define SPU + designa a Correos + protege al usuario frente a CUALQUIER operador.",
    dificultad: 1,
  },
  {
    enunciado: "Respecto a la estructura de Correos, el tema señala que la empresa se organiza en torno a:",
    opciones: [
      "Una red de oficinas de atención al público, centros de tratamiento y unidades de reparto, coordinadas por estructuras de gestión provincial y autonómica bajo la dirección corporativa central.",
      "Delegaciones independientes sin coordinación central alguna.",
      "Un único centro de tratamiento nacional que atiende a todo el territorio.",
      "Filiales privadas independientes en cada comunidad autónoma.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema describe que Correos se organiza en torno a una red de oficinas de atención al público, centros de tratamiento y unidades de reparto distribuidas por todo el territorio, coordinadas por estructuras de gestión provincial y autonómica bajo la dirección corporativa central.",
    mnemotecnia: "Estructura Correos: oficinas + centros + unidades de reparto, coordinados provincial/autonómico bajo dirección central.",
    dificultad: 1,
  },
  {
    enunciado: "Como sociedad estatal, el accionista de Correos es:",
    opciones: [
      "El Estado, a través de la Sociedad Estatal de Participaciones Industriales (SEPI).",
      "Un consorcio de bancos privados españoles.",
      "Cada comunidad autónoma, en proporción a su población.",
      "Los propios trabajadores de la empresa, mediante un plan de participación accionarial.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema indica que, como sociedad estatal, el accionista de Correos es el Estado a través de la SEPI, y que su actividad se somete a las obligaciones de transparencia y buen gobierno del sector público.",
    mnemotecnia: "Correos: accionista = Estado, vía SEPI.",
    dificultad: 1,
  },
  {
    enunciado: "Entre los derechos que el tema atribuye a toda persona usuaria del servicio postal figura:",
    opciones: [
      "La inviolabilidad y el secreto de los envíos postales, protegido constitucionalmente.",
      "La fijación libre y unilateral de las tarifas por parte del usuario.",
      "La designación del operador postal encargado del servicio universal.",
      "El derecho a inspeccionar el contenido de los envíos ajenos con autorización verbal.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema señala que toda persona usuaria del servicio postal tiene derecho, entre otros, a la inviolabilidad y el secreto de los envíos postales, protegido constitucionalmente, a una calidad de servicio mínima garantizada y a presentar reclamaciones.",
    mnemotecnia: "Derecho del usuario nº1: inviolabilidad y secreto, con respaldo constitucional.",
    dificultad: 1,
  },
  {
    enunciado: "Si una reclamación de un usuario postal no queda resuelta satisfactoriamente ante el propio operador, el tema indica que puede dirigirse a:",
    opciones: [
      "La Secretaría de Estado de Telecomunicaciones e Infraestructuras Digitales.",
      "El Tribunal de Cuentas.",
      "La Agencia Española de Protección de Datos, en todo caso.",
      "El Defensor del Pueblo Europeo.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema establece que la persona usuaria tiene derecho a presentar reclamaciones ante el propio operador y, si no quedan resueltas satisfactoriamente, ante la Secretaría de Estado de Telecomunicaciones e Infraestructuras Digitales.",
    mnemotecnia: "Reclamación sin resolver → Secretaría de Estado de Telecomunicaciones e Infraestructuras Digitales.",
    dificultad: 2,
  },
  {
    enunciado: "El tratamiento de datos personales asociado a los envíos postales (direcciones, datos de contacto, datos de seguimiento) debe cumplir, según el tema:",
    opciones: [
      "El Reglamento General de Protección de Datos (RGPD) y la legislación española de desarrollo, con minimización de datos, conservación limitada y medidas de seguridad adecuadas.",
      "Únicamente las normas internas de Correos, sin referencia a normativa externa.",
      "El Reglamento General de Protección de Datos, pero solo para los envíos internacionales.",
      "La normativa de protección de datos exclusivamente si el envío es certificado.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema indica que el tratamiento de esos datos debe cumplir el RGPD y la legislación española de desarrollo: minimización de datos, conservación limitada al tiempo necesario, y medidas de seguridad adecuadas para evitar accesos no autorizados.",
    mnemotecnia: "Datos postales: RGPD + minimización + conservación limitada + seguridad.",
    dificultad: 2,
  },
  {
    enunciado: "El secreto de las comunicaciones postales, según el tema, se proyecta directamente sobre el artículo:",
    opciones: [
      "18.3 de la Constitución, que garantiza el secreto de las comunicaciones salvo resolución judicial.",
      "35 de la Constitución, relativo al derecho al trabajo.",
      "103 de la Constitución, sobre la Administración Pública.",
      "Ningún artículo constitucional, al tratarse de una cuestión meramente reglamentaria.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema señala que el artículo 18.3 de la Constitución garantiza el secreto de las comunicaciones, salvo resolución judicial, y que ese principio se proyecta directamente sobre la correspondencia postal.",
    mnemotecnia: "Secreto postal = artículo 18.3 CE, salvo resolución judicial.",
    dificultad: 1,
  },
  {
    enunciado: "El personal de Correos que en el ejercicio de sus funciones accede a información sobre remitentes, destinatarios o contenido de los envíos está sujeto a:",
    opciones: [
      "Un deber de confidencialidad reforzado por la garantía constitucional del secreto de las comunicaciones.",
      "Ninguna obligación específica distinta de la de cualquier otro empleado público.",
      "Una obligación de comunicar dicha información a la CNMC de forma periódica.",
      "Un deber de confidencialidad limitado únicamente a los envíos internacionales.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema indica que el personal de Correos que accede a esa información está sujeto a un deber de confidencialidad reforzado por la garantía constitucional del secreto de las comunicaciones.",
    mnemotecnia: "Acceso a datos del envío = confidencialidad reforzada por el secreto constitucional.",
    dificultad: 2,
  },
  {
    enunciado: "La Comisión Nacional de los Mercados y la Competencia (CNMC), en su función de supervisión del sector postal, se encarga de:",
    opciones: [
      "Vigilar que las tarifas del servicio postal universal sean asequibles y no discriminatorias, resolver conflictos entre operadores y usuarios, y vigilar el cumplimiento de las condiciones del servicio universal.",
      "Fijar directamente el salario del personal de reparto.",
      "Sustituir a Correos como operador designado cuando lo estime oportuno.",
      "Diseñar las rutas de reparto de cada unidad de distribución.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema explica que la CNMC supervisa el sector postal español vigilando que las tarifas del servicio postal universal sean asequibles y no discriminatorias, resolviendo conflictos entre operadores postales y entre estos y las personas usuarias, y velando por el cumplimiento de las condiciones bajo las que se presta el servicio universal.",
    mnemotecnia: "CNMC: vigila tarifas + resuelve conflictos + vela por el cumplimiento del SPU.",
    dificultad: 2,
  },
  {
    enunciado: "En cuanto a la responsabilidad del operador postal, el tema señala que los límites de indemnización:",
    opciones: [
      "Son siempre idénticos, con independencia de la modalidad de envío contratada.",
      "Varían según la modalidad contratada: un envío ordinario tiene cobertura mínima, mientras que uno certificado o asegurado permite reclamar una indemnización mayor, proporcional al valor declarado o a las tarifas establecidas.",
      "Solo se aplican a los envíos internacionales.",
      "Los fija libremente el destinatario en el momento de la reclamación.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El tema indica que el operador postal responde ante el remitente o el destinatario por la pérdida, el robo, el deterioro o el retraso injustificado de un envío, con límites de indemnización que varían según la modalidad contratada: un envío ordinario tiene una cobertura mínima, mientras que uno certificado o asegurado permite reclamar una indemnización mayor, proporcional al valor declarado o a las tarifas establecidas para cada modalidad.",
    mnemotecnia: "Ordinario = cobertura mínima; certificado/asegurado = indemnización mayor y proporcional.",
    dificultad: 2,
  },
];

export const CORREOS_TEMA11_PREGUNTAS = [
  {
    enunciado: "La Ley 31/1995, de Prevención de Riesgos Laborales, según el tema, obliga a la empresa a:",
    opciones: [
      "Evaluar los riesgos de cada puesto, planificar la actividad preventiva y formar e informar a la plantilla sobre los riesgos específicos de su trabajo.",
      "Contratar exclusivamente personal con formación universitaria en prevención.",
      "Eliminar por completo cualquier riesgo laboral antes de iniciar la actividad.",
      "Delegar toda la responsabilidad preventiva en cada trabajador de forma individual.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema indica que la Ley 31/1995 establece el marco general de protección de la salud de las personas trabajadoras: obliga a la empresa a evaluar los riesgos de cada puesto, planificar la actividad preventiva y formar e informar a la plantilla sobre los riesgos específicos de su trabajo.",
    mnemotecnia: "Ley 31/1995 = evaluar + planificar + formar e informar.",
    dificultad: 1,
  },
  {
    enunciado: "Entre los riesgos específicos del personal de reparto que menciona el tema se encuentran:",
    opciones: [
      "Accidentes de tráfico (en reparto motorizado), caídas al mismo o distinto nivel, exposición climatológica y sobreesfuerzos por manipulación de cargas.",
      "Exposición a radiaciones ionizantes derivadas de la maquinaria de clasificación.",
      "Riesgos exclusivamente informáticos por el uso de la terminal móvil.",
      "Riesgos derivados únicamente del trato con el público en oficinas.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema señala que el personal de reparto está expuesto a riesgos como accidentes de tráfico (en reparto motorizado), caídas al mismo o distinto nivel, exposición climatológica y sobreesfuerzos por manipulación de cargas.",
    mnemotecnia: "Reparto: tráfico + caídas + clima + sobreesfuerzo.",
    dificultad: 1,
  },
  {
    enunciado: "El personal de clasificación, según el tema, enfrenta principalmente:",
    opciones: [
      "Riesgos ergonómicos derivados de movimientos repetitivos y posturas mantenidas, además de los propios de trabajar cerca de maquinaria de clasificación automatizada.",
      "Riesgos de tráfico equivalentes a los del personal de reparto motorizado.",
      "Riesgos de exposición climatológica extrema, al trabajar siempre al aire libre.",
      "Ningún riesgo relevante, al tratarse de un trabajo administrativo.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema indica que el personal de clasificación enfrenta riesgos ergonómicos derivados de movimientos repetitivos y posturas mantenidas, además de los propios de trabajar cerca de maquinaria de clasificación automatizada.",
    mnemotecnia: "Clasificación: ergonomía (movimiento repetitivo/postura) + cercanía a maquinaria.",
    dificultad: 1,
  },
  {
    enunciado: "Según las pautas básicas de manipulación manual de cargas descritas en el tema, al levantar peso hay que:",
    opciones: [
      "Mantener la espalda recta y flexionar las piernas, acercando la carga al cuerpo y evitando giros bruscos del tronco.",
      "Mantener las piernas rectas y flexionar la espalda para ganar impulso.",
      "Girar el tronco rápidamente para reducir el tiempo de exposición a la carga.",
      "Alejar la carga del cuerpo para proteger la espalda.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema señala que la manipulación manual de cargas debe seguir pautas básicas: mantener la espalda recta y flexionar las piernas al levantar peso, acercar la carga al cuerpo, evitar giros bruscos del tronco con carga y, siempre que sea posible, usar ayudas mecánicas para cargas voluminosas o pesadas.",
    mnemotecnia: "Espalda recta, piernas dobladas, carga cerca, sin giros bruscos.",
    dificultad: 1,
  },
  {
    enunciado: "Para cargas voluminosas o pesadas, el tema recomienda, siempre que sea posible:",
    opciones: [
      "Usar ayudas mecánicas, como carretillas o cintas transportadoras.",
      "Repartir la carga entre el mayor número posible de personas sin formación específica.",
      "Levantarlas siempre de forma manual para evitar depender de maquinaria.",
      "Fraccionar la carga sin ningún criterio de peso o volumen.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema indica que, siempre que sea posible, deben usarse ayudas mecánicas (carretillas, cintas transportadoras) para cargas voluminosas o pesadas.",
    mnemotecnia: "Carga pesada = ayuda mecánica (carretilla, cinta transportadora).",
    dificultad: 1,
  },
  {
    enunciado: "Entre las pautas básicas de primeros auxilios que toda persona trabajadora debe conocer, según el tema, figuran:",
    opciones: [
      "El aviso a los servicios de emergencia, la posición lateral de seguridad y la actuación ante heridas o golpes leves.",
      "La administración de medicación sin supervisión médica.",
      "El diagnóstico médico completo del accidentado antes de avisar a emergencias.",
      "La sustitución del personal sanitario en cualquier circunstancia.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema señala que toda persona trabajadora debe conocer las pautas básicas de primeros auxilios: aviso a los servicios de emergencia, posición lateral de seguridad, y actuación ante heridas o golpes leves.",
    mnemotecnia: "Primeros auxilios básicos: avisar, posición lateral de seguridad, atender heridas leves.",
    dificultad: 1,
  },
  {
    enunciado: "La vigilancia periódica del estado de salud de la plantilla, en función de los riesgos del puesto, tiene según el tema carácter:",
    opciones: [
      "Obligatorio en todo caso, sin excepción alguna.",
      "Voluntario para la persona trabajadora, salvo excepciones tasadas.",
      "Exclusivamente voluntario, sin ninguna excepción posible.",
      "Decidido libremente por cada delegado de prevención.",
    ],
    respuestaCorrecta: 1,
    justificacionIa: "El tema indica que la Ley de Prevención de Riesgos Laborales obliga a la empresa a garantizar a su plantilla una vigilancia periódica de su estado de salud, con carácter voluntario para la persona trabajadora salvo excepciones tasadas.",
    mnemotecnia: "Vigilancia de la salud = voluntaria, PERO con excepciones tasadas.",
    dificultad: 2,
  },
  {
    enunciado: "Entre las excepciones tasadas en que el reconocimiento médico deja de ser voluntario, el tema menciona el caso en que:",
    opciones: [
      "El reconocimiento es imprescindible para evaluar los efectos de las condiciones de trabajo sobre la salud, o para verificar que el estado de salud no constituye un peligro para el propio trabajador, para terceros o para otras personas relacionadas con la empresa.",
      "El trabajador ha solicitado un cambio de turno.",
      "La empresa desea reducir el gasto en servicios médicos.",
      "El comité de seguridad y salud lo solicita sin motivo específico.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema recoge como excepciones tasadas los casos en que el reconocimiento es imprescindible para evaluar los efectos de las condiciones de trabajo sobre la salud, o para verificar que el estado de salud no constituye un peligro para el propio trabajador, para terceros o para otras personas relacionadas con la empresa.",
    mnemotecnia: "Excepción a la voluntariedad: evaluar efectos del trabajo en la salud, o verificar que no hay peligro para nadie.",
    dificultad: 3,
  },
  {
    enunciado: "En la señalización de seguridad descrita en el tema, ¿qué color corresponde a la obligación, como el uso obligatorio de un equipo de protección concreto?",
    opciones: [
      "Rojo.",
      "Amarillo.",
      "Azul.",
      "Verde.",
    ],
    respuestaCorrecta: 2,
    justificacionIa: "El tema indica que el azul se usa para obligación (como el uso obligatorio de un equipo de protección concreto), mientras que el rojo es para prohibición o material de lucha contra incendios, el amarillo para advertencia de peligro y el verde para salvamento o situación de seguridad.",
    mnemotecnia: "Rojo prohíbe, amarillo advierte, azul obliga, verde salva.",
    dificultad: 2,
  },
  {
    enunciado: "Respecto a los delegados de prevención y el comité de seguridad y salud, el tema señala que:",
    opciones: [
      "Los delegados de prevención son elegidos entre y por los propios representantes del personal, y en empresas con un número suficiente de trabajadores se constituye además un comité de seguridad y salud, órgano paritario entre empresa y plantilla.",
      "El comité de seguridad y salud sustituye por completo a los delegados de prevención en todas las empresas.",
      "Los delegados de prevención son nombrados directamente por la dirección de la empresa.",
      "El comité de seguridad y salud está compuesto únicamente por representantes de la empresa.",
    ],
    respuestaCorrecta: 0,
    justificacionIa: "El tema indica que los delegados de prevención son elegidos entre y por los propios representantes del personal, y vigilan el cumplimiento de la normativa preventiva; y que en empresas con un número suficiente de personas trabajadoras se constituye además un comité de seguridad y salud, órgano paritario (representantes de la empresa y de la plantilla a partes iguales).",
    mnemotecnia: "Delegados = elegidos por representantes del personal; comité = paritario, mitad y mitad.",
    dificultad: 2,
  },
];
