// Flashcards de la Constitución Española (BOE-A-1978-31229, texto consolidado).
import type { FlashcardSeed, Grupo } from "./flashcards-normas";

const ce = (
  clave: string,
  articulo: number,
  apartado: string,
  anverso: string,
  reverso: string,
  cita: string,
  grupos: Grupo[],
): FlashcardSeed => ({
  clave: `ce-${clave}`,
  norma: "ce",
  articulo: `Artículo ${articulo}`,
  apartado,
  anverso,
  reverso,
  cita,
  grupos,
});

export const FLASHCARDS_CONSTITUCION: FlashcardSeed[] = [
  // Título preliminar
  ce("1-1", 1, "1.1", "¿Qué valores superiores propugna el ordenamiento jurídico español?",
    "La libertad, la justicia, la igualdad y el pluralismo político.",
    "propugna como valores superiores de su ordenamiento jurídico la libertad, la justicia, la igualdad y el pluralismo político", ["ce"]),
  ce("1-2", 1, "1.2", "¿En quién reside la soberanía nacional?",
    "En el pueblo español, del que emanan los poderes del Estado.",
    "La soberanía nacional reside en el pueblo español, del que emanan los poderes del Estado.", ["ce"]),
  ce("1-3", 1, "1.3", "¿Cuál es la forma política del Estado español?",
    "La Monarquía parlamentaria.",
    "La forma política del Estado español es la Monarquía parlamentaria.", ["ce", "corona"]),
  ce("3-1", 3, "3.1", "¿Qué deber y qué derecho tienen todos los españoles respecto al castellano?",
    "El deber de conocerlo y el derecho a usarlo.",
    "Todos los españoles tienen el deber de conocerla y el derecho a usarla.", ["ce"]),
  ce("4-1", 4, "4.1", "¿Cómo es la bandera de España según la Constitución?",
    "Tres franjas horizontales, roja, amarilla y roja; la amarilla tiene doble anchura que cada una de las rojas.",
    "La bandera de España está formada por tres franjas horizontales, roja, amarilla y roja, siendo la amarilla de doble anchura que cada una de las rojas.", ["ce"]),
  ce("5", 5, "5", "¿Cuál es la capital del Estado?",
    "La villa de Madrid.",
    "La capital del Estado es la villa de Madrid.", ["ce"]),
  ce("6", 6, "6", "¿Qué expresan los partidos políticos y cómo debe ser su estructura interna?",
    "Expresan el pluralismo político, concurren a la formación y manifestación de la voluntad popular y son instrumento fundamental para la participación política. Su estructura interna y funcionamiento deben ser democráticos.",
    "Los partidos políticos expresan el pluralismo político, concurren a la formación y manifestación de la voluntad popular y son instrumento fundamental para la participación política.", ["ce"]),
  ce("8-1", 8, "8.1", "¿Qué misión tienen las Fuerzas Armadas?",
    "Garantizar la soberanía e independencia de España, defender su integridad territorial y el ordenamiento constitucional.",
    "tienen como misión garantizar la soberanía e independencia de España, defender su integridad territorial y el ordenamiento constitucional", ["ce"]),
  ce("9-1", 9, "9.1", "¿A qué están sujetos los ciudadanos y los poderes públicos?",
    "A la Constitución y al resto del ordenamiento jurídico.",
    "Los ciudadanos y los poderes públicos están sujetos a la Constitución y al resto del ordenamiento jurídico.", ["ce", "principios"]),
  ce("9-3", 9, "9.3", "¿Qué principios garantiza la Constitución en su artículo 9.3?",
    "Legalidad, jerarquía normativa, publicidad de las normas, irretroactividad de las disposiciones sancionadoras no favorables o restrictivas de derechos individuales, seguridad jurídica, responsabilidad e interdicción de la arbitrariedad de los poderes públicos.",
    "La Constitución garantiza el principio de legalidad, la jerarquía normativa, la publicidad de las normas, la irretroactividad de las disposiciones sancionadoras no favorables o restrictivas de derechos individuales, la seguridad jurídica, la responsabilidad y la interdicción de la arbitrariedad de los poderes públicos.", ["ce", "principios", "fuentes"]),

  // Título I: derechos y deberes
  ce("10-1", 10, "10.1", "¿Qué es, según el art. 10.1, el fundamento del orden político y de la paz social?",
    "La dignidad de la persona, los derechos inviolables que le son inherentes, el libre desarrollo de la personalidad, el respeto a la ley y a los derechos de los demás.",
    "La dignidad de la persona, los derechos inviolables que le son inherentes, el libre desarrollo de la personalidad, el respeto a la ley y a los derechos de los demás son fundamento del orden político y de la paz social.", ["ce"]),
  ce("12", 12, "12", "¿A qué edad son mayores de edad los españoles?",
    "A los dieciocho años.",
    "Los españoles son mayores de edad a los dieciocho años.", ["ce"]),
  ce("14", 14, "14", "¿Por qué razones prohíbe discriminar el artículo 14?",
    "Por razón de nacimiento, raza, sexo, religión, opinión o cualquier otra condición o circunstancia personal o social.",
    "sin que pueda prevalecer discriminación alguna por razón de nacimiento, raza, sexo, religión, opinión o cualquier otra condición o circunstancia personal o social", ["ce"]),
  ce("17-2", 17, "17.2", "¿Cuánto puede durar como máximo la detención preventiva?",
    "El tiempo estrictamente necesario para las averiguaciones y, en todo caso, 72 horas: después el detenido debe quedar en libertad o a disposición judicial.",
    "en el plazo máximo de setenta y dos horas, el detenido deberá ser puesto en libertad o a disposición de la autoridad judicial", ["ce"]),
  ce("18-2", 18, "18.2", "¿Cuándo se puede entrar o registrar un domicilio?",
    "Con consentimiento del titular o resolución judicial, salvo en caso de flagrante delito.",
    "Ninguna entrada o registro podrá hacerse en él sin consentimiento del titular o resolución judicial, salvo en caso de flagrante delito.", ["ce"]),
  ce("20-5", 20, "20.5", "¿Quién puede acordar el secuestro de publicaciones?",
    "Sólo puede acordarse en virtud de resolución judicial.",
    "Sólo podrá acordarse el secuestro de publicaciones, grabaciones y otros medios de información en virtud de resolución judicial.", ["ce"]),
  ce("21-2", 21, "21.2", "¿Qué requisito tienen las reuniones en lugares de tránsito público y las manifestaciones?",
    "Comunicación previa a la autoridad, que sólo puede prohibirlas si hay razones fundadas de alteración del orden público, con peligro para personas o bienes.",
    "En los casos de reuniones en lugares de tránsito público y manifestaciones se dará comunicación previa a la autoridad, que sólo podrá prohibirlas cuando existan razones fundadas de alteración del orden público, con peligro para personas o bienes.", ["ce"]),
  ce("30-1", 30, "30.1", "¿Qué derecho y deber recoge el artículo 30.1?",
    "El derecho y el deber de los españoles de defender a España.",
    "Los españoles tienen el derecho y el deber de defender a España.", ["ce"]),
  ce("35-1", 35, "35.1", "¿Qué reconoce el artículo 35.1 a todos los españoles en relación con el trabajo?",
    "El deber de trabajar y el derecho al trabajo, a la libre elección de profesión u oficio, a la promoción a través del trabajo y a una remuneración suficiente, sin discriminación por razón de sexo.",
    "Todos los españoles tienen el deber de trabajar y el derecho al trabajo, a la libre elección de profesión u oficio, a la promoción a través del trabajo y a una remuneración suficiente para satisfacer sus necesidades y las de su familia", ["ce"]),
  ce("53-2", 53, "53.2", "¿Cómo se tutelan los derechos del art. 14 y de la Sección 1.ª del Capítulo II?",
    "Ante los tribunales ordinarios por un procedimiento basado en los principios de preferencia y sumariedad y, en su caso, mediante recurso de amparo ante el Tribunal Constitucional.",
    "ante los Tribunales ordinarios por un procedimiento basado en los principios de preferencia y sumariedad y, en su caso, a través del recurso de amparo ante el Tribunal Constitucional", ["ce", "tc"]),
  ce("54", 54, "54", "¿Qué es el Defensor del Pueblo según la Constitución?",
    "El alto comisionado de las Cortes Generales, designado por éstas para la defensa de los derechos del Título I; puede supervisar la actividad de la Administración.",
    "como alto comisionado de las Cortes Generales, designado por éstas para la defensa de los derechos comprendidos en este Título", ["ce", "defensor"]),

  // Título II: la Corona
  ce("56-1", 56, "56.1", "¿Qué funciones atribuye el art. 56.1 al Rey?",
    "Es el Jefe del Estado, símbolo de su unidad y permanencia; arbitra y modera el funcionamiento regular de las instituciones y asume la más alta representación del Estado en las relaciones internacionales.",
    "El Rey es el Jefe del Estado, símbolo de su unidad y permanencia, arbitra y modera el funcionamiento regular de las instituciones, asume la más alta representación del Estado español en las relaciones internacionales", ["ce", "corona"]),
  ce("56-3", 56, "56.3", "¿Está sujeta a responsabilidad la persona del Rey?",
    "No: es inviolable y no está sujeta a responsabilidad. Sus actos siempre van refrendados.",
    "La persona del Rey es inviolable y no está sujeta a responsabilidad.", ["ce", "corona"]),
  ce("57-1", 57, "57.1", "¿Qué orden sigue la sucesión en el trono?",
    "Primogenitura y representación; la línea anterior a las posteriores; en la misma línea, el grado más próximo; en el mismo grado, el varón a la mujer; y en el mismo sexo, la persona de más edad.",
    "seguirá el orden regular de primogenitura y representación, siendo preferida siempre la línea anterior a las posteriores; en la misma línea, el grado más próximo al más remoto; en el mismo grado, el varón a la mujer, y en el mismo sexo, la persona de más edad a la de menos", ["corona"]),
  ce("57-2", 57, "57.2", "¿Qué dignidad tiene el heredero de la Corona?",
    "La de Príncipe de Asturias y los demás títulos vinculados tradicionalmente al sucesor de la Corona.",
    "tendrá la dignidad de Príncipe de Asturias y los demás títulos vinculados tradicionalmente al sucesor de la Corona de España", ["corona"]),
  ce("59-2", 59, "59.2", "Si las Cortes reconocen la inhabilitación del Rey, ¿quién ejerce la Regencia?",
    "El Príncipe heredero, si es mayor de edad. Si no lo es, la Regencia se ejerce como prevé el art. 59.1 hasta que lo sea.",
    "entrará a ejercer inmediatamente la Regencia el Príncipe heredero de la Corona, si fuere mayor de edad", ["corona"]),
  ce("64-1", 64, "64.1", "¿Quién refrenda los actos del Rey?",
    "El Presidente del Gobierno y, en su caso, los Ministros competentes. La propuesta y el nombramiento del Presidente del Gobierno y la disolución del art. 99 los refrenda el Presidente del Congreso.",
    "Los actos del Rey serán refrendados por el Presidente del Gobierno y, en su caso, por los Ministros competentes.", ["corona"]),

  // Título III: las Cortes Generales
  ce("66-2", 66, "66.2", "¿Qué funciones ejercen las Cortes Generales?",
    "La potestad legislativa del Estado, aprueban sus Presupuestos, controlan la acción del Gobierno y las demás competencias que les atribuya la Constitución.",
    "Las Cortes Generales ejercen la potestad legislativa del Estado, aprueban sus Presupuestos, controlan la acción del Gobierno y tienen las demás competencias que les atribuya la Constitución.", ["cortes"]),
  ce("66-3", 66, "66.3", "¿Son inviolables las Cortes Generales?",
    "Sí, las Cortes Generales son inviolables.",
    "Las Cortes Generales son inviolables.", ["cortes"]),
  ce("67-2", 67, "67.2", "¿Están ligados por mandato imperativo los miembros de las Cortes Generales?",
    "No.",
    "Los miembros de las Cortes Generales no estarán ligados por mandato imperativo.", ["cortes"]),
  ce("68-1", 68, "68.1", "¿Cuántos Diputados puede tener el Congreso según la Constitución?",
    "Un mínimo de 300 y un máximo de 400.",
    "El Congreso se compone de un mínimo de 300 y un máximo de 400 Diputados", ["cortes"]),
  ce("68-2", 68, "68.2", "¿Cuál es la circunscripción electoral del Congreso?",
    "La provincia. Ceuta y Melilla están representadas cada una por un Diputado.",
    "La circunscripción electoral es la provincia. Las poblaciones de Ceuta y Melilla estarán representadas cada una de ellas por un Diputado.", ["cortes"]),
  ce("68-4", 68, "68.4", "¿Por cuánto tiempo se elige el Congreso?",
    "Por cuatro años. El mandato termina cuatro años después de la elección o el día de la disolución de la Cámara.",
    "El Congreso es elegido por cuatro años. El mandato de los Diputados termina cuatro años después de su elección o el día de la disolución de la Cámara.", ["cortes"]),
  ce("69-1", 69, "69.1", "¿Qué es el Senado según la Constitución?",
    "La Cámara de representación territorial.",
    "El Senado es la Cámara de representación territorial.", ["cortes"]),
  ce("69-2", 69, "69.2", "¿Cuántos Senadores se eligen en cada provincia?",
    "Cuatro, por sufragio universal, libre, igual, directo y secreto.",
    "En cada provincia se elegirán cuatro Senadores por sufragio universal, libre, igual, directo y secreto por los votantes de cada una de ellas", ["cortes"]),
  ce("71-2", 71, "71.2", "¿En qué consiste la inmunidad de Diputados y Senadores?",
    "Durante su mandato sólo pueden ser detenidos en caso de flagrante delito, y no pueden ser inculpados ni procesados sin autorización previa de su Cámara.",
    "Durante el período de su mandato los Diputados y Senadores gozarán asimismo de inmunidad y sólo podrán ser detenidos en caso de flagrante delito. No podrán ser inculpados ni procesados sin la previa autorización de la Cámara respectiva.", ["cortes"]),
  ce("73-1", 73, "73.1", "¿Cuáles son los periodos ordinarios de sesiones de las Cámaras?",
    "Dos al año: de septiembre a diciembre y de febrero a junio.",
    "Las Cámaras se reunirán anualmente en dos períodos ordinarios de sesiones: el primero, de septiembre a diciembre, y el segundo, de febrero a junio.", ["cortes"]),
  ce("81-2", 81, "81.2", "¿Qué mayoría exige aprobar, modificar o derogar una ley orgánica?",
    "Mayoría absoluta del Congreso en una votación final sobre el conjunto del proyecto.",
    "La aprobación, modificación o derogación de las leyes orgánicas exigirá mayoría absoluta del Congreso, en una votación final sobre el conjunto del proyecto.", ["cortes", "fuentes"]),
  ce("86-1", 86, "86.1", "¿En qué caso puede el Gobierno dictar decretos-leyes?",
    "En caso de extraordinaria y urgente necesidad, como disposiciones legislativas provisionales.",
    "En caso de extraordinaria y urgente necesidad, el Gobierno podrá dictar disposiciones legislativas provisionales que tomarán la forma de Decretos-leyes", ["cortes", "fuentes"]),
  ce("86-2", 86, "86.2", "¿En qué plazo debe el Congreso convalidar o derogar un decreto-ley?",
    "En los treinta días siguientes a su promulgación.",
    "en el plazo de los treinta días siguientes a su promulgación", ["cortes", "fuentes"]),
  ce("87-3", 87, "87.3", "¿Cuántas firmas exige la iniciativa legislativa popular?",
    "No menos de 500.000 firmas acreditadas.",
    "En todo caso se exigirán no menos de 500.000 firmas acreditadas.", ["cortes"]),

  // Título IV: Gobierno y Administración
  ce("97", 97, "97", "¿Qué funciones atribuye la Constitución al Gobierno?",
    "Dirige la política interior y exterior, la Administración civil y militar y la defensa del Estado; ejerce la función ejecutiva y la potestad reglamentaria.",
    "El Gobierno dirige la política interior y exterior, la Administración civil y militar y la defensa del Estado. Ejerce la función ejecutiva y la potestad reglamentaria de acuerdo con la Constitución y las leyes.", ["ce", "gobierno"]),
  ce("98-1", 98, "98.1", "¿De quién se compone el Gobierno según la Constitución?",
    "Del Presidente, de los Vicepresidentes, en su caso, de los Ministros y de los demás miembros que establezca la ley.",
    "El Gobierno se compone del Presidente, de los Vicepresidentes, en su caso, de los Ministros y de los demás miembros que establezca la ley.", ["gobierno"]),
  ce("99-3", 99, "99.3", "Si el candidato a Presidente no obtiene la mayoría absoluta, ¿qué ocurre?",
    "Se vota de nuevo la misma propuesta 48 horas después y basta la mayoría simple.",
    "se someterá la misma propuesta a nueva votación cuarenta y ocho horas después de la anterior, y la confianza se entenderá otorgada si obtuviere la mayoría simple", ["gobierno"]),
  ce("99-5", 99, "99.5", "¿Qué pasa si en dos meses desde la primera votación de investidura ningún candidato obtiene la confianza?",
    "El Rey disuelve ambas Cámaras y convoca nuevas elecciones, con el refrendo del Presidente del Congreso.",
    "el Rey disolverá ambas Cámaras y convocará nuevas elecciones con el refrendo del Presidente del Congreso", ["gobierno"]),
  ce("101-1", 101, "101.1", "¿Cuándo cesa el Gobierno?",
    "Tras las elecciones generales, por pérdida de la confianza parlamentaria o por dimisión o fallecimiento de su Presidente.",
    "El Gobierno cesa tras la celebración de elecciones generales, en los casos de pérdida de la confianza parlamentaria previstos en la Constitución, o por dimisión o fallecimiento de su Presidente.", ["gobierno"]),
  ce("103-1", 103, "103.1", "¿Con qué principios actúa la Administración Pública según el art. 103.1?",
    "Sirve con objetividad los intereses generales y actúa conforme a los principios de eficacia, jerarquía, descentralización, desconcentración y coordinación, con sometimiento pleno a la ley y al Derecho.",
    "La Administración Pública sirve con objetividad los intereses generales y actúa de acuerdo con los principios de eficacia, jerarquía, descentralización, desconcentración y coordinación, con sometimiento pleno a la ley y al Derecho.", ["ce", "principios", "gobierno", "age"]),
  ce("103-3", 103, "103.3", "¿Con qué principios se accede a la función pública según la Constitución?",
    "Con los principios de mérito y capacidad.",
    "el acceso a la función pública de acuerdo con los principios de mérito y capacidad", ["gobierno", "personal"]),

  // Título V: relaciones entre el Gobierno y las Cortes
  ce("108", 108, "108", "¿Ante quién responde el Gobierno de su gestión política?",
    "Responde solidariamente ante el Congreso de los Diputados.",
    "El Gobierno responde solidariamente en su gestión política ante el Congreso de los Diputados.", ["relaciones"]),
  ce("112", 112, "112", "¿Qué mayoría necesita la cuestión de confianza para entenderse otorgada?",
    "La mayoría simple de los Diputados.",
    "La confianza se entenderá otorgada cuando vote a favor de la misma la mayoría simple de los Diputados.", ["relaciones"]),
  ce("113-1", 113, "113.1", "¿Qué mayoría exige la moción de censura?",
    "La mayoría absoluta del Congreso.",
    "mediante la adopción por mayoría absoluta de la moción de censura", ["relaciones"]),
  ce("113-2", 113, "113.2", "¿Quién puede proponer una moción de censura y qué debe incluir?",
    "Al menos la décima parte de los Diputados, y debe incluir un candidato a la Presidencia del Gobierno.",
    "La moción de censura deberá ser propuesta al menos por la décima parte de los Diputados, y habrá de incluir un candidato a la Presidencia del Gobierno.", ["relaciones"]),
  ce("116-2", 116, "116.2", "¿Por cuánto tiempo puede declarar el Gobierno el estado de alarma sin autorización del Congreso?",
    "Por un máximo de quince días, dando cuenta al Congreso; la prórroga necesita su autorización.",
    "por un plazo máximo de quince días, dando cuenta al Congreso de los Diputados, reunido inmediatamente al efecto y sin cuya autorización no podrá ser prorrogado dicho plazo", ["relaciones"]),
  ce("116-3", 116, "116.3", "¿Cuánto puede durar el estado de excepción?",
    "No más de treinta días, prorrogables por otro plazo igual con los mismos requisitos. Lo declara el Gobierno previa autorización del Congreso.",
    "no podrá exceder de treinta días, prorrogables por otro plazo igual, con los mismos requisitos", ["relaciones"]),

  // Título VI: Poder Judicial
  ce("117-1", 117, "117.1", "¿De dónde emana la justicia y en nombre de quién se administra?",
    "Emana del pueblo y se administra en nombre del Rey por Jueces y Magistrados independientes, inamovibles, responsables y sometidos únicamente al imperio de la ley.",
    "La justicia emana del pueblo y se administra en nombre del Rey por Jueces y Magistrados integrantes del poder judicial, independientes, inamovibles, responsables y sometidos únicamente al imperio de la ley.", ["judicial"]),
  ce("122-3", 122, "122.3", "¿Cómo está compuesto el Consejo General del Poder Judicial?",
    "Por el Presidente del Tribunal Supremo, que lo preside, y veinte miembros nombrados por el Rey por cinco años.",
    "El Consejo General del Poder Judicial estará integrado por el Presidente del Tribunal Supremo, que lo presidirá, y por veinte miembros nombrados por el Rey por un período de cinco años.", ["judicial"]),
  ce("123-1", 123, "123.1", "¿Qué posición tiene el Tribunal Supremo?",
    "Con jurisdicción en toda España, es el órgano jurisdiccional superior en todos los órdenes, salvo en materia de garantías constitucionales.",
    "El Tribunal Supremo, con jurisdicción en toda España, es el órgano jurisdiccional superior en todos los órdenes, salvo lo dispuesto en materia de garantías constitucionales.", ["judicial"]),
  ce("124-4", 124, "124.4", "¿Cómo se nombra al Fiscal General del Estado?",
    "Lo nombra el Rey, a propuesta del Gobierno, oído el Consejo General del Poder Judicial.",
    "El Fiscal General del Estado será nombrado por el Rey, a propuesta del Gobierno, oído el Consejo General del Poder Judicial.", ["judicial"]),

  // Título VII: Economía y Hacienda
  ce("128-1", 128, "128.1", "¿A qué está subordinada toda la riqueza del país?",
    "Al interés general, en sus distintas formas y sea cual sea su titularidad.",
    "Toda la riqueza del país en sus distintas formas y sea cual fuere su titularidad está subordinada al interés general.", ["economia"]),
  ce("134-2", 134, "134.2", "¿Qué características tienen los Presupuestos Generales del Estado según la Constitución?",
    "Son anuales, incluyen la totalidad de los gastos e ingresos del sector público estatal y consignan el importe de los beneficios fiscales que afecten a los tributos del Estado.",
    "Los Presupuestos Generales del Estado tendrán carácter anual, incluirán la totalidad de los gastos e ingresos del sector público estatal y en ellos se consignará el importe de los beneficios fiscales que afecten a los tributos del Estado.", ["economia", "presupuesto"]),
  ce("134-3", 134, "134.3", "¿Con qué antelación debe presentar el Gobierno los Presupuestos ante el Congreso?",
    "Al menos tres meses antes de que expiren los del año anterior.",
    "al menos tres meses antes de la expiración de los del año anterior", ["economia", "presupuesto"]),
  ce("134-4", 134, "134.4", "¿Qué ocurre si la Ley de Presupuestos no se aprueba antes del primer día del ejercicio?",
    "Se prorrogan automáticamente los Presupuestos del ejercicio anterior hasta que se aprueben los nuevos.",
    "se considerarán automáticamente prorrogados los Presupuestos del ejercicio anterior hasta la aprobación de los nuevos", ["economia", "presupuesto"]),
  ce("136-1", 136, "136.1", "¿Qué es el Tribunal de Cuentas?",
    "El supremo órgano fiscalizador de las cuentas y de la gestión económica del Estado y del sector público. Depende directamente de las Cortes Generales.",
    "El Tribunal de Cuentas es el supremo órgano fiscalizador de las cuentas y de la gestión económica de Estado, así como del sector público.", ["economia", "presupuesto"]),

  // Título VIII: organización territorial
  ce("137", 137, "137", "¿Cómo se organiza territorialmente el Estado?",
    "En municipios, provincias y las Comunidades Autónomas que se constituyan; todas tienen autonomía para gestionar sus intereses.",
    "El Estado se organiza territorialmente en municipios, en provincias y en las Comunidades Autónomas que se constituyan. Todas estas entidades gozan de autonomía para la gestión de sus respectivos intereses.", ["territorial"]),
  ce("140", 140, "140", "¿Cómo se eligen los Concejales?",
    "Por los vecinos del municipio, mediante sufragio universal, igual, libre, directo y secreto.",
    "Los Concejales serán elegidos por los vecinos del municipio mediante sufragio universal, igual, libre, directo y secreto", ["territorial"]),
  ce("141-1", 141, "141.1", "¿Qué es la provincia según la Constitución?",
    "Una entidad local con personalidad jurídica propia, formada por la agrupación de municipios y división territorial para cumplir las actividades del Estado.",
    "La provincia es una entidad local con personalidad jurídica propia, determinada por la agrupación de municipios y división territorial para el cumplimiento de las actividades del Estado.", ["territorial"]),
  ce("145-1", 145, "145.1", "¿Se admite la federación de Comunidades Autónomas?",
    "No, en ningún caso.",
    "En ningún caso se admitirá la federación de Comunidades Autónomas.", ["territorial"]),
  ce("155-1", 155, "155.1", "Si una Comunidad Autónoma no cumple sus obligaciones constitucionales, ¿qué puede hacer el Gobierno?",
    "Tras requerir al Presidente de la Comunidad sin ser atendido, y con la aprobación por mayoría absoluta del Senado, adoptar las medidas necesarias para obligarla al cumplimiento forzoso.",
    "con la aprobación por mayoría absoluta del Senado, podrá adoptar las medidas necesarias para obligar a aquélla al cumplimiento forzoso de dichas obligaciones", ["territorial"]),

  // Título IX: Tribunal Constitucional
  ce("159-1", 159, "159.1", "¿Cuántos miembros tiene el Tribunal Constitucional y quién los propone?",
    "Doce, nombrados por el Rey: cuatro a propuesta del Congreso y cuatro del Senado (por 3/5), dos del Gobierno y dos del Consejo General del Poder Judicial.",
    "El Tribunal Constitucional se compone de 12 miembros nombrados por el Rey; de ellos, cuatro a propuesta del Congreso por mayoría de tres quintos de sus miembros; cuatro a propuesta del Senado, con idéntica mayoría; dos a propuesta del Gobierno, y dos a propuesta del Consejo General del Poder Judicial.", ["tc"]),
  ce("159-3", 159, "159.3", "¿Por cuánto tiempo se designan los miembros del Tribunal Constitucional?",
    "Por nueve años, y se renuevan por terceras partes cada tres.",
    "Los miembros del Tribunal Constitucional serán designados por un período de nueve años y se renovarán por terceras partes cada tres.", ["tc"]),
  ce("160", 160, "160", "¿Quién nombra al Presidente del Tribunal Constitucional y por cuánto tiempo?",
    "El Rey, entre sus miembros y a propuesta del Tribunal en pleno, por tres años.",
    "El Presidente del Tribunal Constitucional será nombrado entre sus miembros por el Rey, a propuesta del mismo Tribunal en pleno y por un período de tres años.", ["tc"]),
  ce("162-1", 162, "162.1.a", "¿Quién puede interponer el recurso de inconstitucionalidad?",
    "El Presidente del Gobierno, el Defensor del Pueblo, 50 Diputados, 50 Senadores, los órganos colegiados ejecutivos de las Comunidades Autónomas y, en su caso, sus Asambleas.",
    "el Presidente del Gobierno, el Defensor del Pueblo, 50 Diputados, 50 Senadores, los órganos colegiados ejecutivos de las Comunidades Autónomas y, en su caso, las Asambleas de las mismas", ["tc"]),

  // Título X: reforma constitucional
  ce("166", 166, "166", "¿Quién tiene la iniciativa de reforma constitucional?",
    "Los sujetos de los apartados 1 y 2 del art. 87 (Gobierno, Congreso, Senado y Asambleas de las Comunidades Autónomas). No cabe iniciativa popular.",
    "La iniciativa de reforma constitucional se ejercerá en los términos previstos en los apartados 1 y 2 del artículo 87.", ["reforma"]),
  ce("167-1", 167, "167.1", "¿Qué mayoría exige la reforma constitucional por el procedimiento ordinario?",
    "Tres quintos de cada una de las Cámaras.",
    "Los proyectos de reforma constitucional deberán ser aprobados por una mayoría de tres quintos de cada una de las Cámaras.", ["reforma"]),
  ce("167-3", 167, "167.3", "¿Cuándo se somete a referéndum una reforma por el procedimiento ordinario?",
    "Cuando lo solicite, en los quince días siguientes a su aprobación, una décima parte de los miembros de cualquiera de las Cámaras.",
    "cuando así lo soliciten, dentro de los quince días siguientes a su aprobación, una décima parte de los miembros de cualquiera de las Cámaras", ["reforma"]),
  ce("168-1", 168, "168.1", "¿Qué reformas exigen el procedimiento agravado del art. 168?",
    "La revisión total, o una parcial que afecte al Título preliminar, a la Sección 1.ª del Capítulo II del Título I o al Título II.",
    "Cuando se propusiere la revisión total de la Constitución o una parcial que afecte al Título preliminar, al Capítulo segundo, Sección primera del Título I, o al Título II", ["reforma"]),
  ce("169", 169, "169", "¿Cuándo no puede iniciarse una reforma constitucional?",
    "En tiempo de guerra o mientras esté vigente alguno de los estados del art. 116 (alarma, excepción o sitio).",
    "No podrá iniciarse la reforma constitucional en tiempo de guerra o de vigencia de alguno de los estados previstos en el artículo 116.", ["reforma"]),
];
