// Flashcards de leyes y reglamentos (textos consolidados del BOE).
import type { ClaveNorma, FlashcardSeed, Grupo } from "./flashcards-normas";

const de =
  (norma: ClaveNorma, prefijo: string) =>
  (
    clave: string,
    articulo: string | number,
    apartado: string,
    anverso: string,
    reverso: string,
    cita: string,
    grupos: Grupo[],
  ): FlashcardSeed => ({
    clave: `${prefijo}-${clave}`,
    norma,
    articulo: typeof articulo === "number" ? `Artículo ${articulo}` : `Artículo ${articulo}`,
    apartado,
    anverso,
    reverso,
    cita,
    grupos,
  });

const lotc = de("lotc", "lotc");
const lodp = de("lodp", "lodp");
const gob = de("gobierno", "l50");
const l39 = de("l39", "l39");
const l40 = de("l40", "l40");
const ebep = de("trebep", "ebep");
const lcsp = de("lcsp", "lcsp");
const lgp = de("lgp", "lgp");
const postal = de("postal", "postal");
const datos = de("lopdgdd", "lopd");
const prl = de("lprl", "lprl");
const conf = de("confianza", "l6");
const ens = de("ens", "ens");

export const FLASHCARDS_LEYES: FlashcardSeed[] = [
  // ===== LO 2/1979, del Tribunal Constitucional =====
  lotc("1", "primero", "1.1", "¿Qué posición tiene el Tribunal Constitucional según su Ley Orgánica?",
    "Es el intérprete supremo de la Constitución, independiente de los demás órganos constitucionales y sometido sólo a la Constitución y a su Ley Orgánica.",
    "El Tribunal Constitucional, como intérprete supremo de la Constitución, es independiente de los demás órganos constitucionales y está sometido sólo a la Constitución y a la presente Ley Orgánica.", ["tc"]),
  lotc("1-2", "primero", "1.2", "¿Qué ámbito territorial tiene la jurisdicción del Tribunal Constitucional?",
    "Es único en su orden y extiende su jurisdicción a todo el territorio nacional.",
    "Es único en su orden y extiende su jurisdicción a todo el territorio nacional.", ["tc"]),
  lotc("6", "sexto", "6.1", "¿En qué formaciones actúa el Tribunal Constitucional?",
    "En Pleno, en Sala o en Sección.",
    "El Tribunal Constitucional actúa en Pleno, en Sala o en Sección.", ["tc"]),
  lotc("7", "séptimo", "7.1", "¿Cuántas Salas tiene el Tribunal Constitucional y cómo se componen?",
    "Dos Salas, cada una de seis Magistrados nombrados por el Tribunal en Pleno.",
    "El Tribunal Constitucional consta de dos Salas. Cada Sala está compuesta por seis Magistrados nombrados por el Tribunal en Pleno.", ["tc"]),
  lotc("33", "treinta y tres", "33.1", "¿En qué plazo se interpone el recurso de inconstitucionalidad?",
    "En tres meses desde la publicación de la ley, disposición o acto con fuerza de ley impugnado.",
    "El recurso de inconstitucionalidad se formulará dentro del plazo de tres meses a partir de la publicación de la Ley, disposición o acto con fuerza de Ley impugnado", ["tc"]),
  lotc("43", "cuarenta y tres", "43.2", "¿Plazo del recurso de amparo contra actos del Gobierno o de la Administración?",
    "Veinte días desde la notificación de la resolución del previo proceso judicial.",
    "El plazo para interponer el recurso de amparo constitucional será el de los veinte días siguientes a la notificación de la resolución recaída en el previo proceso judicial.", ["tc"]),
  lotc("44", "cuarenta y cuatro", "44.2", "¿Plazo del recurso de amparo contra actos u omisiones de un órgano judicial?",
    "Treinta días desde la notificación de la resolución recaída en el proceso judicial.",
    "El plazo para interponer el recurso de amparo será de 30 días, a partir de la notificación de la resolución recaída en el proceso judicial.", ["tc"]),

  // ===== LO 3/1981, del Defensor del Pueblo =====
  lodp("1", "primero", "1", "¿Qué es el Defensor del Pueblo según su Ley Orgánica?",
    "El alto comisionado de las Cortes Generales designado por éstas para defender los derechos del Título I de la Constitución, para lo que puede supervisar la actividad de la Administración.",
    "El Defensor del Pueblo es el alto comisionado de las Cortes Generales designado por éstas para la defensa de los derechos comprendidos en el Título I de la Constitución, a cuyo efecto podrá supervisar la actividad de la Administración", ["defensor"]),
  lodp("2-1", "segundo", "2.1", "¿Por cuánto tiempo se elige al Defensor del Pueblo?",
    "Por las Cortes Generales, para un periodo de cinco años.",
    "El Defensor del Pueblo será elegido por las Cortes Generales para un periodo de cinco años", ["defensor"]),
  lodp("2-4", "segundo", "2.4", "¿Qué mayorías se necesitan para designar al Defensor del Pueblo?",
    "Tres quintos del Congreso y, en un máximo de veinte días, ratificación por la misma mayoría del Senado.",
    "Será designado quien obtuviese una votación favorable de las tres quintas partes de los miembros del Congreso y posteriormente, en un plazo máximo de veinte días, fuese ratificado por esta misma mayoría del Senado.", ["defensor"]),
  lodp("3", "tercero", "3", "¿Quién puede ser elegido Defensor del Pueblo?",
    "Cualquier español mayor de edad en pleno disfrute de sus derechos civiles y políticos.",
    "Podrá ser elegido Defensor del Pueblo cualquier español mayor de edad que se encuentre en el pleno disfrute de sus derechos civiles y políticos.", ["defensor"]),
  lodp("6", "sexto", "6.1", "¿Está sujeto el Defensor del Pueblo a mandato imperativo?",
    "No; no recibe instrucciones de ninguna autoridad y actúa con autonomía y según su criterio.",
    "El Defensor del Pueblo no estará sujeto a mandato imperativo alguno. No recibirá instrucciones de ninguna Autoridad.", ["defensor"]),
  lodp("8", "octavo", "8.1", "¿Quién auxilia al Defensor del Pueblo?",
    "Un Adjunto Primero y un Adjunto Segundo, en los que puede delegar y que le sustituyen por su orden.",
    "El Defensor del Pueblo estará auxiliado por un Adjunto Primero y un Adjunto Segundo", ["defensor"]),
  lodp("15", "quince", "15.1", "¿En qué plazo debe presentarse una queja al Defensor del Pueblo?",
    "En el plazo máximo de un año desde que se conocieron los hechos. Es gratuita y no exige abogado ni procurador.",
    "en el plazo máximo de un año, contado a partir del momento en que tuviera conocimiento de los hechos objeto de la misma", ["defensor"]),
  lodp("15-2", "quince", "15.2", "¿Tiene coste acudir al Defensor del Pueblo? ¿Hace falta abogado?",
    "Es gratuito para el interesado y no es preceptiva la asistencia de letrado ni de procurador.",
    "Todas las actuaciones del Defensor del Pueblo son gratuitas para el interesado y no será preceptiva la asistencia de Letrado ni de Procurador.", ["defensor"]),

  // ===== Ley 50/1997, del Gobierno =====
  gob("1-2", 1, "1.2", "¿De quién se compone el Gobierno según la Ley 50/1997?",
    "Del Presidente, del Vicepresidente o Vicepresidentes, en su caso, y de los Ministros.",
    "El Gobierno se compone del Presidente, del Vicepresidente o Vicepresidentes, en su caso, y de los Ministros.", ["gobierno"]),
  gob("1-3", 1, "1.3", "¿En qué órganos se reúnen los miembros del Gobierno?",
    "En Consejo de Ministros y en Comisiones Delegadas del Gobierno.",
    "Los miembros del Gobierno se reúnen en Consejo de Ministros y en Comisiones Delegadas del Gobierno.", ["gobierno"]),
  gob("11", 11, "11", "¿Qué requisitos se exigen para ser miembro del Gobierno?",
    "Ser español, mayor de edad, disfrutar del sufragio activo y pasivo, no estar inhabilitado por sentencia firme y cumplir los requisitos de idoneidad de la Ley 3/2015.",
    "Para ser miembro del Gobierno se requiere ser español, mayor de edad, disfrutar de los derechos de sufragio activo y pasivo", ["gobierno"]),
  gob("21-2", 21, "21.2", "¿Hasta cuándo continúa en funciones el Gobierno cesante?",
    "Hasta la toma de posesión del nuevo Gobierno.",
    "El Gobierno cesante continúa en funciones hasta la toma de posesión del nuevo Gobierno", ["gobierno"]),
  gob("21-3", 21, "21.3", "¿A qué limita su gestión el Gobierno en funciones?",
    "Al despacho ordinario de los asuntos públicos, absteniéndose de otras medidas salvo urgencia o interés general acreditados.",
    "limitará su gestión al despacho ordinario de los asuntos públicos", ["gobierno"]),
  gob("24-1", 24, "24.1.b", "¿Qué forma adoptan las disposiciones y actos atribuidos al Presidente del Gobierno?",
    "La de Reales Decretos del Presidente del Gobierno.",
    "Reales Decretos del Presidente del Gobierno, las disposiciones y actos cuya adopción venga atribuida al Presidente.", ["gobierno"]),

  // ===== Ley 39/2015, del Procedimiento Administrativo Común =====
  l39("11-2", 11, "11.2", "¿Para qué trámites exige la Administración la firma del interesado?",
    "Sólo para formular solicitudes, presentar declaraciones responsables o comunicaciones, interponer recursos, desistir de acciones y renunciar a derechos.",
    "Las Administraciones Públicas sólo requerirán a los interesados el uso obligatorio de firma para", ["procedimiento", "firma"]),
  l39("14-1", 14, "14.1", "¿Pueden las personas físicas elegir cómo se relacionan con la Administración?",
    "Sí, pueden elegir en todo momento si lo hacen por medios electrónicos o no, salvo que estén obligadas a relacionarse electrónicamente.",
    "Las personas físicas podrán elegir en todo momento si se comunican con las Administraciones Públicas para el ejercicio de sus derechos y obligaciones a través de medios electrónicos o no", ["procedimiento"]),
  l39("14-2", 14, "14.2", "¿Están obligadas las personas jurídicas a relacionarse electrónicamente con la Administración?",
    "Sí, el art. 14.2 las incluye entre los sujetos obligados.",
    "Las personas jurídicas.", ["procedimiento", "firma"]),
  l39("21-1", 21, "21.1", "¿Debe la Administración resolver siempre de forma expresa?",
    "Sí: está obligada a dictar resolución expresa y notificarla en todos los procedimientos, cualquiera que sea su forma de iniciación.",
    "La Administración está obligada a dictar resolución expresa y a notificarla en todos los procedimientos cualquiera que sea su forma de iniciación.", ["procedimiento"]),
  l39("21-2", 21, "21.2", "¿Cuál es el plazo máximo que puede fijar una norma para resolver un procedimiento?",
    "Seis meses, salvo que una norma con rango de ley establezca uno mayor o lo prevea el Derecho de la Unión Europea.",
    "Este plazo no podrá exceder de seis meses salvo que una norma con rango de Ley establezca uno mayor o así venga previsto en el Derecho de la Unión Europea.", ["procedimiento"]),
  l39("21-3", 21, "21.3", "Si la norma del procedimiento no fija plazo para resolver, ¿cuál es?",
    "Tres meses.",
    "Cuando las normas reguladoras de los procedimientos no fijen el plazo máximo, éste será de tres meses.", ["procedimiento"]),
  l39("24-1", 24, "24.1", "En un procedimiento iniciado a solicitud del interesado, ¿qué efecto tiene, como regla general, el silencio?",
    "Estimatorio: el interesado puede entender estimada su solicitud por silencio administrativo.",
    "legitima al interesado o interesados para entenderla estimada por silencio administrativo", ["procedimiento"]),
  l39("24-1b", 24, "24.1", "¿Qué efecto tiene el silencio en los procedimientos sobre el derecho de petición?",
    "Desestimatorio.",
    "El silencio tendrá efecto desestimatorio en los procedimientos relativos al ejercicio del derecho de petición, a que se refiere el artículo 29 de la Constitución", ["procedimiento"]),
  l39("24-2e", 24, "24.2", "¿Qué valor tiene la estimación por silencio administrativo?",
    "A todos los efectos, la de acto administrativo que finaliza el procedimiento.",
    "La estimación por silencio administrativo tiene a todos los efectos la consideración de acto administrativo finalizador del procedimiento.", ["procedimiento"]),
  l39("24-3", 24, "24.3.a", "Tras una estimación por silencio, ¿puede la Administración resolver después en sentido contrario?",
    "No: la resolución expresa posterior sólo puede dictarse si es confirmatoria del acto estimado.",
    "En los casos de estimación por silencio administrativo, la resolución expresa posterior a la producción del acto sólo podrá dictarse de ser confirmatoria del mismo.", ["procedimiento"]),
  l39("24-2", 24, "24.2", "¿Qué valor tiene la desestimación por silencio administrativo?",
    "Sólo permite a los interesados interponer el recurso administrativo o contencioso-administrativo que proceda.",
    "La desestimación por silencio administrativo tiene los solos efectos de permitir a los interesados la interposición del recurso administrativo o contencioso-administrativo que resulte procedente.", ["procedimiento"]),
  l39("30-2", 30, "30.2", "Cuando un plazo se fija en días, ¿cómo se computa?",
    "Son días hábiles: se excluyen los sábados, los domingos y los festivos.",
    "cuando los plazos se señalen por días, se entiende que éstos son hábiles, excluyéndose del cómputo los sábados, los domingos y los declarados festivos", ["procedimiento"]),
  l39("30-3", 30, "30.3", "¿Desde qué día se cuentan los plazos expresados en días?",
    "Desde el día siguiente a la notificación o publicación del acto, o a la estimación o desestimación por silencio.",
    "Los plazos expresados en días se contarán a partir del día siguiente a aquel en que tenga lugar la notificación o publicación del acto de que se trate", ["procedimiento"]),
  l39("30-4", 30, "30.4", "Si el plazo se fija en meses, ¿qué día concluye?",
    "El mismo día en que se produjo la notificación, publicación o silencio, en el mes de vencimiento; si no existe ese día, el último del mes.",
    "El plazo concluirá el mismo día en que se produjo la notificación, publicación o silencio administrativo en el mes o el año de vencimiento.", ["procedimiento"]),
  l39("32-1", 32, "32.1", "¿Cuánto puede ampliarse un plazo de oficio o a petición de los interesados?",
    "Hasta la mitad del plazo inicial, si las circunstancias lo aconsejan y no se perjudican derechos de terceros.",
    "una ampliación de los plazos establecidos, que no exceda de la mitad de los mismos", ["procedimiento"]),
  l39("39-1", 39, "39.1", "¿Desde cuándo producen efectos los actos administrativos?",
    "Se presumen válidos y producen efectos desde la fecha en que se dictan, salvo que en ellos se disponga otra cosa.",
    "Los actos de las Administraciones Públicas sujetos al Derecho Administrativo se presumirán válidos y producirán efectos desde la fecha en que se dicten, salvo que en ellos se disponga otra cosa.", ["procedimiento"]),
  l39("40-2", 40, "40.2", "¿En qué plazo debe cursarse la notificación de un acto?",
    "Dentro de los diez días siguientes a la fecha en que se dictó el acto.",
    "Toda notificación deberá ser cursada dentro del plazo de diez días a partir de la fecha en que el acto haya sido dictado", ["procedimiento"]),
  l39("43-2", 43, "43.2", "¿Cuándo se entiende rechazada una notificación electrónica?",
    "Cuando pasan diez días naturales desde su puesta a disposición sin que se acceda a su contenido.",
    "se entenderá rechazada cuando hayan transcurrido diez días naturales desde la puesta a disposición de la notificación sin que se acceda a su contenido", ["procedimiento"]),
  l39("47-1", 47, "47.1.a", "¿Es nulo de pleno derecho un acto que lesiona derechos susceptibles de amparo?",
    "Sí, es una de las causas de nulidad de pleno derecho del art. 47.1.",
    "Los que lesionen los derechos y libertades susceptibles de amparo constitucional.", ["procedimiento"]),
  l39("48-1", 48, "48.1", "¿Qué actos administrativos son anulables?",
    "Los que incurran en cualquier infracción del ordenamiento jurídico, incluida la desviación de poder.",
    "Son anulables los actos de la Administración que incurran en cualquier infracción del ordenamiento jurídico, incluso la desviación de poder.", ["procedimiento"]),
  l39("68-1", 68, "68.1", "Si una solicitud no reúne los requisitos, ¿qué plazo se da para subsanarla?",
    "Diez días; si no se subsana, se tiene por desistido al interesado.",
    "para que, en un plazo de diez días, subsane la falta o acompañe los documentos preceptivos", ["procedimiento"]),
  l39("82-2", 82, "82.2", "¿Qué plazo tienen los interesados en el trámite de audiencia?",
    "No inferior a diez días ni superior a quince.",
    "en un plazo no inferior a diez días ni superior a quince", ["procedimiento"]),
  l39("122-1", 122, "122.1", "¿Cuál es el plazo para interponer el recurso de alzada contra un acto expreso?",
    "Un mes.",
    "El plazo para la interposición del recurso de alzada será de un mes, si el acto fuera expreso.", ["procedimiento"]),
  l39("122-2", 122, "122.2", "¿Cuál es el plazo máximo para resolver y notificar el recurso de alzada?",
    "Tres meses.",
    "El plazo máximo para dictar y notificar la resolución será de tres meses.", ["procedimiento"]),
  l39("124-1", 124, "124.1", "¿Cuál es el plazo para interponer el recurso de reposición contra un acto expreso?",
    "Un mes.",
    "El plazo para la interposición del recurso de reposición será de un mes, si el acto fuera expreso.", ["procedimiento"]),
  l39("124-2", 124, "124.2", "¿Cuál es el plazo máximo para resolver y notificar el recurso de reposición?",
    "Un mes.",
    "El plazo máximo para dictar y notificar la resolución del recurso será de un mes.", ["procedimiento"]),
  l39("128-2", 128, "128.2", "¿Qué límites tienen los reglamentos?",
    "No pueden vulnerar la Constitución ni las leyes, ni regular materias reservadas a las Cortes Generales o a los Parlamentos autonómicos.",
    "Los reglamentos y disposiciones administrativas no podrán vulnerar la Constitución o las leyes ni regular aquellas materias que la Constitución o los Estatutos de Autonomía reconocen de la competencia de las Cortes Generales o de las Asambleas Legislativas de las Comunidades Autónomas.", ["fuentes", "procedimiento"]),
  l39("131", 131, "131", "¿Qué requisito tienen las normas para entrar en vigor y producir efectos?",
    "Publicarse en el diario oficial correspondiente.",
    "habrán de publicarse en el diario oficial correspondiente para que entren en vigor y produzcan efectos jurídicos", ["fuentes", "procedimiento"]),

  // ===== Ley 40/2015, de Régimen Jurídico del Sector Público =====
  l40("3-1", 3, "3.1", "¿Con qué principios actúan las Administraciones Públicas según la Ley 40/2015?",
    "Sirven con objetividad los intereses generales y actúan con eficacia, jerarquía, descentralización, desconcentración y coordinación, con sometimiento pleno a la Constitución, a la Ley y al Derecho.",
    "Las Administraciones Públicas sirven con objetividad los intereses generales y actúan de acuerdo con los principios de eficacia, jerarquía, descentralización, desconcentración y coordinación, con sometimiento pleno a la Constitución, a la Ley y al Derecho.", ["principios", "age", "procedimiento"]),
  l40("8-1", 8, "8.1", "¿Puede un órgano administrativo renunciar a su competencia?",
    "No: la competencia es irrenunciable y la ejercen los órganos que la tienen atribuida como propia, salvo delegación o avocación.",
    "La competencia es irrenunciable y se ejercerá por los órganos administrativos que la tengan atribuida como propia", ["age", "procedimiento"]),
  l40("9-1", 9, "9.1", "¿Puede delegarse una competencia en un órgano que no dependa jerárquicamente del delegante?",
    "Sí, dentro de la misma Administración, aunque no sea jerárquicamente dependiente.",
    "aun cuando no sean jerárquicamente dependientes", ["age", "procedimiento"]),
  l40("9-4", 9, "9.4", "¿A quién se imputan las resoluciones dictadas por delegación?",
    "Se consideran dictadas por el órgano delegante.",
    "se considerarán dictadas por el órgano delegante", ["age", "procedimiento"]),
  l40("10-1", 10, "10.1", "¿Qué es la avocación?",
    "Que los órganos superiores asuman el conocimiento de asuntos que corresponden ordinariamente o por delegación a sus órganos dependientes.",
    "Los órganos superiores podrán avocar para sí el conocimiento de uno o varios asuntos cuya resolución corresponda ordinariamente o por delegación a sus órganos administrativos dependientes", ["age", "procedimiento"]),
  l40("11-1", 11, "11.1", "¿Qué puede ser objeto de encomienda de gestión?",
    "Actividades de carácter material o técnico, por razones de eficacia o si no se tienen los medios técnicos idóneos.",
    "La realización de actividades de carácter material o técnico de la competencia de los órganos administrativos o de las Entidades de Derecho Público podrá ser encomendada a otros órganos o Entidades de Derecho Público", ["age", "procedimiento"]),
  l40("17-2", 17, "17.2", "¿Qué quórum necesita un órgano colegiado para constituirse válidamente?",
    "Presidente y Secretario (o sus suplentes) y al menos la mitad de sus miembros.",
    "la de la mitad, al menos, de sus miembros", ["age", "procedimiento"]),
  l40("23-2a", 23, "23.2.a", "¿Es causa de abstención tener interés personal en el asunto?",
    "Sí.",
    "Tener interés personal en el asunto de que se trate o en otro en cuya resolución pudiera influir la de aquél", ["procedimiento"]),
  l40("23-2b", 23, "23.2.b", "¿Hasta qué grado de parentesco obliga a abstenerse?",
    "Consanguinidad dentro del cuarto grado y afinidad dentro del segundo (además del vínculo matrimonial o asimilable).",
    "el parentesco de consanguinidad dentro del cuarto grado o de afinidad dentro del segundo", ["procedimiento"]),
  l40("32-1", 32, "32.1", "¿Cuándo tienen derecho los particulares a ser indemnizados por la Administración?",
    "Por toda lesión en sus bienes y derechos causada por el funcionamiento normal o anormal de los servicios públicos, salvo fuerza mayor o deber jurídico de soportarla.",
    "siempre que la lesión sea consecuencia del funcionamiento normal o anormal de los servicios públicos salvo en los casos de fuerza mayor", ["procedimiento"]),
  l40("55-3", 55, "55.3", "¿Cuáles son los órganos superiores de la Administración General del Estado?",
    "Los Ministros y los Secretarios de Estado.",
    "a) Órganos superiores: 1.º Los Ministros. 2.º Los Secretarios de Estado.", ["age"]),
  l40("55-3d", 55, "55.3", "¿Cuáles son los órganos directivos de la organización central de la AGE?",
    "Subsecretarios y Secretarios generales; Secretarios generales técnicos y Directores generales; y Subdirectores generales.",
    "b) Órganos directivos: 1.º Los Subsecretarios y Secretarios generales. 2.º Los Secretarios generales técnicos y Directores generales. 3.º Los Subdirectores generales.", ["age"]),
  l40("63-1", 63, "63.1", "¿Quién ostenta la representación ordinaria del Ministerio?",
    "El Subsecretario.",
    "Los Subsecretarios ostentan la representación ordinaria del Ministerio", ["age"]),
  l40("72-3", 72, "72.3", "¿Qué rango tienen los Delegados del Gobierno y de quién dependen?",
    "Son órganos directivos con rango de Subsecretario; dependen orgánicamente del Presidente del Gobierno y funcionalmente del Ministerio competente por razón de la materia.",
    "Los Delegados del Gobierno son órganos directivos con rango de Subsecretario que dependen orgánicamente del Presidente del Gobierno y funcionalmente del Ministerio competente por razón de la materia.", ["age"]),
  l40("55-5", 55, "55.5", "¿Qué órganos directivos tiene la AGE en el exterior?",
    "Los embajadores y los representantes permanentes ante Organizaciones internacionales.",
    "En la Administración General del Estado en el exterior son órganos directivos los embajadores y representantes permanentes ante Organizaciones internacionales.", ["age"]),
  l40("55-6", 55, "55.6", "¿Qué órganos superiores y directivos de la AGE no tienen la condición de alto cargo?",
    "Los Subdirectores generales y asimilados; el resto de órganos superiores y directivos sí son alto cargo.",
    "Los órganos superiores y directivos tienen además la condición de alto cargo, excepto los Subdirectores generales y asimilados", ["age"]),
  l40("55-9", 55, "55.9", "¿Qué corresponde a los órganos superiores y qué a los directivos?",
    "A los superiores, establecer los planes de actuación de la organización a su cargo; a los directivos, su desarrollo y ejecución.",
    "Corresponde a los órganos superiores establecer los planes de actuación de la organización situada bajo su responsabilidad y a los órganos directivos su desarrollo y ejecución.", ["age"]),

  // ===== TREBEP (RDLeg. 5/2015) =====
  ebep("8-1", 8, "8.1", "¿Quiénes son empleados públicos?",
    "Quienes desempeñan funciones retribuidas en las Administraciones Públicas al servicio de los intereses generales.",
    "Son empleados públicos quienes desempeñan funciones retribuidas en las Administraciones Públicas al servicio de los intereses generales.", ["personal"]),
  ebep("8-2", 8, "8.2", "¿En qué clases se dividen los empleados públicos?",
    "Funcionarios de carrera, funcionarios interinos, personal laboral (fijo, por tiempo indefinido o temporal) y personal eventual.",
    "a) Funcionarios de carrera. b) Funcionarios interinos. c) Personal laboral, ya sea fijo, por tiempo indefinido o temporal. d) Personal eventual.", ["personal"]),
  ebep("9-1", 9, "9.1", "¿Qué son los funcionarios de carrera?",
    "Quienes, por nombramiento legal, están vinculados a una Administración por una relación estatutaria de Derecho Administrativo para prestar servicios profesionales retribuidos de carácter permanente.",
    "Son funcionarios de carrera quienes, en virtud de nombramiento legal, están vinculados a una Administración Pública por una relación estatutaria regulada por el Derecho Administrativo para el desempeño de servicios profesionales retribuidos de carácter permanente.", ["personal"]),
  ebep("9-2", 9, "9.2", "¿Qué funciones corresponden exclusivamente a los funcionarios públicos?",
    "Las que impliquen participar directa o indirectamente en el ejercicio de potestades públicas o en la salvaguardia de los intereses generales.",
    "corresponden exclusivamente a los funcionarios públicos", ["personal"]),
  ebep("12-1", 12, "12.1", "¿Qué es el personal eventual?",
    "El que, por nombramiento y con carácter no permanente, sólo realiza funciones calificadas como de confianza o asesoramiento especial.",
    "Es personal eventual el que, en virtud de nombramiento y con carácter no permanente, sólo realiza funciones expresamente calificadas como de confianza o asesoramiento especial", ["personal"]),
  ebep("55-2", 55, "55.2", "Cita los dos primeros principios rectores de los procesos selectivos del art. 55.2.",
    "Publicidad de las convocatorias y de sus bases, y transparencia (siguen: imparcialidad, independencia, adecuación y agilidad).",
    "a) Publicidad de las convocatorias y de sus bases. b) Transparencia.", ["personal"]),
  ebep("56-1", 56, "56.1.c", "¿Qué edad se exige para participar en procesos selectivos?",
    "Tener cumplidos dieciséis años y no superar, en su caso, la edad máxima de jubilación forzosa.",
    "Tener cumplidos dieciséis años y no exceder, en su caso, de la edad máxima de jubilación forzosa.", ["personal"]),
  ebep("60-2", 60, "60.2", "¿Quién no puede formar parte de los órganos de selección?",
    "El personal de elección o designación política, los funcionarios interinos y el personal eventual.",
    "El personal de elección o de designación política, los funcionarios interinos y el personal eventual no podrán formar parte de los órganos de selección.", ["personal"]),
  ebep("63", 63, "63", "¿Por qué causas se pierde la condición de funcionario de carrera?",
    "Renuncia, pérdida de la nacionalidad, jubilación total, separación del servicio firme e inhabilitación absoluta o especial firme.",
    "a) La renuncia a la condición de funcionario. b) La pérdida de la nacionalidad. c) La jubilación total del funcionario.", ["personal"]),
  ebep("76", 76, "76", "¿En qué Subgrupos se divide el Grupo A de clasificación profesional?",
    "En los Subgrupos A1 y A2.",
    "Grupo A: Dividido en dos Subgrupos, A1 y A2.", ["personal"]),
  ebep("76-b", 76, "76", "¿Qué título se exige para acceder al Grupo B?",
    "El título de Técnico Superior.",
    "Para el acceso a los cuerpos o escalas del Grupo B se exigirá estar en posesión del título de Técnico Superior.", ["personal"]),
  ebep("85-1", 85, "85.1", "¿Cuáles son las situaciones administrativas de los funcionarios de carrera?",
    "Servicio activo, servicios especiales, servicio en otras Administraciones Públicas, excedencia y suspensión de funciones.",
    "a) Servicio activo. b) Servicios especiales. c) Servicio en otras Administraciones Públicas. d) Excedencia. e) Suspensión de funciones.", ["personal"]),
  ebep("89-2", 89, "89.2", "¿Qué antigüedad exige la excedencia voluntaria por interés particular?",
    "Haber prestado servicios efectivos durante al menos cinco años inmediatamente anteriores.",
    "cuando hayan prestado servicios efectivos en cualquiera de las Administraciones Públicas durante un periodo mínimo de cinco años inmediatamente anteriores", ["personal"]),
  ebep("90-1", 90, "90.1", "¿Cuánto puede durar como máximo la suspensión firme por sanción disciplinaria?",
    "Seis años.",
    "La suspensión firme por sanción disciplinaria no podrá exceder de seis años.", ["personal"]),
  ebep("95-1", 95, "95.1", "¿Cómo se clasifican las faltas disciplinarias?",
    "En muy graves, graves y leves.",
    "Las faltas disciplinarias pueden ser muy graves, graves y leves.", ["personal"]),
  ebep("97", 97, "97", "¿Cuándo prescriben las infracciones disciplinarias?",
    "Las muy graves a los 3 años, las graves a los 2 años y las leves a los 6 meses.",
    "Las infracciones muy graves prescribirán a los tres años, las graves a los dos años y las leves a los seis meses", ["personal"]),
  ebep("97-s", 97, "97", "¿Cuándo prescriben las sanciones disciplinarias impuestas?",
    "Por faltas muy graves a los 3 años, por faltas graves a los 2 años y por faltas leves al año.",
    "las sanciones impuestas por faltas muy graves prescribirán a los tres años, las impuestas por faltas graves a los dos años y las impuestas por faltas leves al año", ["personal"]),

  // ===== Ley 9/2017, de Contratos del Sector Público =====
  lcsp("1-1", 1, "1.1", "¿Qué principios garantiza la LCSP en la contratación?",
    "Libertad de acceso a las licitaciones, publicidad y transparencia de los procedimientos, y no discriminación e igualdad de trato entre los licitadores.",
    "libertad de acceso a las licitaciones, publicidad y transparencia de los procedimientos, y no discriminación e igualdad de trato entre los licitadores", ["contratos"]),
  lcsp("12-1", 12, "12.1", "¿Qué tipos de contratos califica la LCSP en su sección de contratos típicos?",
    "Obras, concesión de obras, concesión de servicios, suministro y servicios.",
    "Los contratos de obras, concesión de obras, concesión de servicios, suministro y servicios que celebren las entidades pertenecientes al sector público se calificarán de acuerdo con las normas contenidas en la presente sección.", ["contratos"]),
  lcsp("29-2", 29, "29.2", "¿Es obligatoria la prórroga de un contrato para el empresario?",
    "Sí, si el órgano de contratación la acuerda con un preaviso de al menos dos meses antes del fin del contrato.",
    "será obligatoria para el empresario, siempre que su preaviso se produzca al menos con dos meses de antelación a la finalización del plazo de duración del contrato", ["contratos"]),
  lcsp("29-4", 29, "29.4", "¿Cuál es la duración máxima de los contratos de suministro y servicios de prestación sucesiva?",
    "Cinco años, incluidas las posibles prórrogas.",
    "Los contratos de suministros y de servicios de prestación sucesiva tendrán un plazo máximo de duración de cinco años, incluyendo las posibles prórrogas", ["contratos"]),
  lcsp("29-5", 29, "29.5", "¿Cuál es la duración máxima de los contratos de arrendamiento de bienes muebles?",
    "Cinco años, incluidas las posibles prórrogas.",
    "La duración de los contratos de arrendamiento de bienes muebles no podrá exceder", ["contratos"]),
  lcsp("29-8", 29, "29.8", "¿Cuánto puede durar un contrato menor y puede prorrogarse?",
    "No más de un año y no puede ser objeto de prórroga.",
    "Los contratos menores definidos en el apartado primero del artículo 118 no podrán tener una duración superior a un año ni ser objeto de prórroga.", ["contratos"]),
  lcsp("99-3", 99, "99.3", "¿Cuál es la regla general sobre la división de los contratos en lotes?",
    "Siempre que la naturaleza o el objeto del contrato lo permitan, debe dividirse en lotes; no hacerlo debe justificarse en el expediente.",
    "Siempre que la naturaleza o el objeto del contrato lo permitan, deberá preverse la realización independiente de cada una de sus partes mediante su división en lotes", ["contratos"]),
  lcsp("107-1", 107, "107.1", "¿De qué importe es la garantía definitiva?",
    "El 5 % del precio final ofertado, IVA excluido.",
    "una garantía de un 5 por 100 del precio final ofertado por aquellos, excluido el Impuesto sobre el Valor Añadido", ["contratos"]),
  lcsp("118-1", 118, "118.1", "¿Qué valores estimados delimitan el contrato menor?",
    "Menos de 40.000 euros en obras y menos de 15.000 euros en suministros o servicios.",
    "Se consideran contratos menores los contratos de valor estimado inferior a 40.000 euros, cuando se trate de contratos de obras, o a 15.000 euros, cuando se trate de contratos de suministro o de servicios", ["contratos"]),
  lcsp("131-2", 131, "131.2", "¿Con qué procedimientos se adjudican ordinariamente los contratos?",
    "Con el procedimiento abierto o el restringido, usando normalmente varios criterios basados en la mejor relación calidad-precio.",
    "utilizando el procedimiento abierto o el procedimiento restringido", ["contratos"]),
  lcsp("156-1", 156, "156.1", "¿Qué caracteriza al procedimiento abierto?",
    "Cualquier empresario interesado puede presentar proposición y no se negocian los términos del contrato.",
    "En el procedimiento abierto todo empresario interesado podrá presentar una proposición, quedando excluida toda negociación de los términos del contrato con los licitadores.", ["contratos"]),

  // ===== Ley 47/2003, General Presupuestaria =====
  lgp("32", 32, "32", "¿Qué son los Presupuestos Generales del Estado según la LGP?",
    "La expresión cifrada, conjunta y sistemática de los derechos y obligaciones a liquidar durante el ejercicio por los órganos y entidades del sector público estatal.",
    "Los Presupuestos Generales del Estado constituyen la expresión cifrada, conjunta y sistemática de los derechos y obligaciones a liquidar durante el ejercicio por cada uno de los órganos y entidades que forman parte del sector público estatal.", ["presupuesto"]),
  lgp("34-1", 34, "34.1", "¿Con qué periodo coincide el ejercicio presupuestario?",
    "Con el año natural.",
    "El ejercicio presupuestario coincidirá con el año natural", ["presupuesto"]),
  lgp("37-1", 37, "37.1", "¿Antes de qué fecha debe remitirse a las Cortes el proyecto de Ley de Presupuestos?",
    "Antes del 1 de octubre del año anterior al que se refiera.",
    "será remitido a las Cortes Generales antes del día 1 de octubre del año anterior al que se refiera", ["presupuesto"]),
  lgp("46", 46, "46", "¿Qué carácter tienen los créditos para gastos?",
    "Limitativo: no pueden adquirirse compromisos ni obligaciones por encima de los créditos autorizados; los actos que lo incumplan son nulos de pleno derecho.",
    "Los créditos para gastos son limitativos.", ["presupuesto"]),

  // ===== Ley 43/2010, del servicio postal universal =====
  postal("5", 5, "5", "¿Qué garantía deben respetar los operadores en la prestación de servicios postales?",
    "El secreto de las comunicaciones postales (arts. 18.3 y 55.2 de la Constitución).",
    "Los operadores postales deberán realizar la prestación de los servicios con plena garantía del secreto de las comunicaciones postales", ["postal"]),
  postal("20", 20, "20", "¿Qué es el servicio postal universal?",
    "El conjunto de servicios postales de calidad determinada, prestados de forma ordinaria y permanente en todo el territorio nacional y a precio asequible para todos los usuarios.",
    "Se entiende por servicio postal universal el conjunto de servicios postales de calidad determinada en la ley y sus reglamentos de desarrollo, prestados en régimen ordinario y permanente en todo el territorio nacional y a precio asequible para todos los usuarios.", ["postal", "productosPostales"]),
  postal("21-a", 21, "21.1.a", "¿Hasta qué peso entran las cartas y tarjetas postales en el servicio postal universal?",
    "Hasta dos kilogramos.",
    "Cartas y tarjetas postales que contengan comunicaciones escritas en cualquier tipo de soporte de hasta dos kilogramos de peso.", ["postal", "productosPostales"]),
  postal("21-b", 21, "21.1.b", "¿Hasta qué peso entran los paquetes postales en el servicio postal universal?",
    "Hasta veinte kilogramos, con o sin valor comercial.",
    "Paquetes postales, con o sin valor comercial, de hasta veinte kilogramos de peso.", ["postal", "productosPostales"]),
  postal("22-1", 22, "22.1", "¿Por qué principios se rige la prestación del servicio postal universal?",
    "Equidad, no discriminación, continuidad, buena fe y adaptación a las necesidades de los usuarios.",
    "se regirán por los principios de equidad, no discriminación, continuidad, buena fe, y adaptación a las necesidades de los usuarios", ["postal", "productosPostales"]),
  postal("24", 24, "24", "¿Con qué frecuencia mínima debe entregar los envíos el operador designado?",
    "Al menos todos los días laborables, de lunes a viernes, salvo circunstancias o condiciones geográficas especiales.",
    "Las entregas se practicarán, al menos, todos los días laborables, de lunes a viernes", ["postal", "productosPostales"]),

  // ===== LO 3/2018, de Protección de Datos Personales =====
  datos("5-1", 5, "5.1", "¿Quiénes están sujetos al deber de confidencialidad?",
    "Los responsables y encargados del tratamiento y todas las personas que intervengan en cualquier fase de este.",
    "Los responsables y encargados del tratamiento de datos así como todas las personas que intervengan en cualquier fase de este estarán sujetas al deber de confidencialidad", ["datos"]),
  datos("7-1", 7, "7.1", "¿Desde qué edad puede un menor consentir el tratamiento de sus datos?",
    "Desde que es mayor de catorce años.",
    "El tratamiento de los datos personales de un menor de edad únicamente podrá fundarse en su consentimiento cuando sea mayor de catorce años.", ["datos"]),
  datos("44-1", 44, "44.1", "¿Qué naturaleza tiene la Agencia Española de Protección de Datos?",
    "Es una autoridad administrativa independiente de ámbito estatal.",
    "La Agencia Española de Protección de Datos es una autoridad administrativa independiente de ámbito estatal", ["datos"]),
  datos("72-1", 72, "72.1", "¿Cuándo prescriben las infracciones muy graves de protección de datos?",
    "A los tres años.",
    "se consideran muy graves y prescribirán a los tres años", ["datos"]),

  // ===== Ley 31/1995, de Prevención de Riesgos Laborales =====
  prl("4-2", 4, "4.2", "¿Qué es un riesgo laboral?",
    "La posibilidad de que un trabajador sufra un determinado daño derivado del trabajo.",
    "la posibilidad de que un trabajador sufra un determinado daño derivado del trabajo", ["prl"]),
  prl("4-3", 4, "4.3", "¿Qué se considera daño derivado del trabajo?",
    "Las enfermedades, patologías o lesiones sufridas con motivo u ocasión del trabajo.",
    "las enfermedades, patologías o lesiones sufridas con motivo u ocasión del trabajo", ["prl"]),
  prl("14-1", 14, "14.1", "¿Qué derecho tienen los trabajadores en materia de seguridad y salud?",
    "A una protección eficaz en materia de seguridad y salud en el trabajo.",
    "Los trabajadores tienen derecho a una protección eficaz en materia de seguridad y salud en el trabajo.", ["prl"]),
  prl("14-5", 14, "14.5", "¿Puede recaer sobre el trabajador el coste de las medidas de seguridad y salud?",
    "No, en ningún caso.",
    "El coste de las medidas relativas a la seguridad y la salud en el trabajo no deberá recaer en modo alguno sobre los trabajadores.", ["prl"]),
  prl("15-1", 15, "15.1", "¿Cuáles son los tres primeros principios de la acción preventiva?",
    "Evitar los riesgos, evaluar los que no se puedan evitar y combatir los riesgos en su origen.",
    "a) Evitar los riesgos. b) Evaluar los riesgos que no se puedan evitar. c) Combatir los riesgos en su origen.", ["prl"]),
  prl("35-1", 35, "35.1", "¿Qué son los Delegados de Prevención?",
    "Los representantes de los trabajadores con funciones específicas en materia de prevención de riesgos en el trabajo.",
    "Los Delegados de Prevención son los representantes de los trabajadores con funciones específicas en materia de prevención de riesgos en el trabajo.", ["prl"]),
  prl("38-2", 38, "38.2", "¿En qué empresas debe constituirse un Comité de Seguridad y Salud?",
    "En todas las empresas o centros de trabajo con 50 o más trabajadores.",
    "Se constituirá un Comité de Seguridad y Salud en todas las empresas o centros de trabajo que cuenten con 50 o más trabajadores.", ["prl"]),

  // ===== Ley 6/2020, de servicios electrónicos de confianza =====
  conf("1", 1, "1", "¿Qué regula la Ley 6/2020?",
    "Determinados aspectos de los servicios electrónicos de confianza, como complemento del Reglamento (UE) 910/2014 (eIDAS).",
    "La presente Ley tiene por objeto regular determinados aspectos de los servicios electrónicos de confianza, como complemento del Reglamento (UE) n.º 910/2014", ["firma"]),
  conf("3-1", 3, "3.1", "¿Qué valor tienen los documentos electrónicos públicos, administrativos y privados?",
    "El valor y la eficacia jurídica que corresponda a su respectiva naturaleza, según la legislación aplicable.",
    "Los documentos electrónicos públicos, administrativos y privados, tienen el valor y la eficacia jurídica que corresponda a su respectiva naturaleza", ["firma"]),
  conf("4-1", 4, "4.1", "¿Cómo se extinguen los certificados electrónicos?",
    "Por caducidad al expirar su vigencia o por revocación del prestador de servicios de confianza.",
    "Los certificados electrónicos se extinguen por caducidad a la expiración de su período de vigencia, o mediante revocación por los prestadores de servicios electrónicos de confianza", ["firma"]),
  conf("4-2", 4, "4.2", "¿Cuál es la vigencia máxima de un certificado cualificado?",
    "Cinco años.",
    "El período de vigencia de los certificados cualificados no será superior a cinco años.", ["firma"]),

  // ===== RD 311/2022, Esquema Nacional de Seguridad =====
  ens("5-a", 5, "5", "Cita los dos primeros principios básicos del Esquema Nacional de Seguridad.",
    "La seguridad como proceso integral y la gestión de la seguridad basada en los riesgos.",
    "a) Seguridad como proceso integral. b) Gestión de la seguridad basada en los riesgos.", ["ciberseguridad"]),
  ens("5-obj", 5, "5", "¿Cuál es el objeto último de la seguridad de la información según el ENS?",
    "Garantizar que la organización pueda cumplir sus objetivos, desarrollar sus funciones y ejercer sus competencias utilizando sistemas de información.",
    "El objeto último de la seguridad de la información es garantizar que una organización podrá cumplir sus objetivos, desarrollar sus funciones y ejercer sus competencias utilizando sistemas de información.", ["ciberseguridad"]),
  ens("31-1", 31, "31.1", "¿Con qué periodicidad mínima se audita un sistema sujeto al ENS?",
    "Al menos cada dos años, y extraordinariamente si hay modificaciones sustanciales.",
    "serán objeto de una auditoría regular ordinaria, al menos cada dos años", ["ciberseguridad"]),
  ens("40-1", 40, "40.1", "¿Qué equilibrio modula la categoría de seguridad de un sistema?",
    "El equilibrio entre la importancia de la información y los servicios y el esfuerzo de seguridad requerido según sus riesgos, bajo el principio de proporcionalidad.",
    "La categoría de seguridad de un sistema de información modulará el equilibrio entre la importancia de la información que maneja y los servicios que presta y el esfuerzo de seguridad requerido", ["ciberseguridad"]),
];
