// Segundo bloque de contenido para los temas de GSI ya sembrados con un
// único bloque (ver content/gsi-temario.ts y content/gsi-temario-2.ts),
// ampliando cada uno con subtemas complementarios que no se solapan con el
// primer bloque. Mismo criterio de fuentes y redacción propia que el resto
// de content/*.ts de este proyecto.

export const GSI_TEMA1_PARTE2 = `## Los pliegos del contrato
Todo contrato público se prepara con dos documentos clave. El pliego de cláusulas administrativas particulares (PCAP) regula los aspectos jurídicos y económicos del contrato: criterios de adjudicación, plazos, garantías, penalidades y causas de resolución. El pliego de prescripciones técnicas (PPT) describe el objeto del contrato desde el punto de vista técnico: qué debe entregarse o ejecutarse exactamente y con qué características. Ambos documentos vinculan a la Administración y a la empresa adjudicataria durante toda la vida del contrato, y cualquier discrepancia entre la oferta presentada y lo exigido en los pliegos puede ser causa de exclusión de la licitación.

## Criterios de adjudicación
La LCSP exige que la adjudicación se base en la mejor relación calidad-precio, evaluada con criterios objetivos vinculados al objeto del contrato: pueden ser cuantificables mediante fórmulas (como el precio) o sujetos a un juicio de valor (como la calidad técnica de una propuesta, evaluada por un comité de expertos). En los contratos de servicios y suministros de carácter intelectual —como el desarrollo de software a medida— es habitual que el peso de los criterios evaluables mediante juicio de valor sea significativo, para no primar exclusivamente el precio más bajo en detrimento de la calidad de la solución.

## La ejecución y modificación del contrato
Durante la ejecución, la Administración conserva determinadas prerrogativas: interpretar el contrato en caso de duda, modificarlo por razones de interés público dentro de los límites que fija la ley (y siempre que esa posibilidad y sus condiciones estuvieran previstas en los pliegos), y resolverlo anticipadamente en los supuestos tasados legalmente (como el incumplimiento grave de las obligaciones del contratista). Las modificaciones no previstas en los pliegos solo son posibles, con carácter excepcional, cuando obedezcan a necesidades nuevas o causas imprevisibles, y dentro de límites porcentuales estrictos sobre el precio inicial del contrato.`;

export const GSI_TEMA4_PARTE2 = `## Sellos electrónicos y sellado de tiempo
El sello electrónico identifica a una persona jurídica (un organismo público, una empresa), no a una persona física, y se usa habitualmente para automatizar la firma de grandes volúmenes de documentos generados por un sistema de información sin intervención humana directa (por ejemplo, notificaciones masivas). El sellado de tiempo (time-stamping) certifica, mediante un tercero de confianza, que un documento electrónico existía en un momento concreto y no ha sido modificado desde entonces, lo que resulta esencial para acreditar la fecha de presentación de un documento o la vigencia de una firma en el momento en que se realizó.

## Plataformas de validación e interoperabilidad
La plataforma @firma, gestionada por la Administración General del Estado, permite validar certificados y firmas electrónicas de forma centralizada, comprobando que un certificado es válido, no ha caducado y no ha sido revocado, sin que cada organismo tenga que implementar esa lógica por separado. Esta interoperabilidad es clave para que un certificado emitido por cualquier prestador de servicios de confianza cualificado sea aceptado de forma homogénea por todas las Administraciones Públicas españolas, evitando que cada organismo exija su propio sistema de identificación.

## Custodia y archivo electrónico de documentos firmados
Un documento firmado electrónicamente debe conservarse de forma que se garantice su autenticidad, integridad y disponibilidad durante todo el tiempo exigido por la normativa de archivo, lo que plantea un reto específico: los algoritmos y certificados usados en la firma pueden quedar obsoletos con el paso de los años. Por ello, los sistemas de archivo electrónico a largo plazo aplican técnicas de "resellado" o renovación periódica de las evidencias de firma, de modo que la validez de un documento firmado hace años pueda seguir demostrándose aunque el certificado original ya no esté vigente.`;

export const GSI_TEMA5_PARTE2 = `## Gestión de vulnerabilidades y parches
Una vulnerabilidad es un fallo o debilidad de un sistema que puede ser aprovechado por un atacante. La gestión de vulnerabilidades es un proceso continuo: identificar los activos de la organización, analizarlos periódicamente con herramientas automatizadas que buscan fallos conocidos, priorizar su corrección según la gravedad y la exposición real del sistema afectado, y aplicar los parches o actualizaciones que los fabricantes publican para corregirlas. Cuanto más tiempo pasa un sistema sin actualizar, mayor es la ventana de oportunidad para que un atacante explote una vulnerabilidad ya conocida y documentada públicamente.

## Cifrado y protección de las comunicaciones
El cifrado transforma la información en un formato ilegible para quien no dispone de la clave adecuada. El protocolo TLS, que da la "S" a HTTPS, cifra las comunicaciones entre un navegador y un servidor web, protegiendo los datos frente a la escucha pasiva en redes intermedias. Una VPN (red privada virtual) crea un túnel cifrado entre dos puntos —por ejemplo, entre el equipo de una persona teletrabajadora y la red interna de su organismo—, de modo que el tráfico viaja protegido incluso si atraviesa redes públicas no confiables como el wifi de una cafetería.

## Respuesta a incidentes de seguridad
Un incidente de seguridad es cualquier evento que compromete la confidencialidad, integridad o disponibilidad de un sistema. Un plan de respuesta a incidentes define fases claras: detección (identificar que algo anómalo está ocurriendo), contención (limitar el alcance del incidente, por ejemplo aislando el equipo afectado de la red), erradicación (eliminar la causa raíz, como el malware instalado), recuperación (restaurar el servicio con normalidad) y lecciones aprendidas (analizar lo ocurrido para reforzar las defensas). En el sector público español, los incidentes deben notificarse al CCN-CERT conforme a los procedimientos que fija el Esquema Nacional de Seguridad.`;

export const GSI_TEMA8_PARTE2 = `## Aprendizaje supervisado, no supervisado y por refuerzo
El aprendizaje supervisado entrena un modelo con datos ya etiquetados (por ejemplo, correos marcados como spam o no spam), de modo que el sistema aprende a predecir la etiqueta correcta para datos nuevos. El aprendizaje no supervisado trabaja con datos sin etiquetar, buscando patrones o agrupaciones (clustering) por sí mismo, sin que nadie le indique de antemano cuál es la respuesta correcta. El aprendizaje por refuerzo entrena a un agente mediante prueba y error, recompensando las acciones que se acercan al objetivo deseado y penalizando las que se alejan de él, un enfoque habitual en robótica o en sistemas que deben tomar decisiones secuenciales.

## Grandes modelos de lenguaje
Los grandes modelos de lenguaje (LLM, por sus siglas en inglés) son redes neuronales entrenadas con enormes cantidades de texto, capaces de generar y comprender lenguaje natural con gran fluidez. Su funcionamiento se basa en predecir, dado un fragmento de texto, cuál es la palabra o fragmento siguiente más probable, lo que les permite tanto responder preguntas como redactar o resumir textos. Entre sus limitaciones conocidas están las llamadas "alucinaciones" (generar información que suena plausible pero es incorrecta o inventada), por lo que su uso en la Administración exige siempre supervisión y verificación humana del resultado, especialmente cuando afecta a decisiones sobre personas.

## Gobernanza y auditoría de sistemas de IA
Además de las obligaciones de transparencia y supervisión humana del Reglamento europeo de IA, una gestión responsable de estos sistemas exige documentar de dónde proceden los datos de entrenamiento, evaluar periódicamente si el modelo mantiene sesgos indeseados hacia determinados colectivos, y establecer mecanismos claros para que una persona afectada por una decisión asistida por IA pueda solicitar una revisión humana. En la Administración Pública, estos principios de gobernanza son especialmente relevantes porque muchas decisiones automatizadas o semiautomatizadas afectan directamente a derechos de la ciudadanía.`;

export const GSI_TEMA9_PARTE2 = `## Infraestructura como código
La infraestructura como código (IaC) consiste en definir y gestionar servidores, redes y demás recursos de infraestructura mediante archivos de configuración versionables, en vez de configurarlos manualmente uno a uno. Esto permite recrear un entorno completo de forma automática y reproducible (por ejemplo, para levantar un entorno de pruebas idéntico al de producción), llevar un historial de cambios igual que se hace con el código de una aplicación, y detectar y corregir configuraciones que se han desviado del estado deseado. Herramientas como Terraform o Ansible son habituales en este enfoque.

## Monitorización y observabilidad
La monitorización consiste en recoger y vigilar métricas de un sistema (uso de CPU, memoria, tiempos de respuesta, tasa de errores) para detectar problemas antes de que afecten a las personas usuarias, o al menos reaccionar rápido cuando ocurren. La observabilidad va un paso más allá: además de métricas, combina registros (logs) y trazas (el recorrido completo de una petición a través de los distintos componentes de un sistema) para poder entender por qué está ocurriendo un problema, no solo detectar que está ocurriendo. Las alertas automáticas, configuradas sobre umbrales de estas métricas, permiten avisar al equipo responsable antes de que un incidente escale.

## Metodologías ágiles
Las metodologías ágiles organizan el desarrollo de software en ciclos cortos e iterativos, frente al enfoque tradicional de planificar todo el proyecto de antemano. Scrum estructura el trabajo en sprints (periodos fijos, habitualmente de dos a cuatro semanas) con reuniones breves de seguimiento diario, una planificación al inicio de cada sprint y una revisión y retrospectiva al final. Kanban, en cambio, no fija periodos cerrados: visualiza el flujo de trabajo en un tablero con columnas (por ejemplo, "pendiente", "en curso", "hecho") y limita cuántas tareas pueden estar en curso a la vez, para evitar la sobrecarga del equipo y detectar cuellos de botella.`;
