// Temas 8 (Economía y Hacienda), 9 (organización territorial), 10 (Tribunal
// Constitucional), 11 (reforma constitucional) y 16 (seguridad: ENS y
// protección de datos). Ver tai-banco-boe.ts.
import type { PreguntaBoe } from "./tai-banco-boe";

export const BANCO_BOE_3: PreguntaBoe[] = [
  // ── Tema 8 ──────────────────────────────────────────────────────────────
  {
    id: "tai-boe-t08-01", tema: 8, norma: "CE", art: "Artículo 128",
    cita: "Toda la riqueza del país en sus distintas formas y sea cual fuere su titularidad está subordinada al interés general.",
    clave: "subordinada al interés general",
    e: "Según el artículo 128.1 de la Constitución, toda la riqueza del país en sus distintas formas y sea cual fuere su titularidad:",
    ok: "Está subordinada al interés general.",
    mal: ["Está sometida a la planificación estatal obligatoria.", "Está protegida frente a toda expropiación.", "Pertenece en último término al Estado."],
    d: 1,
  },
  {
    id: "tai-boe-t08-02", tema: 8, norma: "CE", art: "Artículo 129",
    cita: "fomentarán, mediante una legislación adecuada, las sociedades cooperativas",
    clave: "sociedades cooperativas",
    e: "Conforme al artículo 129.2 de la Constitución, los poderes públicos fomentarán, mediante una legislación adecuada:",
    ok: "Las sociedades cooperativas.",
    mal: ["Las sociedades anónimas cotizadas.", "Las fundaciones del sector público.", "Las empresas públicas de servicios esenciales."],
    d: 1,
  },
  {
    id: "tai-boe-t08-03", tema: 8, norma: "CE", art: "Artículo 130",
    cita: "Con el mismo fin, se dispensará un tratamiento especial a las zonas de montaña.",
    clave: "zonas de montaña",
    e: "Con el fin de equiparar el nivel de vida de todos los españoles, el artículo 130.2 de la Constitución dispone un tratamiento especial para:",
    ok: "Las zonas de montaña.",
    mal: ["Las zonas costeras.", "Las zonas rurales despobladas.", "Las zonas fronterizas."],
    d: 1,
  },
  {
    id: "tai-boe-t08-04", tema: 8, norma: "CE", art: "Artículo 132",
    cita: "Son bienes de dominio público estatal los que determine la ley y, en todo caso, la zona marítimo-terrestre, las playas, el mar territorial y los recursos naturales de la zona económica y la plataforma continental.",
    clave: "playas",
    e: "¿Cuál de los siguientes bienes es, en todo caso, de dominio público estatal según el artículo 132.2 de la Constitución?",
    ok: "Las playas.",
    mal: ["Los montes vecinales en mano común.", "Los yacimientos arqueológicos.", "Las vías pecuarias."],
    j: "La Constitución enumera directamente la zona marítimo-terrestre, las playas, el mar territorial y los recursos naturales de la zona económica y la plataforma continental; los demás son de dominio público estatal si así lo determina la ley.",
    d: 2,
  },
  {
    id: "tai-boe-t08-05", tema: 8, norma: "CE", art: "Artículo 133",
    cita: "Las Comunidades Autónomas y las Corporaciones locales podrán establecer y exigir tributos, de acuerdo con la Constitución y las leyes.",
    clave: "establecer y exigir tributos",
    e: "Según el artículo 133.2 de la Constitución, las Comunidades Autónomas y las Corporaciones locales:",
    ok: "Podrán establecer y exigir tributos, de acuerdo con la Constitución y las leyes.",
    mal: ["Solo podrán exigir los tributos que establezca el Estado.", "No podrán crear tributos propios en ningún caso.", "Necesitarán autorización del Ministerio de Hacienda para cada tributo."],
    d: 1,
  },
  {
    id: "tai-boe-t08-06", tema: 8, norma: "CE", art: "Artículo 133",
    cita: "Todo beneficio fiscal que afecte a los tributos del Estado deberá establecerse en virtud de ley.",
    clave: "en virtud de ley",
    e: "Conforme al artículo 133.3 de la Constitución, todo beneficio fiscal que afecte a los tributos del Estado deberá establecerse:",
    ok: "En virtud de ley.",
    mal: ["Por real decreto acordado en Consejo de Ministros.", "Por orden del Ministerio de Hacienda.", "Por acuerdo del Consejo de Política Fiscal y Financiera."],
    d: 1,
  },
  {
    id: "tai-boe-t08-07", tema: 8, norma: "CE", art: "Artículo 134",
    cita: "Corresponde al Gobierno la elaboración de los Presupuestos Generales del Estado y a las Cortes Generales, su examen, enmienda y aprobación.",
    clave: "examen, enmienda y aprobación",
    e: "Según el artículo 134.1 de la Constitución, respecto de los Presupuestos Generales del Estado corresponde a las Cortes Generales:",
    ok: "Su examen, enmienda y aprobación.",
    mal: ["Su elaboración y aprobación.", "Solo su aprobación o rechazo en bloque.", "Su elaboración, a propuesta del Tribunal de Cuentas."],
    d: 1,
  },
  {
    id: "tai-boe-t08-08", tema: 8, norma: "CE", art: "Artículo 134",
    cita: "en ellos se consignará el importe de los beneficios fiscales que afecten a los tributos del Estado",
    clave: "importe de los beneficios fiscales",
    e: "Además de tener carácter anual e incluir la totalidad de los gastos e ingresos del sector público estatal, según el artículo 134.2 de la Constitución en los Presupuestos Generales del Estado se consignará:",
    ok: "El importe de los beneficios fiscales que afecten a los tributos del Estado.",
    mal: ["La previsión de recaudación de cada Comunidad Autónoma.", "El límite de deuda de cada entidad local.", "La retribución individual de cada alto cargo."],
    d: 2,
  },
  {
    id: "tai-boe-t08-09", tema: 8, norma: "CE", art: "Artículo 136",
    cita: "El Tribunal de Cuentas es el supremo órgano fiscalizador de las cuentas y de la gestión económica de Estado, así como del sector público.",
    clave: "supremo órgano fiscalizador",
    e: "Conforme al artículo 136.1 de la Constitución, el Tribunal de Cuentas es:",
    ok: "El supremo órgano fiscalizador de las cuentas y de la gestión económica del Estado y del sector público.",
    mal: ["El supremo órgano consultivo del Gobierno en materia económica.", "El órgano de gobierno de la Hacienda Pública.", "El tribunal superior en materia tributaria."],
    d: 1,
  },
  {
    id: "tai-boe-t08-10", tema: 8, norma: "CE", art: "Artículo 136",
    cita: "Los miembros del Tribunal de Cuentas gozarán de la misma independencia e inamovilidad y estarán sometidos a las mismas incompatibilidades que los Jueces.",
    clave: "que los Jueces",
    e: "Según el artículo 136.3 de la Constitución, los miembros del Tribunal de Cuentas gozan de la misma independencia e inamovilidad y están sometidos a las mismas incompatibilidades:",
    ok: "Que los Jueces.",
    mal: ["Que los Diputados y Senadores.", "Que los miembros del Gobierno.", "Que los interventores del Estado."],
    d: 2,
  },
  {
    id: "tai-boe-t08-11", tema: 8, norma: "LGP", art: "Artículo 32",
    cita: "Los Presupuestos Generales del Estado constituyen la expresión cifrada, conjunta y sistemática de los derechos y obligaciones a liquidar durante el ejercicio",
    clave: "expresión cifrada, conjunta y sistemática",
    e: "Según el artículo 32 de la Ley 47/2003, General Presupuestaria, los Presupuestos Generales del Estado constituyen:",
    ok: "La expresión cifrada, conjunta y sistemática de los derechos y obligaciones a liquidar durante el ejercicio.",
    mal: ["La previsión plurianual de los ingresos y gastos del Estado.", "Una autorización genérica para gastar, sin límite cuantitativo.", "El estado contable de las obligaciones ya pagadas en el ejercicio anterior."],
    d: 2,
  },
  {
    id: "tai-boe-t08-12", tema: 8, norma: "LGP", art: "Artículo 34",
    cita: "El ejercicio presupuestario coincidirá con el año natural",
    clave: "año natural",
    e: "Conforme al artículo 34.1 de la Ley General Presupuestaria, el ejercicio presupuestario:",
    ok: "Coincidirá con el año natural.",
    mal: ["Irá del 1 de julio al 30 de junio.", "Irá del 1 de octubre al 30 de septiembre.", "Coincidirá con la legislatura."],
    d: 1,
  },
  {
    id: "tai-boe-t08-13", tema: 8, norma: "LGP", art: "Artículo 37",
    cita: "será remitido a las Cortes Generales antes del día 1 de octubre del año anterior al que se refiera",
    clave: "1 de octubre",
    e: "Según el artículo 37.1 de la Ley General Presupuestaria, el proyecto de Ley de Presupuestos Generales del Estado será remitido a las Cortes Generales antes del día:",
    ok: "1 de octubre del año anterior al que se refiera.",
    mal: ["1 de septiembre del año anterior al que se refiera.", "1 de noviembre del año anterior al que se refiera.", "31 de diciembre del año anterior al que se refiera."],
    j: "Es la concreción legal del artículo 134.3 de la Constitución, que exige presentarlo al menos tres meses antes de la expiración de los del año anterior.",
    d: 1,
  },

  // ── Tema 9 ──────────────────────────────────────────────────────────────
  {
    id: "tai-boe-t09-01", tema: 9, norma: "CE", art: "Artículo 138",
    cita: "velando por el establecimiento de un equilibrio económico, adecuado y justo entre las diversas partes del territorio español, y atendiendo en particular a las circunstancias del hecho insular",
    clave: "hecho insular",
    e: "Según el artículo 138.1 de la Constitución, al garantizar la realización efectiva del principio de solidaridad, el Estado velará por un equilibrio económico, adecuado y justo entre las diversas partes del territorio, atendiendo en particular a:",
    ok: "Las circunstancias del hecho insular.",
    mal: ["Las zonas de montaña.", "La despoblación rural.", "La situación de las ciudades de Ceuta y Melilla."],
    d: 2,
  },
  {
    id: "tai-boe-t09-02", tema: 9, norma: "CE", art: "Artículo 138",
    cita: "Las diferencias entre los Estatutos de las distintas Comunidades Autónomas no podrán implicar, en ningún caso, privilegios económicos o sociales.",
    clave: "privilegios económicos o sociales",
    e: "Conforme al artículo 138.2 de la Constitución, las diferencias entre los Estatutos de las distintas Comunidades Autónomas no podrán implicar, en ningún caso:",
    ok: "Privilegios económicos o sociales.",
    mal: ["Diferencias en el nivel de competencias asumidas.", "Diferencias en su organización institucional.", "Diferencias en el régimen de las lenguas cooficiales."],
    d: 1,
  },
  {
    id: "tai-boe-t09-03", tema: 9, norma: "CE", art: "Artículo 139",
    cita: "Ninguna autoridad podrá adoptar medidas que directa o indirectamente obstaculicen la libertad de circulación y establecimiento de las personas y la libre circulación de bienes en todo el territorio español.",
    clave: "libre circulación de bienes",
    e: "Según el artículo 139.2 de la Constitución, ninguna autoridad podrá adoptar:",
    ok: "Medidas que obstaculicen la libertad de circulación y establecimiento de las personas y la libre circulación de bienes en todo el territorio español.",
    mal: ["Tributos propios sobre las actividades realizadas en su territorio.", "Normas sobre la organización de sus propias instituciones.", "Medidas de fomento de su lengua cooficial."],
    d: 1,
  },
  {
    id: "tai-boe-t09-04", tema: 9, norma: "CE", art: "Artículo 141",
    cita: "En los archipiélagos, las islas tendrán además su administración propia en forma de Cabildos o Consejos.",
    clave: "Cabildos o Consejos",
    e: "Conforme al artículo 141.4 de la Constitución, en los archipiélagos las islas tendrán además su administración propia en forma de:",
    ok: "Cabildos o Consejos.",
    mal: ["Diputaciones insulares exclusivamente.", "Delegaciones insulares del Gobierno.", "Comarcas insulares."],
    d: 1,
  },
  {
    id: "tai-boe-t09-05", tema: 9, norma: "CE", art: "Artículo 145",
    cita: "En ningún caso se admitirá la federación de Comunidades Autónomas.",
    clave: "federación",
    e: "¿Qué prohíbe en todo caso el artículo 145.1 de la Constitución?",
    ok: "La federación de Comunidades Autónomas.",
    mal: ["Los convenios entre Comunidades Autónomas para la gestión de servicios propios.", "Los acuerdos de cooperación entre Comunidades Autónomas.", "Las oficinas de las Comunidades Autónomas ante la Unión Europea."],
    d: 1,
  },
  {
    id: "tai-boe-t09-06", tema: 9, norma: "CE", art: "Artículo 145",
    cita: "En los demás supuestos, los acuerdos de cooperación entre las Comunidades Autónomas necesitarán la autorización de las Cortes Generales.",
    clave: "autorización de las Cortes Generales",
    e: "Según el artículo 145.2 de la Constitución, fuera de los convenios para la gestión y prestación de servicios propios previstos en los Estatutos, los acuerdos de cooperación entre Comunidades Autónomas necesitarán:",
    ok: "La autorización de las Cortes Generales.",
    mal: ["La autorización del Gobierno.", "La simple comunicación al Senado.", "El dictamen previo del Consejo de Estado."],
    d: 2,
  },
  {
    id: "tai-boe-t09-07", tema: 9, norma: "CE", art: "Artículo 147",
    cita: "La reforma de los Estatutos se ajustará al procedimiento establecido en los mismos y requerirá, en todo caso, la aprobación por las Cortes Generales, mediante ley orgánica.",
    clave: "Cortes Generales, mediante ley orgánica",
    e: "Conforme al artículo 147.3 de la Constitución, la reforma de los Estatutos de Autonomía se ajustará al procedimiento establecido en ellos y requerirá, en todo caso:",
    ok: "La aprobación por las Cortes Generales, mediante ley orgánica.",
    mal: ["Un referéndum en la Comunidad Autónoma.", "Su aprobación por la Asamblea autonómica, sin intervención de las Cortes.", "Un real decreto del Gobierno, previo dictamen del Consejo de Estado."],
    d: 2,
  },
  {
    id: "tai-boe-t09-08", tema: 9, norma: "CE", art: "Artículo 150",
    cita: "El Estado podrá transferir o delegar en las Comunidades Autónomas, mediante ley orgánica, facultades correspondientes a materia de titularidad estatal",
    clave: "ley orgánica",
    e: "Según el artículo 150.2 de la Constitución, el Estado podrá transferir o delegar en las Comunidades Autónomas facultades correspondientes a materia de titularidad estatal mediante:",
    ok: "Ley orgánica.",
    mal: ["Ley marco.", "Ley de armonización.", "Real decreto de traspasos."],
    m: "150.1 ley MARCO, 150.2 ley ORGÁNICA de transferencia o delegación, 150.3 ley de ARMONIZACIÓN.", d: 2,
  },
  {
    id: "tai-boe-t09-09", tema: 9, norma: "CE", art: "Artículo 153",
    cita: "b) Por el Gobierno, previo dictamen del Consejo de Estado, el del ejercicio de funciones delegadas a que se refiere el apartado 2 del artículo 150.",
    clave: "Gobierno, previo dictamen del Consejo de Estado",
    e: "Según el artículo 153 de la Constitución, el control de la actividad de los órganos de las Comunidades Autónomas en el ejercicio de las funciones delegadas del artículo 150.2 se ejercerá:",
    ok: "Por el Gobierno, previo dictamen del Consejo de Estado.",
    mal: ["Por el Tribunal Constitucional.", "Por la jurisdicción contencioso-administrativa.", "Por el Tribunal de Cuentas."],
    j: "El Tribunal Constitucional controla sus normas con fuerza de ley, la jurisdicción contencioso-administrativa la administración autónoma y sus reglamentos, y el Tribunal de Cuentas el control económico y presupuestario.",
    d: 2,
  },
  {
    id: "tai-boe-t09-10", tema: 9, norma: "CE", art: "Artículo 154",
    cita: "Un Delegado nombrado por el Gobierno dirigirá la Administración del Estado en el territorio de la Comunidad Autónoma",
    clave: "Delegado nombrado por el Gobierno",
    e: "Conforme al artículo 154 de la Constitución, ¿quién dirige la Administración del Estado en el territorio de una Comunidad Autónoma?",
    ok: "Un Delegado nombrado por el Gobierno.",
    mal: ["El Consejero de Presidencia de la Comunidad Autónoma.", "Un Subdelegado nombrado por el Ministro del Interior.", "Un Delegado elegido por la Asamblea autonómica."],
    d: 1,
  },
  {
    id: "tai-boe-t09-11", tema: 9, norma: "CE", art: "Artículo 156",
    cita: "con arreglo a los principios de coordinación con la Hacienda estatal y de solidaridad entre todos los españoles",
    clave: "coordinación con la Hacienda estatal",
    e: "Según el artículo 156.1 de la Constitución, las Comunidades Autónomas gozarán de autonomía financiera con arreglo a los principios de:",
    ok: "Coordinación con la Hacienda estatal y solidaridad entre todos los españoles.",
    mal: ["Suficiencia y plena autonomía tributaria.", "Corresponsabilidad fiscal y libre competencia.", "Equilibrio presupuestario y prohibición de endeudamiento."],
    d: 2,
  },
  {
    id: "tai-boe-t09-12", tema: 9, norma: "LBRL", art: "Artículo 11",
    cita: "Son elementos del Municipio el territorio, la población y la organización.",
    clave: "el territorio, la población y la organización",
    e: "Según el artículo 11.2 de la Ley 7/1985, reguladora de las Bases del Régimen Local, son elementos del Municipio:",
    ok: "El territorio, la población y la organización.",
    mal: ["El término municipal, el padrón y el presupuesto.", "La población, el Ayuntamiento y la Hacienda local.", "El territorio, el Alcalde y los Concejales."],
    d: 1,
  },
  {
    id: "tai-boe-t09-13", tema: 9, norma: "LBRL", art: "Artículo 20",
    cita: "b) La Junta de Gobierno Local existe en todos los municipios con población superior a 5.000 habitantes",
    clave: "5.000",
    e: "Conforme al artículo 20.1.b) de la Ley 7/1985, la Junta de Gobierno Local existe en todos los municipios con población superior a:",
    ok: "5.000 habitantes.",
    mal: ["10.000 habitantes.", "20.000 habitantes.", "50.000 habitantes."],
    j: "En los municipios más pequeños existe cuando así lo disponga su reglamento orgánico o lo acuerde el Pleno. El Alcalde, los Tenientes de Alcalde y el Pleno existen en todos los ayuntamientos.",
    d: 2,
  },
  {
    id: "tai-boe-t09-14", tema: 9, norma: "LBRL", art: "Artículo 26",
    cita: "c) En los Municipios con población superior a 20.000 habitantes, además: protección civil, evaluación e información de situaciones de necesidad social y la atención inmediata a personas en situación o riesgo de exclusión social, prevención y extinción de incendios e instalaciones deportivas de uso público.",
    clave: "20.000",
    e: "Según el artículo 26.1 de la Ley 7/1985, ¿a partir de qué población deben prestar los Municipios, en todo caso, el servicio de prevención y extinción de incendios?",
    ok: "Población superior a 20.000 habitantes.",
    mal: ["Población superior a 5.000 habitantes.", "Población superior a 50.000 habitantes.", "Todos los Municipios, sea cual sea su población."],
    m: "Servicios mínimos: todos / +5.000 / +20.000 / +50.000.", d: 2,
  },
  {
    id: "tai-boe-t09-15", tema: 9, norma: "LBRL", art: "Artículo 26",
    cita: "d) En los Municipios con población superior a 50.000 habitantes, además: transporte colectivo urbano de viajeros y medio ambiente urbano.",
    clave: "transporte colectivo urbano",
    e: "¿Qué servicio deben prestar, además, los Municipios con población superior a 50.000 habitantes según el artículo 26.1.d) de la Ley 7/1985?",
    ok: "Transporte colectivo urbano de viajeros.",
    mal: ["Biblioteca pública.", "Protección civil.", "Alumbrado público."],
    j: "La biblioteca pública es obligatoria desde 5.000 habitantes, la protección civil desde 20.000 y el alumbrado público en todos los Municipios.",
    d: 2,
  },

  // ── Tema 10 ─────────────────────────────────────────────────────────────
  {
    id: "tai-boe-t10-01", tema: 10, norma: "CE", art: "Artículo 159",
    cita: "La condición de miembro del Tribunal Constitucional es incompatible: con todo mandato representativo",
    clave: "todo mandato representativo",
    e: "Según el artículo 159.4 de la Constitución, la condición de miembro del Tribunal Constitucional es incompatible, entre otros:",
    ok: "Con todo mandato representativo.",
    mal: ["Con la docencia universitaria.", "Con la condición de funcionario jubilado.", "Con la pertenencia a una Real Academia."],
    d: 2,
  },
  {
    id: "tai-boe-t10-02", tema: 10, norma: "CE", art: "Artículo 159",
    cita: "Los miembros del Tribunal Constitucional serán independientes e inamovibles en el ejercicio de su mandato.",
    clave: "independientes e inamovibles",
    e: "Conforme al artículo 159.5 de la Constitución, los miembros del Tribunal Constitucional en el ejercicio de su mandato serán:",
    ok: "Independientes e inamovibles.",
    mal: ["Independientes y responsables ante las Cortes Generales.", "Inviolables y no sujetos a responsabilidad.", "Revocables por el órgano que los propuso."],
    d: 1,
  },
  {
    id: "tai-boe-t10-03", tema: 10, norma: "CE", art: "Artículo 162",
    cita: "b) Para interponer el recurso de amparo, toda persona natural o jurídica que invoque un interés legítimo, así como el Defensor del Pueblo y el Ministerio Fiscal.",
    clave: "interés legítimo",
    e: "Según el artículo 162.1.b) de la Constitución, están legitimados para interponer el recurso de amparo:",
    ok: "Toda persona natural o jurídica que invoque un interés legítimo, así como el Defensor del Pueblo y el Ministerio Fiscal.",
    mal: ["Solo las personas físicas de nacionalidad española directamente afectadas.", "El Presidente del Gobierno, 50 Diputados y 50 Senadores.", "Solo el Ministerio Fiscal y los órganos judiciales."],
    d: 1,
  },
  {
    id: "tai-boe-t10-04", tema: 10, norma: "CE", art: "Artículo 164",
    cita: "Tienen el valor de cosa juzgada a partir del día siguiente de su publicación y no cabe recurso alguno contra ellas.",
    clave: "día siguiente de su publicación",
    e: "Conforme al artículo 164.1 de la Constitución, las sentencias del Tribunal Constitucional tienen el valor de cosa juzgada:",
    ok: "A partir del día siguiente de su publicación, y no cabe recurso alguno contra ellas.",
    mal: ["Desde el momento en que se dictan.", "Desde su notificación a las partes.", "Transcurridos veinte días desde su publicación, si no se recurren."],
    d: 2,
  },
  {
    id: "tai-boe-t10-05", tema: 10, norma: "CE", art: "Artículo 164",
    cita: "Las sentencias del Tribunal Constitucional se publicarán en el boletín oficial del Estado con los votos particulares, si los hubiere.",
    clave: "con los votos particulares",
    e: "Según el artículo 164.1 de la Constitución, las sentencias del Tribunal Constitucional se publicarán en el Boletín Oficial del Estado:",
    ok: "Con los votos particulares, si los hubiere.",
    mal: ["Sin los votos particulares, que se archivan en la Secretaría del Tribunal.", "Solo en su fallo, sin fundamentos jurídicos.", "Únicamente cuando declaren la inconstitucionalidad de una ley."],
    d: 1,
  },
  {
    id: "tai-boe-t10-06", tema: 10, norma: "CE", art: "Artículo 164",
    cita: "Salvo que en el fallo se disponga otra cosa, subsistirá la vigencia de la ley en la parte no afectada por la inconstitucionalidad.",
    clave: "parte no afectada",
    e: "Cuando el Tribunal Constitucional declara inconstitucional parte de una ley, según el artículo 164.2 de la Constitución, salvo que el fallo disponga otra cosa:",
    ok: "Subsistirá la vigencia de la ley en la parte no afectada por la inconstitucionalidad.",
    mal: ["La ley queda anulada en su totalidad.", "Las Cortes deberán aprobar de nuevo la ley completa.", "La ley queda en suspenso hasta que se apruebe otra."],
    d: 1,
  },
  {
    id: "tai-boe-t10-07", tema: 10, norma: "LOTC", art: "Artículo primero",
    cita: "El Tribunal Constitucional, como intérprete supremo de la Constitución, es independiente de los demás órganos constitucionales y está sometido sólo a la Constitución y a la presente Ley Orgánica.",
    clave: "intérprete supremo de la Constitución",
    e: "Según el artículo 1.1 de la Ley Orgánica 2/1979, el Tribunal Constitucional se define como:",
    ok: "El intérprete supremo de la Constitución, independiente de los demás órganos constitucionales.",
    mal: ["El órgano jurisdiccional superior en todos los órdenes.", "El supremo órgano consultivo del Estado en materia constitucional.", "El órgano de gobierno del Poder Judicial en materia constitucional."],
    d: 1,
  },
  {
    id: "tai-boe-t10-08", tema: 10, norma: "LOTC", art: "Artículo sexto",
    cita: "El Tribunal Constitucional actúa en Pleno, en Sala o en Sección.",
    clave: "en Pleno, en Sala o en Sección",
    e: "Conforme al artículo 6.1 de la Ley Orgánica del Tribunal Constitucional, el Tribunal actúa:",
    ok: "En Pleno, en Sala o en Sección.",
    mal: ["En Pleno y en Comisiones.", "Solo en Pleno.", "En Pleno, en Salas y en Juzgados constitucionales."],
    d: 1,
  },
  {
    id: "tai-boe-t10-09", tema: 10, norma: "LOTC", art: "Artículo séptimo",
    cita: "El Tribunal Constitucional consta de dos Salas. Cada Sala está compuesta por seis Magistrados nombrados por el Tribunal en Pleno.",
    clave: "seis Magistrados",
    e: "Según el artículo 7.1 de la Ley Orgánica del Tribunal Constitucional, el Tribunal consta de:",
    ok: "Dos Salas, compuestas cada una por seis Magistrados nombrados por el Tribunal en Pleno.",
    mal: ["Tres Salas de cuatro Magistrados.", "Dos Salas de cinco Magistrados más el Presidente.", "Cuatro Salas de tres Magistrados."],
    d: 1,
  },
  {
    id: "tai-boe-t10-10", tema: 10, norma: "LOTC", art: "Artículo séptimo",
    cita: "El Presidente del Tribunal lo es también de la Sala Primera",
    clave: "Sala Primera",
    e: "Conforme al artículo 7.2 de la Ley Orgánica del Tribunal Constitucional, el Presidente del Tribunal preside también:",
    ok: "La Sala Primera.",
    mal: ["La Sala Segunda.", "Todas las Secciones.", "Ninguna Sala: solo el Pleno."],
    j: "La Sala Segunda la preside el Vicepresidente del Tribunal.",
    d: 1,
  },
  {
    id: "tai-boe-t10-11", tema: 10, norma: "LOTC", art: "Artículo treinta y tres",
    cita: "El recurso de inconstitucionalidad se formulará dentro del plazo de tres meses a partir de la publicación de la Ley, disposición o acto con fuerza de Ley impugnado",
    clave: "tres meses",
    e: "Con carácter general, según el artículo 33.1 de la Ley Orgánica del Tribunal Constitucional, el recurso de inconstitucionalidad se formulará dentro del plazo de:",
    ok: "Tres meses a partir de la publicación de la norma impugnada.",
    mal: ["Dos meses a partir de la publicación de la norma impugnada.", "Seis meses a partir de la entrada en vigor de la norma impugnada.", "Nueve meses a partir de la publicación de la norma impugnada."],
    j: "El plazo de nueve meses es el especial del artículo 33.2, cuando se ha intentado evitar el recurso mediante la comisión bilateral de cooperación.",
    d: 1,
  },
  {
    id: "tai-boe-t10-12", tema: 10, norma: "LOTC", art: "Artículo treinta y tres",
    cita: "el Presidente del Gobierno y los órganos colegiados ejecutivos de las Comunidades Autónomas podrán interponer el recurso de inconstitucionalidad en el plazo de nueve meses",
    clave: "órganos colegiados ejecutivos",
    e: "Según el artículo 33.2 de la Ley Orgánica del Tribunal Constitucional, ¿quiénes pueden interponer, cuando se cumplen sus requisitos, el recurso de inconstitucionalidad en el plazo de nueve meses?",
    ok: "El Presidente del Gobierno y los órganos colegiados ejecutivos de las Comunidades Autónomas.",
    mal: ["50 Diputados o 50 Senadores.", "El Defensor del Pueblo.", "Las Asambleas legislativas de las Comunidades Autónomas."],
    d: 3,
  },

  // ── Tema 11 ─────────────────────────────────────────────────────────────
  {
    id: "tai-boe-t11-01", tema: 11, norma: "CE", art: "Artículo 167",
    cita: "Si no hubiera acuerdo entre ambas, se intentará obtenerlo mediante la creación de una Comisión de composición paritaria de Diputados y Senadores, que presentará un texto que será votado por el Congreso y el Senado.",
    clave: "composición paritaria",
    e: "Según el artículo 167.1 de la Constitución, si no hubiera acuerdo entre el Congreso y el Senado sobre un proyecto de reforma constitucional, se intentará obtenerlo mediante:",
    ok: "Una Comisión de composición paritaria de Diputados y Senadores, que presentará un texto que votarán ambas Cámaras.",
    mal: ["Una votación conjunta de las Cortes Generales por mayoría absoluta.", "Un arbitraje del Tribunal Constitucional.", "Un referéndum consultivo convocado por el Rey."],
    d: 1,
  },
  {
    id: "tai-boe-t11-02", tema: 11, norma: "CE", art: "Artículo 168",
    cita: "se procederá a la aprobación del principio por mayoría de dos tercios de cada Cámara, y a la disolución inmediata de las Cortes",
    clave: "dos tercios de cada Cámara",
    e: "Cuando se propone la revisión total de la Constitución, el artículo 168.1 exige que la aprobación del principio se haga por:",
    ok: "Mayoría de dos tercios de cada Cámara, con disolución inmediata de las Cortes.",
    mal: ["Mayoría de tres quintos de cada Cámara.", "Mayoría absoluta del Congreso y del Senado.", "Mayoría de dos tercios del Congreso y mayoría absoluta del Senado."],
    d: 2,
  },
  {
    id: "tai-boe-t11-03", tema: 11, norma: "CE", art: "Artículo 168",
    cita: "Las Cámaras elegidas deberán ratificar la decisión y proceder al estudio del nuevo texto constitucional, que deberá ser aprobado por mayoría de dos tercios de ambas Cámaras.",
    clave: "dos tercios de ambas Cámaras",
    e: "En el procedimiento agravado del artículo 168 de la Constitución, el nuevo texto constitucional deberá ser aprobado por las Cámaras elegidas por:",
    ok: "Mayoría de dos tercios de ambas Cámaras.",
    mal: ["Mayoría de tres quintos de ambas Cámaras.", "Mayoría absoluta del Congreso y del Senado.", "Mayoría de dos tercios del Congreso y mayoría absoluta del Senado."],
    d: 2,
  },

  // ── Tema 16 ─────────────────────────────────────────────────────────────
  {
    id: "tai-boe-t16-01", tema: 16, norma: "ENS", art: "Artículo 5",
    cita: "c) Prevención, detección, respuesta y conservación.",
    clave: "detección, respuesta y conservación",
    e: "¿Cuál de los siguientes es uno de los principios básicos del Esquema Nacional de Seguridad según el artículo 5 del Real Decreto 311/2022?",
    ok: "Prevención, detección, respuesta y conservación.",
    mal: ["Centralización de la seguridad en un único responsable.", "Seguridad por oscuridad.", "Auditoría única en el momento de implantar el sistema."],
    j: "Los principios básicos son: seguridad como proceso integral, gestión basada en los riesgos, prevención, detección, respuesta y conservación, existencia de líneas de defensa, vigilancia continua, reevaluación periódica y diferenciación de responsabilidades.",
    d: 1,
  },
  {
    id: "tai-boe-t16-02", tema: 16, norma: "ENS", art: "Artículo 6",
    cita: "La aplicación del ENS estará presidida por este principio, que excluye cualquier actuación puntual o tratamiento coyuntural.",
    clave: "actuación puntual o tratamiento coyuntural",
    e: "Según el artículo 6.1 del Real Decreto 311/2022, el principio de la seguridad como proceso integral excluye:",
    ok: "Cualquier actuación puntual o tratamiento coyuntural.",
    mal: ["La participación de personal no técnico.", "Los elementos jurídicos y organizativos del sistema.", "La concienciación de los responsables jerárquicos."],
    d: 2,
  },
  {
    id: "tai-boe-t16-03", tema: 16, norma: "ENS", art: "Artículo 12",
    cita: "La política de seguridad de la información es el conjunto de directrices que rigen la forma en que una organización gestiona y protege la información que trata y los servicios que presta.",
    clave: "conjunto de directrices",
    e: "Según el artículo 12.1 del Real Decreto 311/2022, la política de seguridad de la información es:",
    ok: "El conjunto de directrices que rigen la forma en que una organización gestiona y protege la información que trata y los servicios que presta.",
    mal: ["El inventario de los activos del sistema de información.", "El documento que recoge el análisis de riesgos.", "La relación de medidas del anexo II aplicables al sistema."],
    d: 2,
  },
  {
    id: "tai-boe-t16-04", tema: 16, norma: "ENS", art: "Artículo 31",
    cita: "serán objeto de una auditoría regular ordinaria, al menos cada dos años, que verifique el cumplimiento de los requerimientos del ENS",
    clave: "cada dos años",
    e: "Conforme al artículo 31.1 del Real Decreto 311/2022, los sistemas de información sujetos al ENS serán objeto de una auditoría regular ordinaria:",
    ok: "Al menos cada dos años.",
    mal: ["Al menos cada año.", "Al menos cada tres años.", "Al menos cada cuatro años."],
    d: 1,
  },
  {
    id: "tai-boe-t16-05", tema: 16, norma: "ENS", art: "Artículo 31",
    cita: "Con carácter extraordinario, deberá realizarse dicha auditoría siempre que se produzcan modificaciones sustanciales en los sistemas de información, que puedan repercutir en las medidas de seguridad requeridas.",
    clave: "modificaciones sustanciales",
    e: "Según el artículo 31.1 del Real Decreto 311/2022, deberá realizarse una auditoría extraordinaria del ENS:",
    ok: "Siempre que se produzcan modificaciones sustanciales en los sistemas de información que puedan repercutir en las medidas de seguridad.",
    mal: ["Cada vez que cambie el responsable de seguridad.", "Solo cuando lo ordene el Centro Criptológico Nacional.", "Cada vez que se renueve un certificado electrónico del sistema."],
    j: "La auditoría extraordinaria marca además la fecha desde la que se cuentan los dos años de la siguiente auditoría ordinaria.",
    d: 2,
  },
  {
    id: "tai-boe-t16-06", tema: 16, norma: "ENS", art: "Artículo 40",
    cita: "con perjuicio para la disponibilidad, autenticidad, integridad, confidencialidad o trazabilidad",
    clave: "autenticidad, integridad, confidencialidad o trazabilidad",
    e: "Según el artículo 40.2 del Real Decreto 311/2022, la categoría de seguridad de un sistema se determina valorando el impacto de un incidente con perjuicio para la disponibilidad y para:",
    ok: "La autenticidad, integridad, confidencialidad o trazabilidad.",
    mal: ["La eficiencia, la usabilidad y el rendimiento.", "La integridad y la confidencialidad, únicamente.", "La escalabilidad y la interoperabilidad."],
    m: "Dimensiones del ENS: «D-A-I-C-T» (Disponibilidad, Autenticidad, Integridad, Confidencialidad, Trazabilidad).", d: 2,
  },
  {
    id: "tai-boe-t16-07", tema: 16, norma: "LOPDGDD", art: "Artículo 7",
    cita: "El tratamiento de los datos personales de un menor de edad únicamente podrá fundarse en su consentimiento cuando sea mayor de catorce años.",
    clave: "catorce años",
    e: "Según el artículo 7.1 de la Ley Orgánica 3/2018, el tratamiento de los datos personales de un menor de edad únicamente podrá fundarse en su consentimiento cuando sea mayor de:",
    ok: "Catorce años.",
    mal: ["Dieciséis años.", "Trece años.", "Doce años."],
    j: "El Reglamento (UE) 2016/679 fija dieciséis años por defecto, pero permite a los Estados rebajarlo hasta trece; España lo fijó en catorce.",
    d: 1,
  },
  {
    id: "tai-boe-t16-08", tema: 16, norma: "LOPDGDD", art: "Artículo 5",
    cita: "Las obligaciones establecidas en los apartados anteriores se mantendrán aun cuando hubiese finalizado la relación del obligado con el responsable o encargado del tratamiento.",
    clave: "aun cuando hubiese finalizado la relación",
    e: "Conforme al artículo 5.3 de la Ley Orgánica 3/2018, el deber de confidencialidad de quienes intervienen en el tratamiento de datos:",
    ok: "Se mantiene aun cuando hubiese finalizado la relación del obligado con el responsable o encargado del tratamiento.",
    mal: ["Se extingue al terminar la relación laboral o contractual.", "Se mantiene solo durante los dos años siguientes al fin de la relación.", "Solo subsiste respecto de las categorías especiales de datos."],
    d: 1,
  },
  {
    id: "tai-boe-t16-09", tema: 16, norma: "LOPDGDD", art: "Artículo 32",
    cita: "El responsable del tratamiento estará obligado a bloquear los datos cuando proceda a su rectificación o supresión.",
    clave: "bloquear los datos",
    e: "Según el artículo 32.1 de la Ley Orgánica 3/2018, cuando el responsable del tratamiento proceda a la rectificación o supresión de datos estará obligado a:",
    ok: "Bloquear los datos.",
    mal: ["Destruir de inmediato todas las copias.", "Notificarlo a la Agencia Española de Protección de Datos en 72 horas.", "Anonimizar los datos y publicarlos con fines estadísticos."],
    j: "El bloqueo consiste en identificarlos y reservarlos para impedir su tratamiento, salvo su puesta a disposición de jueces, Ministerio Fiscal o Administraciones competentes durante el plazo de prescripción de posibles responsabilidades; después deben destruirse.",
    d: 2,
  },
  {
    id: "tai-boe-t16-10", tema: 16, norma: "LOPDGDD", art: "Artículo 37",
    cita: "el delegado de protección de datos comunicará al afectado la decisión que se hubiera adoptado en el plazo máximo de dos meses a contar desde la recepción de la reclamación",
    clave: "dos meses",
    e: "Si el afectado se dirige al delegado de protección de datos antes de reclamar ante la autoridad de control, según el artículo 37.1 de la Ley Orgánica 3/2018 el delegado le comunicará la decisión adoptada en el plazo máximo de:",
    ok: "Dos meses desde la recepción de la reclamación.",
    mal: ["Un mes desde la recepción de la reclamación.", "Tres meses desde la recepción de la reclamación.", "Quince días desde la recepción de la reclamación."],
    d: 2,
  },
];
