// Segundo bloque de contenido para los temas 12-17 de TAI (ver
// content/tai-temario-2.ts), ampliando cada uno con subtemas
// complementarios que no se solapan con el primer bloque. Mismo criterio
// de fuentes (conocimiento técnico general de dominio público) y
// redacción propia que el resto de content/*.ts de este proyecto.

export const TAI_TEMA12_PARTE2 = `## Software libre y software propietario
El software propietario restringe por licencia su copia, modificación y redistribución, y habitualmente no publica su código fuente (ejemplos: Windows, la suite Office). El software libre garantiza cuatro libertades básicas: usarlo con cualquier propósito, estudiar y modificar su código fuente, redistribuir copias y distribuir versiones modificadas. El código abierto (open source) comparte con el software libre la publicación del código fuente, aunque con matices distintos en cuanto a filosofía y condiciones de licencia; en la práctica, buena parte del software que usa la Administración combina ambos modelos (por ejemplo, distribuciones Linux con aplicaciones propietarias sobre ellas).

## Virtualización y máquinas virtuales
La virtualización permite ejecutar varios sistemas operativos "invitados" sobre un mismo equipo físico "anfitrión", cada uno con la sensación de disponer de su propio hardware dedicado. Un hipervisor es el software que gestiona esa virtualización: de tipo 1 o "bare metal" (se instala directamente sobre el hardware, sin sistema operativo anfitrión, típico en servidores) o de tipo 2 (se ejecuta como una aplicación más sobre un sistema operativo ya instalado, típico en equipos de escritorio para pruebas). Entre sus ventajas: mejor aprovechamiento del hardware, aislamiento entre entornos y facilidad para crear, clonar o eliminar equipos virtuales sin tocar la máquina física.

## Computación en la nube: modelos de servicio
La computación en la nube ofrece recursos informáticos (almacenamiento, procesamiento, aplicaciones) como servicio a través de Internet, sin que la persona usuaria tenga que gestionar el hardware subyacente. Se distinguen tres modelos según el nivel de responsabilidad que asume el proveedor: IaaS (infraestructura como servicio: el proveedor da servidores, almacenamiento y red virtualizados, y el cliente instala y gestiona su propio sistema operativo y aplicaciones), PaaS (plataforma como servicio: el proveedor añade además el sistema operativo y el entorno de ejecución, y el cliente solo despliega su aplicación) y SaaS (software como servicio: el cliente usa directamente una aplicación ya completa, como el correo web).`;

export const TAI_TEMA13_PARTE2 = `## Planificación de procesos y multitarea
Un proceso es un programa en ejecución, con su propio espacio de memoria y estado. El planificador (scheduler) del sistema operativo decide en qué orden y durante cuánto tiempo la CPU atiende a cada proceso, permitiendo la multitarea (varios procesos "simultáneos" en un sistema con menos núcleos que procesos activos, mediante reparto rápido del tiempo de CPU). Un proceso puede estar en distintos estados: en ejecución, listo (esperando turno de CPU) o bloqueado (esperando un recurso, como una operación de entrada/salida). Un hilo o thread es una unidad de ejecución más ligera dentro de un mismo proceso, que comparte memoria con los demás hilos del proceso pero puede ejecutarse de forma independiente.

## Gestión de memoria virtual
La memoria virtual permite que cada proceso trabaje como si dispusiera de un espacio de memoria propio y continuo, aunque físicamente esté repartido o incluso parcialmente ausente de la RAM. El sistema operativo traduce direcciones virtuales a direcciones físicas mediante tablas de páginas, y puede llevar temporalmente a disco las partes de memoria menos usadas (el intercambio o swap) para liberar RAM a los procesos activos. Esta técnica permite ejecutar más programas de los que cabrían físicamente en la RAM instalada, a costa de una posible pérdida de rendimiento si el sistema recurre al swap con demasiada frecuencia.

## Contenedores frente a máquinas virtuales
Un contenedor empaqueta una aplicación junto con sus dependencias, pero compartiendo el núcleo del sistema operativo anfitrión, a diferencia de una máquina virtual, que incluye un sistema operativo completo propio. Esto hace que los contenedores sean mucho más ligeros y rápidos de arrancar que las máquinas virtuales, aunque ofrecen un aislamiento algo menor al depender del mismo núcleo subyacente. Docker es la herramienta de contenedores más extendida, y Kubernetes es el sistema más habitual para orquestar (desplegar, escalar y gestionar) grandes conjuntos de contenedores en producción.`;

export const TAI_TEMA14_PARTE2 = `## Paradigmas de programación
Un paradigma de programación es un estilo o enfoque para estructurar y resolver un problema mediante código. La programación estructurada organiza el programa en secuencias, condicionales y bucles, evitando saltos incontrolados. La programación orientada a objetos (POO) modela el problema como un conjunto de objetos que combinan datos (atributos) y comportamiento (métodos), con conceptos como la herencia (una clase reutiliza y extiende el comportamiento de otra), el encapsulamiento (ocultar los detalles internos de un objeto) y el polimorfismo (un mismo método se comporta de forma distinta según el objeto que lo invoca). La programación funcional trata la computación como la evaluación de funciones matemáticas, evitando el estado mutable y los efectos secundarios.

## Compilación e interpretación
Un compilador traduce el código fuente completo a código máquina antes de ejecutarlo, generando un archivo ejecutable independiente (típico de C o C++); la ejecución posterior es rápida, pero cualquier cambio exige recompilar. Un intérprete traduce y ejecuta el código línea a línea en el momento, sin generar un ejecutable previo (típico de Python o JavaScript en su forma más básica); es más flexible para probar cambios pero habitualmente más lento en ejecución. Muchos lenguajes modernos (Java, C#) usan un enfoque intermedio: compilan a un código intermedio (bytecode) que después ejecuta o compila en el momento una máquina virtual específica del lenguaje.

## Estructuras de datos básicas
Una estructura de datos organiza la información para que ciertas operaciones sean eficientes. Un array o vector almacena elementos del mismo tipo en posiciones consecutivas, accesibles directamente por índice. Una lista enlazada encadena elementos mediante punteros o referencias, con inserciones y borrados más ágiles que en un array pero acceso secuencial más lento. Una pila (stack) sigue el orden LIFO ("último en entrar, primero en salir"), típica en la gestión de llamadas a funciones. Una cola (queue) sigue el orden FIFO ("primero en entrar, primero en salir"), típica en la gestión de tareas pendientes o peticiones en espera.`;

export const TAI_TEMA15_PARTE2 = `## Arquitectura cliente-servidor y APIs REST
En el modelo cliente-servidor, el cliente (típicamente el navegador) solicita recursos o acciones y el servidor los procesa y responde. Una API (interfaz de programación de aplicaciones) es el contrato que define cómo un cliente puede comunicarse con un servidor: qué operaciones existen, qué datos hay que enviar y qué formato tendrá la respuesta. El estilo REST (Representational State Transfer) es el más habitual en aplicaciones web actuales: usa los verbos HTTP (GET para consultar, POST para crear, PUT/PATCH para modificar, DELETE para eliminar) sobre URLs que identifican recursos, y suele intercambiar los datos en formato JSON por su ligereza y facilidad de lectura frente a XML.

## Bases de datos relacionales y no relacionales
Una base de datos relacional organiza la información en tablas con filas y columnas, relacionadas entre sí mediante claves, y se consulta con SQL (Structured Query Language); garantiza las propiedades ACID (atomicidad, consistencia, aislamiento y durabilidad) que aseguran la fiabilidad de las transacciones, algo especialmente relevante en sistemas de la Administración. Una base de datos no relacional (NoSQL) prescinde de ese esquema rígido de tablas para ganar flexibilidad y escalabilidad horizontal: puede organizar los datos como documentos (JSON), pares clave-valor, grafos o columnas anchas, según el caso de uso, a costa habitualmente de garantías transaccionales más débiles que las de una base relacional.

## Seguridad básica en aplicaciones web
Entre las vulnerabilidades más frecuentes en aplicaciones web están la inyección SQL (insertar código malicioso en un campo de entrada mal validado para manipular una consulta a la base de datos), el Cross-Site Scripting o XSS (inyectar scripts que se ejecutan en el navegador de otras personas usuarias al visitar la página) y la falta de control de acceso adecuado (permitir a una persona usuaria autenticada acceder a recursos que no le corresponden). Las medidas básicas de defensa incluyen validar y depurar toda entrada de datos, usar consultas parametrizadas en vez de construir SQL a partir de texto concatenado, cifrar las comunicaciones con HTTPS y mantener actualizadas las dependencias del proyecto.`;

export const TAI_TEMA16_PARTE2 = `## Autenticación y gestión de contraseñas
La autenticación verifica que una persona es quien dice ser, habitualmente mediante uno o varios factores: algo que se sabe (una contraseña), algo que se tiene (un token físico o el propio teléfono móvil) o algo que se es (una huella dactilar u otro rasgo biométrico). La autenticación multifactor (MFA) combina al menos dos de estos factores, reduciendo drásticamente el riesgo de que una contraseña filtrada sea suficiente para acceder a una cuenta. Las contraseñas nunca deben almacenarse en texto plano: los sistemas bien diseñados guardan un resumen o hash (una transformación irreversible) de la contraseña, de modo que ni siquiera el propio sistema puede recuperar la contraseña original a partir de lo almacenado.

## Copias de seguridad y planes de contingencia
Una copia de seguridad (backup) es una réplica de la información que permite recuperarla ante un borrado accidental, un fallo de hardware o un ataque como el ransomware. Las estrategias habituales combinan copias completas (todo el conjunto de datos) con copias incrementales (solo lo que ha cambiado desde la última copia), y siguen la regla básica de mantener al menos tres copias, en dos soportes distintos, con una de ellas fuera de las instalaciones principales. Un plan de contingencia va más allá de la copia de seguridad: define cómo restaurar el servicio ante una incidencia grave, con objetivos concretos de tiempo máximo de recuperación (RTO) y de pérdida de datos asumible (RPO).

## El Esquema Nacional de Seguridad (ENS)
El ENS es el marco normativo que fija los principios básicos y los requisitos mínimos de seguridad que deben cumplir los sistemas de información de las Administraciones Públicas españolas, con el objetivo de garantizar el acceso, la confidencialidad, la integridad, la disponibilidad, la trazabilidad y la autenticidad de la información que manejan. Clasifica los sistemas en tres categorías (básica, media y alta) según el impacto que tendría un incidente de seguridad sobre ellos, y exige medidas de seguridad proporcionales a esa categoría. El CCN-CERT, dependiente del Centro Criptológico Nacional, es el organismo de referencia para la respuesta a incidentes de seguridad en el sector público español.`;

export const TAI_TEMA17_PARTE2 = `## El Sistema de Nombres de Dominio (DNS)
El DNS traduce nombres de dominio legibles por personas (como oponow.com) a direcciones IP, que son las que realmente usan los equipos para comunicarse entre sí. Funciona de forma jerárquica y distribuida: un servidor raíz remite a los servidores del dominio de nivel superior (.com, .es), estos remiten al servidor autoritativo del dominio concreto, y este último devuelve la dirección IP correspondiente. Los servidores DNS recursivos (habitualmente los del proveedor de Internet) resuelven esta cadena de consultas en nombre del equipo cliente y guardan el resultado en caché durante un tiempo para agilizar peticiones futuras al mismo dominio.

## Encaminamiento y dispositivos de red
El encaminamiento (routing) es el proceso de decidir por qué camino debe viajar cada paquete de datos para llegar a su destino a través de varias redes intermedias. Un router o encaminador conecta redes distintas y decide, según su tabla de rutas, hacia qué siguiente salto reenviar cada paquete. Un switch o conmutador conecta dispositivos dentro de una misma red local y reenvía el tráfico solo al puerto donde está conectado el destinatario, a diferencia de un hub, que reenvía indiscriminadamente a todos los puertos. Un firewall o cortafuegos filtra el tráfico de red según reglas de seguridad, permitiendo o bloqueando conexiones según su origen, destino o tipo de servicio.

## IPv6 y traducción de direcciones (NAT)
IPv6 usa direcciones de 128 bits, frente a los 32 bits de IPv4, lo que multiplica extraordinariamente el espacio de direcciones disponible y resuelve el agotamiento de IPv4. Mientras la transición a IPv6 se completa, muchas redes IPv4 usan NAT (Network Address Translation) para que varios equipos de una red privada (con direcciones no enrutables públicamente, como las del rango 192.168.x.x) compartan una única dirección IP pública para salir a Internet, traduciendo las direcciones y puertos de cada conexión saliente y entrante. El NAT permitió, además de aliviar la escasez de direcciones IPv4, una capa adicional de aislamiento entre la red interna y el exterior.`;
