// Temas 1 (Constitución: Título preliminar y Título I), 2 (principios de la
// actuación administrativa) y 3 (la Corona). Ver tai-banco-boe.ts.
import type { PreguntaBoe } from "./tai-banco-boe";

export const BANCO_BOE_1: PreguntaBoe[] = [
  // ── Tema 1 ──────────────────────────────────────────────────────────────
  {
    id: "tai-boe-t01-01", tema: 1, norma: "CE", art: "Artículo 9",
    cita: "Los ciudadanos y los poderes públicos están sujetos a la Constitución y al resto del ordenamiento jurídico.",
    clave: "Los ciudadanos y los poderes públicos",
    e: "Según el artículo 9.1 de la Constitución, ¿quiénes están sujetos a la Constitución y al resto del ordenamiento jurídico?",
    ok: "Los ciudadanos y los poderes públicos.",
    mal: ["Solo los poderes públicos.", "Solo los ciudadanos españoles mayores de edad.", "Los poderes públicos y los extranjeros residentes."],
    m: "9.1: sujeción de TODOS, ciudadanos y poderes públicos.", d: 1,
  },
  {
    id: "tai-boe-t01-02", tema: 1, norma: "CE", art: "Artículo 9",
    cita: "remover los obstáculos que impidan o dificulten su plenitud",
    clave: "remover los obstáculos",
    e: "Conforme al artículo 9.2 de la Constitución, respecto de la libertad y la igualdad del individuo y de los grupos en que se integra, corresponde a los poderes públicos, entre otras cosas:",
    ok: "Remover los obstáculos que impidan o dificulten su plenitud.",
    mal: ["Declararlas por ley orgánica al inicio de cada legislatura.", "Limitar su ejercicio cuando lo exija el interés general.", "Garantizarlas únicamente en el ámbito de las relaciones laborales."],
    j: "El 9.2 recoge la igualdad material: promover condiciones, remover obstáculos y facilitar la participación.",
    m: "9.2 = «PRF»: Promover, Remover, Facilitar.", d: 2,
  },
  {
    id: "tai-boe-t01-03", tema: 1, norma: "CE", art: "Artículo 11",
    cita: "La nacionalidad española se adquiere, se conserva y se pierde de acuerdo con lo establecido por la ley.",
    clave: "establecido por la ley",
    e: "Según el artículo 11.1 de la Constitución, la nacionalidad española se adquiere, se conserva y se pierde:",
    ok: "De acuerdo con lo establecido por la ley.",
    mal: ["De acuerdo con lo que dispongan los tratados internacionales ratificados.", "Según lo que resuelva el Ministerio de Justicia en cada caso.", "Conforme a lo que acuerden las Cortes Generales mediante resolución."],
    d: 1,
  },
  {
    id: "tai-boe-t01-04", tema: 1, norma: "CE", art: "Artículo 11",
    cita: "El Estado podrá concertar tratados de doble nacionalidad con los países iberoamericanos o con aquellos que hayan tenido o tengan una particular vinculación con España.",
    clave: "países iberoamericanos",
    e: "De acuerdo con el artículo 11.3 de la Constitución, el Estado podrá concertar tratados de doble nacionalidad con:",
    ok: "Los países iberoamericanos o aquellos que hayan tenido o tengan una particular vinculación con España.",
    mal: ["Exclusivamente los Estados miembros de la Unión Europea.", "Cualquier Estado, siempre que exista reciprocidad.", "Solo los Estados con los que España comparta frontera."],
    d: 1,
  },
  {
    id: "tai-boe-t01-05", tema: 1, norma: "CE", art: "Artículo 13",
    cita: "Quedan excluidos de la extradición los delitos políticos, no considerándose como tales los actos de terrorismo.",
    clave: "no considerándose como tales los actos de terrorismo",
    e: "Según el artículo 13.3 de la Constitución, quedan excluidos de la extradición:",
    ok: "Los delitos políticos, no considerándose como tales los actos de terrorismo.",
    mal: ["Los delitos políticos, incluidos los actos de terrorismo.", "Los delitos castigados con pena de prisión inferior a tres años.", "Los delitos cometidos por nacionales de Estados de la Unión Europea."],
    j: "La extradición solo se concede en cumplimiento de un tratado o de la ley y atendiendo al principio de reciprocidad; el terrorismo nunca se considera delito político a estos efectos.",
    d: 2,
  },
  {
    id: "tai-boe-t01-06", tema: 1, norma: "CE", art: "Artículo 13",
    cita: "La ley establecerá los términos en que los ciudadanos de otros países y los apátridas podrán gozar del derecho de asilo en España.",
    clave: "apátridas",
    e: "Conforme al artículo 13.4 de la Constitución, la ley establecerá los términos en que podrán gozar del derecho de asilo en España:",
    ok: "Los ciudadanos de otros países y los apátridas.",
    mal: ["Solo los nacionales de Estados no pertenecientes a la Unión Europea.", "Únicamente los perseguidos por delitos políticos.", "Solo los ciudadanos de países con tratado de reciprocidad con España."],
    d: 2,
  },
  {
    id: "tai-boe-t01-07", tema: 1, norma: "CE", art: "Artículo 16",
    cita: "sin más limitación, en sus manifestaciones, que la necesaria para el mantenimiento del orden público protegido por la ley",
    clave: "orden público",
    e: "Según el artículo 16.1 de la Constitución, la libertad ideológica, religiosa y de culto no tiene, en sus manifestaciones, más limitación que:",
    ok: "La necesaria para el mantenimiento del orden público protegido por la ley.",
    mal: ["La que establezcan los acuerdos con la Santa Sede.", "La moral pública y las buenas costumbres.", "La que determine el Gobierno mediante real decreto."],
    d: 1,
  },
  {
    id: "tai-boe-t01-08", tema: 1, norma: "CE", art: "Artículo 16",
    cita: "Nadie podrá ser obligado a declarar sobre su ideología, religión o creencias.",
    clave: "Nadie podrá ser obligado a declarar",
    e: "En relación con la ideología, religión o creencias, el artículo 16.2 de la Constitución establece que:",
    ok: "Nadie podrá ser obligado a declarar sobre su ideología, religión o creencias.",
    mal: ["Los funcionarios deberán declarar sus creencias al tomar posesión.", "Solo podrá exigirse su declaración con autorización judicial.", "Su declaración es obligatoria a efectos estadísticos."],
    d: 1,
  },
  {
    id: "tai-boe-t01-09", tema: 1, norma: "CE", art: "Artículo 17",
    cita: "Toda persona tiene derecho a la libertad y a la seguridad.",
    clave: "a la libertad y a la seguridad",
    e: "Según el artículo 17.1 de la Constitución, toda persona tiene derecho:",
    ok: "A la libertad y a la seguridad.",
    mal: ["A la vida y a la integridad física y moral.", "Al honor y a la propia imagen.", "A la tutela judicial efectiva."],
    j: "La vida y la integridad física y moral están en el artículo 15; el honor y la propia imagen, en el 18.1; la tutela judicial, en el 24.1.",
    d: 1,
  },
  {
    id: "tai-boe-t01-10", tema: 1, norma: "CE", art: "Artículo 17",
    cita: "Toda persona detenida debe ser informada de forma inmediata, y de modo que le sea comprensible, de sus derechos y de las razones de su detención, no pudiendo ser obligada a declarar.",
    clave: "de forma inmediata",
    e: "Conforme al artículo 17.3 de la Constitución, toda persona detenida debe ser informada de sus derechos y de las razones de su detención:",
    ok: "De forma inmediata, y de modo que le sea comprensible.",
    mal: ["En el plazo máximo de veinticuatro horas.", "Por escrito, antes de que transcurran setenta y dos horas.", "Cuando sea puesta a disposición de la autoridad judicial."],
    d: 2,
  },
  {
    id: "tai-boe-t01-11", tema: 1, norma: "CE", art: "Artículo 17",
    cita: "La ley regulará un procedimiento de «habeas corpus» para producir la inmediata puesta a disposición judicial de toda persona detenida ilegalmente.",
    clave: "detenida ilegalmente",
    e: "Según el artículo 17.4 de la Constitución, el procedimiento de «habeas corpus» tiene por objeto:",
    ok: "Producir la inmediata puesta a disposición judicial de toda persona detenida ilegalmente.",
    mal: ["Garantizar la asistencia de abogado en las diligencias policiales.", "Fijar el plazo máximo de duración de la prisión provisional.", "Permitir la revisión de las sentencias penales firmes."],
    j: "El mismo apartado remite a la ley el plazo máximo de la prisión provisional, pero ese no es el objeto del habeas corpus.",
    d: 2,
  },
  {
    id: "tai-boe-t01-12", tema: 1, norma: "CE", art: "Artículo 18",
    cita: "Se garantiza el derecho al honor, a la intimidad personal y familiar y a la propia imagen.",
    clave: "propia imagen",
    e: "El artículo 18.1 de la Constitución garantiza:",
    ok: "El derecho al honor, a la intimidad personal y familiar y a la propia imagen.",
    mal: ["El derecho a la libertad y a la seguridad.", "La inviolabilidad del domicilio y la libertad de residencia.", "La libertad de expresión y de información."],
    d: 1,
  },
  {
    id: "tai-boe-t01-13", tema: 1, norma: "CE", art: "Artículo 18",
    cita: "Se garantiza el secreto de las comunicaciones y, en especial, de las postales, telegráficas y telefónicas, salvo resolución judicial.",
    clave: "resolución judicial",
    e: "Según el artículo 18.3 de la Constitución, el secreto de las comunicaciones, en especial de las postales, telegráficas y telefónicas, se garantiza salvo:",
    ok: "Resolución judicial.",
    mal: ["Autorización del Ministerio del Interior.", "Orden del Ministerio Fiscal.", "Consentimiento del Delegado del Gobierno."],
    d: 1,
  },
  {
    id: "tai-boe-t01-14", tema: 1, norma: "CE", art: "Artículo 18",
    cita: "La ley limitará el uso de la informática para garantizar el honor y la intimidad personal y familiar de los ciudadanos y el pleno ejercicio de sus derechos.",
    clave: "intimidad personal y familiar",
    e: "Conforme al artículo 18.4 de la Constitución, la ley limitará el uso de la informática para garantizar:",
    ok: "El honor y la intimidad personal y familiar de los ciudadanos y el pleno ejercicio de sus derechos.",
    mal: ["La seguridad nacional y la defensa de los intereses del Estado.", "La libre competencia en el mercado de las telecomunicaciones.", "La interoperabilidad de los sistemas de las Administraciones públicas."],
    j: "Es la base constitucional del derecho fundamental a la protección de datos personales.",
    m: "18.4: la informática, con límites, para proteger honor e intimidad.", d: 1,
  },
  {
    id: "tai-boe-t01-15", tema: 1, norma: "CE", art: "Artículo 19",
    cita: "Este derecho no podrá ser limitado por motivos políticos o ideológicos.",
    clave: "políticos o ideológicos",
    e: "Según el artículo 19 de la Constitución, el derecho de los españoles a entrar y salir libremente de España no podrá ser limitado por motivos:",
    ok: "Políticos o ideológicos.",
    mal: ["Sanitarios o de salud pública.", "Económicos o fiscales.", "Judiciales o penales."],
    d: 2,
  },
  {
    id: "tai-boe-t01-16", tema: 1, norma: "CE", art: "Artículo 20",
    cita: "El ejercicio de estos derechos no puede restringirse mediante ningún tipo de censura previa.",
    clave: "censura previa",
    e: "¿Qué prohíbe expresamente el artículo 20.2 de la Constitución respecto del ejercicio de las libertades de expresión e información?",
    ok: "Restringirlo mediante ningún tipo de censura previa.",
    mal: ["Regularlo mediante ley orgánica.", "Limitarlo por respeto al derecho al honor.", "Acordar el secuestro de publicaciones por resolución judicial."],
    j: "El honor es precisamente uno de sus límites (20.4) y el secuestro judicial está permitido (20.5).",
    d: 2,
  },
  {
    id: "tai-boe-t01-17", tema: 1, norma: "CE", art: "Artículo 20",
    cita: "especialmente, en el derecho al honor, a la intimidad, a la propia imagen y a la protección de la juventud y de la infancia",
    clave: "juventud y de la infancia",
    e: "Según el artículo 20.4 de la Constitución, las libertades del artículo 20 tienen su límite, especialmente, en el derecho al honor, a la intimidad, a la propia imagen y:",
    ok: "A la protección de la juventud y de la infancia.",
    mal: ["A la seguridad nacional.", "Al secreto de los asuntos de Estado.", "A la protección de la salud pública."],
    d: 2,
  },
  {
    id: "tai-boe-t01-18", tema: 1, norma: "CE", art: "Artículo 20",
    cita: "c) A la libertad de cátedra.",
    clave: "libertad de cátedra",
    e: "¿Cuál de los siguientes derechos se reconoce en el artículo 20.1 de la Constitución?",
    ok: "La libertad de cátedra.",
    mal: ["La libertad de enseñanza.", "La autonomía de las Universidades.", "El derecho de petición."],
    j: "La libertad de enseñanza y la autonomía universitaria están en el artículo 27 (apartados 1 y 10) y el derecho de petición, en el 29.",
    d: 2,
  },
  {
    id: "tai-boe-t01-19", tema: 1, norma: "CE", art: "Artículo 20",
    cita: "La ley regulará el derecho a la cláusula de conciencia y al secreto profesional en el ejercicio de estas libertades.",
    clave: "cláusula de conciencia",
    e: "En relación con la libertad de información, el artículo 20.1.d) de la Constitución remite a la ley la regulación del derecho:",
    ok: "A la cláusula de conciencia y al secreto profesional.",
    mal: ["De rectificación y de réplica.", "A la objeción de conciencia y a la prestación social sustitutoria.", "Al secreto de las comunicaciones y a la inviolabilidad del domicilio."],
    d: 2,
  },
  {
    id: "tai-boe-t01-20", tema: 1, norma: "CE", art: "Artículo 21",
    cita: "El ejercicio de este derecho no necesitará autorización previa.",
    clave: "no necesitará autorización previa",
    e: "Según el artículo 21.1 de la Constitución, el derecho de reunión pacífica y sin armas:",
    ok: "No necesitará autorización previa.",
    mal: ["Requiere autorización previa de la Delegación del Gobierno.", "Requiere autorización previa si participan más de veinte personas.", "Necesita autorización judicial cuando se celebra en lugares de tránsito público."],
    d: 1,
  },
  {
    id: "tai-boe-t01-21", tema: 1, norma: "CE", art: "Artículo 24",
    cita: "sin que, en ningún caso, pueda producirse indefensión",
    clave: "indefensión",
    e: "El artículo 24.1 de la Constitución reconoce a todas las personas el derecho a obtener la tutela efectiva de los jueces y tribunales sin que, en ningún caso, pueda producirse:",
    ok: "Indefensión.",
    mal: ["Dilación.", "Desigualdad procesal.", "Prescripción."],
    d: 1,
  },
  {
    id: "tai-boe-t01-22", tema: 1, norma: "CE", art: "Artículo 25",
    cita: "Nadie puede ser condenado o sancionado por acciones u omisiones que en el momento de producirse no constituyan delito, falta o infracción administrativa, según la legislación vigente en aquel momento.",
    clave: "de producirse",
    e: "Según el artículo 25.1 de la Constitución, nadie puede ser condenado o sancionado por acciones u omisiones que no constituyan delito, falta o infracción administrativa según la legislación vigente en el momento:",
    ok: "De producirse.",
    mal: ["De dictarse la sentencia.", "De iniciarse el procedimiento.", "De ejecutarse la sanción."],
    j: "Es el principio de legalidad penal y sancionadora: cuenta la ley vigente cuando se cometen los hechos.",
    d: 2,
  },
  {
    id: "tai-boe-t01-23", tema: 1, norma: "CE", art: "Artículo 25",
    cita: "Las penas privativas de libertad y las medidas de seguridad estarán orientadas hacia la reeducación y reinserción social y no podrán consistir en trabajos forzados.",
    clave: "reeducación y reinserción social",
    e: "Conforme al artículo 25.2 de la Constitución, las penas privativas de libertad y las medidas de seguridad estarán orientadas hacia:",
    ok: "La reeducación y reinserción social.",
    mal: ["La retribución del daño causado.", "La prevención general y la intimidación.", "La reparación económica a la víctima."],
    d: 1,
  },
  {
    id: "tai-boe-t01-24", tema: 1, norma: "CE", art: "Artículo 25",
    cita: "En todo caso, tendrá derecho a un trabajo remunerado y a los beneficios correspondientes de la Seguridad Social",
    clave: "trabajo remunerado",
    e: "Según el artículo 25.2 de la Constitución, el condenado a pena de prisión tendrá derecho, en todo caso:",
    ok: "A un trabajo remunerado y a los beneficios correspondientes de la Seguridad Social.",
    mal: ["A la reducción de la condena por cada día trabajado.", "A permisos de salida semanales.", "A cumplir la pena en su comunidad autónoma de residencia."],
    d: 2,
  },
  {
    id: "tai-boe-t01-25", tema: 1, norma: "CE", art: "Artículo 27",
    cita: "Se reconoce la autonomía de las Universidades, en los términos que la ley establezca.",
    clave: "autonomía de las Universidades",
    e: "El artículo 27.10 de la Constitución reconoce:",
    ok: "La autonomía de las Universidades, en los términos que la ley establezca.",
    mal: ["La gratuidad de la enseñanza universitaria.", "La competencia exclusiva del Estado sobre las Universidades.", "La obligatoriedad de la enseñanza secundaria superior."],
    d: 1,
  },
  {
    id: "tai-boe-t01-26", tema: 1, norma: "CE", art: "Artículo 27",
    cita: "Los profesores, los padres y, en su caso, los alumnos intervendrán en el control y gestión de todos los centros sostenidos por la Administración con fondos públicos",
    clave: "en su caso, los alumnos",
    e: "Según el artículo 27.7 de la Constitución, ¿quiénes intervendrán en el control y gestión de los centros sostenidos por la Administración con fondos públicos?",
    ok: "Los profesores, los padres y, en su caso, los alumnos.",
    mal: ["Exclusivamente la Administración educativa titular.", "Los profesores y la inspección educativa.", "Los padres y los ayuntamientos."],
    d: 2,
  },
  {
    id: "tai-boe-t01-27", tema: 1, norma: "CE", art: "Artículo 29",
    cita: "Todos los españoles tendrán el derecho de petición individual y colectiva, por escrito, en la forma y con los efectos que determine la ley.",
    clave: "por escrito",
    e: "Según el artículo 29.1 de la Constitución, el derecho de petición de los españoles es:",
    ok: "Individual y colectivo, y se ejerce por escrito.",
    mal: ["Individual y colectivo, de forma oral o escrita.", "Solo individual, por cualquier medio.", "Solo colectivo, mediante representante."],
    d: 2,
  },
  {
    id: "tai-boe-t01-28", tema: 1, norma: "CE", art: "Artículo 32",
    cita: "El hombre y la mujer tienen derecho a contraer matrimonio con plena igualdad jurídica.",
    clave: "plena igualdad jurídica",
    e: "Conforme al artículo 32.1 de la Constitución, el hombre y la mujer tienen derecho a contraer matrimonio:",
    ok: "Con plena igualdad jurídica.",
    mal: ["Conforme a las normas de su confesión religiosa.", "Una vez alcanzada la mayoría de edad.", "Previa autorización del Registro Civil."],
    d: 1,
  },
  {
    id: "tai-boe-t01-29", tema: 1, norma: "CE", art: "Artículo 36",
    cita: "La estructura interna y el funcionamiento de los Colegios deberán ser democráticos.",
    clave: "democráticos",
    e: "Según el artículo 36 de la Constitución, la estructura interna y el funcionamiento de los Colegios Profesionales:",
    ok: "Deberán ser democráticos.",
    mal: ["Los regula cada Colegio sin intervención de la ley.", "Están sometidos a la tutela del Ministerio de Justicia.", "Deben ser aprobados por las Cortes Generales."],
    d: 1,
  },
  {
    id: "tai-boe-t01-30", tema: 1, norma: "CE", art: "Artículo 37",
    cita: "La ley garantizará el derecho a la negociación colectiva laboral entre los representantes de los trabajadores y empresarios, así como la fuerza vinculante de los convenios.",
    clave: "fuerza vinculante",
    e: "El artículo 37.1 de la Constitución dispone que la ley garantizará el derecho a la negociación colectiva laboral, así como:",
    ok: "La fuerza vinculante de los convenios.",
    mal: ["La aprobación de los convenios por el Gobierno.", "La extensión automática de los convenios a todo el sector público.", "La revisión anual de los convenios por la jurisdicción social."],
    d: 1,
  },
  {
    id: "tai-boe-t01-31", tema: 1, norma: "CE", art: "Artículo 40",
    cita: "De manera especial realizarán una política orientada al pleno empleo.",
    clave: "pleno empleo",
    e: "Según el artículo 40.1 de la Constitución, los poderes públicos realizarán de manera especial una política orientada:",
    ok: "Al pleno empleo.",
    mal: ["A la estabilidad de precios.", "Al equilibrio presupuestario.", "A la reducción de la deuda pública."],
    d: 1,
  },
  {
    id: "tai-boe-t01-32", tema: 1, norma: "CE", art: "Artículo 43",
    cita: "Los poderes públicos fomentarán la educación sanitaria, la educación física y el deporte.",
    clave: "educación física y el deporte",
    e: "Conforme al artículo 43.3 de la Constitución, los poderes públicos fomentarán:",
    ok: "La educación sanitaria, la educación física y el deporte.",
    mal: ["La investigación biomédica y la industria farmacéutica.", "El turismo y la hostelería.", "La conservación del patrimonio histórico."],
    d: 1,
  },
  {
    id: "tai-boe-t01-33", tema: 1, norma: "CE", art: "Artículo 46",
    cita: "La ley penal sancionará los atentados contra este patrimonio.",
    clave: "ley penal",
    e: "Según el artículo 46 de la Constitución, los atentados contra el patrimonio histórico, cultural y artístico serán sancionados por:",
    ok: "La ley penal.",
    mal: ["Las comunidades autónomas mediante reglamento.", "El Ministerio de Cultura por vía disciplinaria.", "Los ayuntamientos mediante ordenanza."],
    d: 1,
  },
  {
    id: "tai-boe-t01-34", tema: 1, norma: "CE", art: "Artículo 50",
    cita: "Los poderes públicos garantizarán, mediante pensiones adecuadas y periódicamente actualizadas, la suficiencia económica a los ciudadanos durante la tercera edad.",
    clave: "periódicamente actualizadas",
    e: "Según el artículo 50 de la Constitución, los poderes públicos garantizarán la suficiencia económica a los ciudadanos durante la tercera edad mediante:",
    ok: "Pensiones adecuadas y periódicamente actualizadas.",
    mal: ["Pensiones exclusivamente contributivas.", "Un ingreso mínimo vital de carácter universal.", "Pensiones revisadas cada cinco años por ley orgánica."],
    d: 1,
  },
  {
    id: "tai-boe-t01-35", tema: 1, norma: "CE", art: "Artículo 48",
    cita: "Los poderes públicos promoverán las condiciones para la participación libre y eficaz de la juventud en el desarrollo político, social, económico y cultural.",
    clave: "libre y eficaz",
    e: "El artículo 48 de la Constitución encomienda a los poderes públicos promover las condiciones para:",
    ok: "La participación libre y eficaz de la juventud en el desarrollo político, social, económico y cultural.",
    mal: ["La participación obligatoria de la juventud en un servicio civil.", "La reserva de puestos para jóvenes en las listas electorales.", "La emancipación de los jóvenes a partir de los dieciséis años."],
    d: 1,
  },


  // ── Tema 2 ──────────────────────────────────────────────────────────────
  {
    id: "tai-boe-t02-01", tema: 2, norma: "CE", art: "Artículo 103",
    cita: "actúa de acuerdo con los principios de eficacia, jerarquía, descentralización, desconcentración y coordinación",
    clave: "coordinación",
    e: "Según el artículo 103.1 de la Constitución, la Administración Pública actúa de acuerdo con los principios de eficacia, jerarquía, descentralización, desconcentración y:",
    ok: "Coordinación.",
    mal: ["Cooperación.", "Colaboración.", "Subsidiariedad."],
    m: "103.1 = «EJDDC»: Eficacia, Jerarquía, Descentralización, Desconcentración y Coordinación.", d: 1,
  },
  {
    id: "tai-boe-t02-02", tema: 2, norma: "CE", art: "Artículo 103",
    cita: "La Administración Pública sirve con objetividad los intereses generales",
    clave: "objetividad",
    e: "Conforme al artículo 103.1 de la Constitución, la Administración Pública sirve los intereses generales:",
    ok: "Con objetividad.",
    mal: ["Con neutralidad política.", "Con imparcialidad y eficiencia.", "Con transparencia."],
    d: 1,
  },
  {
    id: "tai-boe-t02-03", tema: 2, norma: "CE", art: "Artículo 103",
    cita: "con sometimiento pleno a la ley y al Derecho",
    clave: "a la ley y al Derecho",
    e: "Según el artículo 103.1 de la Constitución, la Administración Pública actúa con sometimiento pleno:",
    ok: "A la ley y al Derecho.",
    mal: ["A los tratados internacionales y a la costumbre.", "A las instrucciones del Gobierno.", "A los principios generales del Derecho administrativo."],
    d: 1,
  },
  {
    id: "tai-boe-t02-04", tema: 2, norma: "LRJSP", art: "Artículo 3",
    cita: "con sometimiento pleno a la Constitución, a la Ley y al Derecho",
    clave: "a la Constitución, a la Ley y al Derecho",
    e: "A diferencia del artículo 103.1 de la Constitución, el artículo 3.1 de la Ley 40/2015 dice que las Administraciones Públicas actúan con sometimiento pleno:",
    ok: "A la Constitución, a la Ley y al Derecho.",
    mal: ["A la Ley y al Derecho, exclusivamente.", "A los Estatutos de Autonomía y a las ordenanzas locales.", "A las directrices de la Unión Europea."],
    d: 2,
  },
  {
    id: "tai-boe-t02-05", tema: 2, norma: "CE", art: "Artículo 103",
    cita: "el acceso a la función pública de acuerdo con los principios de mérito y capacidad",
    clave: "mérito y capacidad",
    e: "Según el artículo 103.3 de la Constitución, la ley regulará el acceso a la función pública de acuerdo con los principios de:",
    ok: "Mérito y capacidad.",
    mal: ["Igualdad y publicidad.", "Antigüedad y titulación.", "Libre designación y confianza."],
    d: 1,
  },
  {
    id: "tai-boe-t02-06", tema: 2, norma: "CE", art: "Artículo 103",
    cita: "Los órganos de la Administración del Estado son creados, regidos y coordinados de acuerdo con la ley.",
    clave: "creados, regidos y coordinados",
    e: "Según el artículo 103.2 de la Constitución, los órganos de la Administración del Estado son:",
    ok: "Creados, regidos y coordinados de acuerdo con la ley.",
    mal: ["Creados por real decreto y regidos por sus propios estatutos.", "Creados y suprimidos libremente por cada Ministro.", "Regidos por los reglamentos de cada departamento, sin reserva de ley."],
    d: 2,
  },
  {
    id: "tai-boe-t02-07", tema: 2, norma: "CE", art: "Artículo 105",
    cita: "La audiencia de los ciudadanos, directamente o a través de las organizaciones y asociaciones reconocidas por la ley, en el procedimiento de elaboración de las disposiciones administrativas que les afecten.",
    clave: "organizaciones y asociaciones reconocidas por la ley",
    e: "Según el artículo 105.a) de la Constitución, la ley regulará la audiencia de los ciudadanos en el procedimiento de elaboración de las disposiciones administrativas que les afecten:",
    ok: "Directamente o a través de las organizaciones y asociaciones reconocidas por la ley.",
    mal: ["Exclusivamente a través de sus representantes parlamentarios.", "Solo mediante el trámite de información pública en el BOE.", "Únicamente a través de los colegios profesionales."],
    d: 2,
  },
  {
    id: "tai-boe-t02-08", tema: 2, norma: "CE", art: "Artículo 105",
    cita: "salvo en lo que afecte a la seguridad y defensa del Estado, la averiguación de los delitos y la intimidad de las personas",
    clave: "averiguación de los delitos",
    e: "El artículo 105.b) de la Constitución remite a la ley el acceso de los ciudadanos a los archivos y registros administrativos, salvo en lo que afecte a:",
    ok: "La seguridad y defensa del Estado, la averiguación de los delitos y la intimidad de las personas.",
    mal: ["El secreto profesional, la propiedad intelectual y el interés económico del Estado.", "La seguridad y defensa del Estado y las relaciones con las confesiones religiosas.", "La política monetaria, la intimidad de las personas y el secreto industrial."],
    d: 2,
  },
  {
    id: "tai-boe-t02-09", tema: 2, norma: "CE", art: "Artículo 105",
    cita: "El procedimiento a través del cual deben producirse los actos administrativos, garantizando, cuando proceda, la audiencia del interesado.",
    clave: "audiencia del interesado",
    e: "Según el artículo 105.c) de la Constitución, la ley regulará el procedimiento a través del cual deben producirse los actos administrativos, garantizando, cuando proceda:",
    ok: "La audiencia del interesado.",
    mal: ["La gratuidad del procedimiento.", "La intervención del Ministerio Fiscal.", "El informe previo del Consejo de Estado."],
    d: 1,
  },
  {
    id: "tai-boe-t02-10", tema: 2, norma: "CE", art: "Artículo 106",
    cita: "Los Tribunales controlan la potestad reglamentaria y la legalidad de la actuación administrativa, así como el sometimiento de ésta a los fines que la justifican.",
    clave: "Tribunales",
    e: "Según el artículo 106.1 de la Constitución, ¿quién controla la potestad reglamentaria y la legalidad de la actuación administrativa?",
    ok: "Los Tribunales.",
    mal: ["El Consejo de Estado.", "El Tribunal de Cuentas.", "El Defensor del Pueblo."],
    d: 1,
  },
  {
    id: "tai-boe-t02-11", tema: 2, norma: "CE", art: "Artículo 106",
    cita: "tendrán derecho a ser indemnizados por toda lesión que sufran en cualquiera de sus bienes y derechos, salvo en los casos de fuerza mayor, siempre que la lesión sea consecuencia del funcionamiento de los servicios públicos",
    clave: "fuerza mayor",
    e: "Conforme al artículo 106.2 de la Constitución, los particulares tienen derecho a ser indemnizados por toda lesión que sea consecuencia del funcionamiento de los servicios públicos, salvo:",
    ok: "En los casos de fuerza mayor.",
    mal: ["Cuando el funcionamiento del servicio haya sido normal.", "Cuando la lesión afecte a bienes de dominio público.", "Cuando la lesión la cause un contratista de la Administración."],
    j: "La responsabilidad patrimonial cubre tanto el funcionamiento normal como el anormal de los servicios públicos; la única excepción constitucional es la fuerza mayor.",
    d: 2,
  },
  {
    id: "tai-boe-t02-12", tema: 2, norma: "LRJSP", art: "Artículo 3",
    cita: "e) Buena fe, confianza legítima y lealtad institucional.",
    clave: "confianza legítima",
    e: "Según el artículo 3.1 de la Ley 40/2015, ¿cuál de los siguientes figura entre los principios que las Administraciones Públicas deben respetar en su actuación y relaciones?",
    ok: "Buena fe, confianza legítima y lealtad institucional.",
    mal: ["Jerarquía normativa e irretroactividad.", "Unidad de caja y especialidad presupuestaria.", "Oficialidad y celeridad del proceso judicial."],
    d: 2,
  },
  {
    id: "tai-boe-t02-13", tema: 2, norma: "LRJSP", art: "Artículo 3",
    cita: "b) Simplicidad, claridad y proximidad a los ciudadanos.",
    clave: "proximidad a los ciudadanos",
    e: "Entre los principios que, según el artículo 3.1 de la Ley 40/2015, deben respetar las Administraciones Públicas figura:",
    ok: "Simplicidad, claridad y proximidad a los ciudadanos.",
    mal: ["Autonomía, suficiencia financiera y solidaridad.", "Secreto, reserva y discrecionalidad.", "Uniformidad, centralización y exclusividad."],
    d: 1,
  },
  {
    id: "tai-boe-t02-14", tema: 2, norma: "LRJSP", art: "Artículo 3",
    cita: "a través de medios electrónicos, que aseguren la interoperabilidad y seguridad de los sistemas y soluciones adoptadas por cada una de ellas",
    clave: "medios electrónicos",
    e: "Según el artículo 3.2 de la Ley 40/2015, las Administraciones Públicas se relacionarán entre sí y con sus órganos, organismos públicos y entidades vinculados o dependientes a través de:",
    ok: "Medios electrónicos que aseguren la interoperabilidad y seguridad de los sistemas y soluciones adoptadas.",
    mal: ["Comunicaciones en papel registradas, salvo acuerdo en contrario.", "El servicio de correo postal certificado del Estado.", "Cualquier medio, a elección de cada Administración."],
    d: 1,
  },
  {
    id: "tai-boe-t02-15", tema: 2, norma: "LRJSP", art: "Artículo 3",
    cita: "Cada una de las Administraciones Públicas del artículo 2 actúa para el cumplimiento de sus fines con personalidad jurídica única.",
    clave: "personalidad jurídica única",
    e: "Conforme al artículo 3.4 de la Ley 40/2015, cada una de las Administraciones Públicas actúa para el cumplimiento de sus fines con:",
    ok: "Personalidad jurídica única.",
    mal: ["Personalidad jurídica propia para cada uno de sus órganos.", "Personalidad jurídica compartida con el Estado.", "Capacidad de obrar delegada por el Gobierno."],
    d: 2,
  },
  {
    id: "tai-boe-t02-16", tema: 2, norma: "LRJSP", art: "Artículo 140",
    cita: "c) Colaboración, entendido como el deber de actuar con el resto de Administraciones Públicas para el logro de fines comunes.",
    clave: "Colaboración",
    e: "Según el artículo 140.1 de la Ley 40/2015, ¿qué principio se entiende como el deber de actuar con el resto de Administraciones Públicas para el logro de fines comunes?",
    ok: "Colaboración.",
    mal: ["Cooperación.", "Coordinación.", "Lealtad institucional."],
    d: 2,
  },
  {
    id: "tai-boe-t02-17", tema: 2, norma: "LRJSP", art: "Artículo 140",
    cita: "d) Cooperación, cuando dos o más Administraciones Públicas, de manera voluntaria y en ejercicio de sus competencias, asumen compromisos específicos en aras de una acción común.",
    clave: "de manera voluntaria",
    e: "Conforme al artículo 140.1 de la Ley 40/2015, existe cooperación cuando:",
    ok: "Dos o más Administraciones Públicas, de manera voluntaria y en ejercicio de sus competencias, asumen compromisos específicos en aras de una acción común.",
    mal: ["Una Administración garantiza la coherencia de las actuaciones de las demás afectadas por una misma materia.", "La Administración General del Estado impone a las Comunidades Autónomas objetivos comunes obligatorios.", "Las Administraciones comparten el uso de recursos comunes para gestionarlos con eficiencia."],
    j: "Garantizar la coherencia de las actuaciones es la coordinación (letra e) y compartir recursos comunes, la eficiencia (letra f).",
    d: 3,
  },
  {
    id: "tai-boe-t02-18", tema: 2, norma: "LRJSP", art: "Artículo 140",
    cita: "una Administración Pública y, singularmente, la Administración General del Estado, tiene la obligación de garantizar la coherencia de las actuaciones de las diferentes Administraciones Públicas afectadas por una misma materia",
    clave: "Administración General del Estado",
    e: "Al definir el principio de coordinación, el artículo 140.1.e) de la Ley 40/2015 menciona singularmente como obligada a garantizar la coherencia de las actuaciones a:",
    ok: "La Administración General del Estado.",
    mal: ["Las Comunidades Autónomas.", "Las Diputaciones Provinciales.", "Los municipios de gran población."],
    d: 2,
  },
  {
    id: "tai-boe-t02-19", tema: 2, norma: "LPAC", art: "Artículo 13",
    cita: "a) A comunicarse con las Administraciones Públicas a través de un Punto de Acceso General electrónico de la Administración.",
    clave: "Punto de Acceso General electrónico",
    e: "Según el artículo 13 de la Ley 39/2015, quienes tienen capacidad de obrar ante las Administraciones Públicas tienen derecho, entre otros:",
    ok: "A comunicarse con las Administraciones Públicas a través de un Punto de Acceso General electrónico de la Administración.",
    mal: ["A exigir que toda comunicación con la Administración se haga en papel.", "A comunicarse con cualquier Administración a través del Defensor del Pueblo.", "A relacionarse en cualquier lengua oficial de la Unión Europea."],
    d: 1,
  },
  {
    id: "tai-boe-t02-20", tema: 2, norma: "LPAC", art: "Artículo 13",
    cita: "b) A ser asistidos en el uso de medios electrónicos en sus relaciones con las Administraciones Públicas.",
    clave: "asistidos en el uso de medios electrónicos",
    e: "Entre los derechos de las personas en sus relaciones con las Administraciones Públicas, el artículo 13 de la Ley 39/2015 incluye el derecho:",
    ok: "A ser asistidos en el uso de medios electrónicos en sus relaciones con las Administraciones Públicas.",
    mal: ["A no identificarse en los trámites electrónicos.", "A que la Administración les facilite gratuitamente un ordenador.", "A recibir todas las notificaciones exclusivamente en papel."],
    d: 1,
  },
  {
    id: "tai-boe-t02-21", tema: 2, norma: "LPAC", art: "Artículo 13",
    cita: "e) A ser tratados con respeto y deferencia por las autoridades y empleados públicos",
    clave: "respeto y deferencia",
    e: "Según el artículo 13.e) de la Ley 39/2015, las personas tienen derecho a ser tratadas por las autoridades y empleados públicos:",
    ok: "Con respeto y deferencia.",
    mal: ["Con prioridad sobre los demás interesados.", "Con preferencia si son personas jurídicas.", "Con neutralidad y distancia."],
    d: 1,
  },
  {
    id: "tai-boe-t02-22", tema: 2, norma: "LPAC", art: "Artículo 13",
    cita: "h) A la protección de datos de carácter personal, y en particular a la seguridad y confidencialidad de los datos que figuren en los ficheros, sistemas y aplicaciones de las Administraciones Públicas.",
    clave: "seguridad y confidencialidad",
    e: "El artículo 13.h) de la Ley 39/2015 reconoce el derecho a la protección de datos de carácter personal y, en particular:",
    ok: "A la seguridad y confidencialidad de los datos que figuren en los ficheros, sistemas y aplicaciones de las Administraciones Públicas.",
    mal: ["A la supresión inmediata de los datos al terminar cada procedimiento.", "A la publicación de sus datos en la sede electrónica.", "A que sus datos no se traten por medios electrónicos."],
    d: 2,
  },
  {
    id: "tai-boe-t02-23", tema: 2, norma: "LPAC", art: "Artículo 53",
    cita: "c) A no presentar documentos originales salvo que, de manera excepcional, la normativa reguladora aplicable establezca lo contrario.",
    clave: "de manera excepcional",
    e: "Según el artículo 53.1.c) de la Ley 39/2015, los interesados tienen derecho a no presentar documentos originales salvo que:",
    ok: "De manera excepcional, la normativa reguladora aplicable establezca lo contrario.",
    mal: ["Lo solicite el instructor del procedimiento.", "El procedimiento se tramite en papel.", "Se trate de un procedimiento sancionador."],
    d: 2,
  },
  {
    id: "tai-boe-t02-24", tema: 2, norma: "LPAC", art: "Artículo 53",
    cita: "e) A formular alegaciones, utilizar los medios de defensa admitidos por el Ordenamiento Jurídico, y a aportar documentos en cualquier fase del procedimiento anterior al trámite de audiencia",
    clave: "anterior al trámite de audiencia",
    e: "Conforme al artículo 53.1.e) de la Ley 39/2015, los interesados pueden formular alegaciones y aportar documentos:",
    ok: "En cualquier fase del procedimiento anterior al trámite de audiencia.",
    mal: ["Solo dentro de los diez días siguientes a la iniciación.", "Solo durante el trámite de información pública.", "En cualquier momento, incluso después de dictada la resolución."],
    d: 2,
  },
  {
    id: "tai-boe-t02-25", tema: 2, norma: "LPAC", art: "Artículo 53",
    cita: "g) A actuar asistidos de asesor cuando lo consideren conveniente en defensa de sus intereses.",
    clave: "asistidos de asesor",
    e: "Según el artículo 53.1.g) de la Ley 39/2015, los interesados en un procedimiento administrativo tienen derecho:",
    ok: "A actuar asistidos de asesor cuando lo consideren conveniente en defensa de sus intereses.",
    mal: ["A ser asistidos obligatoriamente por abogado en todo procedimiento.", "A que la Administración les designe un asesor gratuito.", "A delegar en un funcionario la defensa de sus intereses."],
    d: 1,
  },

  // ── Tema 3 ──────────────────────────────────────────────────────────────
  {
    id: "tai-boe-t03-01", tema: 3, norma: "CE", art: "Artículo 56",
    cita: "Su título es el de Rey de España y podrá utilizar los demás que correspondan a la Corona.",
    clave: "Rey de España",
    e: "Según el artículo 56.2 de la Constitución, el título del Rey es el de:",
    ok: "Rey de España, y podrá utilizar los demás que correspondan a la Corona.",
    mal: ["Rey de los españoles, sin otros títulos.", "Jefe Supremo de la Nación española.", "Su Majestad Católica, exclusivamente."],
    d: 1,
  },
  {
    id: "tai-boe-t03-02", tema: 3, norma: "CE", art: "Artículo 56",
    cita: "La persona del Rey es inviolable y no está sujeta a responsabilidad.",
    clave: "inviolable",
    e: "Conforme al artículo 56.3 de la Constitución, la persona del Rey:",
    ok: "Es inviolable y no está sujeta a responsabilidad.",
    mal: ["Goza de inmunidad salvo en caso de flagrante delito.", "Solo puede ser juzgada por el Tribunal Supremo.", "Responde de sus actos ante las Cortes Generales."],
    j: "La responsabilidad por los actos del Rey recae en quienes los refrendan (artículo 64.2).",
    d: 1,
  },
  {
    id: "tai-boe-t03-03", tema: 3, norma: "CE", art: "Artículo 56",
    cita: "Sus actos estarán siempre refrendados en la forma establecida en el artículo 64, careciendo de validez sin dicho refrendo, salvo lo dispuesto en el artículo 65, 2.",
    clave: "validez",
    e: "Según el artículo 56.3 de la Constitución, los actos del Rey que no estén refrendados:",
    ok: "Carecen de validez, salvo lo dispuesto en el artículo 65.2.",
    mal: ["Son anulables por el Tribunal Supremo.", "Son eficaces mientras las Cortes Generales no los revoquen.", "Solo son nulos si afectan a derechos fundamentales."],
    d: 2,
  },
  {
    id: "tai-boe-t03-04", tema: 3, norma: "CE", art: "Artículo 57",
    cita: "El Príncipe heredero, desde su nacimiento o desde que se produzca el hecho que origine el llamamiento, tendrá la dignidad de Príncipe de Asturias",
    clave: "hecho que origine el llamamiento",
    e: "Según el artículo 57.2 de la Constitución, el Príncipe heredero tendrá la dignidad de Príncipe de Asturias:",
    ok: "Desde su nacimiento o desde que se produzca el hecho que origine el llamamiento.",
    mal: ["Desde que alcance la mayoría de edad.", "Desde que preste juramento ante las Cortes Generales.", "Desde que lo proclame una ley orgánica."],
    d: 2,
  },
  {
    id: "tai-boe-t03-05", tema: 3, norma: "CE", art: "Artículo 57",
    cita: "Extinguidas todas las líneas llamadas en Derecho, las Cortes Generales proveerán a la sucesión en la Corona en la forma que más convenga a los intereses de España.",
    clave: "Cortes Generales proveerán",
    e: "Conforme al artículo 57.3 de la Constitución, extinguidas todas las líneas llamadas en Derecho:",
    ok: "Las Cortes Generales proveerán a la sucesión en la forma que más convenga a los intereses de España.",
    mal: ["El Rey designará libremente a su sucesor.", "Se convocará un referéndum consultivo sobre la forma de Estado.", "El Gobierno propondrá una terna de candidatos al Congreso."],
    d: 1,
  },
  {
    id: "tai-boe-t03-06", tema: 3, norma: "CE", art: "Artículo 57",
    cita: "Aquellas personas que teniendo derecho a la sucesión en el trono contrajeren matrimonio contra la expresa prohibición del Rey y de las Cortes Generales, quedarán excluidas en la sucesión a la Corona por sí y sus descendientes.",
    clave: "por sí y sus descendientes",
    e: "Según el artículo 57.4 de la Constitución, quienes teniendo derecho a la sucesión en el trono contrajeren matrimonio contra la expresa prohibición del Rey y de las Cortes Generales:",
    ok: "Quedarán excluidos de la sucesión a la Corona por sí y sus descendientes.",
    mal: ["Quedarán excluidos ellos, pero no sus descendientes.", "Perderán el título de Príncipe de Asturias, sin afectar a la sucesión.", "Necesitarán una ley orgánica para conservar sus derechos."],
    d: 2,
  },
  {
    id: "tai-boe-t03-07", tema: 3, norma: "CE", art: "Artículo 57",
    cita: "contra la expresa prohibición del Rey y de las Cortes Generales",
    clave: "del Rey y de las Cortes Generales",
    e: "Para que quien tenga derecho a la sucesión quede excluido por su matrimonio, el artículo 57.4 de la Constitución exige que se haya contraído contra la expresa prohibición:",
    ok: "Del Rey y de las Cortes Generales.",
    mal: ["Del Rey y del Gobierno.", "Solo del Rey.", "De las Cortes Generales y del Tribunal Constitucional."],
    d: 2,
  },
  {
    id: "tai-boe-t03-08", tema: 3, norma: "CE", art: "Artículo 57",
    cita: "Las abdicaciones y renuncias y cualquier duda de hecho o de derecho que ocurra en el orden de sucesión a la Corona se resolverán por una ley orgánica.",
    clave: "ley orgánica",
    e: "Según el artículo 57.5 de la Constitución, las abdicaciones y renuncias y cualquier duda de hecho o de derecho en el orden de sucesión a la Corona se resolverán:",
    ok: "Por una ley orgánica.",
    mal: ["Por el Tribunal Constitucional.", "Por real decreto acordado en Consejo de Ministros.", "Por resolución de las Cortes Generales en sesión conjunta."],
    j: "Así se hizo con la Ley Orgánica 3/2014, que hizo efectiva la abdicación de Juan Carlos I.",
    d: 1,
  },
  {
    id: "tai-boe-t03-09", tema: 3, norma: "CE", art: "Artículo 58",
    cita: "La Reina consorte o el consorte de la Reina no podrán asumir funciones constitucionales, salvo lo dispuesto para la Regencia.",
    clave: "salvo lo dispuesto para la Regencia",
    e: "Conforme al artículo 58 de la Constitución, la Reina consorte o el consorte de la Reina:",
    ok: "No podrán asumir funciones constitucionales, salvo lo dispuesto para la Regencia.",
    mal: ["Podrán asumir funciones constitucionales por delegación del Rey.", "Podrán presidir el Consejo de Ministros en ausencia del Rey.", "No podrán asumir funciones constitucionales en ningún caso."],
    d: 2,
  },
  {
    id: "tai-boe-t03-10", tema: 3, norma: "CE", art: "Artículo 59",
    cita: "Cuando el Rey fuere menor de edad, el padre o la madre del Rey y, en su defecto, el pariente mayor de edad más próximo a suceder en la Corona, según el orden establecido en la Constitución, entrará a ejercer inmediatamente la Regencia",
    clave: "el padre o la madre del Rey",
    e: "Según el artículo 59.1 de la Constitución, cuando el Rey fuere menor de edad ejercerá la Regencia:",
    ok: "El padre o la madre del Rey y, en su defecto, el pariente mayor de edad más próximo a suceder en la Corona.",
    mal: ["Una Regencia de tres personas nombrada por las Cortes Generales.", "El Presidente del Gobierno, hasta la mayoría de edad del Rey.", "El tutor nombrado en el testamento del Rey difunto."],
    d: 2,
  },
  {
    id: "tai-boe-t03-11", tema: 3, norma: "CE", art: "Artículo 59",
    cita: "Si no hubiere ninguna persona a quien corresponda la Regencia, ésta será nombrada por las Cortes Generales, y se compondrá de una, tres o cinco personas.",
    clave: "una, tres o cinco",
    e: "Si no hubiere ninguna persona a quien corresponda la Regencia, según el artículo 59.3 de la Constitución las Cortes Generales la nombrarán y se compondrá de:",
    ok: "Una, tres o cinco personas.",
    mal: ["Una o tres personas.", "Tres o cinco personas.", "Dos, cuatro o seis personas."],
    m: "Regencia de las Cortes: impar, 1-3-5.", d: 2,
  },
  {
    id: "tai-boe-t03-12", tema: 3, norma: "CE", art: "Artículo 59",
    cita: "Para ejercer la Regencia es preciso ser español y mayor de edad.",
    clave: "español y mayor de edad",
    e: "Conforme al artículo 59.4 de la Constitución, para ejercer la Regencia es preciso:",
    ok: "Ser español y mayor de edad.",
    mal: ["Ser español de origen y miembro de la Familia Real.", "Ser mayor de treinta años y residir en España.", "Ser miembro de las Cortes Generales."],
    d: 1,
  },
  {
    id: "tai-boe-t03-13", tema: 3, norma: "CE", art: "Artículo 59",
    cita: "La Regencia se ejercerá por mandato constitucional y siempre en nombre del Rey.",
    clave: "en nombre del Rey",
    e: "Según el artículo 59.5 de la Constitución, la Regencia se ejercerá:",
    ok: "Por mandato constitucional y siempre en nombre del Rey.",
    mal: ["Por delegación de las Cortes Generales y en nombre propio.", "Por mandato del Gobierno y en nombre de la Nación.", "Por mandato constitucional y en nombre de la propia Regencia."],
    d: 1,
  },
  {
    id: "tai-boe-t03-14", tema: 3, norma: "CE", art: "Artículo 61",
    cita: "respetar los derechos de los ciudadanos y de las Comunidades Autónomas",
    clave: "de las Comunidades Autónomas",
    e: "Según el artículo 61.1 de la Constitución, el Rey, al ser proclamado ante las Cortes Generales, jura, entre otras cosas, respetar los derechos:",
    ok: "De los ciudadanos y de las Comunidades Autónomas.",
    mal: ["De los ciudadanos y de las Entidades Locales.", "De las Cortes Generales y del Gobierno.", "De los españoles residentes en el extranjero."],
    d: 2,
  },
  {
    id: "tai-boe-t03-15", tema: 3, norma: "CE", art: "Artículo 61",
    cita: "El Príncipe heredero, al alcanzar la mayoría de edad, y el Regente o Regentes al hacerse cargo de sus funciones, prestarán el mismo juramento, así como el de fidelidad al Rey.",
    clave: "fidelidad al Rey",
    e: "Conforme al artículo 61.2 de la Constitución, el Príncipe heredero al alcanzar la mayoría de edad y el Regente o Regentes al hacerse cargo de sus funciones prestarán:",
    ok: "El mismo juramento que el Rey, así como el de fidelidad al Rey.",
    mal: ["Solo juramento de fidelidad a la Constitución.", "Juramento ante el Tribunal Supremo.", "Ningún juramento hasta ser proclamados."],
    d: 2,
  },
  {
    id: "tai-boe-t03-16", tema: 3, norma: "CE", art: "Artículo 62",
    cita: "i) Ejercer el derecho de gracia con arreglo a la ley, que no podrá autorizar indultos generales.",
    clave: "no podrá autorizar indultos generales",
    e: "Según el artículo 62.i) de la Constitución, corresponde al Rey ejercer el derecho de gracia con arreglo a la ley, que:",
    ok: "No podrá autorizar indultos generales.",
    mal: ["Podrá autorizar indultos generales si los aprueba el Congreso por mayoría absoluta.", "Exigirá informe vinculante del Tribunal Supremo para cada indulto.", "Solo podrá aplicarse a delitos políticos."],
    d: 1,
  },
  {
    id: "tai-boe-t03-17", tema: 3, norma: "CE", art: "Artículo 62",
    cita: "j) El Alto Patronazgo de las Reales Academias.",
    clave: "Reales Academias",
    e: "Conforme al artículo 62.j) de la Constitución, corresponde al Rey:",
    ok: "El Alto Patronazgo de las Reales Academias.",
    mal: ["La presidencia del Consejo General del Poder Judicial.", "La dirección del Centro Nacional de Inteligencia.", "La presidencia del Consejo de Estado."],
    d: 1,
  },
  {
    id: "tai-boe-t03-18", tema: 3, norma: "CE", art: "Artículo 62",
    cita: "f) Expedir los decretos acordados en el Consejo de Ministros, conferir los empleos civiles y militares y conceder honores y distinciones con arreglo a las leyes.",
    clave: "Expedir los decretos",
    e: "¿Cuál de las siguientes funciones atribuye al Rey el artículo 62.f) de la Constitución?",
    ok: "Expedir los decretos acordados en el Consejo de Ministros.",
    mal: ["Aprobar los decretos-leyes en caso de extraordinaria y urgente necesidad.", "Dirigir la política interior y exterior.", "Ejercer la potestad reglamentaria."],
    j: "Dictar decretos-leyes, dirigir la política y ejercer la potestad reglamentaria corresponden al Gobierno (artículos 86 y 97).",
    d: 2,
  },
  {
    id: "tai-boe-t03-19", tema: 3, norma: "CE", art: "Artículo 63",
    cita: "El Rey acredita a los embajadores y otros representantes diplomáticos.",
    clave: "acredita a los embajadores",
    e: "Según el artículo 63.1 de la Constitución, el Rey:",
    ok: "Acredita a los embajadores y otros representantes diplomáticos.",
    mal: ["Nombra libremente a los embajadores sin necesidad de refrendo.", "Ratifica los tratados sin autorización de las Cortes Generales.", "Dirige la política exterior del Estado."],
    d: 1,
  },
  {
    id: "tai-boe-t03-20", tema: 3, norma: "CE", art: "Artículo 63",
    cita: "Al Rey corresponde manifestar el consentimiento del Estado para obligarse internacionalmente por medio de tratados, de conformidad con la Constitución y las leyes.",
    clave: "consentimiento del Estado",
    e: "Conforme al artículo 63.2 de la Constitución, al Rey corresponde, en materia de tratados:",
    ok: "Manifestar el consentimiento del Estado para obligarse internacionalmente por medio de tratados.",
    mal: ["Negociar personalmente los tratados internacionales.", "Autorizar los tratados de carácter militar.", "Declarar la inconstitucionalidad de un tratado."],
    d: 1,
  },
  {
    id: "tai-boe-t03-21", tema: 3, norma: "CE", art: "Artículo 64",
    cita: "De los actos del Rey serán responsables las personas que los refrenden.",
    clave: "que los refrenden",
    e: "Según el artículo 64.2 de la Constitución, de los actos del Rey serán responsables:",
    ok: "Las personas que los refrenden.",
    mal: ["El propio Rey.", "El Consejo de Ministros de forma solidaria.", "El Jefe de la Casa del Rey."],
    d: 1,
  },
  {
    id: "tai-boe-t03-22", tema: 3, norma: "CE", art: "Artículo 65",
    cita: "El Rey nombra y releva libremente a los miembros civiles y militares de su Casa.",
    clave: "libremente",
    e: "Conforme al artículo 65.2 de la Constitución, el Rey nombra y releva a los miembros civiles y militares de su Casa:",
    ok: "Libremente.",
    mal: ["A propuesta del Presidente del Gobierno.", "Previa autorización de las Cortes Generales.", "Con el refrendo del Ministro de la Presidencia."],
    j: "Es la excepción al refrendo a la que remite el artículo 56.3.",
    d: 1,
  },
];
