// Temas 4 (Cortes Generales), 5 (Gobierno y Administración), 6 (relaciones
// Gobierno-Cortes y estados excepcionales) y 7 (Poder Judicial).
// Ver tai-banco-boe.ts.
import type { PreguntaBoe } from "./tai-banco-boe";

export const BANCO_BOE_2: PreguntaBoe[] = [
  // ── Tema 4 ──────────────────────────────────────────────────────────────
  {
    id: "tai-boe-t04-01", tema: 4, norma: "CE", art: "Artículo 66",
    cita: "Las Cortes Generales representan al pueblo español y están formadas por el Congreso de los Diputados y el Senado.",
    clave: "representan al pueblo español",
    e: "Según el artículo 66.1 de la Constitución, las Cortes Generales:",
    ok: "Representan al pueblo español y están formadas por el Congreso de los Diputados y el Senado.",
    mal: ["Representan a las Comunidades Autónomas y están formadas por el Congreso y el Senado.", "Representan a la Nación y están formadas únicamente por el Congreso de los Diputados.", "Representan al Estado y están formadas por el Congreso, el Senado y el Gobierno."],
    d: 1,
  },
  {
    id: "tai-boe-t04-02", tema: 4, norma: "CE", art: "Artículo 67",
    cita: "Nadie podrá ser miembro de las dos Cámaras simultáneamente, ni acumular el acta de una Asamblea de Comunidad Autónoma con la de Diputado al Congreso.",
    clave: "Diputado al Congreso",
    e: "Además de impedir ser miembro de las dos Cámaras a la vez, el artículo 67.1 de la Constitución prohíbe acumular:",
    ok: "El acta de una Asamblea de Comunidad Autónoma con la de Diputado al Congreso.",
    mal: ["El acta de una Asamblea de Comunidad Autónoma con la de Senador.", "El acta de Senador con la de concejal.", "El acta de Senador con la condición de miembro del Gobierno."],
    j: "La Constitución no prohíbe ser a la vez parlamentario autonómico y Senador: de hecho, muchos Senadores designados por las Comunidades Autónomas lo son.",
    d: 2,
  },
  {
    id: "tai-boe-t04-03", tema: 4, norma: "CE", art: "Artículo 67",
    cita: "Las reuniones de Parlamentarios que se celebren sin convocatoria reglamentaria no vincularán a las Cámaras, y no podrán ejercer sus funciones ni ostentar sus privilegios.",
    clave: "no vincularán a las Cámaras",
    e: "Conforme al artículo 67.3 de la Constitución, las reuniones de Parlamentarios que se celebren sin convocatoria reglamentaria:",
    ok: "No vincularán a las Cámaras, y no podrán ejercer sus funciones ni ostentar sus privilegios.",
    mal: ["Vincularán a las Cámaras si asiste la mayoría absoluta de sus miembros.", "Necesitarán la convalidación posterior del Pleno.", "Solo serán válidas si las convoca la Diputación Permanente."],
    d: 2,
  },
  {
    id: "tai-boe-t04-04", tema: 4, norma: "CE", art: "Artículo 68",
    cita: "Las poblaciones de Ceuta y Melilla estarán representadas cada una de ellas por un Diputado.",
    clave: "un Diputado",
    e: "Según el artículo 68.2 de la Constitución, en el Congreso las poblaciones de Ceuta y Melilla estarán representadas:",
    ok: "Cada una de ellas por un Diputado.",
    mal: ["Cada una de ellas por dos Diputados.", "Por tres Diputados entre las dos.", "Por los Diputados que fije la ley según su población."],
    j: "No hay que confundirlo con el Senado: Ceuta y Melilla eligen dos Senadores cada una (artículo 69.4).",
    d: 1,
  },
  {
    id: "tai-boe-t04-05", tema: 4, norma: "CE", art: "Artículo 68",
    cita: "La elección se verificará en cada circunscripción atendiendo a criterios de representación proporcional.",
    clave: "representación proporcional",
    e: "Conforme al artículo 68.3 de la Constitución, la elección de los Diputados se verificará en cada circunscripción atendiendo a criterios de:",
    ok: "Representación proporcional.",
    mal: ["Sistema mayoritario a una vuelta.", "Sistema mayoritario a dos vueltas.", "Voto limitado por provincias."],
    d: 1,
  },
  {
    id: "tai-boe-t04-06", tema: 4, norma: "CE", art: "Artículo 68",
    cita: "El Congreso electo deberá ser convocado dentro de los veinticinco días siguientes a la celebración de las elecciones.",
    clave: "veinticinco días",
    e: "Según el artículo 68.6 de la Constitución, el Congreso electo deberá ser convocado:",
    ok: "Dentro de los veinticinco días siguientes a la celebración de las elecciones.",
    mal: ["Dentro de los quince días siguientes a la celebración de las elecciones.", "Dentro de los treinta días siguientes a la proclamación de electos.", "Dentro de los sesenta días siguientes a la terminación del mandato."],
    m: "Elecciones entre 30 y 60 días tras el fin del mandato; Congreso convocado en 25.", d: 2,
  },
  {
    id: "tai-boe-t04-07", tema: 4, norma: "CE", art: "Artículo 69",
    cita: "El Senado es la Cámara de representación territorial.",
    clave: "representación territorial",
    e: "El artículo 69.1 de la Constitución define el Senado como:",
    ok: "La Cámara de representación territorial.",
    mal: ["La Cámara de segunda lectura.", "La Cámara de representación corporativa.", "La Cámara de representación exclusiva de las provincias."],
    d: 1,
  },
  {
    id: "tai-boe-t04-08", tema: 4, norma: "CE", art: "Artículo 69",
    cita: "uno a cada una de las siguientes islas: Ibiza, Formentera, Menorca, Fuerteventura, La Gomera, El Hierro, Lanzarote y La Palma",
    clave: "Ibiza, Formentera",
    e: "Tras la reforma constitucional de 19 de mayo de 2026, el artículo 69.3 asigna un Senador a cada una de las siguientes islas, entre otras:",
    ok: "Ibiza, Formentera y Menorca, cada una por separado.",
    mal: ["Ibiza-Formentera, como una única circunscripción, y Menorca.", "Gran Canaria, Mallorca y Tenerife.", "Lanzarote-La Graciosa, como una única circunscripción, y Menorca."],
    j: "La reforma separó Ibiza y Formentera en dos circunscripciones de un Senador cada una; según su disposición transitoria única, la separación se aplica a partir de las primeras elecciones al Senado posteriores a su entrada en vigor. Gran Canaria, Mallorca y Tenerife eligen tres Senadores cada una.",
    d: 3,
  },
  {
    id: "tai-boe-t04-09", tema: 4, norma: "CE", art: "Artículo 69",
    cita: "Las poblaciones de Ceuta y Melilla elegirán cada una de ellas dos Senadores.",
    clave: "dos Senadores",
    e: "Según el artículo 69.4 de la Constitución, las poblaciones de Ceuta y Melilla elegirán:",
    ok: "Dos Senadores cada una.",
    mal: ["Un Senador cada una.", "Cuatro Senadores cada una.", "Tres Senadores entre las dos."],
    d: 1,
  },
  {
    id: "tai-boe-t04-10", tema: 4, norma: "CE", art: "Artículo 70",
    cita: "b) A los altos cargos de la Administración del Estado que determine la ley, con la excepción de los miembros del Gobierno.",
    clave: "excepción de los miembros del Gobierno",
    e: "Según el artículo 70.1.b) de la Constitución, las causas de inelegibilidad e incompatibilidad de Diputados y Senadores comprenderán a los altos cargos de la Administración del Estado que determine la ley:",
    ok: "Con la excepción de los miembros del Gobierno.",
    mal: ["Incluidos en todo caso los miembros del Gobierno.", "Con la excepción de los Secretarios de Estado.", "Con la excepción de los Delegados del Gobierno en las Comunidades Autónomas."],
    d: 2,
  },
  {
    id: "tai-boe-t04-11", tema: 4, norma: "CE", art: "Artículo 71",
    cita: "En las causas contra Diputados y Senadores será competente la Sala de lo Penal del Tribunal Supremo.",
    clave: "Sala de lo Penal del Tribunal Supremo",
    e: "Conforme al artículo 71.3 de la Constitución, en las causas contra Diputados y Senadores será competente:",
    ok: "La Sala de lo Penal del Tribunal Supremo.",
    mal: ["El Tribunal Superior de Justicia de su Comunidad Autónoma.", "La Sala de lo Penal de la Audiencia Nacional.", "El Tribunal Constitucional."],
    d: 1,
  },
  {
    id: "tai-boe-t04-12", tema: 4, norma: "CE", art: "Artículo 72",
    cita: "Las sesiones conjuntas serán presididas por el Presidente del Congreso",
    clave: "Presidente del Congreso",
    e: "Según el artículo 72.2 de la Constitución, las sesiones conjuntas de las Cámaras serán presididas por:",
    ok: "El Presidente del Congreso.",
    mal: ["El Presidente del Senado.", "El Rey.", "El de mayor edad de los dos Presidentes de las Cámaras."],
    d: 1,
  },
  {
    id: "tai-boe-t04-13", tema: 4, norma: "CE", art: "Artículo 72",
    cita: "Los Presidentes de las Cámaras ejercen en nombre de las mismas todos los poderes administrativos y facultades de policía en el interior de sus respectivas sedes.",
    clave: "Presidentes de las Cámaras",
    e: "Conforme al artículo 72.3 de la Constitución, ¿quién ejerce los poderes administrativos y las facultades de policía en el interior de las sedes de las Cámaras?",
    ok: "Los Presidentes de las Cámaras, en nombre de las mismas.",
    mal: ["El Ministro del Interior.", "Las Mesas de las Cámaras, de forma colegiada.", "El Director General de la Policía."],
    d: 2,
  },
  {
    id: "tai-boe-t04-14", tema: 4, norma: "CE", art: "Artículo 76",
    cita: "Sus conclusiones no serán vinculantes para los Tribunales, ni afectarán a las resoluciones judiciales",
    clave: "no serán vinculantes para los Tribunales",
    e: "Según el artículo 76.1 de la Constitución, las conclusiones de las Comisiones de investigación:",
    ok: "No serán vinculantes para los Tribunales, ni afectarán a las resoluciones judiciales.",
    mal: ["Vincularán a los Tribunales si se aprueban por mayoría absoluta.", "Se remitirán obligatoriamente al Tribunal Supremo para su ejecución.", "Tendrán valor de prueba pericial en el proceso penal."],
    j: "Su resultado puede comunicarse al Ministerio Fiscal para que ejercite, cuando proceda, las acciones oportunas.",
    d: 1,
  },
  {
    id: "tai-boe-t04-15", tema: 4, norma: "CE", art: "Artículo 79",
    cita: "El voto de Senadores y Diputados es personal e indelegable.",
    clave: "personal e indelegable",
    e: "Conforme al artículo 79.3 de la Constitución, el voto de Senadores y Diputados es:",
    ok: "Personal e indelegable.",
    mal: ["Personal y delegable en el portavoz del grupo.", "Secreto en todo caso.", "Delegable únicamente en caso de enfermedad."],
    d: 1,
  },
  {
    id: "tai-boe-t04-16", tema: 4, norma: "CE", art: "Artículo 82",
    cita: "por una ley ordinaria cuando se trate de refundir varios textos legales en uno solo",
    clave: "ley ordinaria",
    e: "Según el artículo 82.2 de la Constitución, cuando se trate de refundir varios textos legales en uno solo, la delegación legislativa deberá otorgarse mediante:",
    ok: "Una ley ordinaria.",
    mal: ["Una ley de bases.", "Una ley orgánica.", "Un acuerdo del Pleno del Congreso."],
    m: "Bases → textos ARTICULADOS; ordinaria → textos REFUNDIDOS.", d: 2,
  },
  {
    id: "tai-boe-t04-17", tema: 4, norma: "CE", art: "Artículo 82",
    cita: "Tampoco podrá permitir la subdelegación a autoridades distintas del propio Gobierno.",
    clave: "autoridades distintas del propio Gobierno",
    e: "En cuanto a la delegación legislativa, el artículo 82.3 de la Constitución establece que:",
    ok: "No podrá permitir la subdelegación a autoridades distintas del propio Gobierno.",
    mal: ["Podrá subdelegarse en los Ministros competentes por razón de la materia.", "Podrá entenderse concedida de modo implícito.", "Podrá otorgarse por tiempo indeterminado."],
    d: 2,
  },
  {
    id: "tai-boe-t04-18", tema: 4, norma: "CE", art: "Artículo 86",
    cita: "en el plazo de los treinta días siguientes a su promulgación",
    clave: "treinta días siguientes a su promulgación",
    e: "Según el artículo 86.2 de la Constitución, los Decretos-leyes deberán ser sometidos a debate y votación de totalidad en el Congreso:",
    ok: "En el plazo de los treinta días siguientes a su promulgación.",
    mal: ["En el plazo de los quince días siguientes a su promulgación.", "En el plazo de dos meses desde su publicación.", "En el plazo de los treinta días siguientes a su entrada en vigor."],
    d: 2,
  },
  {
    id: "tai-boe-t04-19", tema: 4, norma: "CE", art: "Artículo 87",
    cita: "delegando ante dicha Cámara un máximo de tres miembros de la Asamblea encargados de su defensa",
    clave: "tres miembros",
    e: "Cuando una Asamblea de Comunidad Autónoma remite a la Mesa del Congreso una proposición de ley, según el artículo 87.2 de la Constitución puede delegar para su defensa:",
    ok: "Un máximo de tres miembros de la Asamblea.",
    mal: ["Un máximo de cinco miembros de la Asamblea.", "Un único portavoz.", "Al Presidente de la Comunidad Autónoma."],
    d: 2,
  },
  {
    id: "tai-boe-t04-20", tema: 4, norma: "CE", art: "Artículo 87",
    cita: "En todo caso se exigirán no menos de 500.000 firmas acreditadas.",
    clave: "500.000",
    e: "Según el artículo 87.3 de la Constitución, para la iniciativa legislativa popular se exigirán en todo caso:",
    ok: "No menos de 500.000 firmas acreditadas.",
    mal: ["No menos de 250.000 firmas acreditadas.", "No menos de 750.000 firmas acreditadas.", "No menos de 1.000.000 de firmas acreditadas."],
    j: "Tampoco procede en materias propias de ley orgánica, tributarias o de carácter internacional, ni en lo relativo a la prerrogativa de gracia.",
    d: 1,
  },
  {
    id: "tai-boe-t04-21", tema: 4, norma: "CE", art: "Artículo 91",
    cita: "El Rey sancionará en el plazo de quince días las leyes aprobadas por las Cortes Generales, y las promulgará y ordenará su inmediata publicación.",
    clave: "quince días",
    e: "Conforme al artículo 91 de la Constitución, el Rey sancionará las leyes aprobadas por las Cortes Generales en el plazo de:",
    ok: "Quince días.",
    mal: ["Diez días.", "Treinta días.", "Un mes."],
    d: 1,
  },
  {
    id: "tai-boe-t04-22", tema: 4, norma: "CE", art: "Artículo 92",
    cita: "El referéndum será convocado por el Rey, mediante propuesta del Presidente del Gobierno, previamente autorizada por el Congreso de los Diputados.",
    clave: "previamente autorizada por el Congreso",
    e: "Según el artículo 92.2 de la Constitución, el referéndum consultivo será convocado por el Rey, mediante propuesta del Presidente del Gobierno:",
    ok: "Previamente autorizada por el Congreso de los Diputados.",
    mal: ["Previamente autorizada por el Senado.", "Previo dictamen del Consejo de Estado.", "Previamente acordada por las Cortes Generales en sesión conjunta."],
    d: 2,
  },

  // ── Tema 5 ──────────────────────────────────────────────────────────────
  {
    id: "tai-boe-t05-01", tema: 5, norma: "CE", art: "Artículo 98",
    cita: "El Presidente dirige la acción del Gobierno y coordina las funciones de los demás miembros del mismo, sin perjuicio de la competencia y responsabilidad directa de éstos en su gestión.",
    clave: "coordina las funciones de los demás miembros",
    e: "Según el artículo 98.2 de la Constitución, el Presidente del Gobierno:",
    ok: "Dirige la acción del Gobierno y coordina las funciones de los demás miembros del mismo.",
    mal: ["Dirige la acción del Gobierno y asume la responsabilidad exclusiva de la gestión de cada Ministro.", "Nombra y separa a los Ministros sin intervención del Rey.", "Preside el Consejo de Estado y el Consejo de Ministros."],
    d: 1,
  },
  {
    id: "tai-boe-t05-02", tema: 5, norma: "CE", art: "Artículo 98",
    cita: "Los miembros del Gobierno no podrán ejercer otras funciones representativas que las propias del mandato parlamentario",
    clave: "mandato parlamentario",
    e: "Conforme al artículo 98.3 de la Constitución, los miembros del Gobierno no podrán ejercer otras funciones representativas que:",
    ok: "Las propias del mandato parlamentario.",
    mal: ["Las de concejal en su municipio.", "Las de diputado de una Asamblea autonómica.", "Las que autorice el Consejo de Ministros."],
    d: 2,
  },
  {
    id: "tai-boe-t05-03", tema: 5, norma: "CE", art: "Artículo 99",
    cita: "previa consulta con los representantes designados por los Grupos políticos con representación parlamentaria, y a través del Presidente del Congreso, propondrá un candidato a la Presidencia del Gobierno",
    clave: "Presidente del Congreso",
    e: "Según el artículo 99.1 de la Constitución, el Rey, previa consulta con los representantes designados por los Grupos políticos con representación parlamentaria, propondrá un candidato a la Presidencia del Gobierno a través de:",
    ok: "El Presidente del Congreso.",
    mal: ["El Presidente del Senado.", "El Presidente del Gobierno en funciones.", "La Mesa de las Cortes Generales."],
    d: 1,
  },
  {
    id: "tai-boe-t05-04", tema: 5, norma: "CE", art: "Artículo 99",
    cita: "se someterá la misma propuesta a nueva votación cuarenta y ocho horas después de la anterior",
    clave: "cuarenta y ocho horas",
    e: "Si en la primera votación de investidura el candidato no obtiene la mayoría absoluta, el artículo 99.3 de la Constitución prevé una nueva votación:",
    ok: "Cuarenta y ocho horas después de la anterior.",
    mal: ["Veinticuatro horas después de la anterior.", "Setenta y dos horas después de la anterior.", "Cinco días después de la anterior."],
    d: 1,
  },
  {
    id: "tai-boe-t05-05", tema: 5, norma: "CE", art: "Artículo 99",
    cita: "Si transcurrido el plazo de dos meses, a partir de la primera votación de investidura, ningún candidato hubiere obtenido la confianza del Congreso, el Rey disolverá ambas Cámaras",
    clave: "a partir de la primera votación",
    e: "Según el artículo 99.5 de la Constitución, el Rey disolverá ambas Cámaras si ningún candidato hubiere obtenido la confianza del Congreso transcurrido el plazo de dos meses contados:",
    ok: "A partir de la primera votación de investidura.",
    mal: ["Desde la celebración de las elecciones.", "Desde la constitución del Congreso.", "Desde la primera ronda de consultas del Rey."],
    d: 2,
  },
  {
    id: "tai-boe-t05-06", tema: 5, norma: "CE", art: "Artículo 102",
    cita: "sólo podrá ser planteada por iniciativa de la cuarta parte de los miembros del Congreso, y con la aprobación de la mayoría absoluta del mismo",
    clave: "cuarta parte",
    e: "Según el artículo 102.2 de la Constitución, la acusación contra miembros del Gobierno por traición o por cualquier delito contra la seguridad del Estado en el ejercicio de sus funciones solo podrá plantearse:",
    ok: "Por iniciativa de la cuarta parte de los miembros del Congreso y con la aprobación de la mayoría absoluta del mismo.",
    mal: ["Por iniciativa de la décima parte de los Diputados y con la aprobación de la mayoría simple.", "Por iniciativa del Fiscal General del Estado, oído el Consejo de Estado.", "Por iniciativa de un tercio del Senado y con mayoría de tres quintos."],
    d: 2,
  },
  {
    id: "tai-boe-t05-07", tema: 5, norma: "CE", art: "Artículo 102",
    cita: "La prerrogativa real de gracia no será aplicable a ninguno de los supuestos del presente artículo.",
    clave: "no será aplicable",
    e: "En los supuestos de responsabilidad criminal de los miembros del Gobierno del artículo 102 de la Constitución, la prerrogativa real de gracia:",
    ok: "No será aplicable a ninguno de ellos.",
    mal: ["Podrá aplicarse con autorización del Congreso.", "Solo podrá aplicarse como indulto parcial.", "Podrá aplicarse salvo en los delitos de traición."],
    d: 1,
  },
  {
    id: "tai-boe-t05-08", tema: 5, norma: "CE", art: "Artículo 104",
    cita: "Las Fuerzas y Cuerpos de seguridad, bajo la dependencia del Gobierno, tendrán como misión proteger el libre ejercicio de los derechos y libertades y garantizar la seguridad ciudadana.",
    clave: "seguridad ciudadana",
    e: "Según el artículo 104.1 de la Constitución, las Fuerzas y Cuerpos de seguridad tienen como misión proteger el libre ejercicio de los derechos y libertades y:",
    ok: "Garantizar la seguridad ciudadana.",
    mal: ["Garantizar la soberanía e independencia de España.", "Defender la integridad territorial y el ordenamiento constitucional.", "Ejercer en exclusiva las funciones de policía judicial."],
    j: "Garantizar la soberanía e independencia y defender la integridad territorial y el ordenamiento constitucional es la misión de las Fuerzas Armadas (artículo 8.1).",
    d: 1,
  },
  {
    id: "tai-boe-t05-09", tema: 5, norma: "CE", art: "Artículo 107",
    cita: "El Consejo de Estado es el supremo órgano consultivo del Gobierno.",
    clave: "supremo órgano consultivo del Gobierno",
    e: "Conforme al artículo 107 de la Constitución, el Consejo de Estado es:",
    ok: "El supremo órgano consultivo del Gobierno.",
    mal: ["El supremo órgano consultivo de las Cortes Generales.", "El órgano de control externo de las cuentas del Estado.", "El órgano de gobierno de la Administración General del Estado."],
    d: 1,
  },
  {
    id: "tai-boe-t05-10", tema: 5, norma: "LG", art: "Artículo 5",
    cita: "h) Aprobar los reglamentos para el desarrollo y la ejecución de las leyes, previo dictamen del Consejo de Estado",
    clave: "previo dictamen del Consejo de Estado",
    e: "Según el artículo 5.1.h) de la Ley 50/1997, del Gobierno, corresponde al Consejo de Ministros aprobar los reglamentos para el desarrollo y la ejecución de las leyes:",
    ok: "Previo dictamen del Consejo de Estado.",
    mal: ["Previo informe del Consejo General del Poder Judicial.", "Previa autorización de las Cortes Generales.", "Previo dictamen de la Comisión General de Codificación."],
    d: 2,
  },
  {
    id: "tai-boe-t05-11", tema: 5, norma: "LG", art: "Artículo 5",
    cita: "f) Declarar los estados de alarma y de excepción y proponer al Congreso de los Diputados la declaración del estado de sitio.",
    clave: "Proponer al Congreso de los Diputados",
    e: "En relación con el estado de sitio, el artículo 5.1.f) de la Ley 50/1997 atribuye al Consejo de Ministros la función de:",
    ok: "Proponer al Congreso de los Diputados su declaración.",
    mal: ["Declararlo mediante decreto por un plazo máximo de quince días.", "Declararlo previa autorización del Congreso.", "Declararlo dando cuenta inmediata al Senado."],
    d: 2,
  },
  {
    id: "tai-boe-t05-12", tema: 5, norma: "LG", art: "Artículo 6",
    cita: "La creación, modificación y supresión de las Comisiones Delegadas del Gobierno será acordada por el Consejo de Ministros mediante Real Decreto, a propuesta del Presidente del Gobierno.",
    clave: "Consejo de Ministros mediante Real Decreto",
    e: "Según el artículo 6.1 de la Ley 50/1997, la creación, modificación y supresión de las Comisiones Delegadas del Gobierno será acordada:",
    ok: "Por el Consejo de Ministros mediante Real Decreto, a propuesta del Presidente del Gobierno.",
    mal: ["Por el Presidente del Gobierno mediante Real Decreto del Presidente.", "Por las Cortes Generales mediante ley.", "Por el Ministro de la Presidencia mediante Orden ministerial."],
    d: 2,
  },
  {
    id: "tai-boe-t05-13", tema: 5, norma: "LG", art: "Artículo 12",
    cita: "de forma que cada uno de los sexos suponga como mínimo el cuarenta por ciento en su conjunto",
    clave: "cuarenta por ciento",
    e: "Desde la Ley Orgánica 2/2024, el artículo 12.2 bis de la Ley 50/1997 exige que, en el nombramiento de las personas titulares de las Vicepresidencias y los Ministerios, cada uno de los sexos suponga en su conjunto como mínimo:",
    ok: "El cuarenta por ciento.",
    mal: ["El cincuenta por ciento.", "El treinta y tres por ciento.", "El veinticinco por ciento."],
    d: 2,
  },
  {
    id: "tai-boe-t05-14", tema: 5, norma: "LG", art: "Artículo 13",
    cita: "las funciones del Presidente del Gobierno serán asumidas por los Vicepresidentes, de acuerdo con el correspondiente orden de prelación, y, en defecto de ellos, por los Ministros, según el orden de precedencia de los Departamentos",
    clave: "orden de precedencia de los Departamentos",
    e: "Según el artículo 13.1 de la Ley 50/1997, en caso de vacante, ausencia o enfermedad, las funciones del Presidente del Gobierno serán asumidas:",
    ok: "Por los Vicepresidentes según su orden de prelación y, en su defecto, por los Ministros según el orden de precedencia de los Departamentos.",
    mal: ["Por el Ministro de la Presidencia en todo caso.", "Por el Presidente del Congreso de los Diputados.", "Por el Ministro de mayor edad."],
    d: 2,
  },
  {
    id: "tai-boe-t05-15", tema: 5, norma: "LG", art: "Artículo 13",
    cita: "será determinada por Real Decreto del Presidente del Gobierno, debiendo recaer, en todo caso, en otro miembro del Gobierno",
    clave: "otro miembro del Gobierno",
    e: "Conforme al artículo 13.2 de la Ley 50/1997, la suplencia de los Ministros para el despacho ordinario de los asuntos de su competencia debe recaer, en todo caso:",
    ok: "En otro miembro del Gobierno.",
    mal: ["En el Secretario de Estado del Departamento.", "En el Subsecretario del Ministerio.", "En el alto cargo que designe el propio Ministro."],
    d: 2,
  },
  {
    id: "tai-boe-t05-16", tema: 5, norma: "LG", art: "Artículo 18",
    cita: "El Presidente del Gobierno convoca y preside las reuniones del Consejo de Ministros, actuando como Secretario el Ministro de la Presidencia.",
    clave: "Ministro de la Presidencia",
    e: "Según el artículo 18.1 de la Ley 50/1997, en las reuniones del Consejo de Ministros actúa como Secretario:",
    ok: "El Ministro de la Presidencia.",
    mal: ["El Secretario de Estado de Relaciones con las Cortes.", "El Ministro de Justicia.", "El Vicepresidente primero."],
    d: 1,
  },
  {
    id: "tai-boe-t05-17", tema: 5, norma: "LG", art: "Artículo 24",
    cita: "2.º Disposiciones aprobadas por Orden Ministerial.",
    clave: "Orden Ministerial",
    e: "Según el artículo 24.2 de la Ley 50/1997, en la jerarquía de los reglamentos, por debajo de las disposiciones aprobadas por Real Decreto del Presidente del Gobierno o acordado en Consejo de Ministros se sitúan:",
    ok: "Las disposiciones aprobadas por Orden Ministerial.",
    mal: ["Los Acuerdos del Consejo de Ministros.", "Los Reales Decretos-leyes.", "Las instrucciones de los Secretarios de Estado."],
    d: 2,
  },
  {
    id: "tai-boe-t05-18", tema: 5, norma: "LG", art: "Artículo 24",
    cita: "Cuando la disposición o resolución afecte a varios Departamentos revestirá la forma de Orden del Ministro de la Presidencia, dictada a propuesta de los Ministros interesados.",
    clave: "Orden del Ministro de la Presidencia",
    e: "Conforme al artículo 24.1.f) de la Ley 50/1997, cuando una disposición o resolución ministerial afecte a varios Departamentos revestirá la forma de:",
    ok: "Orden del Ministro de la Presidencia, dictada a propuesta de los Ministros interesados.",
    mal: ["Real Decreto del Presidente del Gobierno.", "Orden conjunta firmada por todos los Ministros afectados.", "Acuerdo de la Comisión General de Secretarios de Estado y Subsecretarios."],
    d: 3,
  },

  // ── Tema 6 ──────────────────────────────────────────────────────────────
  {
    id: "tai-boe-t06-01", tema: 6, norma: "CE", art: "Artículo 109",
    cita: "Las Cámaras y sus Comisiones podrán recabar, a través de los Presidentes de aquéllas, la información y ayuda que precisen del Gobierno",
    clave: "Presidentes",
    e: "Según el artículo 109 de la Constitución, las Cámaras y sus Comisiones podrán recabar la información y ayuda que precisen del Gobierno y de sus Departamentos a través de:",
    ok: "Los Presidentes de las Cámaras.",
    mal: ["El Ministro competente en relaciones con las Cortes.", "Los portavoces de los grupos parlamentarios.", "La Mesa del Congreso, exclusivamente."],
    d: 2,
  },
  {
    id: "tai-boe-t06-02", tema: 6, norma: "CE", art: "Artículo 110",
    cita: "y podrán solicitar que informen ante las mismas funcionarios de sus Departamentos",
    clave: "funcionarios de sus Departamentos",
    e: "Además de tener acceso a las sesiones de las Cámaras y a sus Comisiones y la facultad de hacerse oír en ellas, según el artículo 110.2 de la Constitución los miembros del Gobierno:",
    ok: "Podrán solicitar que informen ante ellas funcionarios de sus Departamentos.",
    mal: ["Podrán votar en las Comisiones aunque no sean parlamentarios.", "Podrán presidir las Comisiones de su ámbito.", "Podrán vetar el orden del día de las Comisiones."],
    d: 2,
  },
  {
    id: "tai-boe-t06-03", tema: 6, norma: "CE", art: "Artículo 113",
    cita: "Si la moción de censura no fuere aprobada por el Congreso, sus signatarios no podrán presentar otra durante el mismo período de sesiones.",
    clave: "mismo período de sesiones",
    e: "Según el artículo 113.4 de la Constitución, si la moción de censura no fuere aprobada, sus signatarios no podrán presentar otra:",
    ok: "Durante el mismo período de sesiones.",
    mal: ["Durante un año.", "Durante la misma legislatura.", "En los seis meses siguientes."],
    d: 1,
  },
  {
    id: "tai-boe-t06-04", tema: 6, norma: "CE", art: "Artículo 114",
    cita: "Si el Congreso niega su confianza al Gobierno, éste presentará su dimisión al Rey, procediéndose a continuación a la designación de Presidente del Gobierno, según lo dispuesto en el artículo 99.",
    clave: "dimisión al Rey",
    e: "Conforme al artículo 114.1 de la Constitución, si el Congreso niega su confianza al Gobierno:",
    ok: "El Gobierno presentará su dimisión al Rey y se procederá a designar Presidente según el artículo 99.",
    mal: ["El Rey disolverá las Cortes y convocará elecciones.", "El Presidente podrá plantear una nueva cuestión de confianza al mes siguiente.", "Quedará investido el candidato propuesto por el principal grupo de la oposición."],
    d: 1,
  },
  {
    id: "tai-boe-t06-05", tema: 6, norma: "CE", art: "Artículo 116",
    cita: "El estado de alarma será declarado por el Gobierno mediante decreto acordado en Consejo de Ministros por un plazo máximo de quince días, dando cuenta al Congreso de los Diputados",
    clave: "plazo máximo de quince días",
    e: "Según el artículo 116.2 de la Constitución, el estado de alarma será declarado:",
    ok: "Por el Gobierno, mediante decreto acordado en Consejo de Ministros, por un plazo máximo de quince días, dando cuenta al Congreso.",
    mal: ["Por el Congreso, por mayoría absoluta, a propuesta exclusiva del Gobierno.", "Por el Gobierno, previa autorización del Congreso, por treinta días.", "Por el Rey, con el refrendo del Presidente del Gobierno, por un mes."],
    m: "Alarma: Gobierno da cuenta. Excepción: Gobierno con autorización. Sitio: lo declara el Congreso.", d: 1,
  },
  {
    id: "tai-boe-t06-06", tema: 6, norma: "CE", art: "Artículo 116",
    cita: "su duración, que no podrá exceder de treinta días, prorrogables por otro plazo igual, con los mismos requisitos",
    clave: "treinta días, prorrogables por otro plazo igual",
    e: "Conforme al artículo 116.3 de la Constitución, la duración del estado de excepción:",
    ok: "No podrá exceder de treinta días, prorrogables por otro plazo igual, con los mismos requisitos.",
    mal: ["No podrá exceder de quince días, prorrogables con autorización del Congreso.", "No podrá exceder de sesenta días improrrogables.", "No podrá exceder de treinta días, sin posibilidad de prórroga."],
    d: 2,
  },
  {
    id: "tai-boe-t06-07", tema: 6, norma: "CE", art: "Artículo 116",
    cita: "El estado de sitio será declarado por la mayoría absoluta del Congreso de los Diputados, a propuesta exclusiva del Gobierno.",
    clave: "mayoría absoluta del Congreso",
    e: "Según el artículo 116.4 de la Constitución, el estado de sitio será declarado:",
    ok: "Por la mayoría absoluta del Congreso de los Diputados, a propuesta exclusiva del Gobierno.",
    mal: ["Por el Gobierno, previa autorización del Congreso de los Diputados.", "Por el Gobierno, dando cuenta al Congreso de los Diputados.", "Por mayoría absoluta de las Cortes Generales en sesión conjunta."],
    d: 1,
  },
  {
    id: "tai-boe-t06-08", tema: 6, norma: "CE", art: "Artículo 116",
    cita: "Disuelto el Congreso o expirado su mandato, si se produjere alguna de las situaciones que dan lugar a cualquiera de dichos estados, las competencias del Congreso serán asumidas por su Diputación Permanente.",
    clave: "Diputación Permanente",
    e: "Según el artículo 116.5 de la Constitución, si estando disuelto el Congreso se produjere alguna de las situaciones que dan lugar a los estados de alarma, excepción o sitio, las competencias del Congreso serán asumidas por:",
    ok: "Su Diputación Permanente.",
    mal: ["El Senado.", "El Gobierno en funciones.", "La Mesa del Congreso."],
    d: 2,
  },
  {
    id: "tai-boe-t06-09", tema: 6, norma: "LOEAES", art: "Artículo cuarto",
    cita: "b) Crisis sanitarias, tales como epidemias y situaciones de contaminación graves.",
    clave: "Crisis sanitarias",
    e: "¿Cuál de los siguientes es uno de los supuestos que, según el artículo 4 de la Ley Orgánica 4/1981, permiten al Gobierno declarar el estado de alarma?",
    ok: "Crisis sanitarias, como epidemias y situaciones de contaminación graves.",
    mal: ["Una insurrección o acto de fuerza contra la soberanía de España.", "Una alteración tan grave del funcionamiento de las instituciones democráticas que las potestades ordinarias no basten.", "Un conflicto armado con otro Estado."],
    j: "La insurrección contra la soberanía es supuesto del estado de sitio (artículo 32) y la alteración grave del orden público y de las instituciones, del estado de excepción (artículo 13).",
    d: 2,
  },
  {
    id: "tai-boe-t06-10", tema: 6, norma: "LOEAES", art: "Artículo séptimo",
    cita: "A los efectos del estado de alarma la Autoridad competente será el Gobierno o, por delegación de éste, el Presidente de la Comunidad Autónoma cuando la declaración afecte exclusivamente a todo o parte del territorio de una Comunidad.",
    clave: "Presidente de la Comunidad Autónoma",
    e: "Según el artículo 7 de la Ley Orgánica 4/1981, a los efectos del estado de alarma la Autoridad competente será el Gobierno o, por delegación de este, cuando la declaración afecte exclusivamente a todo o parte del territorio de una Comunidad:",
    ok: "El Presidente de la Comunidad Autónoma.",
    mal: ["El Delegado del Gobierno en la Comunidad Autónoma.", "El Ministro del Interior.", "La Asamblea legislativa de la Comunidad Autónoma."],
    d: 2,
  },
  {
    id: "tai-boe-t06-11", tema: 6, norma: "LOEAES", art: "Artículo sexto",
    cita: "Sólo se podrá prorrogar con autorización expresa del Congreso de los Diputados, que en este caso podrá establecer el alcance y las condiciones vigentes durante la prórroga.",
    clave: "alcance y las condiciones",
    e: "Conforme al artículo 6.2 de la Ley Orgánica 4/1981, al autorizar la prórroga del estado de alarma, el Congreso de los Diputados:",
    ok: "Podrá establecer el alcance y las condiciones vigentes durante la prórroga.",
    mal: ["Solo puede aprobarla o rechazarla en los términos que proponga el Gobierno.", "Debe fijarla siempre en quince días.", "Necesita el acuerdo previo del Senado."],
    d: 3,
  },
  {
    id: "tai-boe-t06-12", tema: 6, norma: "LOEAES", art: "Artículo treinta y dos",
    cita: "La declaración podrá autorizar, además de lo previsto para los estados de alarma y excepción, la suspensión temporal de las garantías jurídicas del detenido que se reconocen en el apartado tres del artículo diecisiete de la Constitución.",
    clave: "garantías jurídicas del detenido",
    e: "Según el artículo 32.3 de la Ley Orgánica 4/1981, la declaración del estado de sitio podrá autorizar, además de lo previsto para los estados de alarma y excepción:",
    ok: "La suspensión temporal de las garantías jurídicas del detenido del artículo 17.3 de la Constitución.",
    mal: ["La suspensión del derecho a la vida y a la integridad física.", "La suspensión del derecho de sufragio.", "La disolución del Congreso de los Diputados."],
    d: 3,
  },

  // ── Tema 7 ──────────────────────────────────────────────────────────────
  {
    id: "tai-boe-t07-01", tema: 7, norma: "CE", art: "Artículo 117",
    cita: "Los Jueces y Magistrados no podrán ser separados, suspendidos, trasladados ni jubilados, sino por alguna de las causas y con las garantías previstas en la ley.",
    clave: "previstas en la ley",
    e: "Según el artículo 117.2 de la Constitución, los Jueces y Magistrados solo podrán ser separados, suspendidos, trasladados o jubilados:",
    ok: "Por alguna de las causas y con las garantías previstas en la ley.",
    mal: ["Por acuerdo del Ministro de Justicia.", "Por decisión del Gobierno, oído el Consejo General del Poder Judicial.", "Por votación del Congreso por mayoría absoluta."],
    d: 1,
  },
  {
    id: "tai-boe-t07-02", tema: 7, norma: "CE", art: "Artículo 117",
    cita: "corresponde exclusivamente a los Juzgados y Tribunales determinados por las leyes, según las normas de competencia y procedimiento que las mismas establezcan",
    clave: "determinados por las leyes",
    e: "Conforme al artículo 117.3 de la Constitución, el ejercicio de la potestad jurisdiccional en todo tipo de procesos, juzgando y haciendo ejecutar lo juzgado, corresponde exclusivamente a:",
    ok: "Los Juzgados y Tribunales determinados por las leyes.",
    mal: ["Los Juzgados y Tribunales y al Ministerio Fiscal.", "El Consejo General del Poder Judicial.", "Los Juzgados y Tribunales para juzgar, y a la Administración para ejecutar."],
    d: 1,
  },
  {
    id: "tai-boe-t07-03", tema: 7, norma: "CE", art: "Artículo 117",
    cita: "Los Juzgados y Tribunales no ejercerán más funciones que las señaladas en el apartado anterior y las que expresamente les sean atribuidas por ley en garantía de cualquier derecho.",
    clave: "en garantía de cualquier derecho",
    e: "Según el artículo 117.4 de la Constitución, además de la potestad jurisdiccional, los Juzgados y Tribunales solo ejercerán las funciones que expresamente les atribuya la ley:",
    ok: "En garantía de cualquier derecho.",
    mal: ["A petición del Gobierno.", "Por delegación del Consejo General del Poder Judicial.", "Con carácter consultivo para las Cortes Generales."],
    d: 2,
  },
  {
    id: "tai-boe-t07-04", tema: 7, norma: "CE", art: "Artículo 119",
    cita: "La justicia será gratuita cuando así lo disponga la ley y, en todo caso, respecto de quienes acrediten insuficiencia de recursos para litigar.",
    clave: "insuficiencia de recursos para litigar",
    e: "Conforme al artículo 119 de la Constitución, la justicia será gratuita cuando así lo disponga la ley y, en todo caso:",
    ok: "Respecto de quienes acrediten insuficiencia de recursos para litigar.",
    mal: ["En todos los procesos penales.", "Para todos los ciudadanos en cualquier proceso.", "Respecto de los menores de edad."],
    d: 1,
  },
  {
    id: "tai-boe-t07-05", tema: 7, norma: "CE", art: "Artículo 120",
    cita: "El procedimiento será predominantemente oral, sobre todo en materia criminal.",
    clave: "predominantemente oral",
    e: "Según el artículo 120.2 de la Constitución, el procedimiento judicial será:",
    ok: "Predominantemente oral, sobre todo en materia criminal.",
    mal: ["Predominantemente escrito, salvo en materia criminal.", "Exclusivamente oral en todas las jurisdicciones.", "Oral solo en materia civil."],
    d: 1,
  },
  {
    id: "tai-boe-t07-06", tema: 7, norma: "CE", art: "Artículo 120",
    cita: "Las sentencias serán siempre motivadas y se pronunciarán en audiencia pública.",
    clave: "siempre motivadas",
    e: "Conforme al artículo 120.3 de la Constitución, las sentencias:",
    ok: "Serán siempre motivadas y se pronunciarán en audiencia pública.",
    mal: ["Solo serán motivadas cuando sean condenatorias.", "Se pronunciarán en audiencia reservada cuando afecten a menores.", "Serán motivadas solo si lo solicita una de las partes."],
    d: 1,
  },
  {
    id: "tai-boe-t07-07", tema: 7, norma: "CE", art: "Artículo 121",
    cita: "Los daños causados por error judicial, así como los que sean consecuencia del funcionamiento anormal de la Administración de Justicia, darán derecho a una indemnización a cargo del Estado, conforme a la ley.",
    clave: "a cargo del Estado",
    e: "Según el artículo 121 de la Constitución, los daños causados por error judicial o por el funcionamiento anormal de la Administración de Justicia darán derecho a una indemnización:",
    ok: "A cargo del Estado, conforme a la ley.",
    mal: ["A cargo del Juez o Magistrado responsable.", "A cargo del Consejo General del Poder Judicial.", "A cargo de la Comunidad Autónoma con competencias en justicia."],
    d: 1,
  },
  {
    id: "tai-boe-t07-08", tema: 7, norma: "CE", art: "Artículo 122",
    cita: "El Consejo General del Poder Judicial es el órgano de gobierno del mismo.",
    clave: "órgano de gobierno",
    e: "Conforme al artículo 122.2 de la Constitución, el Consejo General del Poder Judicial es:",
    ok: "El órgano de gobierno del Poder Judicial.",
    mal: ["El órgano jurisdiccional superior en todos los órdenes.", "El supremo órgano consultivo del Gobierno en materia de justicia.", "El tribunal que resuelve en última instancia los recursos de casación."],
    d: 1,
  },
  {
    id: "tai-boe-t07-09", tema: 7, norma: "CE", art: "Artículo 123",
    cita: "El Presidente del Tribunal Supremo será nombrado por el Rey, a propuesta del Consejo General del Poder Judicial, en la forma que determine la ley.",
    clave: "a propuesta del Consejo General del Poder Judicial",
    e: "Según el artículo 123.2 de la Constitución, el Presidente del Tribunal Supremo será nombrado por el Rey:",
    ok: "A propuesta del Consejo General del Poder Judicial.",
    mal: ["A propuesta del Gobierno, oído el Consejo General del Poder Judicial.", "A propuesta del Congreso por mayoría de tres quintos.", "Por elección entre los Magistrados del Tribunal Supremo."],
    j: "La fórmula «a propuesta del Gobierno, oído el Consejo General del Poder Judicial» es la del Fiscal General del Estado (artículo 124.4).",
    d: 2,
  },
  {
    id: "tai-boe-t07-10", tema: 7, norma: "CE", art: "Artículo 124",
    cita: "El Ministerio Fiscal ejerce sus funciones por medio de órganos propios conforme a los principios de unidad de actuación y dependencia jerárquica y con sujeción, en todo caso, a los de legalidad e imparcialidad.",
    clave: "unidad de actuación y dependencia jerárquica",
    e: "Conforme al artículo 124.2 de la Constitución, el Ministerio Fiscal ejerce sus funciones conforme a los principios de:",
    ok: "Unidad de actuación y dependencia jerárquica, con sujeción en todo caso a los de legalidad e imparcialidad.",
    mal: ["Independencia, inamovilidad y responsabilidad.", "Oportunidad y discrecionalidad.", "Autonomía funcional y libre designación."],
    j: "Independencia, inamovilidad y responsabilidad son notas de los Jueces y Magistrados (artículo 117.1).",
    d: 2,
  },
  {
    id: "tai-boe-t07-11", tema: 7, norma: "CE", art: "Artículo 126",
    cita: "La policía judicial depende de los Jueces, de los Tribunales y del Ministerio Fiscal en sus funciones de averiguación del delito y descubrimiento y aseguramiento del delincuente",
    clave: "Ministerio Fiscal",
    e: "Según el artículo 126 de la Constitución, en sus funciones de averiguación del delito y descubrimiento y aseguramiento del delincuente, la policía judicial depende:",
    ok: "De los Jueces, de los Tribunales y del Ministerio Fiscal.",
    mal: ["Exclusivamente del Ministerio del Interior.", "Del Consejo General del Poder Judicial.", "De las Comunidades Autónomas con policía propia."],
    d: 1,
  },
  {
    id: "tai-boe-t07-12", tema: 7, norma: "LOPJ", art: "Artículo primero",
    cita: "sometidos únicamente a la Constitución y al imperio de la ley",
    clave: "a la Constitución y al imperio de la ley",
    e: "A diferencia del artículo 117.1 de la Constitución, el artículo 1 de la Ley Orgánica del Poder Judicial dice que los Jueces y Magistrados están sometidos únicamente:",
    ok: "A la Constitución y al imperio de la ley.",
    mal: ["Al imperio de la ley.", "A la ley y a la jurisprudencia del Tribunal Supremo.", "A la Constitución y a las instrucciones del Consejo General del Poder Judicial."],
    j: "El artículo 117.1 de la Constitución habla solo de «sometidos únicamente al imperio de la ley».",
    d: 3,
  },
  {
    id: "tai-boe-t07-13", tema: 7, norma: "LOPJ", art: "Artículo veintiséis",
    cita: "e) Tribunal Central de Instancia.",
    clave: "Tribunal Central de Instancia",
    e: "Tras la Ley Orgánica 1/2025, ¿cuál de los siguientes figura entre los Tribunales a los que el artículo 26 de la Ley Orgánica del Poder Judicial atribuye el ejercicio de la potestad jurisdiccional?",
    ok: "El Tribunal Central de Instancia.",
    mal: ["Los Juzgados Centrales de Instrucción.", "Los Juzgados de Primera Instancia e Instrucción.", "Los Juzgados de lo Penal."],
    j: "La Ley Orgánica 1/2025 sustituyó los juzgados unipersonales por los Tribunales de Instancia y los Juzgados Centrales por el Tribunal Central de Instancia. El artículo 26 enumera ahora: Jueces y juezas de paz, Tribunales de Instancia, Audiencias Provinciales, Tribunales Superiores de Justicia, Tribunal Central de Instancia, Audiencia Nacional y Tribunal Supremo.",
    d: 3,
  },
];
